#include <logigab.h>


TSLGField	tab_LGFields[] = {
	
	{LG_SEPERATOR,LG_ALPHA,1,"Separateur "},
	{LG_INST_RESERVED_ZONE,LG_ALPHA,8,"Zone reservee etablissement "},
	{LG_FUNCTION_CODE,LG_ALPHA,1,"Code fonction "},
	{LG_MSG_NBR,LG_NUMBER,4,"Numero de message "},
	{LG_TERMINAL_NO,LG_NUMBER,8,"Numero de l automate "},
	{LG_DATE,LG_NUMBER,6,"Date (AAMMJJ) "},
	{LG_TIME,LG_NUMBER,6,"Heure (HHMMSS) "},
	{LG_OP_NO,LG_NUMBER,6,"Numero d operation bancaire "},
	{LG_ACC_BATCH_REF,LG_NUMBER,5,"Reference arrete comptable "},
	{LG_REENTRY_IND,LG_NUMBER,1,"Indicateur de Reentree "},
	{LG_LAST_MSG_IND,LG_NUMBER,1,"Indicateur dernier message "},
	{LG_FORMAT_IND,LG_NUMBER,1,"Indicateur de format "},
	{LG_RELEASE_1,LG_ALPHA,1,"Release 1"},
	{LG_RUF_013,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_SOFT_VER_NO,LG_NUMBER,3,"Numero de version logiciel actif "},
	{LG_SOFT_REL_NO,LG_ALPHA,3,"Numero de release logiciel actif "},
	{LG_LAST_JE_REF,LG_NUMBER,5,"Reference du dernier fichier JE sauvegarde "},
	{LG_PARAM_FILE_VER_CURR,LG_NUMBER,5,"Numero de version des fichiers parametres actifs "},
	{LG_TERM_STATE_CURR,LG_ALPHA,3,"Etat actuel de l automate "},
	{LG_AMNT_OUT_TH_CRNY_1,LG_NUMBER,10,"Encaisse Out theorique dans la devise 1 (Devise principale) "},
	{LG_NB_ADV_NACK,LG_NUMBER,4,"Comptes rendus non-acquittes ou non transmis "},
	{LG_NB_JE_NSAVE,LG_NUMBER,3,"Nombre de fichiers JE non sauvegardes "},
	{LG_HD_AVAIL_SIZE,LG_NUMBER,6,"Place disque disponible (k octets) "},
	{LG_ACTION_CODE,LG_ALPHA,1,"Code action "},
	{LG_PARAM_FILE_VER_TRNSF,LG_ALPHA,5,"Numero de version des fichiers parametres transferes "},
	{LG_EXP_CMD_OP_CD,LG_NUMBER,2,"Code de l operation d exploitation telecommandee "},
	{LG_EXP_CMD_DATA,LG_ALPHA,12,"Donnees de l operation d exploitation telecommandee "},
	{LG_RES_STATE_CURR,LG_NUMBER,30,"Etat des ressources "},
	{LG_RES_STATE_PREV,LG_NUMBER,30,"Etat precedent des ressources "},
	{LG_TERM_STATE_PREV,LG_ALPHA,3,"Etat precedent de l automate "},
	{LG_DL_OTHER_CV_IND,LG_NUMBER,7,"Indicateur de telechargement autre CV "},
	{LG_UNDEF_031,LG_UNDEF,0,"Undefined"},
	{LG_CONS_STATUS,LG_ALPHA,1,"Status constructeur "},
	{LG_TERM_STATE_VAR,LG_ALPHA,1,"Variable d etat automate "},
	{LG_KEY_TYPE_RECV,LG_ALPHA,1,"Type de cle reçu "},
	{LG_KEY_TYPE_SENT,LG_NUMBER,1,"Type de cle envoye "},
	{LG_KEY_IND,LG_NUMBER,2,"Indice de cle "},
	{LG_ENV,LG_NUMBER,1,"Environnement "},
	{LG_KEY_ENC,LG_ALPHA,16,"Cle chiffre "},
	{LG_KEY_SENT_IND,LG_NUMBER,1,"Indicateur cle transmise "},
	{LG_LAST_DATA_BLOCK_RECV,LG_NUMBER,3,"Dernier numero de bloc reçu "},
	{LG_FILE_TRSFT_REPORT_CD,LG_NUMBER,1,"Code compte rendu de transfert de fichier "},
	{LG_CASST_ORDER_NO,LG_NUMBER,1,"Numero d ordre de la cassette "},
	{LG_BLOCK_NO,LG_NUMBER,3,"Numero de bloc "},
	{LG_LOCAL_EXP_OP_CD,LG_NUMBER,2,"Code operation d exploitation locale "},
	{LG_EXP_REPORT_CODE,LG_NUMBER,2,"Code compte rendu d exploitation "},
	{LG_EXP_OP_RESULT,LG_VAR_ALPHA,150,"Resultat de l operation d exploitation "},
	{LG_CASST_NO,LG_NUMBER,2,"Numero de la cassette "},
	{LG_DEPOSIT_FLOOR_LIMIT,LG_NUMBER,10,"Montant plancher deposable "},
	{LG_DEPOSIT_CEIL_LIMIT,LG_NUMBER,10,"Montant plafond deposable "},
	{LG_ISO2_CONTENT,LG_ALPHA,37,"Contenu ISO2 "},
	{LG_PIN_LEN,LG_NUMBER,2,"Longueur du code confidentiel "},
	{LG_PIN_BLOCK,LG_ALPHA,16,"Code chiffre "},
	{LG_TEMP_CARD_IND,LG_NUMBER,1,"Indicateur carte temporisee "},
	{LG_PROC_CODE,LG_NUMBER,1,"Code traitement "},
	{LG_REASON_CODE,LG_NUMBER,1,"Code motif "},
	{LG_SPEC_WELCOME,LG_ALPHA,34,"Accueil personnalise "},
	{LG_SERVER_MENU,LG_NUMBER,32,"Menu serveur "},
	{LG_NB_AVAIL_COM_WAG,LG_NUMBER,1,"Nombre de wagons commerciaux disponibles "},
	{LG_NB_AVAIL_PRD_WAG,LG_NUMBER,1,"Nombre de wagons produits disponibles "},
	{LG_WTHDRAWAL_FLAG,LG_NUMBER,6,"Droit au retrait "},
	{LG_SPEC_FAST_CASH,LG_NUMBER,6,"Retrait rapide personnalise "},
	{LG_CARD_ID,LG_ALPHA,19,"Identifiant carte "},
	{LG_NB_PRD_WAG_RECV,LG_NUMBER,1,"Nombre de wagons produits deja reçus "},
	{LG_NB_COM_WAG_RECV,LG_NUMBER,1,"Nombre de wagons commerciaux deja reçus "},
	{LG_CASST_TYPE,LG_NUMBER,1,"Type de la cassette "},
	{LG_RUF_066,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_PRODUCT_NO,LG_NUMBER,11,"Numero du produit "},
	{LG_PRODUCT_LABEL_CODE,LG_NUMBER,2,"Code libelle produit "},
	{LG_DC_CR_CODE,LG_NUMBER,1,"Code debit credit "},
	{LG_BALANCE_1,LG_X_NUMBER,13,"Solde 1 signe "},
	{LG_BALANCE_2,LG_X_NUMBER,13,"Solde 2 signe "},
	{LG_VAL_CODE,LG_NUMBER,1,"Code validation "},
	{LG_COM_WAG_LABEL,LG_ALPHA,40,"Libelle du wagon commercial "},
	{LG_RUF_074,LG_NUMBER,11,"RUF "},
	{LG_INQUIRY_TYPE,LG_NUMBER,2,"Type d interrogation "},
	{LG_NB_RESP_BLOCK_RECV,LG_NUMBER,2,"Nombre de blocs reponse deja reçus "},
	{LG_KEY_REPLIED,LG_ALPHA,12,"Cle retournee (interrogation) "},
	{LG_ACCOUNT_1,LG_NUMBER,11,"Compte 1 "},
	{LG_CHOICE_1,LG_NUMBER,1,"Choix 1 "},
	{LG_CHOICE_2,LG_NUMBER,1,"Choix 2 "},
	{LG_CHOICE_3,LG_NUMBER,1,"Choix 3 "},
	{LG_CHOICE_4,LG_NUMBER,1,"Choix 4 "},
	{LG_LAST_INQ_BLOCK_IND,LG_NUMBER,1,"Indicateur dernier bloc interrogation "},
	{LG_INQUIRY_LABEL,LG_VAR_ALPHA,2048,"Libelle interrogation "},
	{LG_TO_REPLY_KEY_INQ,LG_ALPHA,12,"Cle a retourner (interrogation) "},
	{LG_REPLIED_KEY,LG_ALPHA,12,"Cle retournee "},
	{LG_OP_CODE,LG_ALPHA,2,"Code operation bancaire "},
	{LG_LAST_ILS_BLOCK_IND,LG_NUMBER,1,"Indicateur dernier bloc ILS "},
	{LG_MAX_COL_NBR,LG_NUMBER,3,"Nombre de colonnes maximum par ligne "},
	{LG_NB_LINES,LG_NUMBER,2,"Numero de ligne "},
	{LG_TO_REPLY_KEY,LG_ALPHA,12,"Cle a retourner "},
	{LG_RUF_092,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_MEDIA_TYPE,LG_NUMBER,1,"Type de media de la cassette "},
	{LG_CONV_RATE,LG_X_NUMBER,13,"Taux de conversion ou Cours suivant la quotite "},
	{LG_DISC_FEE_AMOUNT,LG_NUMBER,5,"Montant de la commission fixe ou frais "},
	{LG_DISC_RATE,LG_NUMBER,4,"Taux de commission "},
	{LG_DISC_FEE_FLOOR_LIMIT,LG_NUMBER,6,"Montant plancher de commission ou de frais "},
	{LG_DISC_FEE_CEIL_LIMIT,LG_NUMBER,6,"Montant plafond de commission ou de frais "},
	{LG_TVA_RATE,LG_NUMBER,4,"Taux de TVA "},
	{LG_TAX_CODE,LG_NUMBER,1,"Code taxe "},
	{LG_QUOTA,LG_NUMBER,6,"Quotite "},
	{LG_SALE_COND_RESP_CD,LG_NUMBER,2,"Code reponse conditions de vente "},
	{LG_PIN_ENTRY_CODE,LG_NUMBER,1,"Code saisie du code confidentiel "},
	{LG_REQUESTED_AMOUNT,LG_NUMBER,12,"Montant demande "},
	{LG_BANK_CODE,LG_NUMBER,5,"Code banque "},
	{LG_RESPONSE_CODE,LG_ALPHA,2,"Code reponse autorisation "},
	{LG_AUTHORIZED_AMOUNT,LG_NUMBER,12,"Montant autorise (en devise principale) "},
	{LG_AUTH_CODE,LG_ALPHA,6,"Numero d autorisation "},
	{LG_REQUESTED_AMNT_CRNCY,LG_NUMBER,12,"Montant demande en devise "},
	{LG_ACCOUNT_TO_DEBIT,LG_NUMBER,11,"Numero du compte a debiter "},
	{LG_ACCOUNT_TO_CREDIT,LG_VAR_ALPHA,23,"Numero du compte a crediter "},
	{LG_CASST_CURR_STATE,LG_ALPHA,1,"Etat actuel de la cassette "},
	{LG_ACC_STATE_CODE,LG_ALPHA,1,"Code etat du compte "},
	{LG_INFO_LABEL,LG_ALPHA,40,"Libelle d information "},
	{LG_BAL_ACCOUNT_TO_DEBIT,LG_X_NUMBER,13,"Solde signe du compte a debiter (demande de solde) "},
	{LG_BAL_ACCOUNT_TO_CREDIT,LG_X_NUMBER,13,"Solde signe du compte a crediter (demande de solde) "},
	{LG_CASST_PREV_STATE,LG_ALPHA,1,"Etat precedent de la cassette "},
	{LG_STATE_1_IND,LG_NUMBER,2,"Indicateur ETAT1 "},
	{LG_STATE_2_IND,LG_ALPHA,2,"Indicateur ETAT2 "},
	{LG_STATE_3_IND,LG_ALPHA,2,"Indicateur ETAT3 "},
	{LG_DISTRIBUTED_AMOUNT,LG_NUMBER,12,"Montant distribue "},
	{LG_REVERSAL_NOTIF,LG_NUMBER,2,"Notification de redressement "},
	{LG_RUF_123,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_K7OUT_O1_NB_DIST,LG_NUMBER,2,"Nombre de medias distribues en cassette de type K7Out ordre 1 "},
	{LG_K7OUT_O2_NB_DIST,LG_NUMBER,2,"Nombre de medias distribues en cassette de type K7Out ordre 2 "},
	{LG_K7OUT_O3_NB_DIST,LG_NUMBER,2,"Nombre de medias distribues en cassette de type K7Out ordre 3 "},
	{LG_K7OUT_O4_NB_DIST,LG_NUMBER,2,"Nombre de medias distribues en cassette de type K7Out ordre 4 "},
	{LG_RUF_128,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_RUF_129,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_RUF_130,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_OP_AMOUNT,LG_NUMBER,12,"Montant de l operation "},
	{LG_RUF_132,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_RUF_133,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_SELECTED_ACC_NO,LG_NUMBER,11,"Numero du compte choisi "},
	{LG_DEPOSIT_NO,LG_NUMBER,4,"Numero de depot "},
	{LG_DISTR_AMNT_P_CRNCY,LG_NUMBER,12,"Montant distribue (en devise principale) "},
	{LG_DISTR_AMNT_F_CRNCY,LG_NUMBER,7,"Montant distribue (en devise etrangere) "},
	{LG_DISC_AMNT_HT,LG_NUMBER,6,"Montant de la commission HT "},
	{LG_AVAIL_CRNY,LG_NUMBER,12,"Encaisse Out disponible de la devise "},
	{LG_RUF_140,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_RUF_141,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_B0_PROC_CTX,LG_NUMBER,2,"Contexte traitement puce B0  "},
	{LG_B0_AUTH_ITEM,LG_ALPHA,8,"Element d authentification B0  "},
	{LG_BO_CALC_DATA,LG_ALPHA,5,"Donnees du calcul B0  "},
	{LG_B0_FINAL_STATE_W,LG_ALPHA,10,"Mot d etat final B0  "},
	{LG_BO_PROC_RES,LG_NUMBER,2,"Resultat traitement microcircuit B0  "},
	{LG_MAC_TYPE,LG_NUMBER,1,"Type de scellement execute "},
	{LG_MAC_LEN,LG_NUMBER,1,"Longueur du sceau "},
	{LG_MAC,LG_ALPHA,8,"Sceau du message "},
	{LG_B0_BLOCK_CHIP_ATM_REQ,LG_NUMBER,2,"Blocage puce B0  demande au GAB "},
	{LG_B0_BLOCK_CHIP,LG_NUMBER,2,"Demande de blocage puce B0  "},
	{LG_CHECK_CMC7_NO,LG_ALPHA,7,"Numero CMC7 du cheque "},
	{LG_CHECK_INTERBANK_CMC7_CD,LG_ALPHA,12,"Code interbancaire CMC7 du cheque "},
	{LG_CHECK_CMC7_ACC_NO,LG_ALPHA,12,"Numero de compte CMC7 du cheque "},
	{LG_CHECK_REMITTANCE_NO,LG_NUMBER,4,"Numero de la remise de cheques "},
	{LG_REMITTANCE_NB_CHECK,LG_NUMBER,2,"Nombre de cheques de la remise "},
	{LG_REMITTANCE_FINAL_AMOUNT,LG_NUMBER,12,"Montant final de la remise "},
	{LG_AMOUNT_SCANNED,LG_NUMBER,12,"Montant lu par le scanner "},
	{LG_TRX_ADDRESS_1,LG_ALPHA,24,"Lieu de la transaction (adresse, ville) "},
	{LG_TRX_ADDRESS_2,LG_ALPHA,20,"Lieu de la transaction (pays, code postal) "},
	{LG_OP_CD_REPORT_TYPE,LG_ALPHA,1,"Type de compte-rendu d operation bancaire "},
	{LG_EXP_MODE,LG_NUMBER,2,"Mode exploitant "},
	{LG_DL_SOFT_VER_NO,LG_NUMBER,3,"Numero de version du logiciel telecharge "},
	{LG_DL_SOFT_REL_NO,LG_ALPHA,3,"Numero de release du logiciel telecharge "},
	{LG_DL_FILE_PARAM_VER_NO,LG_NUMBER,5,"Numero de version des fichiers parametres telecharges ou stockes "},
	{LG_CB_READER_ID,LG_ALPHA,6,"Identifiant lecteur coupleur agree CB "},
	{LG_MAINTAIN_REQ,LG_NUMBER,1,"Demande de maintenance preventive ou curative "},
	{LG_REQ_RES_NO,LG_NUMBER,2,"Numero de la ressource faisant l objet d une demande "},
	{LG_MAINTAIN_REQ_LABEL,LG_ALPHA,40,"Libelle correspondant a la demande de maintenance "},
	{LG_REQ_WAG_TYPE,LG_NUMBER,1,"Type de wagons souhaites "},
	{LG_RUF_171,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_RUF_172,LG_UNDEF,0,"Rubrique non utilisee"},
	{LG_WAD_NO,LG_NUMBER,2,"Numero de la liasse "},
	{LG_NO1_WAD_NBR,LG_NUMBER,4,"Nombre total de medias hors type 1 de la liasse "},
	{LG_LAST_PRD_WAG_IND,LG_NUMBER,1,"Indicateur dernier wagon produit "},
	{LG_LAST_COM_WAG_IND,LG_NUMBER,1,"Indicateur dernier wagon commercial "},
	{LG_TOTAL_WAD_AMOUNT,LG_NUMBER,12,"Montant total de la liasse "},
	{LG_NB_WAD_DEN_NBR,LG_NUMBER,1,"Nombre total de denomination de la liasse "},
	{LG_CURR_OP_CURRENCY,LG_NUMBER,3,"Code devise de l operation en cours "},
	{LG_PRODUCT_CURRENCY,LG_NUMBER,3,"Code devise du produit "},
	{LG_AUTH_PRD_OP,LG_ALPHA,17,"Operations autorisees pour le produit "},
	{LG_PRINCIPAL_CRNCY,LG_NUMBER,3,"Code devise de la devise principale "},
	{LG_SALE_TYPE,LG_NUMBER,1,"Type de vente "},
	{LG_SPEC_ATM_PARAM_VER_NO,LG_ALPHA,4,"Numero de version des parametres specifiques de l automate "},
	{LG_GRAPHIC_F_VER_NO,LG_ALPHA,6,"Numero de version des fonds graphiques "},
	{LG_PRINTER_BINS_STATE,LG_NUMBER,4,"Etats des bacs (imprimante large ou laser) "},
	{LG_PIN_IND,LG_NUMBER,1,"Indicateur de saisie du code confidentiel "},
	{LG_RECV_MSG_MAX_SIZE,LG_NUMBER,4,"Taille maximum des messages en reception "},
	{LG_ACK_IMM_DIFF,LG_NUMBER,1,"Prise en compte immediate ou differee "},
	{LG_DATA_LEN,LG_NUMBER,4,"Longueur du champ de donnees "},
	{LG_INQ_LABEL_LEN,LG_NUMBER,3,"Longueur du libelle interrogation "},
	{LG_PRINTER_ID,LG_ALPHA,8,"Identification de l imprimante large ou laser "},
	{LG_NEXT_LINE_NO_TOPRINT,LG_NUMBER,4,"Numero de la prochaine ligne a imprimer "},
	{LG_CURR_PRINT_PAGE,LG_NUMBER,2,"Numero de la page en cours d impression "},
	{LG_MAX_LINE_PER_PAGE,LG_NUMBER,2,"Nombre de lignes maximum par page "},
	{LG_PAPER_FORMAT,LG_NUMBER,1,"Format du papier "},
	{LG_FIRST_HEADER_NB_LINES,LG_NUMBER,2,"Nombre de lignes constituant la premiere entête "},
	{LG_HEADERS_NB_LINES,LG_NUMBER,2,"Nombre de lignes constituant les entêtes suivantes "},
	{LG_ILS_DATA_LEN,LG_NUMBER,4,"Longueur des donnees ILS "},
	{LG_K7OUT_O1_DEN,LG_NUMBER,6,"Denomination cassette de type K7Out ordre 1 "},
	{LG_K7OUT_O2_DEN,LG_NUMBER,6,"Denomination cassette de type K7Out ordre 2 "},
	{LG_K7OUT_O3_DEN,LG_NUMBER,6,"Denomination cassette de type K7Out ordre 3 "},
	{LG_K7OUT_O4_DEN,LG_NUMBER,6,"Denomination cassette de type K7Out ordre 4 "},
	{LG_TERM_LAST_MSG_IND,LG_NUMBER,1,"Indicateur dernier message automate "},
	{LG_AVAIL_BAL_CRNCY_1,LG_NUMBER,10,"Encaisse Out disponible dans la devise 1(devise principale) "},
	{LG_NEIGHBOR_TERM_1_STATE,LG_NUMBER,1,"Etat de l automate voisin 1 "},
	{LG_NEIGHBOR_TERM_2_STATE,LG_NUMBER,1,"Etat de l automate voisin 2 "},
	{LG_CURR_TRSNF_FILE_REF,LG_NUMBER,5,"Reference du fichier en cours de transfert "},
	{LG_CURR_TRSNF_FILE_LINE_NO,LG_NUMBER,6,"Numero de la ligne dans le fichier en cours de transfert "},
	{LG_RECORD_SIZE,LG_NUMBER,2,"Taille de l enregistrement "},
	{LG_MSG_NB_RECORD,LG_NUMBER,2,"Nombre d enregistrements transfere dans le message "},
	{LG_TRSNF_FILE_DATA,LG_VAR_ALPHA,2048,"Donnees du fichier en cours de transfert "},
	{LG_CH_NAME,LG_ALPHA,26,"Nom du porteur "},
	{LG_ILS_DATA,LG_VAR_ALPHA,2048,"Donnees ILS "},
	{LG_MIDDLE_AMOUNT,LG_NUMBER,10,"Montant intermediaire "},
	{LG_TOP_AMOUNT,LG_NUMBER,10,"Montant superieur "},
	{LG_K7MIXT_O1_NB_DIST,LG_NUMBER,2,"Nombre de medias distribues en cassette de type K7Mixte ordre 1 "},
	{LG_K7MIXT_O2_NB_DIST,LG_NUMBER,2,"Nombre de medias distribues en cassette de type K7Mixte ordre 2 "},
	{LG_K7MIXT_O3_NB_DIST,LG_NUMBER,2,"Nombre de medias distribues en cassette de type K7Mixte ordre 3 "},
	{LG_K7MIXT_O4_NB_DIST,LG_NUMBER,2,"Nombre de medias distribues en cassette de type K7Mixte ordre 4 "},
	{LG_MONEY_DEPOSIT_NO,LG_NUMBER,4,"Numero du depot d argent "},
	{LG_K7MIXT_O1_DEN,LG_NUMBER,6,"Denomination cassette de type K7Mixte ordre 1 "},
	{LG_K7MIXT_O2_DEN,LG_NUMBER,6,"Denomination cassette de type K7Mixte ordre 2"},
	{LG_K7MIXT_O3_DEN,LG_NUMBER,6,"Denomination cassette de type K7Mixte ordre 3 "},
	{LG_K7MIXT_O4_DEN,LG_NUMBER,6,"Denomination cassette de type K7Mixte ordre 4 "},
	{LG_K7MIXT_O1_NB_STORED,LG_NUMBER,3,"Nombre de medias stockes en cassette de type K7Mixte ordre 1 "},
	{LG_K7MIXT_O2_NB_STORED,LG_NUMBER,3,"Nombre de medias stockes en cassette de type K7Mixte ordre 2 "},
	{LG_K7MIXT_O3_NB_STORED,LG_NUMBER,3,"Nombre de medias stockes en cassette de type K7Mixte ordre 3 "},
	{LG_K7MIXT_O4_NB_STORED,LG_NUMBER,3,"Nombre de medias stockes en cassette de type K7Mixte ordre 4 "},
	{LG_DEPOSIT_AMNT_OP_CRNY,LG_NUMBER,12,"Montant total depose dans la devise de l operation en cours "},
	{LG_DEPOSIT_AMNT_P_CRNCY,LG_NUMBER,12,"Montant total depose dans la devise principale "},
	{LG_BIN_TBL_VER_NO,LG_NUMBER,4,"Numero de version de la table des Bins active "},
	{LG_AID_TBL_VER_NO,LG_NUMBER,4,"Numero de version de la table des AID EMV active "},
	{LG_DENIAL_TAC_VER_NO,LG_NUMBER,4,"Numero de version de la table des TAC Denial EMV active "},
	{LG_RSA_KEYS_TBL_VER_NO,LG_NUMBER,4,"Numero de version de la table des cles RSA active "},
	{LG_CURR_DEN,LG_NUMBER,6,"Code denomination de la denomination courante "},
	{LG_NB_TABLES_TO_TRNSFT,LG_NUMBER,2,"Nombre de tables a transferer "},
	{LG_MNG_TBL_ID_TO_TRNSFT,LG_NUMBER,2,"Identifiant de la table gestionnaire a transferer "},
	{LG_TABLE_TO_TRNSFT_MNG_VER_NO,LG_NUMBER,4,"Numero de version gestionnaire de la table a transferer "},
	{LG_TABLE_TO_TRNSFT_SIZE,LG_NUMBER,7,"Taille totale de la table a transferer "},
	{LG_TRSNF_TBL_TERM_ID,LG_NUMBER,2,"Identifiant automate de la table en cours de transfert "},
	{LG_TRSNF_TBL_TERM_VER_NO,LG_NUMBER,4,"Numero de version automate de la table en cours de transfert "},
	{LG_LAST_TERM_RECV_BLOCK_NO,LG_NUMBER,6,"Numero du dernier bloc reçu par l automate "},
	{LG_TRSNF_TBL_MNG_ID,LG_NUMBER,2,"Identifiant gestionnaire de la table en cours de transfert "},
	{LG_TRSNF_TBL_MNG_VER_NO,LG_NUMBER,4,"Numero de version gestionnaire de la table en cours de transfert "},
	{LG_CURR_TRSNF_BLOCK_NO,LG_NUMBER,6,"Numero de bloc de donnees en cours de transfert "},
	{LG_TP_REPORT_CODE,LG_NUMBER,2,"Code compte rendu de Tele Parametrage "},
	{LG_ERR_TBL_ID,LG_NUMBER,2,"Identifiant de la table en erreur "},
	{LG_OP_PROC_MODE,LG_NUMBER,1,"Mode de traitement de l operation "},
	{LG_EMV_PROC_RESULT,LG_NUMBER,2,"Resultat du traitement du microcircuit EMV "},
	{LG_EMV_WAG_IND,LG_NUMBER,1,"Indicateur wagon EMV "},
	{LG_CHIP_MNG_REQ_STATE,LG_NUMBER,4,"Etat voulu par le gestionnaire pour le traitement du microcircuit "},
	{LG_MAG_CHIP_TERM_CAP,LG_NUMBER,1,"Capacite materiel de l automate a traiter le piste ISO2 et le microcircuit "},
	{LG_TRSNF_SCREEN_PAGE_NO,LG_NUMBER,2,"Numero de la page ecran en cours de transfert "},
	{LG_TRSNF_SCREEN_LAST_BLOCK_IND,LG_NUMBER,1,"Indicateur dernier bloc de la page ecran "},
	{LG_DATA_BLOCK_LEN,LG_NUMBER,4,"Longueur du bloc de donnees "},
	{LG_DATA_BLOCK,LG_VAR_ALPHA,2048,"Bloc de donnees "},
	{LG_EDIT_FORMAT,LG_NUMBER,1,"Format de l edition "},
	{LG_EDIT_WITH_GRAPHIC,LG_NUMBER,1,"Edition avec fond graphique "},
	{LG_TRNSF_PARAM_FILE_CD,LG_ALPHA,1,"Code fichier parametre en cours de transfert "},
	{LG_LAST_DISP_SCREEN_PAGE_NO,LG_NUMBER,2,"Numero de la derniere page ecran visualisee "},
	{LG_TRNSF_PRINT_PAGE_NO,LG_NUMBER,2,"Numero de la page a imprimer en cours de transfert "},
	{LG_LAST_BLOCK_PRINT_PAGE_IND,LG_NUMBER,1,"Indicateur dernier bloc de la page a imprimer "},
	{LG_WAG_TYPE_CODE,LG_NUMBER,1,"Code type de Wagon "},
	{LG_TERM_CAPTURE_CAP,LG_NUMBER,1,"Capacite materiel de l automate a capturer les cartes "},
	{LG_TERM_PIN_CTRL_CAP,LG_NUMBER,1,"Capacite materiel de l automate a controler le code confidentiel "},
	{LG_DATA_FIELD_LEN,LG_NUMBER,4,"Longueur du champ de donnees "},
	{LG_ACQ_ID,LG_NUMBER,11,"Identifiant de l organisme acquereur "},
	{LG_CASST_STATE_CHG,LG_NUMBER,1,"Changement d etat des cassettes physiques "},
	{LG_CRYPTO_MOD_TYPE,LG_NUMBER,1,"Type de module cryptographique utilise "},
	{LG_KEY_REQ_REASON_CODE,LG_NUMBER,1,"Motif de la demande des cles "},
	{LG_SEQUENCE_NO,LG_NUMBER,1,"Numero de sequence "},
	{LG_SCD_USAGE_MODE_TERM,LG_NUMBER,3,"Modes d utilisations SCD "},
	{LG_MNG_STATE_VAR,LG_NUMBER,1,"Variable d etat gestionnaire "},
	{LG_SCD_USAGE_MODE_MNG,LG_NUMBER,3,"Modes d utilisations SCD "},
	{LG_KEY_DATA_BLOCK_LEN,LG_NUMBER,4,"Longueur du bloc de donnees Cles "},
	{LG_KEY_DATA_BLOCK,LG_VAR_ALPHA,2048,"Bloc de donnees Cles "},
	{LG_WITHDRAWAL_REPORT_SEND_COND,LG_NUMBER,1,"Condition d emission du compte rendu de retrait "},
	{LG_MANAGED_ENC_FMT,LG_NUMBER,1,"Format de chiffrement gere "},
	{LG_MNG_ROOT_KEY_VER_NO,LG_NUMBER,3,"Numero de version de la cle maître gestionnaire "},
	{LG_TERM_ROOT_KEY_VER_NO,LG_NUMBER,3,"Numero de version de la cle maître automate "},
	{LG_VISUALLY_IMPAIRED_TIMEOUT,LG_NUMBER,1,"Seuil time out mal voyant "},
	{LG_UNDEF_283,LG_UNDEF,0,"Undefined"},
	{LG_IS1_WAD_NBR,LG_NUMBER,4,"Nombre total de media de type 1 de la liasse "},
	{LG_P_CRNCY_TH_BAL,LG_NUMBER,10,"Encaisse coffre theorique de la devise principale "},
	{LG_P_CRNCY_DISP_BAL,LG_NUMBER,10,"Encaisse coffre disponible de la devise principale "},
	{LG_UNDEF_287,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_288,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_289,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_290,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_291,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_292,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_293,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_294,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_295,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_296,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_297,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_298,LG_UNDEF,0,"Undefined"},
	{LG_BUNDLES_DEP_REPORT_WAG_IND,LG_NUMBER,1,"Indicateur wagon compte rendu depot en liasse "},
	{LG_RIB_KEY,LG_ALPHA,2,"Cle RIB "},
	{LG_BRANCH_CODE,LG_ALPHA,5,"Code agence (ou code guichet) "},
	{LG_CR_ACC_BANK_CODE,LG_ALPHA,5,"Code banque du compte a crediter "},
	{LG_COM_TICKETS_TO_DIST,LG_ALPHA,1,"Nombre de coupons commerciaux a distribuer "},
	{LG_COM_TICKETS_DIST,LG_ALPHA,1,"Nombre de coupons commerciaux distribues "},
	{LG_CURR_DEN_TYPE2_MEDIA_NBR,LG_NUMBER,3,"Nombre de medias de type 2 de la denomination courante "},
	{LG_CURR_DEN_TYPE3_MEDIA_NBR,LG_NUMBER,3,"Nombre de medias de type 3 de la denomination courante "},
	{LG_CURR_DEN_TYPE4A_MEDIA_NBR,LG_NUMBER,3,"Nombre de medias de type 4a de la denomination courante "},
	{LG_CURR_DEN_TYPE4B_MEDIA_NBR,LG_NUMBER,3,"Nombre de medias de type 4b de la denomination courante "},
	{LG_CHG_ST_NB_CASST,LG_NUMBER,1,"Nombre de cassettes ayant change d etat "},
	{LG_MONEO_CHIP_PROC_RES,LG_NUMBER,4,"Resultat traitement microcircuit Moneo "},
	{LG_UNDEF_311,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_312,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_313,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_314,LG_UNDEF,0,"Undefined"},
	{LG_OP_CRNCY_DEP_BAL,LG_NUMBER,10,"Encaisse In theorique du depot valorise dans la devise de l operation "},
	{LG_RUF_316,LG_UNDEF,0,"RUF"},
	{LG_T3_SUSP_CR_MODE,LG_NUMBER,1,"Mode credit en compte des medias de type 3 ou douteux "},
	{LG_RUF_318,LG_UNDEF,0,"RUF"},
	{LG_TYPE_1_MEDIA_NBR,LG_NUMBER,4,"Nombre total de media de type 1 "},
	{LG_NTYPE_1_MEDIA_NBR,LG_NUMBER,4,"Nombre total de media hors type 1 "},
	{LG_NB_OP_BUNDLES,LG_NUMBER,2,"Nombre total de liasses de l operation "},
	{LG_UNDEF_322,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_323,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_324,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_325,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_326,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_327,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_328,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_329,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_330,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_331,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_332,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_333,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_334,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_335,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_336,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_337,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_338,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_339,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_340,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_341,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_342,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_343,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_344,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_345,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_346,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_347,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_348,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_349,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_350,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_351,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_352,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_353,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_354,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_355,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_356,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_357,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_358,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_359,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_360,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_361,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_362,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_363,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_364,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_365,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_366,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_367,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_368,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_369,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_370,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_371,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_372,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_373,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_374,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_375,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_376,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_377,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_378,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_379,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_380,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_381,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_382,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_383,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_384,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_385,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_386,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_387,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_388,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_389,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_390,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_391,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_392,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_393,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_394,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_395,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_396,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_397,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_398,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_399,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_400,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_401,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_402,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_403,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_404,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_405,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_406,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_407,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_408,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_409,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_410,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_411,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_412,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_413,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_414,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_415,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_416,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_417,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_418,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_419,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_420,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_421,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_422,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_423,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_424,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_425,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_426,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_427,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_428,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_429,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_430,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_431,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_432,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_433,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_434,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_435,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_436,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_437,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_438,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_439,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_440,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_441,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_442,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_443,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_444,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_445,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_446,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_447,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_448,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_449,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_450,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_451,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_452,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_453,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_454,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_455,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_456,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_457,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_458,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_459,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_460,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_461,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_462,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_463,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_464,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_465,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_466,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_467,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_468,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_469,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_470,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_471,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_472,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_473,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_474,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_475,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_476,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_477,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_478,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_479,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_480,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_481,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_482,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_483,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_484,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_485,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_486,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_487,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_488,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_489,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_490,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_491,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_492,LG_UNDEF,0,"Undefined"},
	{LG_PME_AUTH_NO,LG_ALPHA,6,"Numero d autorisation PME "},
	{LG_MONERO_WAG_IND,LG_NUMBER,1,"Indicateur wagon Moneo "},
	{LG_DOWNLOAD_TYPE,LG_NUMBER,2,"Type de chargement "},
	{LG_TSEQ,LG_NUMBER,6,"TSEQ (N sequence reçu lors de la demande de contexte) "},
	{LG_TERMINAL_ID,LG_NUMBER,8,"Terminal_Id (N terminal reçu lors de la demande de contexte) "},
	{LG_SAM,LG_NUMBER,19,"N SAM "},
	{LG_UNDEF_499,LG_UNDEF,0,"Undefined"},
	{LG_CH_NO,LG_ALPHA,19,"Numero de porteur issu de l application "},
	{LG_AMONT_ENTERED,LG_NUMBER,12,"Montant du chargement compose "},
	{LG_SERVER_RESP_CODE,LG_NUMBER,2,"Code reponse GDG "},
	{LG_UNDEF_503,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_504,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_505,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_506,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_507,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_508,LG_UNDEF,0,"Undefined"},
	{LG_PME_EXPIRY_DATE,LG_NUMBER,4,"Date d echeance du PME "},
	{LG_ADD_CARD_DATA_LEN,LG_NUMBER,3,"Longueur des donnees complementaires issues de la carte "},
	{LG_ADD_CARD_DATA,LG_VAR_ALPHA,2048,"Bloc des donnees complementaires issues de la carte "},
	{LG_PME_EXPIRY_DATE_TOPUP_RESP,LG_NUMBER,4,"Date d echeance du PME, en reponse a la demande de chargement "},
	{LG_PME_MNG_HOUR_TOPUP_RESP,LG_NUMBER,6,"Heure du gestionnaire service PME, en reponse a la demande de chargement "},
	{LG_PME_MNG_DATE_TOPUP_RESP,LG_NUMBER,4,"Date du gestionnaire service PME, en reponse a la demande de chargement "},
	{LG_UNDEF_515,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_516,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_517,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_518,LG_UNDEF,0,"Undefined"},
	{LG_UNDEF_519,LG_UNDEF,0,"Undefined"},
	{LG_MNG_RESP_CODE_TOPUP_RESP,LG_NUMBER,2,"Code reponse gestionnaire, en reponse a la demande de chargement "},
	{LG_ADD_DATA_LEN_TOPUP_RESP,LG_NUMBER,3,"Longueur des donnees complementaires en reponse a la demande de chargement"},
	{LG_ADD_DATA_TOPUP_RESP,LG_VAR_ALPHA,2048,"Bloc des donnees complementaires retournees par le gestionnaire en reponse a la demande  de chargement"},
	{LG_MSG_HEADER,LG_ALPHA,48,"Header"},
	{LG_ADD_DATA,LG_VAR_ALPHA,2048,"Additional data"},
	{LG_SPEC_FILLER,LG_VAR_ALPHA,2048,"Filler"},


};









