/*SKARROUMI PLUTONL-4833*/
#include <iso8583.h>
#include <gen_tlv_msg_mapping_flow.h>
#include <msgflow_fields.h>



static const TlvInfoProperties TSMsgMappingFlow = {
3,3,TLV_LT_ASCII, TLV_LT_ASCII, MSGFLOW_NB_FIELDS,
{
    {MSGFLOW_MSG_ID, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,12 , PP_PRINT,"NULL","MSG_ID","NULL",NOT_REPEATABLE},
    {MSGFLOW_MSG_TYPE, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,4 , PP_PRINT,"NULL","MSG_TYPE","NULL",NOT_REPEATABLE},
    {MSGFLOW_PROCESSING, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,2 , PP_PRINT,"NULL","PROCESSING","NULL",NOT_REPEATABLE},
    {MSGFLOW_SRC_NODE_ID, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE, 4, PP_PRINT,"NULL","SRC_NODE_ID","NULL",NOT_REPEATABLE},
    {MSGFLOW_SRC_RES_ID, FT_SINGLE, FF_ALPHA_AN, AF_ASCII, FL_FIX, LU_BYTE,6 , PP_PRINT,"NULL","SRC_RES_ID","NULL",NOT_REPEATABLE},
    {MSGFLOW_SRC_PID, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,8 , PP_PRINT,"NULL","SRC_PID","NULL",NOT_REPEATABLE},
    {MSGFLOW_DST_NODE_ID, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE, 4, PP_PRINT,"NULL","DST_NODE_ID","NULL",NOT_REPEATABLE},
    {MSGFLOW_DST_RES_ID, FT_SINGLE, FF_ALPHA_AN, AF_ASCII, FL_FIX, LU_BYTE,6 , PP_PRINT,"NULL","DST_RES_ID","NULL",NOT_REPEATABLE},
    {MSGFLOW_TAG_DST_PID, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE, 8, PP_PRINT,"NULL","TAG_DST_PID","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_REQ_RECV, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_REQ_RECV","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_REQ_FWD, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_REQ_FWD","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_FWD_REQ_RETRV, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_FWD_REQ_RETRV","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_REQ_SENT, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_REQ_SENT","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_REP_RECV, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_REP_RECV","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_REP_REPLIED, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_REP_REPLIED","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_REP_RETRV, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_REP_RETRV","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_REP_SENT, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_REP_SENT","NULL",NOT_REPEATABLE},
    {MSGFLOW_STATUS, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,1 , PP_PRINT,"NULL","STATUS","NULL",NOT_REPEATABLE},
    {MSGFLOW_MSG_STAN, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,6 , PP_PRINT,"NULL","MSG_STAN","NULL",NOT_REPEATABLE},
    {MSGFLOW_ORIGIN_CODE, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,1 , PP_PRINT,"NULL","ORIGIN_CODE","NULL",NOT_REPEATABLE},
    {MSGFLOW_RESP_CODE, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,3 , PP_PRINT,"NULL","RESP_CODE","NULL",NOT_REPEATABLE},
    {MSGFLOW_ORPHAN_FLAG, FT_SINGLE, FF_ALPHA_A, AF_ASCII, FL_FIX, LU_BYTE, 1, PP_PRINT,"NULL","ORPHAN_FLAG","NULL",NOT_REPEATABLE},
    {MSGFLOW_SRC_TIMEOUT_FLAG, FT_SINGLE, FF_ALPHA_A, AF_ASCII, FL_FIX, LU_BYTE, 1, PP_PRINT,"NULL","SRC_TIMEOUT_FLAG","NULL",NOT_REPEATABLE},
    {MSGFLOW_DST_TIMEOUT_FLAG, FT_SINGLE, FF_ALPHA_A, AF_ASCII, FL_FIX, LU_BYTE,1 , PP_PRINT,"NULL","DST_TIMEOUT_FLAG","NULL",NOT_REPEATABLE},
    {MSGFLOW_MALFUNCTION_FLAG, FT_SINGLE, FF_ALPHA_A, AF_ASCII, FL_FIX, LU_BYTE,1 , PP_PRINT,"NULL","MALFUNCTION_FLAG","NULL",NOT_REPEATABLE},
    {MSGFLOW_TIME_EXCEPTION, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,13 , PP_PRINT,"NULL","TIME_EXCEPTION","NULL",NOT_REPEATABLE},
    {MSGFLOW_DONE_FLAG, FT_SINGLE, FF_ALPHA_A, AF_ASCII, FL_FIX, LU_BYTE, 1, PP_PRINT,"NULL","DONE_FLAG","NULL",NOT_REPEATABLE},
    {MSGFLOW_REASON_CODE, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,4 , PP_PRINT,"NULL","REASON_CODE","NULL",NOT_REPEATABLE},
    {MSGFLOW_TERMINAL_ID, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,8 , PP_PRINT,"NULL","TERMINAL_ID","NULL",NOT_REPEATABLE},
    {MSGFLOW_BANK_CODE, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE, 6, PP_PRINT,"NULL","_BANK_CODE","NULL",NOT_REPEATABLE},
    {MSGFLOW_SAF_IND, FT_SINGLE, FF_ALPHA_N, AF_ASCII, FL_FIX, LU_BYTE,1 , PP_PRINT,"NULL","SAF_IND","NULL",NOT_REPEATABLE},
},
"TSMsgMappingFlow"
};


void InitTSMsgMappingFlow(TlvInfo* pkTlvInfo){
    pkTlvInfo->pkProperties = &TSMsgMappingFlow;
    ResetTlvInfo(pkTlvInfo);
}
/*SKARROUMI PLUTONL-4833*/