#include <p7_macros.h>
#include <iso8583.h>
#include <hsm_atalla_define.h>
#include <hsm_atalla.h>

#include <p7_common.h>
#include <p7_globals.h>
#include <iso8583.h>

extern const AtallaCmdInfoProperties	AtallaFieldsDataProp;
extern const AtallaCmdTagProperties		AtallaCmdTagProp;

void ResetAtallaCmdInfo(TSAtallaCmd* pkAtallaCmd);






/* UNKOWN_RESP */
static TSAtallaMsgLayout gs_ly_UNKOWN_RESP = {
	ATALLA_MN_UNKOWN_00,3,2048,ATALLA_FN_CMD_RESP_UNKOWN_00,
	{
		{ATALLA_FN_CHECK_DIGITS						},
		{ATALLA_FN_CHECK_DIGITS						},
		
	}
};

/* GENERATE_KEY_REQ*/
static TSAtallaMsgLayout gs_ly_GENERATE_KEY_REQ = {
	ATALLA_MN_REQ_GENERATE_KEY_10,3,2048,ATALLA_FN_CMD_REQ_GENERATE_KEY_10,
	{
		{ATALLA_FN_KEY_USAGE				},
		{ATALLA_FN_KEY_EXCHANGE_KEY			},
		{ATALLA_FN_KEY_LENGTH				},

	}
};

/* GENERATE_KEY_RESP*/
static TSAtallaMsgLayout gs_ly_GENERATE_KEY_RESP = {
	ATALLA_MN_RESP_GENERATE_KEY_20,3,2048,ATALLA_FN_CMD_RESP_GENERATE_KEY_20,
	{
		{ATALLA_FN_WORKING_KEY_MFK				},
		{ATALLA_FN_WORKING_KEY_KEK				},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* EXPORT_KEY_REQ*/
static TSAtallaMsgLayout gs_ly_EXPORT_KEY_REQ = {
	ATALLA_MN_REQ_EXPORT_KEY_11,3,2048,ATALLA_FN_CMD_REQ_EXPORT_KEY_11,
	{
		{ATALLA_FN_KEY_USAGE				},
		{ATALLA_FN_KEY_EXCHANGE_KEY			},
		{ATALLA_FN_WORKING_KEY_MFK			},

	}
};

/* EXPORT_KEY_RESP*/
static TSAtallaMsgLayout gs_ly_EXPORT_KEY_RESP = {
	ATALLA_MN_RESP_EXPORT_KEY_21,2,2048,ATALLA_FN_CMD_RESP_EXPORT_KEY_21,
	{
		{ATALLA_FN_WORKING_KEY_KEK				},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* IMPORT_KEY_REQ*/
static TSAtallaMsgLayout gs_ly_IMPORT_KEY_REQ = {
	ATALLA_MN_REQ_IMPORT_KEY_13,3,2048,ATALLA_FN_CMD_REQ_IMPORT_KEY_13,
	{
		{ATALLA_FN_KEY_USAGE				},
		{ATALLA_FN_KEY_EXCHANGE_KEY			},
		{ATALLA_FN_WORKING_KEY_KEK			},
	}
};

/* IMPORT_KEY_RESP*/
static TSAtallaMsgLayout gs_ly_IMPORT_KEY_RESP = {
	ATALLA_MN_RESP_IMPORT_KEY_23,2,2048,ATALLA_FN_CMD_RESP_IMPORT_KEY_23,
	{
		{ATALLA_FN_WORKING_KEY_MFK				},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* EXPORT_KEY_REQ_1A*/
static TSAtallaMsgLayout gs_ly_EXPORT_KEY_1A_REQ = {
	ATALLA_MN_REQ_EXPORT_KEY_1A,3,2048,ATALLA_FN_CMD_REQ_EXPORT_KEY_1A,
	{
		{ATALLA_FN_KEY_USAGE				},
		{ATALLA_FN_KEY_EXCHANGE_KEY			},
		{ATALLA_FN_WORKING_KEY_MFK			},
	}
};

/* EXPORT_KEY_RESP_1A*/
static TSAtallaMsgLayout gs_ly_EXPORT_KEY_2A_RESP = {
	ATALLA_MN_RESP_EXPORT_KEY_2A,3,2048,ATALLA_FN_CMD_RESP_EXPORT_KEY_2A,
	{
		{ATALLA_FN_WORKING_KEY_KEK				},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_WORKING_KEY_MFK				},
	}
};

/* VERIFY_CVV_REQ_5E*/
static TSAtallaMsgLayout gs_ly_VERIFY_CVV_5E_REQ = {
	ATALLA_MN_REQ_VERIFY_CVV_5E,5,2048,ATALLA_FN_CMD_REQ_VERIFY_CVV_5E,
	{
		{ATALLA_FN_CVV_ALGORITHM			},
		{ATALLA_FN_CVV_KEY					},
		{ATALLA_FN_KEY_USAGE				},
		{ATALLA_FN_CVV_DATA					},
		{ATALLA_FN_CVV						},
	}
};

/* VERIFY_CVV_RESP_6E*/
static TSAtallaMsgLayout gs_ly_VERIFY_CVV_6E_RESP = {
	ATALLA_MN_RESP_VERIFY_CVV_6E,3,2048,ATALLA_FN_CMD_RESP_VERIFY_CVV_6E,
	{
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
	}
};

/* VERIFY_DCVV_REQ_357*/
static TSAtallaMsgLayout gs_ly_VERIFY_DCVV_357_REQ = {
	ATALLA_MN_REQ_VERIFY_DCVV_357,7,2048,ATALLA_FN_CMD_REQ_VERIFY_DCVV_357,
	{
		{ATALLA_FN_ISSUER_MASTER_KEY_CVV			},
		{ATALLA_FN_PAN								},
		{ATALLA_FN_PAN_SEQ_NUMBER					},
		{ATALLA_FN_EXPIRY_DATE						},
		{ATALLA_FN_SERVICE_CODE						},
		{ATALLA_FN_ATC								},
		{ATALLA_FN_DCVV								},
	}
};

/* VERIFY_DCVV_RESP_457*/
static TSAtallaMsgLayout gs_ly_VERIFY_DCVV_457_RESP = {
	ATALLA_MN_RESP_VERIFY_DCVV_457,2,2048,ATALLA_FN_CMD_RESP_VERIFY_DCVV_457,
	{
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* VERIFY_CVC3_REQ_359*/
static TSAtallaMsgLayout gs_ly_VERIFY_CVC3_359_REQ = {
	ATALLA_MN_REQ_VERIFY_CVC3_359,7,2048,ATALLA_FN_CMD_REQ_VERIFY_CVC3_359,
	{
		{ATALLA_FN_ISSUER_MASTER_KEY_CVC3			},
		{ATALLA_FN_PAN								},
		{ATALLA_FN_PAN_SEQ_NUMBER					},
		{ATALLA_FN_TRACK_1_2_DATA					},
		{ATALLA_FN_UNPREDICTABLE_NUMBER				},
		{ATALLA_FN_ATC								},
		{ATALLA_FN_DCVC3							},
	}
};

/* VERIFY_CVC3_RESP_459*/
static TSAtallaMsgLayout gs_ly_VERIFY_CVC3_459_RESP = {
	ATALLA_MN_RESP_VERIFY_CVC3_459,2,2048,ATALLA_FN_CMD_RESP_VERIFY_CVC3_459,
	{
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* VERIFY_CSC_REQ_35A*/
static TSAtallaMsgLayout gs_ly_VERIFY_CSC_35A_REQ = {
	ATALLA_MN_REQ_VERIFY_CSC_35A,6,2048,ATALLA_FN_CMD_REQ_VERIFY_CSC_35A,
	{
		{ATALLA_FN_CSC_DATA							},
		{ATALLA_FN_EXPIRY_DATE						},
		{ATALLA_FN_CARD_SECURITY_CODE_KEY			},
		{ATALLA_FN_CSC_5							},
		{ATALLA_FN_CSC_4							},
		{ATALLA_FN_CSC_3							},
	}
};

/* VERIFY_CVC3_RESP_45A*/
static TSAtallaMsgLayout gs_ly_VERIFY_CSC_45A_RESP = {
	ATALLA_MN_RESP_VERIFY_CSC_45A,4,2048,ATALLA_FN_CMD_RESP_VERIFY_CSC_45A,
	{
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_VERIFICATION_FLAG_2			},
		{ATALLA_FN_VERIFICATION_FLAG_3			},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* TRANSLATE_PIN_REQ_335*/
static TSAtallaMsgLayout gs_ly_TRANSLATE_PIN_335_REQ = {
		ATALLA_MN_REQ_TRANSLATE_PIN_335,9,2048,ATALLA_FN_CMD_REQ_TRANSLATE_PIN_335,
	{
		{ATALLA_FN_INC_KEY_USAGE				},
		{ATALLA_FN_INC_PIN_BLOCK_FORMAT			},
		{ATALLA_FN_OUTG_KEY_USAGE				},
		{ATALLA_FN_OUTG_PIN_BLOCK_FORMAT		},
		{ATALLA_FN_INC_KEY						},
		{ATALLA_FN_OUTG_KEY						},
		{ATALLA_FN_INC_PIN_BLOCK				},
		{ATALLA_FN_INC_PIN_BLOCK_DATA			},
		{ATALLA_FN_OUTG_PIN_BLOCK_DATA			},
	}
};

/* TRANSLATE_PIN_RESP_435*/
static TSAtallaMsgLayout gs_ly_TRANSLATE_PIN_435_RESP = {
		ATALLA_MN_RESP_TRANSLATE_PIN_435,6,2048,ATALLA_FN_CMD_RESP_TRANSLATE_PIN_435,
	{
		{ATALLA_FN_OUTG_PIN_BLOCK				},
		{ATALLA_FN_SANITY_CHECK_IND				},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
		{ATALLA_FN_CHECK_DIGITS_3				},
		{ATALLA_FN_CHECK_DIGITS_4				},
	}
};

/* VERIFY_PIN_IBM_REQ_32*/
static TSAtallaMsgLayout gs_ly_VERIFY_PIN_IBM_32_REQ = {
		ATALLA_MN_REQ_VERIFY_PIN_IBM_32,11,2048,ATALLA_FN_CMD_REQ_VERIFY_PIN_IBM_32,
	{
		{ATALLA_FN_PIN_METHOD					},
		{ATALLA_FN_INC_PIN_BLOCK_FORMAT			},
		{ATALLA_FN_INC_PIN_BLOCK				},
		{ATALLA_FN_INC_KEY						},
		{ATALLA_FN_CONVERSION_TABLE				},
		{ATALLA_FN_OFFSET						},
		{ATALLA_FN_VALIDATION_DATA				},
		{ATALLA_FN_PAD							},
		{ATALLA_FN_CHECK_LENGTH					},
		{ATALLA_FN_PVK							},
		{ATALLA_FN_INC_PIN_BLOCK_DATA			},
	}
};

/* VERIFY_PIN_IBM_RESP_42*/
static TSAtallaMsgLayout gs_ly_VERIFY_PIN_IBM_42_RESP = {
		ATALLA_MN_RESP_VERIFY_PIN_IBM_42,2,2048,ATALLA_FN_CMD_RESP_VERIFY_PIN_IBM_42,
	{
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_IBM_SEQ_NUMBER				},
	}
};

/* VERIFY_PIN_VISA_REQ_32*/
static TSAtallaMsgLayout gs_ly_VERIFY_PIN_VISA_32_REQ = {
		ATALLA_MN_REQ_VERIFY_PIN_VISA_32,10,2048,ATALLA_FN_CMD_REQ_VERIFY_PIN_VISA_32,
	{
		{ATALLA_FN_PIN_METHOD					},
		{ATALLA_FN_INC_PIN_BLOCK_FORMAT			},
		{ATALLA_FN_INC_PIN_BLOCK				},
		{ATALLA_FN_INC_KEY						},
		{ATALLA_FN_PVK							},
		{ATALLA_FN_PVK_2						},
		{ATALLA_FN_PVV							},
		{ATALLA_FN_PVKI							},
		{ATALLA_FN_PAN							},
		{ATALLA_FN_INC_PIN_BLOCK_DATA			},

	}
};

/* VERIFY_PIN_VISA_RESP_42*/
static TSAtallaMsgLayout gs_ly_VERIFY_PIN_VISA_42_RESP = {
		ATALLA_MN_RESP_VERIFY_PIN_VISA_42,2,2048,ATALLA_FN_CMD_RESP_VERIFY_PIN_VISA_42,
	{
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_IBM_SEQ_NUMBER				},
	}
};

/* PIN_CHANGE_IBM_REQ_37*/
static TSAtallaMsgLayout gs_ly_PIN_CHANGE_IBM_37_REQ = {
		ATALLA_MN_REQ_PIN_CHANGE_IBM_37,12,2048,ATALLA_FN_CMD_REQ_PIN_CHANGE_IBM_37,
	{
		{ATALLA_FN_PIN_METHOD					},
		{ATALLA_FN_INC_PIN_BLOCK_FORMAT			},
		{ATALLA_FN_INC_PIN_BLOCK				},
		{ATALLA_FN_INC_KEY						},
		{ATALLA_FN_CONVERSION_TABLE				},
		{ATALLA_FN_OFFSET						},
		{ATALLA_FN_VALIDATION_DATA				},
		{ATALLA_FN_PAD							},
		{ATALLA_FN_CHECK_LENGTH					},
		{ATALLA_FN_PVK							},
		{ATALLA_FN_NEW_PIN_BLOCK				},
		{ATALLA_FN_INC_PIN_BLOCK_DATA			},
	}
};

/* PIN_CHANGE_IBM_RESP_47*/
static TSAtallaMsgLayout gs_ly_PIN_CHANGE_IBM_47_RESP = {
		ATALLA_MN_RESP_PIN_CHANGE_IBM_47,3,2048,ATALLA_FN_CMD_RESP_PIN_CHANGE_IBM_47,
	{
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_NEW_OFFSET					},
		{ATALLA_FN_IBM_SEQ_NUMBER				},
	}
};

/* PIN_CHANGE_VISA_REQ_37*/
static TSAtallaMsgLayout gs_ly_PIN_CHANGE_VISA_37_REQ = {
		ATALLA_MN_REQ_PIN_CHANGE_VISA_37,11,2048,ATALLA_FN_CMD_REQ_PIN_CHANGE_VISA_37,
	{
		{ATALLA_FN_PIN_METHOD					},
		{ATALLA_FN_INC_PIN_BLOCK_FORMAT			},
		{ATALLA_FN_INC_PIN_BLOCK				},
		{ATALLA_FN_INC_KEY						},
		{ATALLA_FN_PVK							},
		{ATALLA_FN_PVK_2						},
		{ATALLA_FN_PVV							},
		{ATALLA_FN_PVKI							},
		{ATALLA_FN_PAN							},
		{ATALLA_FN_NEW_PIN_BLOCK				},
		{ATALLA_FN_INC_PIN_BLOCK_DATA			},

	}
};

/* PIN_CHANGE_VISA_RESP_47*/
static TSAtallaMsgLayout gs_ly_PIN_CHANGE_VISA_47_RESP = {
		ATALLA_MN_RESP_PIN_CHANGE_VISA_47,3,2048,ATALLA_FN_CMD_RESP_PIN_CHANGE_VISA_47,
	{
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_NEW_PVV						},
		{ATALLA_FN_IBM_SEQ_NUMBER				},
	}
};

/* VERIFY_ARQC_REQ_350*/
static TSAtallaMsgLayout gs_ly_VERIFY_ARQC_350_REQ = {
		ATALLA_MN_REQ_VERIFY_ARQC_350,12,2048,ATALLA_FN_CMD_REQ_VERIFY_ARQC_350,
	{
		{ATALLA_FN_DERIVATION_TYPE				},
		{ATALLA_FN_KEY_AC						},
		{ATALLA_FN_PAN							},
		{ATALLA_FN_PAN_SEQ_NUMBER				},
		{ATALLA_FN_DIVERSIFICATION_DATA			},
		{ATALLA_FN_ARQC							},
		{ATALLA_FN_PADDED_DATA_BLOCK			},
		{ATALLA_FN_ARC							},
		{ATALLA_FN_H_EMV_TREE					},
		{ATALLA_FN_IV_EMV_TREE					},
		{ATALLA_FN_INDEX_EMV_TREE				},
		{ATALLA_FN_FRC							},

	}
};

/* VERIFY_ARQC_RESP_450*/
static TSAtallaMsgLayout gs_ly_VERIFY_ARQC_450_RESP = {
		ATALLA_MN_RESP_VERIFY_ARQC_450,4,2048,ATALLA_FN_CMD_RESP_VERIFY_ARQC_450,
	{
		{ATALLA_FN_ARPC							},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
		{ATALLA_FN_VERIFICATION_FLAG			},
	}
};

/* EMV_PIN_CHANGE_REQ_351*/
static TSAtallaMsgLayout gs_ly_EMV_PIN_CHANGE_351_REQ = {
		ATALLA_MN_REQ_EMV_PIN_CHANGE_351,18,2048,ATALLA_FN_CMD_REQ_EMV_PIN_CHANGE_351,
	{
		{ATALLA_FN_DERIVATION_TYPE				},
		{ATALLA_FN_INC_PIN_BLOCK_FORMAT			},
		{ATALLA_FN_KEY_USAGE					},
		{ATALLA_FN_INC_KEY						},
		{ATALLA_FN_KEY_ENC						},
		{ATALLA_FN_KEY_MAC						},
		{ATALLA_FN_KEY_AC						},
		{ATALLA_FN_NEW_PIN_BLOCK				},
		{ATALLA_FN_PIN_ISSUE_NUMBER				},
		{ATALLA_FN_PAN							},
		{ATALLA_FN_PAN_SEQ_NUMBER				},
		{ATALLA_FN_DIVERSIFICATION_DATA			},
		{ATALLA_FN_APPLICATION_DATA				},
		{ATALLA_FN_INC_PIN_BLOCK_DATA			},
		{ATALLA_FN_INC_PIN_BLOCK				},
		{ATALLA_FN_H_EMV_TREE					},
		{ATALLA_FN_IV_EMV_TREE					},
		{ATALLA_FN_INDEX_EMV_TREE				},


	}
};

/* EMV_PIN_CHANGE_RESP_451*/
static TSAtallaMsgLayout gs_ly_EMV_PIN_CHANGE_451_RESP = {
		ATALLA_MN_RESP_EMV_PIN_CHANGE_451,9,2048,ATALLA_FN_CMD_RESP_EMV_PIN_CHANGE_451,
	{
		{ATALLA_FN_SANITY_CHECK_IND				},
		{ATALLA_FN_OUTG_PIN_BLOCK				},
		{ATALLA_FN_MAC							},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
		{ATALLA_FN_CHECK_DIGITS_3				},
		{ATALLA_FN_CHECK_DIGITS_3				},
		{ATALLA_FN_CHECK_DIGITS_3				},
		{ATALLA_FN_CHECK_DIGITS_3				},

	}
};

/* GENERATE_EMV_MAC_REQ_352*/
static TSAtallaMsgLayout gs_ly_GENERATE_EMV_MAC_352_REQ = {
		ATALLA_MN_REQ_GENERATE_EMV_MAC_352,11,2048,ATALLA_FN_CMD_REQ_GENERATE_EMV_MAC_352,
	{
		{ATALLA_FN_DERIVATION_TYPE				},
		{ATALLA_FN_KEY_MAC						},
		{ATALLA_FN_PAN							},
		{ATALLA_FN_PAN_SEQ_NUMBER				},
		{ATALLA_FN_DIVERSIFICATION_DATA			},
		{ATALLA_FN_MAC_LENGTH					},
		{ATALLA_FN_CONTINUATION_INIT_VECTOR		},
		{ATALLA_FN_PADDED_DATA_BLOCK			},
		{ATALLA_FN_H_EMV_TREE					},
		{ATALLA_FN_IV_EMV_TREE					},
		{ATALLA_FN_INDEX_EMV_TREE				},
	}
};

/* GENERATE_EMV_MAC_RESP_452*/
static TSAtallaMsgLayout gs_ly_GENERATE_EMV_MAC_452_RESP = {
		ATALLA_MN_RESP_GENERATE_EMV_MAC_452,4,2048,ATALLA_FN_CMD_RESP_GENERATE_EMV_MAC_452,
	{
		{ATALLA_FN_MAC_LENGTH					},
		{ATALLA_FN_MAC							},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
	}
};

/* EMV_PIN_CHANGE_IBM_REQ_3FC*/
static TSAtallaMsgLayout gs_ly_EMV_PIN_CHANGE_IBM_3FC_REQ = {
		ATALLA_MN_REQ_EMV_PIN_CHANGE_IBM_3FC,14,2048,ATALLA_FN_CMD_REQ_EMV_PIN_CHANGE_IBM_3FC,
	{
		{ATALLA_FN_DERIVATION_TYPE				},
		{ATALLA_FN_PIN_METHOD					},
		{ATALLA_FN_KEY_ENC						},
		{ATALLA_FN_KEY_MAC						},
		{ATALLA_FN_KEY_AC						},
		{ATALLA_FN_PAN							},
		{ATALLA_FN_PAN_SEQ_NUMBER				},
		{ATALLA_FN_DIVERSIFICATION_DATA			},
		{ATALLA_FN_APPLICATION_DATA				},
		{ATALLA_FN_PVK							},
		{ATALLA_FN_CONVERSION_TABLE				},
		{ATALLA_FN_OFFSET						},
		{ATALLA_FN_VALIDATION_DATA				},
		{ATALLA_FN_PAD							},
	}
};

/* EMV_PIN_CHANGE_IBM_RESP_4FC*/
static TSAtallaMsgLayout gs_ly_EMV_PIN_CHANGE_IBM_4FC_RESP = {
		ATALLA_MN_RESP_EMV_PIN_CHANGE_IBM_4FC,8,2048,ATALLA_FN_CMD_RESP_EMV_PIN_CHANGE_IBM_4FC,
	{
		{ATALLA_FN_OUTG_PIN_BLOCK				},
		{ATALLA_FN_MAC							},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
		{ATALLA_FN_CHECK_DIGITS_3				},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
		{ATALLA_FN_CHECK_DIGITS_3				},
	}
};

/* GENERATE_MAC_REQ_98*/
static TSAtallaMsgLayout gs_ly_GENERATE_MAC_98_REQ = {
		ATALLA_MN_REQ_GENERATE_MAC_98,8,2048,ATALLA_FN_CMD_REQ_GENERATE_MAC_98,
	{
		{ATALLA_FN_MSG_AUTHENTICATION_KEY		},
		{ATALLA_FN_MAC_LENGTH					},
		{ATALLA_FN_MAC_ALGORITHM				},
		{ATALLA_FN_CONTINUATION_INIT_VECTOR		},
		{ATALLA_FN_DATA_FORMAT					},
		{ATALLA_FN_DATA_LENGTH					},
		{ATALLA_FN_DATA							},
		{ATALLA_FN_KEY_USAGE					},

	}
};

/* GENERATE_MAC_RESP_A8*/
static TSAtallaMsgLayout gs_ly_GENERATE_MAC_A8_RESP = {
		ATALLA_MN_RESP_GENERATE_MAC_A8,4,2048,ATALLA_FN_CMD_RESP_GENERATE_MAC_A8,
	{
		{ATALLA_FN_MAC_LENGTH					},
		{ATALLA_FN_MAC							},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_MAC_ALGORITHM				},
	}
};

/* VERIFY_MAC_REQ_99*/
static TSAtallaMsgLayout gs_ly_VERIFY_MAC_99_REQ = {
		ATALLA_MN_REQ_VERIFY_MAC_99,9,2048,ATALLA_FN_CMD_REQ_VERIFY_MAC_99,
	{
		{ATALLA_FN_MSG_AUTHENTICATION_KEY		},
		{ATALLA_FN_MAC_ALGORITHM				},
		{ATALLA_FN_CONTINUATION_INIT_VECTOR		},
		{ATALLA_FN_MAC_LENGTH					},
		{ATALLA_FN_DATA_FORMAT					},
		{ATALLA_FN_DATA_LENGTH					},
		{ATALLA_FN_DATA							},
		{ATALLA_FN_MAC							},
		{ATALLA_FN_KEY_USAGE					},

	}
};

/* VERIFY_MAC_RESP_A9*/
static TSAtallaMsgLayout gs_ly_VERIFY_MAC_A9_RESP = {
		ATALLA_MN_RESP_VERIFY_MAC_A9,4,2048,ATALLA_FN_CMD_RESP_VERIFY_MAC_A9,
	{
		{ATALLA_FN_MAC_LENGTH					},
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_MAC_ALGORITHM				},
	}
};

/* GENERATE_MAC_HMAC_REQ_39B*/
static TSAtallaMsgLayout gs_ly_GENERATE_MAC_HMAC_39B_REQ = {
		ATALLA_MN_REQ_GENERATE_MAC_HMAC_39B,4,2048,ATALLA_FN_CMD_REQ_GENERATE_MAC_HMAC_39B,
	{
		{ATALLA_FN_MSG_AUTHENTICATION_KEY		},
		{ATALLA_FN_MSG_AUTHENTICATION_KEY_2		},
		{ATALLA_FN_MAC_ALGORITHM				},
		{ATALLA_FN_DATA							},

	}
};

/* GENERATE_MAC_HMAC_RESP_49B*/
static TSAtallaMsgLayout gs_ly_GENERATE_MAC_HMAC_49B_RESP = {
		ATALLA_MN_RESP_GENERATE_MAC_HMAC_49B,3,2048,ATALLA_FN_CMD_RESP_GENERATE_MAC_HMAC_49B,
	{
		{ATALLA_FN_MAC							},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
	}
};

/* GENERATE_RSA_KEY_PAIR_REQ_120*/
static TSAtallaMsgLayout gs_ly_GENERATE_RSA_KEY_PAIR_120_REQ = {
		ATALLA_MN_REQ_GENERATE_RSA_KEY_PAIR_120,4,2048,ATALLA_FN_CMD_REQ_GENERATE_RSA_KEY_PAIR_120,
	{
		{ATALLA_FN_KEY_USAGE					},
		{ATALLA_FN_PUBLIC_EXPONENT				},
		{ATALLA_FN_MODULUS_SIZE					},
		{ATALLA_FN_KEY_SLOT						},

	}
};

/* GENERATE_RSA_KEY_PAIR_RESP_220*/
static TSAtallaMsgLayout gs_ly_GENERATE_RSA_KEY_PAIR_220_RESP = {
		ATALLA_MN_RESP_GENERATE_RSA_KEY_PAIR_220,4,2048,ATALLA_FN_CMD_RESP_GENERATE_RSA_KEY_PAIR_220,
	{
		{ATALLA_FN_RSA_PUBLIC_KEY				},
		{ATALLA_FN_RSA_PRIVATE_KEY				},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_KEY_SLOT						},
	}
};

/* VERIF_PUB_KEY_AND_GEN_RSA_AKB_REQ_123*/
static TSAtallaMsgLayout gs_ly_VERIF_PUB_KEY_AND_GEN_RSA_AKB_123_REQ = {
		ATALLA_MN_REQ_VERIF_PUB_KEY_AND_GEN_RSA_AKB_123,8,2048,ATALLA_FN_CMD_REQ_VERIF_PUB_KEY_AND_GEN_RSA_AKB_123,
	{
		{ATALLA_FN_KEY_USAGE					},
		{ATALLA_FN_HASH_ALGORITHM				},
		{ATALLA_FN_SIGNATURE_ALGORITHM			},
		{ATALLA_FN_PUBLIC_EXPONENT				},
		{ATALLA_FN_MODULUS_SIZE					},
		{ATALLA_FN_PUBLIC_KEY_DATA				},
		{ATALLA_FN_SIGNATURE					},
		{ATALLA_FN_CA_PUBLIC_KEY				},

	}
};

/* VERIF_PUB_KEY_AND_GEN_RSA_AKB_RESP_223*/
static TSAtallaMsgLayout gs_ly_VERIF_PUB_KEY_AND_GEN_RSA_AKB_223_RESP = {
		ATALLA_MN_RESP_VERIF_PUB_KEY_AND_GEN_RSA_AKB_223,2,2048,ATALLA_FN_CMD_RESP_VERIF_PUB_KEY_AND_GEN_RSA_AKB_223,
	{
		{ATALLA_FN_RSA_PUBLIC_KEY				},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* GEN_DIGITAL_SIGNATURE_REQ_124*/
static TSAtallaMsgLayout gs_ly_GEN_DIGITAL_SIGNATURE_124_REQ = {
		ATALLA_MN_REQ_GEN_DIGITAL_SIGNATURE_124,7,2048,ATALLA_FN_CMD_REQ_GEN_DIGITAL_SIGNATURE_124,
	{
		{ATALLA_FN_KEY_USAGE					},
		{ATALLA_FN_HASH_ALGORITHM				},
		{ATALLA_FN_SIGNATURE_ALGORITHM			},
		{ATALLA_FN_DATA_LENGTH					},
		{ATALLA_FN_DATA							},
		{ATALLA_FN_EMPTY_FIELD					},
		{ATALLA_FN_RSA_PRIVATE_KEY				},

	}
};

/* GEN_DIGITAL_SIGNATURE_RESP_224*/
static TSAtallaMsgLayout gs_ly_GEN_DIGITAL_SIGNATURE_224_RESP = {
		ATALLA_MN_RESP_GEN_DIGITAL_SIGNATURE_224,3,2048,ATALLA_FN_CMD_RESP_GEN_DIGITAL_SIGNATURE_224,
	{
		{ATALLA_FN_KEY_USAGE					},
		{ATALLA_FN_SIGNATURE					},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* VERIF_DIGITAL_SIGNATURE_REQ_125*/
static TSAtallaMsgLayout gs_ly_VERIF_DIGITAL_SIGNATURE_125_REQ = {
		ATALLA_MN_REQ_VERIF_DIGITAL_SIGNATURE_125,8,2048,ATALLA_FN_CMD_REQ_VERIF_DIGITAL_SIGNATURE_125,
	{
		{ATALLA_FN_KEY_USAGE					},
		{ATALLA_FN_HASH_ALGORITHM				},
		{ATALLA_FN_SIGNATURE_ALGORITHM			},
		{ATALLA_FN_DATA_LENGTH					},
		{ATALLA_FN_DATA							},
		{ATALLA_FN_EMPTY_FIELD					},
		{ATALLA_FN_SIGNATURE					},
		{ATALLA_FN_RSA_PUBLIC_KEY				},

	}
};

/* VERIF_DIGITAL_SIGNATURE_RESP_225*/
static TSAtallaMsgLayout gs_ly_VERIF_DIGITAL_SIGNATURE_225_RESP = {
		ATALLA_MN_RESP_VERIF_DIGITAL_SIGNATURE_225,3,2048,ATALLA_FN_CMD_RESP_VERIF_DIGITAL_SIGNATURE_225,
	{
		{ATALLA_FN_KEY_USAGE					},
		{ATALLA_FN_VERIFICATION_FLAG			},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* GEN_MESSAGE_DIGEST_REQ_126*/
static TSAtallaMsgLayout gs_ly_GEN_MESSAGE_DIGEST_126_REQ = {
		ATALLA_MN_REQ_GEN_MESSAGE_DIGEST_126,6,2048,ATALLA_FN_CMD_REQ_GEN_MESSAGE_DIGEST_126,
	{
		{ATALLA_FN_FLAG							},
		{ATALLA_FN_HASH_ALGORITHM				},
		{ATALLA_FN_ENCODING						},
		{ATALLA_FN_DATA_LENGTH					},
		{ATALLA_FN_DATA							},
		{ATALLA_FN_INTERMEDIATE_RESULT			},

	}
};

/* GEN_MESSAGE_DIGEST_RESP_226*/
static TSAtallaMsgLayout gs_ly_GEN_MESSAGE_DIGEST_226_RESP = {
		ATALLA_MN_RESP_GEN_MESSAGE_DIGEST_226,3,2048,ATALLA_FN_CMD_RESP_GEN_MESSAGE_DIGEST_226,
	{
		{ATALLA_FN_FLAG							},
		{ATALLA_FN_MESSAGE_DIGEST				},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* GEN_TMK_AND_ENCRYPT_PK_REQ_12F*/
static TSAtallaMsgLayout gs_ly_GEN_TMK_AND_ENCRYPT_PK_12F_REQ = {
		ATALLA_MN_REQ_GEN_TMK_AND_ENCRYPT_PK_12F,5,2048,ATALLA_FN_CMD_REQ_GEN_TMK_AND_ENCRYPT_PK_12F,
	{
		{ATALLA_FN_KEY_LENGTH					},
		{ATALLA_FN_DATA_LENGTH					},
		{ATALLA_FN_DATA							},
		{ATALLA_FN_RSA_PUBLIC_KEY				},
		{ATALLA_FN_MASTER_KEY_HEADER			},
	}
};

/* GEN_TMK_AND_ENCRYPT_PK_RESP_22F*/
static TSAtallaMsgLayout gs_ly_GEN_TMK_AND_ENCRYPT_PK_22F_RESP = {
		ATALLA_MN_RESP_GEN_TMK_AND_ENCRYPT_PK_22F,5,2048,ATALLA_FN_CMD_RESP_GEN_TMK_AND_ENCRYPT_PK_22F,
	{
		{ATALLA_FN_KEY_LENGTH					},
		{ATALLA_FN_ATM_MASTER_KEY				},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_ATM_MASTER_KEY_UNDER_PK		},
		{ATALLA_FN_CHECK_DIGITS_2				},
	}
};

/* GEN_CHECK_DIGITS_REQ_7E*/
static TSAtallaMsgLayout gs_ly_GEN_CHECK_DIGITS_7E_REQ = {
		ATALLA_MN_REQ_GEN_CHECK_DIGITS_7E,3,2048,ATALLA_FN_CMD_REQ_GEN_CHECK_DIGITS_7E,
	{
		{ATALLA_FN_METHOD						},
		{ATALLA_FN_KEY_USAGE					},
		{ATALLA_FN_WORKING_KEY_MFK				},

	}
};

/* GEN_CHECK_DIGITS_RESP_8E*/
static TSAtallaMsgLayout gs_ly_GEN_CHECK_DIGITS_8E_RESP = {
		ATALLA_MN_RESP_GEN_CHECK_DIGITS_8E,2,2048,ATALLA_FN_CMD_RESP_GEN_CHECK_DIGITS_8E,
	{
		{ATALLA_FN_METHOD						},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};

/* TRANSLATE_ISO_PIN_REQ_3E*/
static TSAtallaMsgLayout gs_ly_TRANSLATE_ISO_PIN_3E_REQ = {
		ATALLA_MN_REQ_TRANSLATE_ISO_PIN_3E,11,2048,ATALLA_FN_CMD_REQ_TRANSLATE_ISO_PIN_3E,
	{
		{ATALLA_FN_INC_PIN_BLOCK_FORMAT			},
		{ATALLA_FN_OUTG_PIN_BLOCK_FORMAT		},
		{ATALLA_FN_INC_KEY						},
		{ATALLA_FN_INC_KEY_MNG					},
		{ATALLA_FN_INC_KEY_KSN					},
		{ATALLA_FN_OUTG_KEY						},
		{ATALLA_FN_OUTG_KEY_MNG					},
		{ATALLA_FN_OUTG_KEY_KSN					},
		{ATALLA_FN_INC_PIN_BLOCK				},
		{ATALLA_FN_INC_PIN_BLOCK_DATA			},
		{ATALLA_FN_OUTG_PIN_BLOCK_DATA			},
	}
};

/* TRANSLATE_ISO_PIN_RESP_4E*/
static TSAtallaMsgLayout gs_ly_TRANSLATE_ISO_PIN_4E_RESP = {
		ATALLA_MN_RESP_TRANSLATE_ISO_PIN_4E,4,2048,ATALLA_FN_CMD_RESP_TRANSLATE_ISO_PIN_4E,
	{
		{ATALLA_FN_OUTG_PIN_BLOCK				},
		{ATALLA_FN_SANITY_CHECK_IND				},
		{ATALLA_FN_CHECK_DIGITS					},
		{ATALLA_FN_CHECK_DIGITS_2				},
	}
};

/* IMPORT_KEY_NAKB_REQ_11B*/
static TSAtallaMsgLayout gs_ly_IMPORT_KEY_NAKB_11B_REQ = {
	ATALLA_MN_REQ_IMPORT_KEY_NAKB_11B,3,2048,ATALLA_FN_CMD_REQ_IMPORT_KEY_NAKB_11B,
	{
		{ATALLA_FN_KEY_USAGE				},
		{ATALLA_FN_WORKING_KEY_KEK			},
		{ATALLA_FN_KEY_EXCHANGE_KEY			},

	}
};

/* IMPORT_KEY_NAKB_RESP_21B*/
static TSAtallaMsgLayout gs_ly_IMPORT_KEY_NAKB_21B_RESP = {
	ATALLA_MN_RESP_IMPORT_KEY_NAKB_21B,2,2048,ATALLA_FN_CMD_RESP_IMPORT_KEY_NAKB_21B,
	{
		{ATALLA_FN_WORKING_KEY_MFK				},
		{ATALLA_FN_CHECK_DIGITS					},
	}
};


static TSAtallaMsgLayout* tab_atalla_layouts[ATALLA_LAYOUT_TYPE_QTY] = {

&gs_ly_UNKOWN_RESP,							/*	ATALLA_MN_UNKOWN_RESP_00					*/
&gs_ly_GENERATE_KEY_REQ,                    /*	ATALLA_MN_GENERATE_KEY_10					*/
&gs_ly_GENERATE_KEY_RESP,                   /*	ATALLA_MN_GENERATE_KEY_20					*/
&gs_ly_EXPORT_KEY_REQ,						/*	ATALLA_MN_GENERATE_KEY_11					*/
&gs_ly_EXPORT_KEY_RESP,						/*	ATALLA_MN_GENERATE_KEY_21					*/
&gs_ly_IMPORT_KEY_REQ,
&gs_ly_IMPORT_KEY_RESP,
&gs_ly_EXPORT_KEY_1A_REQ,
&gs_ly_EXPORT_KEY_2A_RESP,
&gs_ly_VERIFY_CVV_5E_REQ,
&gs_ly_VERIFY_CVV_6E_RESP,
&gs_ly_VERIFY_DCVV_357_REQ,
&gs_ly_VERIFY_DCVV_457_RESP,
&gs_ly_VERIFY_CVC3_359_REQ,
&gs_ly_VERIFY_CVC3_459_RESP,
&gs_ly_VERIFY_CSC_35A_REQ,
&gs_ly_VERIFY_CSC_45A_RESP,
&gs_ly_TRANSLATE_PIN_335_REQ,
&gs_ly_TRANSLATE_PIN_435_RESP,
&gs_ly_VERIFY_PIN_IBM_32_REQ,
&gs_ly_VERIFY_PIN_IBM_42_RESP,
&gs_ly_VERIFY_PIN_VISA_32_REQ,
&gs_ly_VERIFY_PIN_VISA_42_RESP,
&gs_ly_PIN_CHANGE_IBM_37_REQ,
&gs_ly_PIN_CHANGE_IBM_47_RESP,
&gs_ly_PIN_CHANGE_VISA_37_REQ,
&gs_ly_PIN_CHANGE_VISA_47_RESP,
&gs_ly_VERIFY_ARQC_350_REQ,
&gs_ly_VERIFY_ARQC_450_RESP,
&gs_ly_EMV_PIN_CHANGE_351_REQ,
&gs_ly_EMV_PIN_CHANGE_451_RESP,
&gs_ly_GENERATE_EMV_MAC_352_REQ,
&gs_ly_GENERATE_EMV_MAC_452_RESP,
&gs_ly_EMV_PIN_CHANGE_IBM_3FC_REQ,
&gs_ly_EMV_PIN_CHANGE_IBM_4FC_RESP,
&gs_ly_GENERATE_MAC_98_REQ,
&gs_ly_GENERATE_MAC_A8_RESP,
&gs_ly_VERIFY_MAC_99_REQ,
&gs_ly_VERIFY_MAC_A9_RESP,
&gs_ly_GENERATE_MAC_HMAC_39B_REQ,
&gs_ly_GENERATE_MAC_HMAC_49B_RESP,
&gs_ly_GENERATE_RSA_KEY_PAIR_120_REQ,
&gs_ly_GENERATE_RSA_KEY_PAIR_220_RESP,
&gs_ly_VERIF_PUB_KEY_AND_GEN_RSA_AKB_123_REQ,
&gs_ly_VERIF_PUB_KEY_AND_GEN_RSA_AKB_223_RESP,
&gs_ly_GEN_DIGITAL_SIGNATURE_124_REQ,
&gs_ly_GEN_DIGITAL_SIGNATURE_224_RESP,
&gs_ly_VERIF_DIGITAL_SIGNATURE_125_REQ,
&gs_ly_VERIF_DIGITAL_SIGNATURE_225_RESP,
&gs_ly_GEN_MESSAGE_DIGEST_126_REQ,
&gs_ly_GEN_MESSAGE_DIGEST_226_RESP,
&gs_ly_GEN_TMK_AND_ENCRYPT_PK_12F_REQ,
&gs_ly_GEN_TMK_AND_ENCRYPT_PK_22F_RESP,
&gs_ly_GEN_CHECK_DIGITS_7E_REQ,
&gs_ly_GEN_CHECK_DIGITS_8E_RESP,
&gs_ly_TRANSLATE_ISO_PIN_3E_REQ,
&gs_ly_TRANSLATE_ISO_PIN_4E_RESP,
&gs_ly_IMPORT_KEY_NAKB_11B_REQ,
&gs_ly_IMPORT_KEY_NAKB_21B_RESP,

};




int InitAtallaCmd(TSAtallaCmd* pkAtallaCmd, E_ATALLA_LAYOUT_TYPE eCmdType)
{
	char sLine[MAX_LINE_TRC];
	TSAtallaMsgLayout* pkAtallaMsgLayout;

	if( eCmdType >= ATALLA_LAYOUT_TYPE_QTY )
	{
		sprintf(sLine,"Invalid Atalla Layout (%d)",eCmdType);
		trace_event(sLine,ERROR);
		return NOK;
	}

	pkAtallaMsgLayout = tab_atalla_layouts[eCmdType];

	if( pkAtallaMsgLayout->eLayoutType == ATALLA_LAYOUT_TYPE_QTY )
	{
		sprintf(sLine,"Undefined Atalla Layout (%d)",eCmdType);
		trace_event(sLine,ERROR);
	}
	ResetAtallaCmdInfo(pkAtallaCmd);
	pkAtallaCmd->pkLayout = pkAtallaMsgLayout;
	pkAtallaCmd->pkProperties = &AtallaFieldsDataProp;
	pkAtallaCmd->pkCmdTagProperties = &AtallaCmdTagProp;
	return OK;
}

