#ifndef HPS_CB2A_FIELDS_H
#define HPS_CB2A_FIELDS_H

#define CB2A_BIT_MAP2                    0
#define CB2A_CARD_NBR                    1
#define CB2A_PROC_CODE                   2
#define CB2A_TRANS_AMOUNT                3
#define CB2A_STLMNT_AMOUNT               4
#define CB2A_BILLING_AMOUNT              5
#define CB2A_XMIT_TIME                   6
#define CB2A_BILLING_AMOUNT_FEES         7
#define CB2A_STLMNT_CNVRSN_RATE          8
#define CB2A_BILLING_CNVRSN_RATE         9
#define CB2A_AUDIT_NBR                   10
#define CB2A_TRANS_DATE_TIME             11
#define CB2A_START_EXPIRY_DATE           12
#define CB2A_EXPIRY_DATE                 13
#define CB2A_STLMNT_DATE                 14
#define CB2A_CNVRSN_DATE                 15
#define CB2A_CAPTURE_DATE                16
#define CB2A_MERCHANT_TYPE               17
#define CB2A_ACQR_COUNTRY                18
#define CB2A_PAN_COUNTRY                 19
#define CB2A_FORWD_COUNTRY               20
#define CB2A_POS_DATA                    21
#define CB2A_CARD_SEQUENCE_NBR           22
#define CB2A_FUNCTION_CODE               23
#define CB2A_MSG_REASON                  24
#define CB2A_ACCEPTOR_ACTIV_CODE         25
#define CB2A_AUTHOR_ID_LENGTH            26
#define CB2A_RECONC_DATE                 27
#define CB2A_RECONC_INDICATOR            28
#define CB2A_ORIGINAL_AMOUNTS            29
#define CB2A_ACQR_REFERENCE_DATA         30
#define CB2A_ACQR_ID                     31
#define CB2A_FORWD_ID                    32
#define CB2A_PAN_EXTENDED                33
#define CB2A_T2_DATA                     34
#define CB2A_T3_DATA                     35
#define CB2A_REFERENCE_NBR               36
#define CB2A_AUTHOR_ID                   37
#define CB2A_RESPONSE_CODE               38
#define CB2A_SERVICE_CODE                39
#define CB2A_TERMINAL_NBR                40
#define CB2A_OUTLET_NBR                  41
#define CB2A_TERMINAL_ADR                42
#define CB2A_ADTNL_RESP_DATA             43
#define CB2A_T1_DATA                     44
#define CB2A_FEES_AMOUNT                 45
#define CB2A_ADTNL_DATA_NATL             46
#define CB2A_ADTNL_DATA_PRIV             47
#define CB2A_TRANS_CRNCY                 48
#define CB2A_STLMNT_CRNCY                49
#define CB2A_BILLING_CRNCY               50
#define CB2A_PIN_DATA                    51
#define CB2A_SECURITY_DATA               52
#define CB2A_ADTNL_AMOUNTS               53
#define CB2A_ICC_DATA                    54
#define CB2A_ORIG_DATA                   55
#define CB2A_AUTHORIZATION_CYCLE_CODE    56
#define CB2A_AUTHOR_INSTITN_ID_CODE      57
#define CB2A_NATNL_DATA                  58
#define CB2A_ADTNL_POS_INFO              59
#define CB2A_NET_POS_DATA                60
#define CB2A_CPS_FIELDS                  61
#define CB2A_NETWORK_DATA                62
#define CB2A_MAC1                        63
#define CB2A_STLMNT_CODE                 65
#define CB2A_RECEIVER_COUNTRY            67
#define CB2A_STLMNT_INST_COUNTRY         68
#define CB2A_NW_MNGMT_INFO               69
#define CB2A_MESSAGE_NBR                 70
#define CB2A_RECORD_DATA                 71
#define CB2A_ACTION_DATE                 72
#define CB2A_CR_NBR                      73
#define CB2A_CR_REV_NBR                  74
#define CB2A_DB_NBR                      75
#define CB2A_DB_REV_NBR                  76
#define CB2A_TRANSFER_NBR                77
#define CB2A_TRANSFER_REV_NBR            78
#define CB2A_INQ_NBR                     79
#define CB2A_AUT_NBR                     80
#define CB2A_INF_REV_NBR                 81
#define CB2A_PAYMENT_NBR                 82
#define CB2A_PAYMENT_REV_NBR             83
#define CB2A_FEES_COLLCT_NBR             84
#define CB2A_CR_AMOUNT                   85
#define CB2A_CR_REV_AMOUNT               86
#define CB2A_DB_AMOUNT                   87
#define CB2A_DB_REV_AMOUNT               88
#define CB2A_ADJUST_NBR                  89
#define CB2A_TRX_RECEIVER_COUNTRY_CODE   90
#define CB2A_TRX_ORIGINATOR_COUNTRY_CODE 91
#define CB2A_TRX_RECEIVER_ID             92
#define CB2A_TRX_ORIGINATOR_ID           93
#define CB2A_CARD_ISSUER_REF_DATA        94
#define CB2A_KEY_MNG_DATA                95
#define CB2A_NET_AMOUNT                  96
#define CB2A_STLMNT_INSTITN              98
#define CB2A_RECEIVER_ID                 99
#define CB2A_FILE_NAME                   100
#define CB2A_ACCOUNT_ID1                 101
#define CB2A_ACCOUNT_ID2                 102
#define CB2A_TRANS_DESC                  103
#define CB2A_CR_REJ_AMOUNT               104
#define CB2A_DB_REJ_AMOUNT               105
#define CB2A_CR_REJ_NUMBER               106
#define CB2A_DB_REJ_NUMBER               107
#define CB2A_CR_FEES_AMOUNT              108
#define CB2A_DB_FEES_AMOUNT              109
#define CB2A_RESERVED_CB2A_2             110
#define CB2A_RESERVED_CB2A_3             111
#define CB2A_RESERVED_CB2A_4             112
#define CB2A_RESERVED_CB2A_5             113
#define CB2A_ADTNL_TRACE_DATA            114
#define CB2A_TRANS_FEE                   115
#define CB2A_STLMNT_FEE                  116
#define CB2A_PROCES_FEE                  117
#define CB2A_ORIG_MSG_TYPE               119
#define CB2A_RESERV_NATIONAL_USAGE_6     120
#define CB2A_RESERV_PRIV_USAGE_1         121
#define CB2A_ADR_VERIF_DATA              122
#define CB2A_RESERV_PRIV_USAGE_3         123
#define CB2A_SUPPORT_INFO                124
#define CB2A_RESERVED_PRIVE_USAGE_5      125
#define CB2A_FILE_SEC_CODE               126
#define CB2A_MAC2                        127

#endif /** HPS_CB2A_FIELDS_H **/
