#ifndef HPS_EURO_ICTAG_H
#define HPS_EURO_ICTAG_H

#define    EURO_TAG_ISS_SCRIPT1         "7100"
#define    EURO_TAG_ISS_SCRIPT2         "7200"
#define    EURO_TAG_ISS_SCRIPT_CMD      "8600"
#define    EURO_TAG_APP_INTER_PROFILE   "8200"
#define    EURO_TAG_DED_FILE_NAME       "8400"
#define    EURO_TAG_ICC_APP_ID          "4F00"
#define    EURO_TAG_AUTHOR_RESP_CODE    "8A00"
#define    EURO_TAG_ISS_AUTHEN_DATA     "9100"
#define    EURO_TAG_TVR                 "9500"
#define    EURO_TAG_TRANS_DATE          "9A00"
#define    EURO_TAG_TRANS_TYPE          "9C00"
#define    EURO_TAG_TRANS_CUR_CODE      "5F2A"
#define    EURO_TAG_TRANS_AMOUNT        "9F02"
#define    EURO_TAG_OTHER_AMOUNT        "9F03"
#define    EURO_TAG_TERM_APP_VER_NUM    "9F09"
#define    EURO_TAG_ISS_APP_DATA        "9F10"
#define    EURO_TAG_TERM_COUNTRY_CODE   "9F1A"
#define    EURO_TAG_IFD_SERIAL_NUM      "9F1E"
#define    EURO_TAG_APP_CRYPTOGRAM      "9F26"
#define    EURO_TAG_CRYPTO_INFO_DATA    "9F27"
#define    EURO_TAG_TERM_CAP            "9F33"
#define    EURO_TAG_CVM                 "9F34"
#define    EURO_TAG_TERM_TYPE           "9F35"
#define    EURO_TAG_ATC                 "9F36"
#define    EURO_TAG_UNPRED_NUMBER       "9F37"
#define    EURO_TAG_TRANS_SEQ_NUM       "9F41"
#define    EURO_TAG_TRANS_CATEG_CODE    "9F53"

#endif /** HPS_EURO_ICTAG_H **/
