#ifndef PWC_HSM_ATALLA__DEFINE_H
#define PWC_HSM_ATALLA__DEFINE_H





/* Commands requests */
#define ATALLA_CMD_REQ_GENERATE_KEY_10 				"10"
#define ATALLA_CMD_REQ_EXPORT_KEY_11 				"11"
#define ATALLA_CMD_REQ_IMPORT_KEY_13 				"13"
#define ATALLA_CMD_REQ_EXPORT_KEY_1A				"1A"
#define ATALLA_CMD_REQ_VERIFY_CVV_5E				"5E"
#define ATALLA_CMD_REQ_VERIFY_DCVV_357				"357"
#define ATALLA_CMD_REQ_VERIFY_CVC3_359				"359"
#define ATALLA_CMD_REQ_VERIFY_CSC_35A				"35A"
#define ATALLA_CMD_REQ_TRANSLATE_PIN_335			"335"
#define ATALLA_CMD_REQ_VERIFY_PIN_IBM_32			"32"
#define ATALLA_CMD_REQ_VERIFY_PIN_VISA_32			"32"
#define ATALLA_CMD_REQ_PIN_CHANGE_IBM_37			"37"
#define ATALLA_CMD_REQ_PIN_CHANGE_VISA_37			"37"
#define ATALLA_CMD_REQ_VERIFY_ARQC_350				"350"
#define ATALLA_CMD_REQ_EMV_PIN_CHANGE_351			"351"
#define ATALLA_CMD_REQ_GENERATE_EMV_MAC_352			"352"
#define ATALLA_CMD_REQ_EMV_PIN_CHANGE_IBM_3FC		"3FC"
#define ATALLA_CMD_REQ_GENERATE_MAC_98				"98"
#define ATALLA_CMD_REQ_VERIFY_MAC_99				"99"
#define ATALLA_CMD_REQ_GENERATE_MAC_HMAC_39B		"39B"
#define ATALLA_CMD_REQ_GENERATE_RSA_KEY_PAIR_120	"120"
#define ATALLA_CMD_REQ_VERIF_PUB_KEY_AND_GEN_RSA_AKB_123	"123"
#define ATALLA_CMD_REQ_GEN_DIGITAL_SIGNATURE_124	"124"
#define ATALLA_CMD_REQ_VERIF_DIGITAL_SIGNATURE_125	"125"
#define ATALLA_CMD_REQ_GEN_MESSAGE_DIGEST_126		"126"
#define ATALLA_CMD_REQ_GEN_TMK_AND_ENCRYPT_PK_12F	"12F"
#define ATALLA_CMD_REQ_GEN_CHECK_DIGITS_7E			"7E"
#define ATALLA_CMD_REQ_TRANSLATE_ISO_PIN_3E			"3E"
#define ATALLA_CMD_REQ_IMPORT_KEY_NAKB_11B			"11B"










/* Commands responses */
#define ATALLA_CMD_RESP_UNKOWN_00 					"00"		/*Réponse à Commande inconnue*/
#define ATALLA_CMD_RESP_GENERATE_KEY_20 			"20"
#define ATALLA_CMD_RESP_EXPORT_KEY_21 				"21"
#define ATALLA_CMD_RESP_IMPORT_KEY_23 				"23"
#define ATALLA_CMD_RESP_EXPORT_KEY_2A 				"2A"
#define ATALLA_CMD_RESP_VERIFY_CVV_6E 				"6E"
#define ATALLA_CMD_RESP_VERIFY_DCVV_457 			"457"
#define ATALLA_CMD_RESP_VERIFY_CVC3_459 			"459"
#define ATALLA_CMD_RESP_VERIFY_CSC_45A				"45A"
#define ATALLA_CMD_RESP_TRANSLATE_PIN_435			"435"
#define ATALLA_CMD_RESP_VERIFY_PIN_IBM_42			"42"
#define ATALLA_CMD_RESP_VERIFY_PIN_VISA_42			"42"
#define ATALLA_CMD_RESP_PIN_CHANGE_IBM_47			"47"
#define ATALLA_CMD_RESP_PIN_CHANGE_VISA_47			"47"
#define ATALLA_CMD_RESP_VERIFY_ARQC_450				"450"
#define ATALLA_CMD_RESP_EMV_PIN_CHANGE_451			"451"
#define ATALLA_CMD_RESP_GENERATE_EMV_MAC_452		"452"
#define ATALLA_CMD_RESP_EMV_PIN_CHANGE_IBM_4FC		"4FC"
#define ATALLA_CMD_RESP_GENERATE_MAC_A8				"A8"
#define ATALLA_CMD_RESP_VERIFY_MAC_A9				"A9"
#define ATALLA_CMD_RESP_GENERATE_MAC_HMAC_49B		"49B"
#define ATALLA_CMD_RESP_GENERATE_RSA_KEY_PAIR_220	"220"
#define ATALLA_CMD_RESP_VERIF_PUB_KEY_AND_GEN_RSA_AKB_223	"223"
#define ATALLA_CMD_RESP_GEN_DIGITAL_SIGNATURE_224	"224"
#define ATALLA_CMD_RESP_VERIF_DIGITAL_SIGNATURE_225	"225"
#define ATALLA_CMD_RESP_GEN_MESSAGE_DIGEST_226		"226"
#define ATALLA_CMD_RESP_GEN_TMK_AND_ENCRYPT_PK_12F	"22F"
#define ATALLA_CMD_RESP_GEN_CHECK_DIGITS_8E			"8E"
#define ATALLA_CMD_RESP_TRANSLATE_ISO_PIN_4E		"4E"
#define ATALLA_CMD_RESP_IMPORT_KEY_NAKB_21B			"21B"




/* below order is as per pair REQ/RESP (tab_atalla_layouts) */
typedef enum {

	ATALLA_MN_UNKOWN_00							= 0	,

	ATALLA_MN_REQ_GENERATE_KEY_10					,
	ATALLA_MN_RESP_GENERATE_KEY_20					,
	ATALLA_MN_REQ_EXPORT_KEY_11						,
	ATALLA_MN_RESP_EXPORT_KEY_21					,
	ATALLA_MN_REQ_IMPORT_KEY_13						,
	ATALLA_MN_RESP_IMPORT_KEY_23					,
	ATALLA_MN_REQ_EXPORT_KEY_1A						,
	ATALLA_MN_RESP_EXPORT_KEY_2A					,
	ATALLA_MN_REQ_VERIFY_CVV_5E						,
	ATALLA_MN_RESP_VERIFY_CVV_6E					,
	ATALLA_MN_REQ_VERIFY_DCVV_357					,
	ATALLA_MN_RESP_VERIFY_DCVV_457					,
	ATALLA_MN_REQ_VERIFY_CVC3_359					,
	ATALLA_MN_RESP_VERIFY_CVC3_459					,
	ATALLA_MN_REQ_VERIFY_CSC_35A					,
	ATALLA_MN_RESP_VERIFY_CSC_45A					,
	ATALLA_MN_REQ_TRANSLATE_PIN_335					,
	ATALLA_MN_RESP_TRANSLATE_PIN_435				,
	ATALLA_MN_REQ_VERIFY_PIN_IBM_32					,
	ATALLA_MN_RESP_VERIFY_PIN_IBM_42				,
	ATALLA_MN_REQ_VERIFY_PIN_VISA_32				,
	ATALLA_MN_RESP_VERIFY_PIN_VISA_42				,
	ATALLA_MN_REQ_PIN_CHANGE_IBM_37					,
	ATALLA_MN_RESP_PIN_CHANGE_IBM_47				,
	ATALLA_MN_REQ_PIN_CHANGE_VISA_37				,
	ATALLA_MN_RESP_PIN_CHANGE_VISA_47				,
	ATALLA_MN_REQ_VERIFY_ARQC_350					,
	ATALLA_MN_RESP_VERIFY_ARQC_450					,
	ATALLA_MN_REQ_EMV_PIN_CHANGE_351				,
	ATALLA_MN_RESP_EMV_PIN_CHANGE_451				,
	ATALLA_MN_REQ_GENERATE_EMV_MAC_352				,
	ATALLA_MN_RESP_GENERATE_EMV_MAC_452				,
	ATALLA_MN_REQ_EMV_PIN_CHANGE_IBM_3FC			,
	ATALLA_MN_RESP_EMV_PIN_CHANGE_IBM_4FC			,
	ATALLA_MN_REQ_GENERATE_MAC_98					,
	ATALLA_MN_RESP_GENERATE_MAC_A8					,
	ATALLA_MN_REQ_VERIFY_MAC_99						,
	ATALLA_MN_RESP_VERIFY_MAC_A9					,
	ATALLA_MN_REQ_GENERATE_MAC_HMAC_39B				,
	ATALLA_MN_RESP_GENERATE_MAC_HMAC_49B			,
	ATALLA_MN_REQ_GENERATE_RSA_KEY_PAIR_120			,
	ATALLA_MN_RESP_GENERATE_RSA_KEY_PAIR_220		,
	ATALLA_MN_REQ_VERIF_PUB_KEY_AND_GEN_RSA_AKB_123	,
	ATALLA_MN_RESP_VERIF_PUB_KEY_AND_GEN_RSA_AKB_223,
	ATALLA_MN_REQ_GEN_DIGITAL_SIGNATURE_124			,
	ATALLA_MN_RESP_GEN_DIGITAL_SIGNATURE_224		,
	ATALLA_MN_REQ_VERIF_DIGITAL_SIGNATURE_125		,
	ATALLA_MN_RESP_VERIF_DIGITAL_SIGNATURE_225		,
	ATALLA_MN_REQ_GEN_MESSAGE_DIGEST_126			,
	ATALLA_MN_RESP_GEN_MESSAGE_DIGEST_226			,
	ATALLA_MN_REQ_GEN_TMK_AND_ENCRYPT_PK_12F		,
	ATALLA_MN_RESP_GEN_TMK_AND_ENCRYPT_PK_22F		,
	ATALLA_MN_REQ_GEN_CHECK_DIGITS_7E				,
	ATALLA_MN_RESP_GEN_CHECK_DIGITS_8E				,
	ATALLA_MN_REQ_TRANSLATE_ISO_PIN_3E				,
	ATALLA_MN_RESP_TRANSLATE_ISO_PIN_4E				,
	ATALLA_MN_REQ_IMPORT_KEY_NAKB_11B				,
	ATALLA_MN_RESP_IMPORT_KEY_NAKB_21B				,

	ATALLA_LAYOUT_TYPE_QTY
} E_ATALLA_LAYOUT_TYPE;


/* Tags */

#define		ATALLA_KEY_USAGE					"00"
#define		ATALLA_KEY_EXCHANGE_KEY				"01"
#define		ATALLA_KEY_LENGTH					"02"
#define		ATALLA_WORKING_KEY_MFK				"03"
#define		ATALLA_WORKING_KEY_KEK				"04"
#define		ATALLA_CHECK_DIGITS					"05"
#define		ATALLA_CVV_ALGORITHM				"06"
#define		ATALLA_CVV_KEY						"07"
#define		ATALLA_CVV_DATA						"08"
#define		ATALLA_CVV							"09"
#define		ATALLA_VERIFICATION_FLAG			"10"
#define		ATALLA_ISSUER_MASTER_KEY_CVV		"11"
#define		ATALLA_PAN							"12"
#define		ATALLA_PAN_SEQ_NUMBER				"13"
#define		ATALLA_EXPIRY_DATE					"14"
#define		ATALLA_SERVICE_CODE					"15"
#define		ATALLA_ATC							"16"
#define		ATALLA_DCVV							"17"
#define		ATALLA_ISSUER_MASTER_KEY_CVC3		"18"
#define		ATALLA_TRACK_1_2_DATA				"19"
#define		ATALLA_UNPREDICTABLE_NUMBER			"20"
#define		ATALLA_DCVC3						"21"
#define		ATALLA_CSC_DATA						"22"
#define		ATALLA_CARD_SECURITY_CODE_KEY		"23"
#define		ATALLA_CSC_5						"24"
#define		ATALLA_CSC_4						"25"
#define		ATALLA_CSC_3						"26"
#define		ATALLA_CHECK_DIGITS_2				"27"
#define		ATALLA_VERIFICATION_FLAG_2			"28"
#define		ATALLA_VERIFICATION_FLAG_3			"29"
#define		ATALLA_INC_PIN_BLOCK_FORMAT			"30"
#define		ATALLA_OUTG_PIN_BLOCK_FORMAT		"31"
#define		ATALLA_INC_KEY						"32"
#define		ATALLA_INC_KEY_USAGE				"33"
#define		ATALLA_OUTG_KEY						"34"
#define		ATALLA_OUTG_KEY_USAGE				"35"
#define		ATALLA_INC_PIN_BLOCK				"36"
#define		ATALLA_INC_PIN_BLOCK_DATA			"37"
#define		ATALLA_OUTG_PIN_BLOCK_DATA			"38"
#define		ATALLA_OUTG_PIN_BLOCK				"39"
#define		ATALLA_SANITY_CHECK_IND				"40"
#define		ATALLA_CHECK_DIGITS_3				"41"
#define		ATALLA_CHECK_DIGITS_4				"42"
#define		ATALLA_PIN_METHOD					"43"
#define		ATALLA_CONVERSION_TABLE				"44"
#define		ATALLA_OFFSET						"45"
#define		ATALLA_VALIDATION_DATA				"46"
#define		ATALLA_CHECK_LENGTH					"47"
#define		ATALLA_PAD							"48"
#define		ATALLA_PVK							"49"
#define		ATALLA_IBM_SEQ_NUMBER				"50"
#define		ATALLA_PVK_2						"51"
#define		ATALLA_PVV							"52"
#define		ATALLA_PVKI							"53"
#define		ATALLA_NEW_PIN_BLOCK				"54"
#define		ATALLA_NEW_OFFSET					"55"
#define		ATALLA_NEW_PVV						"56"
#define		ATALLA_DERIVATION_TYPE				"57"
#define		ATALLA_KEY_AC						"58"
#define		ATALLA_DIVERSIFICATION_DATA			"59"
#define		ATALLA_ARQC							"60"
#define		ATALLA_PADDED_DATA_BLOCK			"61"
#define		ATALLA_ARC							"62"
#define		ATALLA_H_EMV_TREE					"63"
#define		ATALLA_IV_EMV_TREE					"64"
#define		ATALLA_INDEX_EMV_TREE				"65"
#define		ATALLA_FRC							"66"
#define		ATALLA_ARPC							"67"
#define		ATALLA_KEY_ENC						"68"
#define		ATALLA_KEY_MAC						"69"
#define		ATALLA_PIN_ISSUE_NUMBER				"70"
#define		ATALLA_APPLICATION_DATA				"71"
#define		ATALLA_MAC_LENGTH					"72"
#define		ATALLA_CONTINUATION_INIT_VECTOR		"73"
#define		ATALLA_MAC							"74"
#define		ATALLA_MAC_ALGORITHM				"75"
#define		ATALLA_DATA_FORMAT					"76"
#define		ATALLA_DATA_LENGTH					"77"
#define		ATALLA_DATA							"78"
#define		ATALLA_MSG_AUTHENTICATION_KEY		"79"
#define		ATALLA_MSG_AUTHENTICATION_KEY_2		"80"
#define		ATALLA_PUBLIC_EXPONENT				"81"
#define		ATALLA_MODULUS_SIZE					"82"
#define		ATALLA_KEY_SLOT						"83"
#define		ATALLA_RSA_PUBLIC_KEY				"84"
#define		ATALLA_RSA_PRIVATE_KEY				"85"
#define		ATALLA_HASH_ALGORITHM				"86"
#define		ATALLA_SIGNATURE_ALGORITHM			"87"
#define		ATALLA_PUBLIC_KEY_DATA				"88"
#define		ATALLA_SIGNATURE					"89"
#define		ATALLA_CA_PUBLIC_KEY				"90"
#define		ATALLA_EMPTY_FIELD					"91"
#define		ATALLA_FLAG							"92"
#define		ATALLA_ENCODING						"93"
#define		ATALLA_INTERMEDIATE_RESULT			"94"
#define		ATALLA_MESSAGE_DIGEST				"95"
#define		ATALLA_MASTER_KEY_HEADER			"96"
#define		ATALLA_ATM_MASTER_KEY				"97"
#define		ATALLA_ATM_MASTER_KEY_UNDER_PK		"98"
#define		ATALLA_METHOD						"99"
#define		ATALLA_INC_KEY_MNG					"100"
#define		ATALLA_INC_KEY_KSN					"101"
#define		ATALLA_OUTG_KEY_MNG					"102"
#define		ATALLA_OUTG_KEY_KSN					"103"




/* below order is as per AtallaFieldsDataProp */
typedef enum {

	ATALLA_FN_KEY_USAGE							=0	,
	ATALLA_FN_KEY_EXCHANGE_KEY						,
	ATALLA_FN_KEY_LENGTH							,
	ATALLA_FN_WORKING_KEY_MFK						,
	ATALLA_FN_WORKING_KEY_KEK						,
	ATALLA_FN_CHECK_DIGITS							,
	ATALLA_FN_CVV_ALGORITHM							,
	ATALLA_FN_CVV_KEY								,
	ATALLA_FN_CVV_DATA								,
	ATALLA_FN_CVV									,
	ATALLA_FN_VERIFICATION_FLAG						,
	ATALLA_FN_ISSUER_MASTER_KEY_CVV					,
	ATALLA_FN_PAN									,
	ATALLA_FN_PAN_SEQ_NUMBER						,
	ATALLA_FN_EXPIRY_DATE							,
	ATALLA_FN_SERVICE_CODE							,
	ATALLA_FN_ATC									,
	ATALLA_FN_DCVV									,
	ATALLA_FN_ISSUER_MASTER_KEY_CVC3				,
	ATALLA_FN_TRACK_1_2_DATA						,
	ATALLA_FN_UNPREDICTABLE_NUMBER					,
	ATALLA_FN_DCVC3									,
	ATALLA_FN_CSC_DATA								,
	ATALLA_FN_CARD_SECURITY_CODE_KEY				,
	ATALLA_FN_CSC_5									,
	ATALLA_FN_CSC_4									,
	ATALLA_FN_CSC_3									,
	ATALLA_FN_CHECK_DIGITS_2						,
	ATALLA_FN_VERIFICATION_FLAG_2					,
	ATALLA_FN_VERIFICATION_FLAG_3					,
	ATALLA_FN_INC_PIN_BLOCK_FORMAT					,
	ATALLA_FN_OUTG_PIN_BLOCK_FORMAT					,
	ATALLA_FN_INC_KEY				                ,
	ATALLA_FN_INC_KEY_USAGE		                    ,
	ATALLA_FN_OUTG_KEY				                ,
	ATALLA_FN_OUTG_KEY_USAGE		                ,
	ATALLA_FN_INC_PIN_BLOCK		                    ,
	ATALLA_FN_INC_PIN_BLOCK_DATA	                ,
	ATALLA_FN_OUTG_PIN_BLOCK_DATA	                ,
	ATALLA_FN_OUTG_PIN_BLOCK		                ,
	ATALLA_FN_SANITY_CHECK_IND		                ,
	ATALLA_FN_CHECK_DIGITS_3		                ,
	ATALLA_FN_CHECK_DIGITS_4		                ,
	ATALLA_FN_PIN_METHOD							,
	ATALLA_FN_CONVERSION_TABLE	                    ,
	ATALLA_FN_OFFSET			                    ,
	ATALLA_FN_VALIDATION_DATA	                    ,
	ATALLA_FN_CHECK_LENGTH		                    ,
	ATALLA_FN_PAD				                    ,
	ATALLA_FN_PVK				                    ,
	ATALLA_FN_IBM_SEQ_NUMBER                        ,
	ATALLA_FN_PVK_2									,
	ATALLA_FN_PVV									,
	ATALLA_FN_PVKI									,
	ATALLA_FN_NEW_PIN_BLOCK							,
	ATALLA_FN_NEW_OFFSET							,
	ATALLA_FN_NEW_PVV								,
	ATALLA_FN_DERIVATION_TYPE						,
	ATALLA_FN_KEY_AC								,
	ATALLA_FN_DIVERSIFICATION_DATA					,
	ATALLA_FN_ARQC									,
	ATALLA_FN_PADDED_DATA_BLOCK						,
	ATALLA_FN_ARC									,
	ATALLA_FN_H_EMV_TREE							,
	ATALLA_FN_IV_EMV_TREE							,
	ATALLA_FN_INDEX_EMV_TREE						,
	ATALLA_FN_FRC									,
	ATALLA_FN_ARPC									,
	ATALLA_FN_KEY_ENC								,
	ATALLA_FN_KEY_MAC			                    ,
	ATALLA_FN_PIN_ISSUE_NUMBER                      ,
	ATALLA_FN_APPLICATION_DATA                      ,
	ATALLA_FN_MAC_LENGTH							,
	ATALLA_FN_CONTINUATION_INIT_VECTOR				,
	ATALLA_FN_MAC									,
	ATALLA_FN_MAC_ALGORITHM							,
	ATALLA_FN_DATA_FORMAT							,
	ATALLA_FN_DATA_LENGTH							,
	ATALLA_FN_DATA									,
	ATALLA_FN_MSG_AUTHENTICATION_KEY				,
	ATALLA_FN_MSG_AUTHENTICATION_KEY_2				,
	ATALLA_FN_PUBLIC_EXPONENT						,
	ATALLA_FN_MODULUS_SIZE		                    ,
	ATALLA_FN_KEY_SLOT			                    ,
	ATALLA_FN_RSA_PUBLIC_KEY	                    ,
	ATALLA_FN_RSA_PRIVATE_KEY	                    ,
	ATALLA_FN_HASH_ALGORITHM						,
	ATALLA_FN_SIGNATURE_ALGORITHM	                ,
	ATALLA_FN_PUBLIC_KEY_DATA		                ,
	ATALLA_FN_SIGNATURE			                    ,
	ATALLA_FN_CA_PUBLIC_KEY		                    ,
	ATALLA_FN_EMPTY_FIELD		                    ,
	ATALLA_FN_FLAG									,
	ATALLA_FN_ENCODING								,
	ATALLA_FN_INTERMEDIATE_RESULT					,
	ATALLA_FN_MESSAGE_DIGEST						,
	ATALLA_FN_MASTER_KEY_HEADER						,
	ATALLA_FN_ATM_MASTER_KEY						,
	ATALLA_FN_ATM_MASTER_KEY_UNDER_PK				,
	ATALLA_FN_METHOD								,
	ATALLA_FN_INC_KEY_MNG							,
	ATALLA_FN_INC_KEY_KSN	                        ,
	ATALLA_FN_OUTG_KEY_MNG                          ,
	ATALLA_FN_OUTG_KEY_KSN                          ,


	ATALLA_FN_QTY
} E_ATALLA_FIELD_ID;


/* below order is as per AtallaCmdDataProp */
typedef enum {

	ATALLA_FN_CMD_REQ_GENERATE_KEY_10		= 0	,
	ATALLA_FN_CMD_REQ_EXPORT_KEY_11				,
	ATALLA_FN_CMD_REQ_IMPORT_KEY_13				,
	ATALLA_FN_CMD_REQ_EXPORT_KEY_1A				,
	ATALLA_FN_CMD_REQ_VERIFY_CVV_5E				,
	ATALLA_FN_CMD_REQ_VERIFY_DCVV_357			,
	ATALLA_FN_CMD_REQ_VERIFY_CVC3_359			,
	ATALLA_FN_CMD_REQ_VERIFY_CSC_35A			,
	ATALLA_FN_CMD_REQ_TRANSLATE_PIN_335			,
	ATALLA_FN_CMD_REQ_VERIFY_PIN_IBM_32			,
	ATALLA_FN_CMD_REQ_VERIFY_PIN_VISA_32		,
	ATALLA_FN_CMD_REQ_PIN_CHANGE_IBM_37			,
	ATALLA_FN_CMD_REQ_PIN_CHANGE_VISA_37		,
	ATALLA_FN_CMD_REQ_VERIFY_ARQC_350			,
	ATALLA_FN_CMD_REQ_EMV_PIN_CHANGE_351		,
	ATALLA_FN_CMD_REQ_GENERATE_EMV_MAC_352		,
	ATALLA_FN_CMD_REQ_EMV_PIN_CHANGE_IBM_3FC	,
	ATALLA_FN_CMD_REQ_GENERATE_MAC_98			,
	ATALLA_FN_CMD_REQ_VERIFY_MAC_99				,
	ATALLA_FN_CMD_REQ_GENERATE_MAC_HMAC_39B		,
	ATALLA_FN_CMD_REQ_GENERATE_RSA_KEY_PAIR_120	,
	ATALLA_FN_CMD_REQ_VERIF_PUB_KEY_AND_GEN_RSA_AKB_123,
	ATALLA_FN_CMD_REQ_GEN_DIGITAL_SIGNATURE_124	,
	ATALLA_FN_CMD_REQ_VERIF_DIGITAL_SIGNATURE_125,
	ATALLA_FN_CMD_REQ_GEN_MESSAGE_DIGEST_126	,
	ATALLA_FN_CMD_REQ_GEN_TMK_AND_ENCRYPT_PK_12F,
	ATALLA_FN_CMD_REQ_GEN_CHECK_DIGITS_7E		,
	ATALLA_FN_CMD_REQ_TRANSLATE_ISO_PIN_3E		,
	ATALLA_FN_CMD_REQ_IMPORT_KEY_NAKB_11B		,
	ATALLA_FN_CMD_RESP_UNKOWN_00				,
	ATALLA_FN_CMD_RESP_GENERATE_KEY_20			,
	ATALLA_FN_CMD_RESP_EXPORT_KEY_21			,
	ATALLA_FN_CMD_RESP_IMPORT_KEY_23			,
	ATALLA_FN_CMD_RESP_EXPORT_KEY_2A			,
	ATALLA_FN_CMD_RESP_VERIFY_CVV_6E			,
	ATALLA_FN_CMD_RESP_VERIFY_DCVV_457			,
	ATALLA_FN_CMD_RESP_VERIFY_CVC3_459			,
	ATALLA_FN_CMD_RESP_VERIFY_CSC_45A			,
	ATALLA_FN_CMD_RESP_TRANSLATE_PIN_435		,
	ATALLA_FN_CMD_RESP_VERIFY_PIN_IBM_42		,
	ATALLA_FN_CMD_RESP_VERIFY_PIN_VISA_42		,
	ATALLA_FN_CMD_RESP_PIN_CHANGE_IBM_47		,
	ATALLA_FN_CMD_RESP_PIN_CHANGE_VISA_47		,
	ATALLA_FN_CMD_RESP_VERIFY_ARQC_450			,
	ATALLA_FN_CMD_RESP_EMV_PIN_CHANGE_451		,
	ATALLA_FN_CMD_RESP_GENERATE_EMV_MAC_452		,
	ATALLA_FN_CMD_RESP_EMV_PIN_CHANGE_IBM_4FC	,
	ATALLA_FN_CMD_RESP_GENERATE_MAC_A8			,
	ATALLA_FN_CMD_RESP_VERIFY_MAC_A9			,
	ATALLA_FN_CMD_RESP_GENERATE_MAC_HMAC_49B	,
	ATALLA_FN_CMD_RESP_GENERATE_RSA_KEY_PAIR_220,
	ATALLA_FN_CMD_RESP_VERIF_PUB_KEY_AND_GEN_RSA_AKB_223,
	ATALLA_FN_CMD_RESP_GEN_DIGITAL_SIGNATURE_224,
	ATALLA_FN_CMD_RESP_VERIF_DIGITAL_SIGNATURE_225,
	ATALLA_FN_CMD_RESP_GEN_MESSAGE_DIGEST_226	,
	ATALLA_FN_CMD_RESP_GEN_TMK_AND_ENCRYPT_PK_22F,
	ATALLA_FN_CMD_RESP_GEN_CHECK_DIGITS_8E		,
	ATALLA_FN_CMD_RESP_TRANSLATE_ISO_PIN_4E		,
	ATALLA_FN_CMD_RESP_IMPORT_KEY_NAKB_21B		,


	ATALLA_CMD_CODE_QTY

} E_ATALLA_CMD_CODE;


#define	EMV_ATALLA_SKD_MCI		'0'
#define	EMV_ATALLA_SKD_VISA		'1'
#define EMV_ATALLA_SKD_CSK		'2'
#define	EMV_ATALLA_SKD_UPI		'4'

#endif
