#ifndef HPS_TLV_EMEAFIELDS_H
#define HPS_TLV_EMEAFIELDS_H

#define EMEA_HD_DV 				"002" 
#define EMEA_HD_TYPE         	"003"
#define EMEA_HD_TRX_CODE       	"004"
#define EMEA_HD_BATCH_DATE     	"005"
#define EMEA_HD_BATCH_NBR      	"006"
#define EMEA_HD_MERCH_NBR      	"007"
#define EMEA_HD_STORE_NBR      	"008"
#define EMEA_HD_MERCH_TERM_NBR 	"009"
#define EMEA_HD_BLOCK_FACT     	"010"
#define EMEA_HD_CRNCY_CODE     	"011"
#define EMEA_HD_BANK_CODE      	"012"
#define EMEA_HD_TERM_NBR       	"013"


#define EMEA_PR_DV 				"014" 
#define EMEA_PR_TYPE         	"015"
#define EMEA_PR_TRX_CODE       	"016"
#define EMEA_PR_STORE_NBR      	"017"
#define EMEA_PR_TERM_NBR       	"018"
#define EMEA_PR_MERCH_NAME     	"019"
#define EMEA_PR_MERCH_CITY     	"020"
#define EMEA_PR_MERCH_STATE    	"021"
#define EMEA_PR_MERCH_MCC      	"022"
#define EMEA_PR_MERCH_LOC      	"023"
#define EMEA_PR_TERM_SER       	"024"
#define EMEA_PR_ZIP_CODE       	"025"
#define EMEA_PR_CNTRY_CODE     	"026"
#define EMEA_PR_BATCH_CRED     	"027"
#define EMEA_PR_TRX_CRED       	"028"
#define EMEA_PR_BATCH_DEB      	"029"
#define EMEA_PR_TRX_DEB        	"030"
#define EMEA_PR_VOID           	"031"

#define EMEA_DT_DV 				"032" 
#define EMEA_DT_TYPE         	"033"
#define EMEA_DT_TRX_CODE       	"034"
#define EMEA_DT_STORE_NBR      	"035"
#define EMEA_DT_TERM_NBR      	"036"
#define EMEA_DT_TRX_DATE      	"037"
#define EMEA_DT_PAN           	"038"
#define EMEA_DT_SOURCE_CODE   	"039"
#define EMEA_DT_CARD_ID       	"040"
#define EMEA_DT_TRX_AMNT      	"041"
#define EMEA_DT_VOID_ID       	"042"
#define EMEA_DT_AUTHOR_SOURCE 	"043"
#define EMEA_DT_AUTHOR_CODE   	"044"
#define EMEA_DT_REF_NBR       	"045"
#define EMEA_DT_TRX_TIME      	"046"
#define EMEA_DT_CASHBACK_AMNT 	"047"


#define EMEA_TR_DV 				"048" 
#define EMEA_TR_TYPE         	"049"
#define EMEA_TR_TRX_CODE       	"050"
#define EMEA_TR_BATCH_DATE     	"051"
#define EMEA_TR_BATCH_NBR      	"052"
#define EMEA_TR_BATCH_COUNT    	"053"
#define EMEA_TR_BATCH_TOT      	"054"

#endif /* HPS_TLV_EMEAFIELDS_H */

