#ifndef HPS_TLV_FIELDS_H
#define HPS_TLV_FIELDS_H

#define AUTO_PAN 						"002" 
#define AUTO_PROCESSING_CODE  			"003"
#define AUTO_AMOUNT_TRANSACTION        	"004" 
#define AUTO_AMOUNT_SETTLEMENT         	"005" 
#define AUTO_AMOUNT_CARD_BILLING       	"006" 
#define AUTO_TRANS_DATE_TIME           	"007"
#define AUTO_AMOUNT_CARD_BILL_FEE      	"008" 
#define AUTO_CONV_RATE_SETTLEMENT      	"009"
#define AUTO_CONV_RATE_CARD_BILL       	"010"
#define AUTO_INTERNAL_STAN              "011" 
#define AUTO_DATE_TIME_LOCAL_TRAN      	"012" 
#define AUTO_EFFECTIVE_DATE            	"013"
#define AUTO_EXPIRY_DATE               	"014" 
#define AUTO_SETTLEMENT_DATE           	"015"
#define AUTO_CONVERSION_DATE           	"016"
#define AUTO_CAPTURE_DATE              	"017"
#define AUTO_MERCHANT_TYPE             	"018"
#define AUTO_ACQU_INST_COUNTRY         	"019" 
#define AUTO_PAN_EXTENDED_COUNTRY      	"020"
#define AUTO_FORW_INST_COUNTRY         	"021"
#define AUTO_POS_DATA                  	"022"
#define AUTO_CARD_SEQUENCE_NUMBER      	"023"
#define AUTO_FUNCTION_CODE             	"024"
#define AUTO_MESSAGE_REASON_CODE       	"025"
#define AUTO_MERCHANT_ACTIVITY         	"026" 
#define AUTO_AUTH_NUMBER_LENGTH        	"027"
#define AUTO_RECONCILIATION_DATE       	"028"
#define AUTO_RECON_INDICATOR           	"029"
#define AUTO_INITIAL_AMOUNTS           	"030"
#define AUTO_ACQUIRER_REF_DATA         	"031"
#define AUTO_ACQ_INST_IDENT_CODE       	"032"
#define AUTO_FOR_INST_IDENT_CODE       	"033"
#define AUTO_PAN_EXTENDED              	"034"
#define AUTO_TRACK2_DATA               	"035"
#define AUTO_TRACK3_DATA               	"036"
#define AUTO_RRN                       	"037"
#define AUTO_AUTH_NUMBER               	"038"
#define AUTO_RESPONSE_CODE             	"039"
#define AUTO_SERVICE_CODE              	"040"
#define AUTO_CARD_ACC_TERMINAL         	"041"
#define AUTO_CARD_ACC_ID               	"042"
#define AUTO_CARD_ACC_LOCATION         	"043"
#define AUTO_ADDITIONAL_RESP_DATA      	"044"
#define AUTO_TRACK1_DATA    			"045"
#define AUTO_AMOUNT_FEE					"046"
#define AUTO_ADD_DATA_NATIONAL  		"047"
#define AUTO_ADD_DATA_PRIVATE   		"048"
#define AUTO_TRAN_CURRENCY_CODE    		"049"
#define AUTO_SETL_CURRENCY_CODE    		"050"
#define AUTO_BILL_CURRENCY_CODE    		"051"
#define AUTO_PIN_DATA					"052"
#define AUTO_SECURITY_DATA				"053"
#define AUTO_ADD_AMOUNTS				"054"
#define AUTO_ICC_DATA					"055"
#define AUTO_ORIGINAL_DATA				"056"
#define AUTO_AUTH_CYCLE_CODE			"057"
#define AUTO_AUTH_INST_ID				"058"
#define AUTO_TRANSPORT_DATA				"059"
#define AUTO_ADD_POS_DATA				"060"
#define AUTO_NETWORK_POS_DATA			"061"
#define AUTO_CPS_DATA					"062"
#define AUTO_NETWORK_DATA				"063"
#define AUTO_MAC_2						"064"
#define AUTO_EXTENDED_BIT_MAP			"065"
#define AUTO_ORIGINAL_AMOUNT_FEE		"066"
#define AUTO_EXT_PAYMENT_CODE			"067"
#define AUTO_RECEIV_INST_COUNTRY		"068"
#define AUTO_SETTL_INST_COUNTRY			"069" 
#define AUTO_AUTH_INST_CODE				"070"
#define AUTO_MESSAGE_NUMBER				"071" 
#define AUTO_UF_FILE_RECORD 			"072"
#define AUTO_UF_ACTION_DATE 			"073"
#define AUTO_CREDITS_NUMBER				"074"
#define AUTO_CREDITS_REV_NUMBER			"075"
#define AUTO_DEBITS_NUMBER				"076"
#define AUTO_DEBITS_REV_NUMBER			"077"
#define AUTO_TRANSFER_NUMBER			"078"
#define AUTO_TRANSFER_REV_NUMBER		"079"
#define AUTO_INQUIRIES_NUMBER			"080"
#define AUTO_AUTHS_NUMBER				"081"
#define AUTO_INQUIRIES_REV_NUMBER		"082"
#define AUTO_PAYMENT_NUMBER				"083" 
#define AUTO_PAYMENT_REV_NUMBER			"084" 
#define AUTO_FEES_NUMBER				"085"
#define AUTO_CREDITS_AMOUNT				"086"
#define AUTO_CREDITS_REV_AMOUNT			"087"
#define AUTO_DEBITS_AMOUNT				"088"
#define AUTO_DEBITS_REV_AMOUNT			"089"
#define AUTO_AUTHS_REV_NUMBER			"090"
#define AUTO_REC_INST_COUNTRY			"091"
#define AUTO_INITIATOR_COUNTRY			"092" 
#define AUTO_RECEIVING_INST_ID			"093"
#define AUTO_INITIATOR_INST_ID 			"094"
#define AUTO_ISSUER_REF_DATA			"095" 
#define AUTO_KEY_MANAGE_DATA           	"096" 
#define AUTO_AMOUNT_NET_SETTL			"097"
#define AUTO_PAYEE						"098"
#define AUTO_SETTL_INST_ID				"099" 
#define AUTO_RECEIV_INST_ID				"100"
#define AUTO_UF_FILENAME 				"101"
#define AUTO_ACCOUNT_ID_1  				"102"
#define AUTO_ACCOUNT_ID_2  				"103"
#define AUTO_TRANS_DESCRIPTION			"104"
#define AUTO_CREDITS_REJECT_AMOUNT		"105"
#define AUTO_DEBITS_REJECT_AMOUNT		"106"
#define AUTO_CREDITS_REJECT_NUMBER		"107"
#define AUTO_DEBITS_REJECT_NUMBER		"108"
#define AUTO_CREDITS_FEE_AMOUNT    		"109"
#define AUTO_CREDITS_FEE_NUMBER    		"110"
#define AUTO_RESERVED_ISO_1 			"111"
#define AUTO_RESERVED_ISO_2 			"112"
#define AUTO_RESERVED_ISO_3 			"113"
#define AUTO_RESERVED_ISO_4 			"114"
#define AUTO_RESERVED_ISO_5 			"115"
#define AUTO_RESERVED_NATIONAL_1 		"116"
#define AUTO_RESERVED_NATIONAL_2 		"117"
#define AUTO_RESERVED_NATIONAL_3 		"118"
#define AUTO_RESERVED_NATIONAL_4 		"119"
#define AUTO_RESERVED_NATIONAL_5 		"120"
#define AUTO_RESERVED_NATIONAL_6 		"121"
#define AUTO_RESERVED_NATIONAL_7 		"122"
#define AUTO_RESERVED_PRIVATE_1  		"123"
#define AUTO_RESERVED_PRIVATE_2  		"124"
#define AUTO_RESERVED_PRIVATE_3  		"125"
#define AUTO_RESERVED_PRIVATE_4  		"126"
#define AUTO_RESERVED_PRIVATE_5  		"127"
#define AUTO_MAC						"128"
#define AUTO_REVERSAL_STAN             "129"
#define AUTO_USER						"130"
#define AUTO_INTER_ROUT_CHECK			"131"
#define AUTO_CTRL_VERIF_INDEX			"132"
#define AUTO_PIN_RETRY_MAX    			"133"
#define AUTO_DB_SERVICE_CODE  			"134"

#define AUTO_GET_CARD_DATA_LEVEL        "135" 
#define AUTO_SCENARIO_CODE              "136"
#define AUTO_RECORD_STATUS              "137"
#define AUTO_LOYALTY_POINTS_SIGN        "138" 
#define AUTO_CURRENT_MOUNTH_IND         "139" 
#define AUTO_OFF_LINE_INDICATOR         "140" 
#define AUTO_NUMBER_OF_PRODUCT_GROUP    "141" 
#define AUTO_CATALOGUE_CODE             "142"
#define AUTO_BAL_CLOSING_DATE           "143"
#define AUTO_CARD_ACTIVITY_FLAG         "144"
#define AUTO_PIN_NBR 					"145"
#define AUTO_TRANS_FEE                  "146"  /* ENH VISA 200904 HBU */
#define AUTO_FPI                     		"147" /* ENH VISA 200904 SWI */

/*****Additional TAG For AUTHO_ACTIVITY    ****/
#define AUTO_ROUTING_CODE              "200"
#define AUTO_CAPTURE_CODE              "201"
#define AUTO_ORIG_ACTION_CODE          "202"
#define AUTO_EVENT_CODE                "203"
#define AUTO_NETWORK_CODE              "204"
#define AUTO_ISSUING_BANK              "205"
#define AUTO_RESP_DATE_TIME            "206"
#define AUTO_INTERN_DATE_TIME          "207"
#define AUTO_BUSINESS_DATE             "208"
#define AUTO_PRODUCT_CODE              "209"
#define AUTO_CARD_TYPE                 "210"
#define AUTO_VIP_LEVEL                 "211"
#define AUTO_DST_ACCOUNT_BANK          "212"
#define AUTO_ISS_STLMNT_AMOUNT         "213"
#define AUTO_ISS_STLMNT_CURRENCY       "214"
#define AUTO_ISS_STLMNT_DATE           "215"
#define AUTO_ISS_CNV_RATE_STLMNT       "216"
#define AUTO_ISS_CNV_RAT_STL_DATE      "217"
#define AUTO_ACQ_STLMNT_AMOUNT         "218"
#define AUTO_ACQ_STLMNT_CURRENCY       "219"
#define AUTO_ACQ_STLMNT_DATE           "220"
#define AUTO_ACQ_CNV_RATE_STLMNT       "221"
#define AUTO_ACQ_CNV_RAT_STL_DATE      "222"
#define AUTO_ISS_STLMNT_FEE            "223"
#define AUTO_ACQ_STLMNT_FEE            "224"
#define AUTO_SERV_SETUP_CODE           "225"
#define AUTO_PRODUCT_CUR_CODE          "226"
#define AUTO_LIMITS_INDEXES            "227"
#define AUTO_PERIOD_CODE               "228"
#define AUTO_PERIOD_TYPE               "229"
#define AUTO_PERIOD_VALUE              "230"
#define AUTO_CR_CUR_CODE               "231"
#define AUTO_CR_CREDIT_LIMIT           "232"
#define AUTO_CR_CASH_LIMIT             "233"
#define AUTO_CR_LOAN_LIMIT             "234"
#define AUTO_CR_VIP_LEVEL              "235"
#define AUTO_CR_CREDIT_CUR_BAL         "236"
#define AUTO_CR_CASH_CUR_BAL           "237"
#define AUTO_CR_LOAN_CUR_BAL           "238"
#define AUTO_CR_RESPONSE_CODE          "239"
#define AUTO_CR_PEND_AUT_CREDIT        "240"
#define AUTO_CR_PEND_AUT_CASH          "241"
#define AUTO_CR_PEND_AUT_LOAN          "242"
#define AUTO_CR_AVAILABLE_BAL          "243"
#define AUTO_CR_FIRST_DUE_DATE         "244"
#define AUTO_CR_INSTALL_AMOUNT         "245"
#define AUTO_CR_TERM_COUNT             "246"
#define AUTO_CR_PRODUCT_GRP1           "247"
#define AUTO_CR_PRODUCT_GRP2           "248"
#define AUTO_CR_PRODUCT_GRP3           "249"
#define AUTO_CR_PRODUCT_GRP4           "250"
#define AUTO_CR_PRODUCT_GRP5           "251"
#define AUTO_LOYALTY_POINTS            "252"
#define AUTO_ACQUIRER_BANK             "253"
#define AUTO_FORWARD_BANK              "254"
#define AUTO_AUTHOR_SRC                "255"
#define AUTO_CARD_LEVEL                "256"
#define AUTO_BAL_LEVEL                 "257"
#define AUTO_DB_CUR_BAL                "258"
#define AUTO_LIMIT_BEFORE_TRN          "259"
#define AUTO_LIMIT_ID                  "260"
#define AUTO_SHADOW_ACT_LEVEL          "261"
#define AUTO_HOST_LEVEL                "262"
#define AUTO_CLIENT_LEVEL              "263"
#define AUTO_EXECPT_LEVEL              "264"
#define AUTO_ACTION_TRANSL_LEVEL       "265"
#define AUTO_CARD_LIMIT_EXP_LEVEL      "266"
#define AUTO_VIP_ACTION_TRL_LEVEL      "267"
#define AUTO_AUTHO_PERIOD_LEVEL        "268"
#define AUTO_SECURITY_VERIF_FLAGS      "269"
#define AUTO_SECURITY_VER_RESULTS      "270"
#define AUTO_ADDRESS_VERIF_DATA        "271"
#define AUTO_REJECT_CODE               "272"
#define AUTO_REJECT_REASON             "273"
#define AUTO_TIME_STAMP_PLUS_MSG       "274"
#define AUTO_ORIGIN_CODE               "275"
#define AUTO_ORIG_TRANS_DATE_TIME      "276"
#define AUTO_AUTHO_FLAG                "277"
#define AUTO_REVERSAL_FLAG             "278"
#define AUTO_TRANSACTION_FLAG          "279"
#define AUTO_MATCH_STATUS              "280"
#define AUTO_MATCH_DATE                "281"
#define AUTO_MATCH_LEVEL               "282"
#define AUTO_MATCH_PURGE_DATE          "283"
#define AUTO_TRACK_INFO                "284"
#define AUTO_ACQ_RESOURCE_CODE         "285"
#define AUTO_ISS_RESOURCE_CODE         "286"
#define AUTO_TABLE_INDICATOR           "287"
#define AUTO_CUR_TABLE_INDICATOR       "288"

#define AUTO_REVERSAL_DATE             "291"
#define AUTO_CASH_BACK_AMOUNT          "293"
#define AUTO_REPLACEMENT_AMOUNT        "294"
#define AUTO_REPLACEMENT_BILLING       "295"
#define AUTO_TRANSACTION_IDENTIFIER		"296"	/*EBE131202*/
#define AUTO_AUTHORIZATION_IDENTIFIER	"297"	/*EBE140623*/
#define AUTO_CARD_PRODUCT_TYPE			"298"	/*EBE140623*/

#define AUTO_MSG_TYPE                  "300"
#define AUTO_ORIG_MSG_TYPE             "301" /* EBE150912: handle repeats/incremental*/
#define AUTO_REPLACEMENT_FEE		   "302"
#define AUTO_ROUTING_MODE				"303"
#define AUTO_REPLACEMENT_SETTL			"304"	/*AMER20210414 PLUTONL-2991*/

/* File Update Messages Tags */
#define AUTO_SRC_ACC_ENT_CODE       "321"
#define AUTO_SRC_ACC_ENT_ID         "322"
#define AUTO_SRC_ACC_SEQ            "323"
#define AUTO_SRCACC_TYPE            "324"
#define AUTO_SRC_ACC_ENT_LEVEL      "325"
#define AUTO_DST_ACC_ENT_COD  		"326"
#define AUTO_DST_ACC_ENT_ID   		"327"
#define AUTO_DST_ACC_SEQ    		"328"
#define AUTO_DST_ACC_TYPE        	"329"
#define AUTO_DST_ACC_ENT_LEV  		"330"
#define AUTO_ACCOUNT_LEVEL			"331"

#define AUTO_UF_UPDATE_CODE        		"332"
#define AUTO_UF_PURGE_DATE         		"334"
#define AUTO_UF_ACTION_CODE        		"335"

/* ---- START ADDED BY KR LE 26-10-2002 --------*/

#define  AUTO_ISO3_SMART_OPTION                  "360"/*not used*/
#define  DB_CARD_SEQ_NO                          "360"/*ICH20170927*/

/*#define  AUTO_ISO3_SMART_PROC_MODE               "361" */
#define  AUTO_REPLACEMENT_FEE_DTL				 "361"

#define  AUTO_ROT_MEM_OPTION                     "362" 
#define  AUTO_ROT_MEM_CTRL_LIMIT                 "363" 
#define  AUTO_ROT_MEM_CTRL_AVAILABLE             "364" 
#define  AUTO_ROT_MEM_SCANF_ISO2ISO3             "365" 
#define  AUTO_ROT_MEM_LAST_USAGE_DATE            "366" 
#define  AUTO_OFF_LINE_ATM_PERIOD                "367" 
#define  AUTO_OFF_LINE_ATM_LIMIT_ONUS            "368" 
#define  AUTO_OFF_LINE_ATM_LIMIT_OFFUS           "369" 

/* BRS RECONCILIATION TAGS  */

#define  AUTO_SRC_DBSERV_ID					      "370"
#define  AUTO_START_TIME						  "371"
#define  AUTO_END_TIME						      "372"
#define  AUTO_RECONCILIATION_ID				      "373"
#define  AUTO_SRC_NB_FIN_AUTHORS		          "374"
#define  AUTO_SRC_NB_NFIN_AUTHORS		          "375"
#define  AUTO_SRC_NB_FIN_TRX				      "376"
#define  AUTO_SRC_NB_PREAUTHS			          "377"
#define  AUTO_SRC_NB_REVERSALS			          "378"
#define  AUTO_SRC_NB_SAF_RECORDS		          "379"
#define  AUTO_SRC_NB_SLF_RECORDS			      "380"
#define  AUTO_SRC_TOTAL_FIN_AUTHORS	              "381"
#define  AUTO_SRC_TOTAL_FIN_TRX			          "382"
#define  AUTO_SRC_TOTAL_PREAUTHS		          "383"
#define  AUTO_DST_NB_SAF_SLF		              "384"

#define AUTO_ACTION_FLAG						"400"
#define AUTO_NODE_ID							"401"
#define AUTO_DBSERV_ID							"402"

#define AUTO_CAPTURE_RES_INFO					"403"
#define AUTO_ROUTING_RES_INFO_1					"404"
#define AUTO_ROUTING_RES_INFO_2					"405"
#define AUTO_SWI_DBSERV_ID						"406"
#define AUTO_AUTH_SERV_ID						"407"


#define AUTO_SEL_ROUTING_CODE					"408"
#define AUTO_SEL_ROUTING_INFO					"409"

/* Fields for Dynamic services */
#define AUTO_SERV_CONTAINER						"410"
#define AUTO_SERV_PROC_ENTRY					"411"
#define AUTO_SERV_STANDIN_ENTRY					"412"
#define AUTO_SERV_ROUTING_REPLY_ENTRY			"413"
#define AUTO_SERV_ROUTING_TIMEOUT_ENTRY			"414"
#define AUTO_SERV_ROUTING_PATH					"415"	/*POCEBE*/

#define AUTO_SERV_USER_PROC_1_ENTRY				"417"
#define AUTO_SERV_USER_PROC_1_PARAM				"418"


#define AUTO_CARD_INFO_DATA						"420"
#define AUTO_ISS_INFO_DATA						"421"
#define AUTO_TERM_INFO_DATA						"422"
#define AUTO_ACQ_INFO_DATA						"423"

#define AUTO_EMV_CARD_INFO_DATA					"424"
#define AUTO_EMV_CARD_INFO_PARAM				"425"
#define AUTO_CARD_SEC_INFO_DATA					"426"
#define AUTO_CARD_SEC_INFO_PARAM				"427"
#define AUTO_PAN_INFO_DATA						"428"

#define DYNAMIC_AUTHENTICATION_INFO				"430" /*MJI 13/10/2020*/

#define AUTO_EMV_AC_KEY							"440"
#define AUTO_EMV_SMI_KEY						"441"
#define AUTO_EMV_SMC_KEY						"442"
#define AUTO_PVK_KEY							"443"
#define AUTO_CVK_KEY							"444"
#define AUTO_DCVV_KEY							"445"
#define AUTO_AAV_KEY							"446"
#define AUTO_CUT_OFF_DATA						"447" /*ICH20171205 Cut off info*/
#define AUTO_PVK_V1								"448" /*ZKO26032019 pvk for IBM offset*/

#define AUTO_FRAUD_PARAMS                                              "460"

#define AUTO_ON_OFF_ROUTING						"470"

#define AUTO_DB_PROC_TRACE						"499"

#define AUTO_USER_DEF_FIELDS					"500"	/*User specific fields 500-599*/


#define AUTO_MSG_FLOW_MAPPING_ID				"800"	/*EBE130925:SWMON*/



/* ---- END ADDED BY KR LE 26-10-2002 --------*/
/** ME140606 ADDED for EMV SCRIPTS ***/
#define ICC_APPLICATION_INDX                     "900"
#define ISSUER_BIN                               "901"
#define AUTO_MALFUNCTION_EVENT                   "998"		/* if we encouter a processing error during reply, it's set to Y*/
#define SERVICE_CALL_RESULT                      "999"

#define CSID_PIN_LEN_OFST                   0
#define CSID_PVKI_OFST                      2
#define CSID_VISA_PVV_OFST					3
#define CSID_IBM_OFST_OFST                  7 /* PROD00036553 */ 
#define CSID_CVKI_OFST                      19 /*ICH20200310*/

#define CSID_PIN_LEN_LEN					2
#define CSID_PVKI_LEN						1
#define CSID_VISA_PVV_LEN					4
#define CSID_IBM_OFST_LEN					12
#define CSID_CVKI_LEN						1 /*ICH20200310*/




#endif /* HPS_TLV_FIELDS_H */

