#include <stdio.h>
#include <link_define.h>
#include <iso8583.h>
#include <link_fields.h>

static MsgInfoProperties	LinkMsgInfoProperties = {
	FF_ALPHA_N,			/* eMsgTypeType */
	4,				/* nMsgTypeLen */
	AF_EBCDIC,		/* eMsgTypeAlphaFormat */
	"LINK",		/* szProtocolName	*/
	"LINK",			/* szProtocolPrefix */
	{
		192,		/* nNbFields */
		3,			/* nNbBitmaps */
		2,			/* nNbConsBitmaps */
		8,					/* nBitmapLen */
		FF_ALPHA_AN,		/* eBitmapFmt */
		{

{LINK_F001_BIT_MAP2,		FT_UNDEF,FF_HEX,AF_EBCDIC,FL_FIX,LU_BYTE,0,PP_HIDE,"","BIT_MAP2",""},
{LINK_F002_CARD_NBR,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,19,PP_PRINT,"","CARD_NBR",""},
{LINK_F003_PROC_CODE,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","PROC_CODE",""},
{LINK_F004_TRANS_AMOUNT,	FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","TRANS_AMOUNT",""},
{LINK_F005_RESERVED_LINK_1, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","RESERVED_LINK_1",""},
{LINK_F006_BILLING_AMOUNT,	FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","BILLING_AMOUNT",""},
{LINK_F007_XMIT_TIME,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","XMIT_TIME",""},
{LINK_F008_RESERVED_LINK_2, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","RESERVED_LINK_2",""},
{LINK_F009_RESERVED_LINK_3, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","RESERVED_LINK_3",""},
{LINK_F010_BILLING_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_CNVRSN_RATE",""},
{LINK_F011_AUDIT_NBR,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUDIT_NBR",""},
{LINK_F012_TRANS_TIME,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","TRANS_TIME",""},
{LINK_F013_TRANS_DATE,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","TRANS_DATE",""},
{LINK_F014_EXPIRY_DATE,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","EXPIRY_DATE",""},
{LINK_F015_STLMNT_DATE,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","STLMNT_DATE",""},
{LINK_F016_RESERVED_LINK_4, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","RESERVED_LINK_4",""},
{LINK_F017_RESERVED_LINK_5, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","RESERVED_LINK_5",""},
{LINK_F018_RESERVED_LINK_6, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","RESERVED_LINK_6",""},
{LINK_F019_ACQR_COUNTRY,	FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","ACQR_COUNTRY",""},
{LINK_F020_RESERVED_LINK_7, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_7",""},
{LINK_F021_RESERVED_LINK_8, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_8",""},
{LINK_F022_POS_ENTRY_MODE,	FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","POS_ENTRY_MODE",""},
{LINK_F023_CARD_SEQUENCE_NBR, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","CARD_SEQUENCE_NBR",""},
{LINK_F024_RESERVED_LINK_9, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_9",""},
{LINK_F025_POS_CONDITION,	FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","POS_CONDITION",""},
{LINK_F026_RESERVED_LINK_10, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","RESERVED_LINK_10",""},
{LINK_F027_RESERVED_LINK_11, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","RESERVED_LINK_11",""},
{LINK_F028_STLMNT_AMOUNT_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","STLMNT_AMOUNT_FEE",""},
{LINK_F029_RESERVED_LINK_12, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_12",""},
{LINK_F030_STLMNT_PROC_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","STLMNT_PROC_FEE",""},
{LINK_F031_RESERVED_LINK_13, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,9,PP_PRINT,"","RESERVED_LINK_13",""},
{LINK_F032_ACQR_ID,			FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","ACQR_ID",""},
{LINK_F033_FORWD_ID,		FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","FORWD_ID",""},
{LINK_F034_RESERVED_LINK_14, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","RESERVED_LINK_14",""},
{LINK_F035_T2_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,37,PP_PRINT,"","T2_DATA",""},
{LINK_F036_RESERVED_LINK_15, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,4,PP_PRINT,"","RESERVED_LINK_15",""},
{LINK_F037_REFERENCE_NBR,	FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","REFERENCE_NBR",""},
{LINK_F038_RESERVED_LINK_16, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","RESERVED_LINK_16",""},
{LINK_F039_RESPONSE_CODE,	FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","RESPONSE_CODE",""},



{LINK_F040_RESERVED_LINK_17, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_17",""},
{LINK_F041_TERMINAL_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","TERMINAL_NBR",""},
{LINK_F042_OUTLET_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"","OUTLET_NBR",""},
{LINK_F043_TERMINAL_ADR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,40,PP_PRINT,"","TERMINAL_ADR",""},
{LINK_F044_RESERVED_LINK_18, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RESERVED_LINK_18",""},
{LINK_F045_RESERVED_LINK_19, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,77,PP_PRINT,"","RESERVED_LINK_19",""},
{LINK_F046_RESERVED_LINK_20, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","RESERVED_LINK_20",""},
{LINK_F047_RESERVED_LINK_21, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","RESERVED_LINK_21",""},
{LINK_F048_RESERVED_LINK_22, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RESERVED_LINK_22",""},
{LINK_F049_TRANS_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRANS_CRNCY",""},
{LINK_F050_RESERVED_LINK_23, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_23",""},
{LINK_F051_BILLING_CRNCY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","BILLING_CRNCY",""},
{LINK_F052_PIN_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","PIN_DATA",""},
{LINK_F053_RESERVED_LINK_24, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,16,PP_PRINT,"","RESERVED_LINK_24",""},
{LINK_F054_ADTNL_AMOUNTS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,120,PP_PRINT,"","ADTNL_AMOUNTS",""},
{LINK_F055_RESERVED_LINK_25, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","RESERVED_LINK_25",""},
{LINK_F056_RESERVED_LINK_26, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,255,PP_PRINT,"","RESERVED_LINK_26",""},
{LINK_F057_RESERVED_LINK_27, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_27",""},
{LINK_F058_RESERVED_LINK_28, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,255,PP_PRINT,"","RESERVED_LINK_28",""},
{LINK_F059_RESERVED_LINK_29, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,14,PP_PRINT,"","RESERVED_LINK_29",""},
{LINK_F060_ADV_REASON_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,9,PP_PRINT,"","ADV_REASON_CODE",""},
{LINK_F061_NET_POS_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,40,PP_PRINT,"","NET_POS_DATA",""},
{LINK_F062_RESERVED_LINK_30, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RESERVED_LINK_30",""},
{LINK_F063_RESERVED_LINK_31, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RESERVED_LINK_31",""},
{LINK_F064_RESERVED_LINK_32, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","RESERVED_LINK_32",""},
/*{LINK_F065_BIT_MAP3, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_HIDE,"","BIT_MAP3",""},*/
{LINK_F065_BIT_MAP3, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_HIDE,"","BIT_MAP3",""},
{LINK_F066_RESERVED_LINK_33, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","RESERVED_LINK_33",""},
{LINK_F067_RESERVED_LINK_34, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","RESERVED_LINK_34",""},
{LINK_F068_RESERVED_LINK_35, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_35",""},
{LINK_F069_RESERVED_LINK_36, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_36",""},
{LINK_F070_NW_MNGMT_INFO, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","NW_MNGMT_INFO",""},
{LINK_F071_RESERVED_LINK_37, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","RESERVED_LINK_37",""},
{LINK_F072_RESERVED_LINK_38, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RESERVED_LINK_38",""},
{LINK_F073_RESERVED_LINK_39, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","RESERVED_LINK_39",""},
{LINK_F074_RESERVED_LINK_40, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_40",""},
{LINK_F075_RESERVED_LINK_41, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_41",""},
{LINK_F076_RESERVED_LINK_42, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_42",""},
{LINK_F077_RESERVED_LINK_43, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_43",""},
{LINK_F078_RESERVED_LINK_44, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_44",""},
{LINK_F079_RESERVED_LINK_45, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_45",""},
{LINK_F080_RESERVED_LINK_46, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_46",""},
{LINK_F081_RESERVED_LINK_47, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_47",""},
{LINK_F082_RESERVED_LINK_48, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_48",""},
{LINK_F083_RESERVED_LINK_49, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_49",""},
{LINK_F084_RESERVED_LINK_50, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_50",""},
{LINK_F085_RESERVED_LINK_51, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_51",""},
{LINK_F086_RESERVED_LINK_52, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","RESERVED_LINK_52",""},
{LINK_F087_RESERVED_LINK_53, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","RESERVED_LINK_53",""},
{LINK_F088_RESERVED_LINK_54, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","RESERVED_LINK_54",""},
{LINK_F089_RESERVED_LINK_55, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","RESERVED_LINK_55",""},
{LINK_F090_ORIG_DATA, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","ORIG_DATA",""},
{LINK_F091_RESERVED_LINK_56, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_56",""},
{LINK_F092_RESERVED_LINK_57, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESERVED_LINK_57",""},
{LINK_F093_RESERVED_LINK_58, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","RESERVED_LINK_58",""},
{LINK_F094_RESERVED_LINK_59, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","RESERVED_LINK_59",""},
{LINK_F095_REPLACE_AMOUNTS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","REPLACE_AMOUNTS",""},
{LINK_F096_MSG_SECURITY, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MSG_SECURITY",""},
{LINK_F097_RESERVED_LINK_60, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,17,PP_PRINT,"","RESERVED_LINK_60",""},
{LINK_F098_RESERVED_LINK_61, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"","RESERVED_LINK_61",""},
{LINK_F099_RESERVED_LINK_62, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","RESERVED_LINK_62",""},
{LINK_F100_RESERVED_LINK_63, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","RESERVED_LINK_63",""},
{LINK_F101_RESERVED_LINK_64, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,17,PP_PRINT,"","RESERVED_LINK_64",""},
{LINK_F102_ACCOUNT_ID1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID1",""},
{LINK_F103_RESERVED_LINK_65, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","RESERVED_LINK_65",""},
{LINK_F104_RESERVED_LINK_66, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,16,PP_PRINT,"","RESERVED_LINK_66",""},
{LINK_F105_RESERVED_LINK_67, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","RESERVED_LINK_67",""},
{LINK_F106_RESERVED_LINK_68, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","RESERVED_LINK_68",""},
{LINK_F107_RESERVED_LINK_69, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_69",""},
{LINK_F108_RESERVED_LINK_70, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","RESERVED_LINK_70",""},
{LINK_F109_RESERVED_LINK_71, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_71",""},
{LINK_F110_RESERVED_LINK_72, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_72",""},
{LINK_F111_RESERVED_LINK_73, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_73",""},
{LINK_F112_RESERVED_LINK_74, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_74",""},
{LINK_F113_AUTH_AGENT_INS_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LLL,LU_BYTE,11,PP_PRINT,"","AUTH_AGENT_INS_ID",""},
{LINK_F114_RESERVED_LINK_75, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_75",""},
{LINK_F115_RESERVED_LINK_76, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,24,PP_PRINT,"","RESERVED_LINK_76",""},
{LINK_F116_RESERVED_LINK_77, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_77",""},
{LINK_F117_RESERVED_LINK_78, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_78",""},
{LINK_F118_RESERVED_LINK_79, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_79",""},
{LINK_F119_RESERVED_LINK_80, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_80",""},
{LINK_F120_RESERVED_LINK_81, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_81",""},
{LINK_F121_RESERVED_LINK_82, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_82",""},
{LINK_F122_RESERVED_LINK_83, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_LINK_83",""},
{LINK_F123_AUTH_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","AUTH_DATA",""},
{LINK_F124_INFO_TEXT, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","INFO_TEXT",""},
{LINK_F125_NTW_MNG_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","NTW_MNG_INFO",""},/* AHA20220927 PLUTONL-4980*/
{LINK_F126_ISS_TRACE_ID, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,6,PP_PRINT,"","ISS_TRACE_ID",""},
{LINK_F127_EXTENDED_PAYMENT_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","EXTENDED_PAYMENT_DATA",""},
{LINK_F128_RESERVED_LINK_84, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","RESERVED_LINK_84",""},
{LINK_F129_RESERVED_LINK_85, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","RESERVED_LINK_85",""},
{LINK_F130_TERM_CAPABILITY_PROFILE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","TERM_CAPABILITY_PROFILE",""},
{LINK_F131_TERM_VERIF_RESULTS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","TERM_VERIF_RESULTS",""},
{LINK_F132_UNPREDICTABLE_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","UNPREDICTABLE_NBR",""},
{LINK_F133_TERM_SERIAL_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","TERM_SERIAL_NBR",""},
{LINK_F134_ISS_APPL_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,64,PP_PRINT,"","ISS_APPL_DATA",""},
{LINK_F135_RESERVED_LINK_86, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"","RESERVED_LINK_86",""},
{LINK_F136_CRYPTOGRAM, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","CRYPTOGRAM",""},
{LINK_F137_APPL_TRANS_COUNTER, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","APPL_TRANS_COUNTER",""},
{LINK_F138_APPL_INTERCHANGE_PROFILE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","APPL_INTERCHANGE_PROFILE",""},
{LINK_F139_ISS_AUTHENTICATION_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,32,PP_PRINT,"","ISS_AUTHENTICATION_DATA",""},
{LINK_F140_RESERVED_LINK_87, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,20,PP_PRINT,"","RESERVED_LINK_87",""},
{LINK_F141_RESERVED_LINK_88, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,21,PP_PRINT,"","RESERVED_LINK_88",""},
{LINK_F142_ISSUER_SCRIPT, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","ISSUER_SCRIPT",""},
{LINK_F143_RESERVED_LINK_89, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,23,PP_PRINT,"","RESERVED_LINK_89",""},
{LINK_F144_CRYPT_TRANS_TYPE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","CRYPT_TRANS_TYPE",""},
{LINK_F145_TERMINAL_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","TERMINAL_COUNTRY",""},
{LINK_F146_TERMINAL_TRANS_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","TERMINAL_TRANS_DATE",""},
{LINK_F147_CRYPTOGRAM_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","CRYPTOGRAM_AMOUNT",""},
{LINK_F148_CRYPTOGRAM_CURRENCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","CRYPTOGRAM_CURRENCY",""},
{LINK_F149_RESERVED_LINK_90, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,29,PP_PRINT,"","RESERVED_LINK_90",""},
{LINK_F150_RESERVED_LINK_91, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,30,PP_PRINT,"","RESERVED_LINK_91",""},
{LINK_F151_RESERVED_LINK_92, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,31,PP_PRINT,"","RESERVED_LINK_92",""},
{LINK_F152_RESERVED_LINK_93, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,32,PP_PRINT,"","RESERVED_LINK_93",""},
{LINK_F153_RESERVED_LINK_94, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,33,PP_PRINT,"","RESERVED_LINK_94",""},
{LINK_F154_RESERVED_LINK_95, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,34,PP_PRINT,"","RESERVED_LINK_95",""},
{LINK_F155_RESERVED_LINK_96, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,35,PP_PRINT,"","RESERVED_LINK_96",""},
{LINK_F156_RESERVED_LINK_97, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,36,PP_PRINT,"","RESERVED_LINK_97",""},
{LINK_F157_RESERVED_LINK_98, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,37,PP_PRINT,"","RESERVED_LINK_98",""},
{LINK_F158_RESERVED_LINK_99, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,38,PP_PRINT,"","RESERVED_LINK_99",""},
{LINK_F159_RESERVED_LINK_100, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,39,PP_PRINT,"","RESERVED_LINK_100",""},
{LINK_F160_RESERVED_LINK_101, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,40,PP_PRINT,"","RESERVED_LINK_101",""},
{LINK_F161_RESERVED_LINK_102, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,41,PP_PRINT,"","RESERVED_LINK_102",""},
{LINK_F162_RESERVED_LINK_103, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","RESERVED_LINK_103",""},
{LINK_F163_RESERVED_LINK_104, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,43,PP_PRINT,"","RESERVED_LINK_104",""},
{LINK_F164_RESERVED_LINK_105, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,44,PP_PRINT,"","RESERVED_LINK_105",""},
{LINK_F165_RESERVED_LINK_106, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,45,PP_PRINT,"","RESERVED_LINK_106",""},
{LINK_F166_RESERVED_LINK_107, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,46,PP_PRINT,"","RESERVED_LINK_107",""},
{LINK_F167_RESERVED_LINK_108, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,47,PP_PRINT,"","RESERVED_LINK_108",""},
{LINK_F168_RESERVED_LINK_109, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,48,PP_PRINT,"","RESERVED_LINK_109",""},
{LINK_F169_RESERVED_LINK_110, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,49,PP_PRINT,"","RESERVED_LINK_110",""},
{LINK_F170_RESERVED_LINK_111, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,50,PP_PRINT,"","RESERVED_LINK_111",""},
{LINK_F171_RESERVED_LINK_112, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,51,PP_PRINT,"","RESERVED_LINK_112",""},
{LINK_F172_RESERVED_LINK_113, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,52,PP_PRINT,"","RESERVED_LINK_113",""},
{LINK_F173_RESERVED_LINK_114, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,53,PP_PRINT,"","RESERVED_LINK_114",""},
{LINK_F174_RESERVED_LINK_115, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,54,PP_PRINT,"","RESERVED_LINK_115",""},
{LINK_F175_RESERVED_LINK_116, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,55,PP_PRINT,"","RESERVED_LINK_116",""},
{LINK_F176_RESERVED_LINK_117, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,56,PP_PRINT,"","RESERVED_LINK_117",""},
{LINK_F177_RESERVED_LINK_118, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,57,PP_PRINT,"","RESERVED_LINK_118",""},
{LINK_F178_RESERVED_LINK_119, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,58,PP_PRINT,"","RESERVED_LINK_119",""},
{LINK_F179_RESERVED_LINK_120, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,59,PP_PRINT,"","RESERVED_LINK_120",""},
{LINK_F180_RESERVED_LINK_121, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,60,PP_PRINT,"","RESERVED_LINK_121",""},
{LINK_F181_RESERVED_LINK_122, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,61,PP_PRINT,"","RESERVED_LINK_122",""},
{LINK_F182_RESERVED_LINK_123, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,62,PP_PRINT,"","RESERVED_LINK_123",""},
{LINK_F183_RESERVED_LINK_124, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,63,PP_PRINT,"","RESERVED_LINK_124",""},
{LINK_F184_RESERVED_LINK_125, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,64,PP_PRINT,"","RESERVED_LINK_125",""},
{LINK_F185_RESERVED_LINK_126, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,65,PP_PRINT,"","RESERVED_LINK_126",""},
{LINK_F186_RESERVED_LINK_127, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,66,PP_PRINT,"","RESERVED_LINK_127",""},
{LINK_F187_RESERVED_LINK_128, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,67,PP_PRINT,"","RESERVED_LINK_128",""},
{LINK_F188_RESERVED_LINK_129, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,68,PP_PRINT,"","RESERVED_LINK_129",""},
{LINK_F189_RESERVED_LINK_130, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,69,PP_PRINT,"","RESERVED_LINK_130",""},
{LINK_F190_RESERVED_LINK_131, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,70,PP_PRINT,"","RESERVED_LINK_131",""},
{LINK_F191_RESERVED_LINK_132, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,71,PP_PRINT,"","RESERVED_LINK_132",""},
{LINK_F192_RESERVED_LINK_133, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,72,PP_PRINT,"","RESERVED_LINK_133",""},


		},
		"LinkMsgInfoProperties",
	},
	"LinkMsgInfoProperties", /* szPropertiesName*/
	ISO8583_LINK,				/* nProtocolId */
	E_FIXED_LENGTH,				/* eHeaderType */
	FF_HEX,						/* eHeaderFormat */
	0,							/* nHeaderLen */
};

static const TlvInfoProperties	LINKAuthorisationData = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,LINK_F123_LEN,
{
{LINK_F123_PRODUCT_TYPE, FT_SINGLE,FF_ALPHA_A,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","PRODUCT_TYPE","NULL",NOT_REPEATABLE},
{LINK_F123_PRODUCT_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"NULL","PRODUCT_ID","NULL",NOT_REPEATABLE},
{LINK_F123_PRODUCT_DESCRIPTION, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,20,PP_PRINT,"NULL","PRODUCT_DESCRIPTION","NULL",NOT_REPEATABLE},
{LINK_F123_NEW_PIN, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"NULL","NEW_PIN","NULL",NOT_REPEATABLE},
{LINK_F123_ISSUER_SCRIPT_RESULTS, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","ISSUER_SCRIPT_RESULTS","NULL",NOT_REPEATABLE},
{LINK_F123_BILATERAL_DISCRETIONARY_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,99,PP_PRINT,"NULL","BILATERAL_DISCRETIONARY_DATA","NULL",NOT_REPEATABLE},
{LINK_F123_FCD_COMMISSION, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,24,PP_PRINT,"NULL","FCD_COMMISSION","NULL",NOT_REPEATABLE},
{LINK_F123_SENDER_PROXY, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,40,PP_PRINT,"NULL","SENDER_PROXY","NULL",NOT_REPEATABLE},
{LINK_F123_RECIPIENT_PROXY, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,40,PP_PRINT,"NULL","RECIPIENT_PROXY","NULL",NOT_REPEATABLE},
{LINK_F123_TRANSACTION_REFERENCE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,18,PP_PRINT,"NULL","TRANSACTION_REFERENCE","NULL",NOT_REPEATABLE},
{LINK_F123_SENDER_SORT_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,6,PP_PRINT,"NULL","SENDER_SORT_CODE","NULL",NOT_REPEATABLE},
{LINK_F123_SENDER_ACCOUNT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,8,PP_PRINT,"NULL","SENDER_ACCOUNT","NULL",NOT_REPEATABLE},
{LINK_F123_PAYMENT_REFERENCE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,18,PP_PRINT,"NULL","PAYMENT_REFERENCE","NULL",NOT_REPEATABLE},
{LINK_F123_RECEIVER_SORT_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,6,PP_PRINT,"NULL","RECEIVER_SORT_CODE","NULL",NOT_REPEATABLE},
{LINK_F123_RECEIVER_ACCOUNT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,8,PP_PRINT,"NULL","RECEIVER_ACCOUNT","NULL",NOT_REPEATABLE},
},
"LINKAuthorisationData"
};
/*AHA20221006 PLUTONL-4980 START*/
/*start LINK 125*/
static const TlvInfoProperties	LINKAdditionalData125 = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,LINK_F125_NB_FIELDS,
{
{LINK_F125_PIN_KEY, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,112,PP_PRINT,"NULL","PIN_KEY","NULL",NOT_REPEATABLE},

},
"LINKAdditionalData125"
};
/*end LINK 125*/

/*start LINK 125_001*/
static const TlvInfoProperties	LINKAdditionalData125001 = {
2,3,TLV_LT_ASCII,TLV_LT_ASCII,LINK_F125_001_NB_FIELDS,
{
{LINK_F125_KEY_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,96,PP_PRINT,"NULL","KEY_DATA","NULL",NOT_REPEATABLE},
{LINK_F125_CHECK_VALUE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,6,PP_PRINT,"NULL","CHEK_DIGITS","NULL",NOT_REPEATABLE},

},
"LINKAdditionalData125001"
};
/*AHA20221006 PLUTONL-4980 END*/

static const BitMappedProperties	LinkF060Prop = {
LINK_F60_NB_FIELDS,1,1,1,FF_ALPHA_AN,
{
{LINK_F060_SF02_REV_REASON,		FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","REV_REASON",""},
{LINK_F060_SF03_OTHER_SERV,		FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","OTHER_SERV",""},
{LINK_F060_SF04_STATUS_LAST_CHIP,FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","STATUS_LAST_CHIP",""},
{LINK_F060_SF05_CID,				FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","CID",""},
},
"LINK_F060_PROP"
};



static int nIsAscii = 1;

int SetAlphaEbcdic()
{
	int nSize;
	int i;

	E_ALPHA_FORMAT eFormat;
	eFormat = AF_EBCDIC;
	if( nIsAscii == 1 )
	{
		eFormat = AF_ASCII;
	}

	nSize = sizeof(LinkMsgInfoProperties.kDataPorperties.tabFieldsInfo)/sizeof(LinkMsgInfoProperties.kDataPorperties.tabFieldsInfo[0]);
	LinkMsgInfoProperties.eMsgTypeAlphaFormat=eFormat;
	for(i=0; i < nSize; i++ )
	{
		LinkMsgInfoProperties.kDataPorperties.tabFieldsInfo[i].field_info.eAlphaFormat = eFormat;

	}

	return 0;
}



int InitLinkProtocol()
{
	SetAlphaEbcdic();
	RegisterMsgInfoProp(&LinkMsgInfoProperties);
	return OK;
}

/******************************************************************************/
void InitLinkAuthorisationDataTlvInfo(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &LINKAuthorisationData;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitAdviceReversalReasionInfo(BitMappedInfo* kBitMappedInfo)
{
	kBitMappedInfo->pkProperties = &LinkF060Prop;
	ResetBitMappedInfo(kBitMappedInfo);
}
/*AHA20221006 PLUTONL-4980 START*/
/******************************************************************************/
void initLINKAdditionalData125(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &LINKAdditionalData125;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void initLINKAdditionalData125001(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &LINKAdditionalData125001;
	ResetTlvInfo(pkTlvInfo);
}
/*AHA20221006 PLUTONL-4980 END*/