/******************************************************************************\
* Changes are listed at the end of the file
*
*
\******************************************************************************/
#include <stdio.h>
#include <stddef.h>
#include <sys/time.h>
#include <define.h>
#include <pthread.h>
#include <param_arg.h>
#include <stdlib.h>
#include <errno.h>

typedef void * sql_context; /* Evil, yes.... */

#include <param_ctx.h>
/******************************************************************************/
/*#define MAX_DB_INACTIV_PERIOD			0*/
#define MAX_DB_CONN_RENEW_WAIT_PERIOD		2
/******************************************************************************/
#define MAX_DBCON_THREADS			100
#define DEFAULT_NB_DBCON_THREADS	25
#define MAX_TIME_TO_REFRESH			500 /*500 (ms)*/
/******************************************************************************/
/* The refresher thread states */
#define DBCON_ST_INVALID			0
#define DBCON_ST_FREE				1
#define DBCON_ST_ASSIGNED			2
#define DBCON_ST_RUNNING			3
/******************************************************************************/
/* The DB connection to refresh states */
#define CON_ST_NONE					0
#define CON_ST_TO_REFRESH			1
#define CON_ST_REFRESHED			2
#define CON_ST_REFRESH_FAILURE		3
/******************************************************************************/
/* The DB connection ctx state */
#define CTX_ST_NORMAL				0
#define CTX_ST_DROPPED				9
/******************************************************************************/
/* Owner state */
#define OWNER_ST_UNDEF					0
#define OWNER_ST_WAITING_RESPONSE		1
#define OWNER_ST_DONE					8
/******************************************************************************/

/******************************************************************************/
/* The ORA ERROR SQL CODE *//*ICH20160729*/
/******************************************************************************/
#define ORA_12514						-12514 /*TNS:listener does not currently know of service*/
#define ORA_01089						-1089 /* immediate shutdown in progress-no operations are permitted tips */
#define ORA_03114						-1089 /* not connected to ORACLE */
#define ORA_01034						-01034/* ORACLE not available */
#define ORA_27101						-27101/* shared memory realm does not exist */
#define ORA_03113						-03113/* end-of-file on communication channel */
#define ORA_12537						-12537/* TNS:connection closed */
/******************************************************************************/
int ToFullTrace(int nIndexCtx)
{


	if (nIndexCtx == SAF_THREAD_ID			||
		nIndexCtx == CTL_THREAD_ID			||
		nIndexCtx == FU_THREAD_ID			||
		nIndexCtx == SYSMON_PURGE_ID		||
		nIndexCtx == SYSMON_PROC_ID			||
		nIndexCtx == SYSMON_PRIS_PROC_ID	||
		nIndexCtx == SWMON_PURGE_THREAD_ID	||
		nIndexCtx == SWMON_PROC_THREAD_ID	||
		nIndexCtx == PRIS_THREAD_ID			||
		nIndexCtx == IPC_THREAD_ID			||
		nIndexCtx == UFS_THREAD_ID			||
		nIndexCtx == DBTS_THREAD_ID)
	{
		return NOK;
	}
	return OK;
}
/******************************************************************************/
typedef struct {

	int				nId;
	int				nIndex;			/* index of the connexion to renew in tab_ParamCtx[] */
	int				nState;			/* The refresher thread states */
	time_t			nExpiryTime;	/* the request expiry time */
	pthread_t		nThreadId;		/* Thread id of thread using owning this connexion */
	pthread_t		tid;			/* this thread id */
	pthread_mutex_t	ThrMutex;		/* managing nState */
	pthread_cond_t	ThrCond;

	pthread_mutex_t	ResultMutex;	/* managing nConState & nCtxState */
	pthread_cond_t	ResultCond;
	int				nConState;		/* The DB connection to refresh states */
	int				nCtxState;		/* The DB connection ctx state */

	/*EBE140905: Adding requester state variable*/
	int				nCtxOwnerState;
	pthread_mutex_t	CtxOwnerStMutex;	/* managing nCtxOwnerState */

	int				nFullTrace;
	TSParamCtx		ParamCtx;/*ICH20170830 this parm ill be used to fix issue raised by NTS this issue is generated by the ICH20170830_TC*/


} TSDBConThread;
/******************************************************************************/
static TSDBConThread	tab_DBConThread[MAX_DBCON_THREADS];
static int				nNbThreads=0;
static pthread_mutex_t	TabMutex   = PTHREAD_MUTEX_INITIALIZER;	/* managing tab_DBConThread[] &  nNbThreads */
static int 				tOraError [MAX_LENGTH_ORA_ERROR_LIST] = {0};	/* ELKAM14092022 PLUTONL-5169 */
/******************************************************************************/
void *thread_dbcon_refresh(void * arg);
/******************************************************************************\
* This function assumes that TabMutex is acquired by the caller
*
\******************************************************************************/


/******************************************************************************\
* Exit process in some database issue
*
\******************************************************************************/
int	ShutdownProcess(int nError)
{
	int i = 0;
	/* if (	nError==ORA_12514 ||
			nError==ORA_01089 ||
			nError==ORA_03114 ||
			nError==ORA_01034 ||
			nError==ORA_27101 ||
			nError==ORA_03113 ||
			nError==ORA_12537) */

	while (i < MAX_LENGTH_ORA_ERROR_LIST && tOraError[i] != 0)
	{
		if (nError == tOraError[i++])
		{
			trace_event("Shutdown  [Connexion Error]", FATAL);
			fprintf(stderr,"Shutdown  [Connexion Error]\n");
			exit (0);
		}
	}

	return OK;
}

static int	CreateDBConThread()
{

	pthread_attr_t	pattr;
	int				nThrIndex;
	TSArgParam		*p_arg;
	char			sLine[512];

	/*trace_event ( "Start CreateDBConThread()", PROCESSING );*/

	pthread_attr_init(&pattr);
	p_arg = (TSArgParam *) malloc(sizeof(TSArgParam));

	nThrIndex	=  nNbThreads;
	p_arg->nIndice = nThrIndex;

	if (pthread_create(&(tab_DBConThread[nNbThreads].tid), &pattr,
		thread_dbcon_refresh, p_arg) < 0)
	{
		fprintf(stderr,"pthread_create Error %d\n", errno);
		free(p_arg);
		return -1;
	}

	nNbThreads++;

	sprintf(sLine,"End   CreateDBConThread(OK): nNbThreads(%d)",nNbThreads);
	trace_event (sLine , PROCESSING );
	return nThrIndex;
}
/******************************************************************************/
int WaitDBConRequest (int nIndex)
{

	int	nResult;

	/*trace_event ( "Start WaitDBConRequest()", PROCESSING );*/
	nResult = pthread_mutex_lock (&(tab_DBConThread[nIndex].ThrMutex));
	if(nResult == EDEADLK)
	{
		trace_event ( "End   WaitDBConRequest(EDEADLK)", PROCESSING );
		return NOK;
	}


	/* EBE140805: This is flag assignement should not be done here:
	* 1- If this thread has just been created then is should be flagged as assigned to not get stolen by 
	*	another thread while the requester is waiting for its initialization
	* 2- if this thread has completed at least one job, then it will be flagged as "free" by FreeDBConThread()
	*/
	/*tab_DBConThread[nIndex].nState = DBCON_ST_FREE;*/
	while ( (tab_DBConThread[nIndex].nState != DBCON_ST_RUNNING))
		pthread_cond_wait(&(tab_DBConThread[nIndex].ThrCond),
		&(tab_DBConThread[nIndex].ThrMutex));

	pthread_mutex_unlock (&(tab_DBConThread[nIndex].ThrMutex));




	/*trace_event ( "End   WaitDBConRequest(OK)", PROCESSING );*/
	return OK;
}
/******************************************************************************/
int InfoDBConThread(int nIndex)
{

	int	nResult;

	if (tab_DBConThread[nIndex].nFullTrace == OK)
	{
		trace_event("Start InfoDBConThread()", PROCESSING);
	}

	nResult = pthread_mutex_lock (&(tab_DBConThread[nIndex].ThrMutex));

	if(nResult == EDEADLK)
	{
		trace_event ( "End   InfoDBConThread(EDEADLK)", ERROR );
		return NOK;
	}

	tab_DBConThread[nIndex].nState = DBCON_ST_RUNNING;

	nResult = pthread_cond_signal( &(tab_DBConThread[nIndex].ThrCond));
	nResult = pthread_mutex_unlock (&(tab_DBConThread[nIndex].ThrMutex));

	if (tab_DBConThread[nIndex].nFullTrace == OK)
	{
		trace_event("End   InfoDBConThread(OK)", PROCESSING);
	}
	return(nResult);
}
/******************************************************************************/
int FreeDBConThread (int nIndex)
{

	int		nResult;
	char		sLine[MAX_LINE_TRC];

	if( tab_DBConThread[nIndex].nFullTrace == OK )
	{
		trace_event ( "Start FreeDBConThread()", PROCESSING );
	}

	/*EBE140905: We need to wait until our previous requester has finished before we say we are free
	* we need to make sure it has received the signal
	*/

	while ((tab_DBConThread[nIndex].nCtxOwnerState != OWNER_ST_DONE))
	{

		/* sprintf(sLine, ">>> Sleeping to wait for Owner(%d)(%lu)", tab_DBConThread[nIndex].nCtxOwnerState, tab_DBConThread[nIndex].nThreadId);
		trace_event(sLine, PROCESSING);*/
		usleep(200000);
	}


	nResult = pthread_mutex_lock (&(tab_DBConThread[nIndex].ThrMutex));
	tab_DBConThread[nIndex].nState = DBCON_ST_FREE;
	pthread_mutex_unlock (&(tab_DBConThread[nIndex].ThrMutex));

	if( tab_DBConThread[nIndex].nFullTrace == OK )
	{
		trace_event ( "End   FreeDBConThread(OK)", PROCESSING );
	}

	return OK;
}
/******************************************************************************\
* This function needs to be called by an interface to initialize the
* dbcon refresh threads
*
\******************************************************************************/
int	InitDBConThreads()
{
	int i;
	pthread_mutexattr_t mattr;
	pthread_condattr_t  cattr;

	trace_event ( "Start InitDBConThreads()", PROCESSING );

	pthread_mutexattr_init(&mattr);
	pthread_condattr_init(&cattr);


	for( i=0; i < sizeof(tab_DBConThread)/sizeof(tab_DBConThread[0]); i++)
	{

		tab_DBConThread[i].nId		= 0;
		tab_DBConThread[i].nIndex	= 0;
		tab_DBConThread[i].nState	= DBCON_ST_INVALID;
		tab_DBConThread[i].nExpiryTime = 0;
		tab_DBConThread[i].nThreadId = 0;
		tab_DBConThread[i].tid		=0;
		tab_DBConThread[i].nFullTrace = OK;

		pthread_mutex_init( &(tab_DBConThread[i].ThrMutex) , &mattr);
		pthread_cond_init ( &(tab_DBConThread[i].ThrCond) , &cattr);

		pthread_mutex_init( &(tab_DBConThread[i].ResultMutex) , &mattr);
		pthread_cond_init ( &(tab_DBConThread[i].ResultCond) , &cattr);
		tab_DBConThread[i].nConState	= CON_ST_NONE;
		tab_DBConThread[i].nCtxState	= CTX_ST_NORMAL;

		tab_DBConThread[i].nCtxOwnerState = OWNER_ST_UNDEF;
		pthread_mutex_init(&(tab_DBConThread[i].CtxOwnerStMutex), &mattr);

	}

	FillOraErrorList(MAIN_THREAD_ID ,tOraError);

	return OK;
}
/******************************************************************************/
static int AllocDBConThread()
{
	int		i=0;
	int		nIndex;


	/*trace_event ( "Start AllocDBConThread()", PROCESSING );*/
	/* Get a free thread or create one if non exceeding the maximum */
	pthread_mutex_lock(&TabMutex);
	for(i=0; i < nNbThreads; i++ )
	{
		if( tab_DBConThread[i].nState == DBCON_ST_FREE )
		{
			tab_DBConThread[i].nState = DBCON_ST_ASSIGNED;
			pthread_mutex_unlock(&TabMutex);
			/*trace_event ( "End   AllocDBConThread(OK)", PROCESSING );*/
			return i;
		}
	}


	if( nNbThreads < MAX_DBCON_THREADS )
	{
		nIndex = CreateDBConThread();
		tab_DBConThread[nIndex].nState = DBCON_ST_ASSIGNED;
		pthread_mutex_unlock(&TabMutex);
		/* Need to sleep a little bit to let the thread initialize itself*/
		sleep(1);
		trace_event ( "End   AllocDBConThread(OK): Creating thread", PROCESSING );
		return nIndex;
	}

	pthread_mutex_unlock(&TabMutex);
	trace_event ( "End   AllocDBConThread(NONE)", ERROR );
	return -1;
}
/******************************************************************************/
static int DBConDoRefresh(int nIndexCtx)
{

	int				nResult;
	char			sLine[1024];
	time_t			start_time,end_time;


	if (ToFullTrace(nIndexCtx) == OK)
	{
		trace_event("Start DBConDoRefresh()", PROCESSING);
	}



	time(&start_time);
	nResult = RefreshDBConnection(nIndexCtx);
	time(&end_time);


	if ( nResult != OK)
	{
		/*if the request took too much time, do nothing. The requester thread should wake up and automatically renew the db connection*/
		if( end_time - start_time > 1 )
		{
			sprintf(sLine, "DB_CONN_REFRESH: Too much time to serve the request for ctx %d(%lu)", nIndexCtx, end_time - start_time);
			trace_event(sLine,ERROR);
			nResult = NOK;
		}
		else
		{
			sprintf(sLine,"DB_CONN_REFRESH: Refresh DB Connection by Exception for ctx %d",nIndexCtx);
			trace_event(sLine,ERROR);
			DeconnectOracle(nIndexCtx);
			/*EBE160628 */
			nResult = ConnectOracle(nIndexCtx);
			if( nResult != OK )
			{
				nResult = NOK;
			}
		}

	}

	if (ToFullTrace(nIndexCtx) == OK )
	{
		trace_event("End   DBConDoRefresh(OK)", PROCESSING);
	}

	/*EBE160628 
	return OK;*/
	return nResult;

}
/******************************************************************************/
int	ProcessDBConRequest(int nIndex)
{
	time_t			nCurrTime;
	int				nResult;
	int				nRefreshResult;
	char			sLine[1024];
	TSParamCtx		ParamCtx;


	if (tab_DBConThread[nIndex].nFullTrace == OK)
	{
		sprintf(sLine, "Start ProcessDBConRequest(RefThrIdx(%d),CtxIdx(%d), ProcThrId(%.08lu)", nIndex, tab_DBConThread[nIndex].nIndex, tab_DBConThread[nIndex].nThreadId);
		trace_event(sLine, PROCESSING);
	}

	/* we need to keep a backup of the ctx in case we have to free it*/
	/*ParamCtx = tab_ParamCtx[tab_DBConThread[nIndex].nIndex];*/
	ParamCtx = tab_DBConThread[nIndex].ParamCtx;/*ICH20170830*/

	time(&nCurrTime);

	/* we have a request to serve but first check if the request has expired*/
	if( tab_DBConThread[nIndex].nExpiryTime < nCurrTime )
	{
		sprintf(sLine,"End   ProcessDBConRequest(TOOLATE) for ctx %d",tab_DBConThread[nIndex].nIndex);
		trace_event (sLine , ERROR );
		return OK;
	}

	nRefreshResult = DBConDoRefresh(tab_DBConThread[nIndex].nIndex);

	/* Make sure to not signal until the requester go to sleep */
	nResult = pthread_mutex_lock (&(tab_DBConThread[nIndex].ResultMutex));
	if(nResult == EDEADLK)
	{
		trace_event ( "End   ProcessDBConRequest(EDEADLK)", ERROR );
		return NOK;
	}

	if( nRefreshResult == OK )
	{
		tab_DBConThread[nIndex].nConState = CON_ST_REFRESHED;
	}
	else
	{
		tab_DBConThread[nIndex].nConState = CON_ST_REFRESH_FAILURE;
	}

	/* if by this time, the requester already abondonned this ctx, then we need to free it */
	if( tab_DBConThread[nIndex].nCtxState	== CTX_ST_DROPPED )
	{
		sprintf(sLine,">>> Free Dropped ctx %d",tab_DBConThread[nIndex].nIndex);
		trace_event ( sLine, ERROR );
		DeconnectOracleParamCtx(&ParamCtx);
		FreeOracleParamCtx(&ParamCtx);
	}

	nResult = pthread_cond_signal( &(tab_DBConThread[nIndex].ResultCond));
	nResult = pthread_mutex_unlock (&(tab_DBConThread[nIndex].ResultMutex));


	if (tab_DBConThread[nIndex].nFullTrace == OK)
	{
		trace_event("End   ProcessDBConRequest(OK)", PROCESSING);
	}

	return OK;
}


/******************************************************************************\
* This function is to be called by an interface thread to check
* and renew its connection
* ICH20160729 return ORA error in the case of problem with DB
*
\******************************************************************************/
int LitecheckAndRefreshDBCon(int nIndexCtx, struct timeval	lastTime)
{

	struct timeval		currTime;
	int					nThreadIndex;
	int					nResult;
	struct timespec		maxTimeToServe;
	struct timeval  	tv;
	char				sLine[1024];
	int					nFullTrace = OK;
	int					nRefreshResult = OK;
	int					nORAError;

	if (ToFullTrace(nIndexCtx) == OK )
	{
		nFullTrace = OK;
	}
	else
	{
		nFullTrace = NOK;
	}

	if (nFullTrace == OK)
	{
		sprintf(sLine, "Start CheckAndRefreshDBCon(IdxCtx(%d), ThrId(%.08lu))", nIndexCtx, pthread_self());
		trace_event(sLine, PROCESSING);
	}

	gettimeofday(&currTime,NULL);
	/* Check if a "long" time elapsed from the last time we used the DB connection */

/*ICH	if( currTime.tv_sec - lastTime.tv_sec < MAX_DB_INACTIV_PERIOD )
	{
		trace_event ( "End   CheckAndRefreshDBCon(OK): Nothing to be done", PROCESSING );
		return OK;
	}*/

	/* Try to get a free thread to refresh our connection*/
	nThreadIndex = AllocDBConThread();
	if( nThreadIndex < 0 )
	{

		sprintf(sLine,">>>>> No thread available -> Self refresh for ctx %d",nIndexCtx);
		trace_event (sLine , ERROR );
		/* If can't get a thread to do this, then just renew the connection ourself */
		DeconnectOracle(nIndexCtx);
		FreeOracleCtx(nIndexCtx); /*EBE140131*/


		AllocateOracleCtx(nIndexCtx); /*EBE140131*/

		nORAError=ConnectOracle(nIndexCtx);

		if (nFullTrace == OK)
		{
			trace_event("End   CheckAndRefreshDBCon(OK)", PROCESSING);
		}

		return nORAError;

	}
	
	if (gettimeofday(&tv, NULL) < 0) 
	{
		fprintf(stderr, "gettimeofday Error : %d\n", errno);
		return (NOK);
	}

	/*EBE140905: set our state as waiting response from the refresher*/
	nResult = pthread_mutex_lock(&(tab_DBConThread[nThreadIndex].CtxOwnerStMutex));
	tab_DBConThread[nThreadIndex].nCtxOwnerState = OWNER_ST_WAITING_RESPONSE;
	pthread_mutex_unlock(&(tab_DBConThread[nThreadIndex].CtxOwnerStMutex));


	/*Build the request parameters and inform the refresher to start refreshing the DB connection*/
	nResult = pthread_mutex_lock (&(tab_DBConThread[nThreadIndex].ResultMutex));
	if(nResult == EDEADLK)
	{
		trace_event ( "End   CheckAndRefreshDBCon(EDEADLK on ResultMutex)", ERROR );
		pthread_mutex_unlock(&(tab_DBConThread[nThreadIndex].ResultMutex));
		return NOK;
	}
	
	
	maxTimeToServe.tv_sec = tv.tv_sec + MAX_TIME_TO_REFRESH/1000;
	maxTimeToServe.tv_nsec = (tv.tv_usec *1000) + (MAX_TIME_TO_REFRESH%1000) * 1000000;
	if( maxTimeToServe.tv_nsec > 1000000000 )
	{
		maxTimeToServe.tv_nsec -= 1000000000;
		maxTimeToServe.tv_sec++;
	}


	tab_DBConThread[nThreadIndex].nConState		= CON_ST_TO_REFRESH;
	tab_DBConThread[nThreadIndex].nCtxState		= CTX_ST_NORMAL;
	tab_DBConThread[nThreadIndex].nIndex		= nIndexCtx;
	tab_DBConThread[nThreadIndex].nExpiryTime	= maxTimeToServe.tv_sec;
	tab_DBConThread[nThreadIndex].nThreadId		= p7_thread_id();
	tab_DBConThread[nThreadIndex].nFullTrace	= nFullTrace;
	tab_DBConThread[nThreadIndex].ParamCtx		= tab_ParamCtx[nIndexCtx];/*ICH20170830*/


	InfoDBConThread(nThreadIndex);

	/*Waiting for a response from the refresher*/
	while ( (tab_DBConThread[nThreadIndex].nConState == CON_ST_TO_REFRESH))
	{
		nResult = pthread_cond_timedwait(&(tab_DBConThread[nThreadIndex].ResultCond),
			&(tab_DBConThread[nThreadIndex].ResultMutex),&maxTimeToServe);
		if( nResult == ETIMEDOUT )
		{
			sprintf(sLine,"DB_CONN_REFRESH: TIMEOUT ON REFRESH for ctx %d(%d)(%d)",nIndexCtx,tab_DBConThread[nThreadIndex].nConState,nThreadIndex);
			trace_event ( sLine, ERROR );
			break;
		}
		else if( nResult != 0 )
		{
			/*sprintf(sLine,"DB_CONN_REFRESH: ERROR WAIT ON REFRESH for ctx %d(%d)(%d)",nIndexCtx,tab_DBConThread[nThreadIndex].nConState,nThreadIndex);*/
			sprintf(sLine,"DB_CONN_REFRESH: ERROR(%d,%d) WAIT ON REFRESH for ctx %d(%d)(%d)",nResult, errno, nIndexCtx,tab_DBConThread[nThreadIndex].nConState,nThreadIndex);
			trace_event (sLine , ERROR );
			break;
		}
	}



	if( tab_DBConThread[nThreadIndex].nConState == CON_ST_REFRESH_FAILURE ||
		tab_DBConThread[nThreadIndex].nConState == CON_ST_TO_REFRESH )
	{
		sprintf(sLine,">>>>> External process failed to refresh -> local refresh for ctx %d(%d)(%d)",nIndexCtx,tab_DBConThread[nThreadIndex].nConState,nThreadIndex);
		trace_event (sLine , ERROR );
		/* EBE140422: This will be done by refresher thread, we just allocate a new ctx
		DeconnectOracle(nIndexCtx);
		FreeOracleCtx(nIndexCtx); *EBE140131*
		*/

		/*EBE160628: we may have a leak in case of CON_ST_REFRESH_FAILURE. No thread will free the ctx*/
		if( tab_DBConThread[nThreadIndex].nConState == CON_ST_REFRESH_FAILURE )
		{
			DeconnectOracle(nIndexCtx);
			FreeOracleCtx(nIndexCtx);
		}
		else
		{
			tab_DBConThread[nThreadIndex].nCtxState	= CTX_ST_DROPPED;
		}

		AllocateOracleCtx(nIndexCtx); /*EBE140131*/
		nORAError = ConnectOracle(nIndexCtx);
	}
	else if( tab_DBConThread[nThreadIndex].nConState == CON_ST_REFRESHED )
	{
		if (tab_DBConThread[nThreadIndex].nFullTrace == OK)
		{
			sprintf(sLine, ">>> Refresh Success %d(used %d)", nIndexCtx, nThreadIndex);
			trace_event(sLine, ERROR);
		}
		nORAError = OK;
	}
	tab_DBConThread[nThreadIndex].nConState = CON_ST_NONE;
	pthread_mutex_unlock (&(tab_DBConThread[nThreadIndex].ResultMutex));

	/*EBE140905*/
	nResult = pthread_mutex_lock(&(tab_DBConThread[nThreadIndex].CtxOwnerStMutex));
	tab_DBConThread[nThreadIndex].nCtxOwnerState = OWNER_ST_DONE;
	pthread_mutex_unlock(&(tab_DBConThread[nThreadIndex].CtxOwnerStMutex));


	if (nFullTrace == OK)
	{
		trace_event("End   CheckAndRefreshDBCon(OK)", PROCESSING);
	}

	return nORAError;
}
/******************************************************************************\
* This function is to be called by an interface thread to check
* and renew its connection and stop interface in the case of ORA errors
*ICH20160729
\******************************************************************************/
int CheckAndRefreshDBCon(int nIndexCtx, struct timeval	lastTime)
{

	int					nResult;
	char				sLine[1024];


	nResult=LitecheckAndRefreshDBCon(nIndexCtx,lastTime);

	nResult=ShutdownProcess(nResult);

	return nResult;
}
/******************************************************************************/


/******************************************************************************\
EBE140905: 
> Bug description: 
1- Processing thread P1 request refresh
2- Refresher thread R1 is assigned
3- R1 processes the request, signal to proc thread, and free itself
4- Processing thread P2 request refresh
5- Refresher thread R1 is assigned while P1 didn't yet received the signal <-- Bug 1
6- P1 wake up, create a new ctx and flag ctx as 'dropped'
7- R1 processes the request, find ctx is dropped so it frees the ctx of P2 and signal to thread P2 <- Bug 2
7- P2 wake up and try to use the connection while its not valid one
> Solution:
The context and connection states and mutex/cond belongs to the connection so we move the fields to tab_ParamCtx
-------------------------------------------------------------------------------
ICH20170830_TC

1- Processing thread P1 request refresh
2- Refresher thread R1 is assigned
3- R1 processes the request,
4- P1 wake up, create a new ctx and flag ctx as 'dropped'
5- R1 wake up and continue, find ctx is dropped so it frees the new ctx of P1 intead of the old ctx

> Solution:
Save the old contex in structure

\******************************************************************************/

