#include <stdio.h>
#include <stdlib.h>
#include <define.h>
#include <iso8583.h>
#include <visa_define.h>
#include <visa_fields.h>
#include <visa_ictag.h>


/*START PLUTONL-1822*/
static MsgInfoProperties	Base1MsgProperties = {
	FF_BCD,			/* eMsgTypeType */
	4,				/* nMsgTypeLen */
	AF_EBCDIC,		/* eMsgTypeAlphaFormat */
	"BASE1",		/* szProtocolName	*/
	"VISA",			/* szProtocolPrefix */
	{
		128,		/* nNbFields */
		2,			/* nNbBitmaps */
		2,			/* nNbConsBitmaps */
		8,			/* nBitmapLen */
		FF_BIN,		/* eBitmapFmt */
		{
{VISA_BIT_MAP2, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,0,PP_PRINT,"","BIT_MAP2",""},
{VISA_CARD_NBR, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,19,PP_HIDE,"","CARD_NBR",""},
{VISA_PROC_CODE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","PROC_CODE",""},
{VISA_TRANS_AMOUNT, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","TRANS_AMOUNT",""},
{VISA_STLMNT_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","STLMNT_AMOUNT",""},
{VISA_BILLING_AMOUNT, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","BILLING_AMOUNT",""},
{VISA_XMIT_TIME, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","XMIT_TIME",""},
{STD_ISO_BILLING_AMOUNT_FEES, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,8,PP_PRINT,"","BILLING_AMOUNT_FEES",""},
{STD_ISO_STLMNT_CNVRSN_RATE, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","STLMNT_CNVRSN_RATE",""},
{VISA_BILLING_CNVRSN_RATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,8,PP_PRINT,"","BILLING_CNVRSN_RATE",""},
{VISA_AUDIT_NBR, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","AUDIT_NBR",""},
{VISA_TRANS_TIME, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","TRANS_TIME",""},
{VISA_TRANS_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","TRANS_DATE",""},
{VISA_EXPIRY_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","EXPIRY_DATE",""},
{VISA_STLMNT_DATE, FT_SINGLE/*FT_UNDEF*/,FF_BCD/*FF_ALPHA_N*/,AF_EBCDIC,FL_FIX,LU_NIBBLES/*LU_BYTE*/,4,PP_PRINT,"","STLMNT_DATE",""},
{VISA_CNVRSN_DATE, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","CNVRSN_DATE",""},
{STD_ISO_CAPTURE_DATE, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","CAPTURE_DATE",""},
{VISA_MERCHANT_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","MERCHANT_TYPE",""},
{VISA_ACQR_COUNTRY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","ACQR_COUNTRY",""},
{VISA_PAN_COUNTRY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","PAN_COUNTRY",""},
{VISA_FORWD_COUNTRY, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","FORWD_COUNTRY",""},
{VISA_POS_ENTRY_MODE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","POS_ENTRY_MODE",""},
{VISA_CARD_SEQUENCE_NBR, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","CARD_SEQUENCE_NBR",""},
{STD_ISO_FUNCTION_CODE, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","NET_INT_ID",""},
{VISA_POS_CONDITION, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,2,PP_PRINT,"","POS_CONDITION",""},
{VISA_POS_PIN_CAPTURE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,2,PP_PRINT,"","POS_PIN_CAPTURE",""},
{VISA_AUTHOR_ID_LENGTH, FT_UNDEF/*FT_SINGLE*/,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,1,PP_PRINT,"","AUTHOR_ID_LENGTH",""},
{VISA_TRANS_FEE, FT_SINGLE,FF_X_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","TRANS_FEE",""},
{STD_ISO_RECONC_INDICATOR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","TANS_SETTL_FEE",""},
{STD_ISO_ORIGINAL_AMOUNTS, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","AMNT_TRANS_PROC_FEE",""},
{STD_ISO_ACQR_REFERENCE_DATA, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","AMNT_SETTL_PROC_FEE",""},
{VISA_ACQR_ID, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,11,PP_PRINT,"","ACQR_ID",""},
{VISA_FORWD_ID, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,11,PP_PRINT,"","FORWD_ID",""},
{VISA_PAN_EXTENDED /*PLUTONL-5548 Enh 2023Q2  Visa 1.2 AHA20221221*/,FT_STRUCT_TLV /*FT_SINGLE*/,FF_HEX,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ELECTRONIC_COMMERCE_DATA","B1_F034_PROP"},
{VISA_T2_DATA, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_B,LU_NIBBLES,37,PP_HIDE,"","T2_DATA",""},
{VISA_T3_DATA, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,104,PP_PRINT,"","T3_DATA",""},
{VISA_REFERENCE_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","REFERENCE_NBR",""},
{VISA_AUTHOR_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUTHOR_ID",""},
{VISA_RESPONSE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","RESPONSE_CODE",""},
{VISA_SERVICE_CODE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","SERVICE_CODE",""},
{VISA_TERMINAL_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","TERMINAL_NBR",""},
{VISA_OUTLET_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"","OUTLET_NBR",""},
{VISA_TERMINAL_ADR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,40,PP_PRINT,"","TERMINAL_ADR",""},
{VISA_ADTNL_RESP_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,25,PP_PRINT,"","ADTNL_RESP_DATA","B1_F044_PROP"},
{VISA_T1_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,76,PP_HIDE,"","T1_DATA",""},
{STD_ISO_FEES_AMOUNT, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_ISO",""},
{STD_ISO_ADTNL_DATA_NATL, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_NATL",""},
{VISA_ADTNL_DATA_PRIV, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_PRIV",""},
{VISA_TRANS_CRNCY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","TRANS_CRNCY",""},
{VISA_STLMNT_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_CRNCY",""},
{VISA_BILLING_CRNCY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","BILLING_CRNCY",""},
{VISA_PIN_DATA, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_FIX,LU_NIBBLES,16,PP_HIDE,"","PIN_DATA",""},
{VISA_SECURITY_DATA, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,16,PP_PRINT,"","SECURITY_DATA",""},
{VISA_ADTNL_AMOUNTS, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,120,PP_PRINT,"","ADTNL_AMOUNTS",""},
{VISA_ICC_DATA, FT_STRUCT_BER,FF_BIN,AF_EBCDIC,FL_B,LU_BYTE,255,PP_HIDE,"","ICC_DATA","B1_F055_PROP"},
{VISA_I_ORIG_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_BB,LU_BYTE,255,PP_PRINT,"","Customer Related Data",""}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2*/
{VISA_ORIG_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ORIG_DATA",""},
{VISA_FILE_UPDATE, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_NAT_1",""},
{VISA_FILE_SECURITY, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_NAT_2",""},
{VISA_GEOGR_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,14,PP_PRINT,"","GEOGR_DATA",""},
{VISA_ADTNL_POS_INFO, FT_STRUCT_STATIC,FF_BCD,AF_EBCDIC,FL_B,LU_BYTE,12,PP_PRINT,"","ADTNL_POS_INFO","B1_F060_PROP"},
{VISA_OTHER_AMOUNTS, FT_STRUCT_STATIC,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,36,PP_PRINT,"","OTHER_AMOUNTS","B1_F061_PROP"},
{VISA_CPS_FIELDS, FT_STRUCT_BITMAPPED,FF_BIN,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","CPS_FIELDS","B1_F062_PROP"},
{VISA_PRIV_USE_FIELDS, FT_STRUCT_BITMAPPED,FF_BIN,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","PRIV_USE_FIELDS","B1_F063_PROP"},
{VISA_MAC1, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC1",""},
{STD_ISO_BIT_MAP_2, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","BIT_MAP_2",""},
{VISA_STLMNT_CODE, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","STLMNT_CODE",""},
{STD_ISO_EXT_PAYMENT_CODE, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,2,PP_PRINT,"","EXT_PAYMENT_CODE",""},
{VISA_RECEIVER_COUNTRY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","RECEIVER_COUNTRY",""},
{VISA_STLMNT_INST_COUNTRY, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_INST_COUNTRY",""},
{VISA_NW_MNGMT_INFO, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","NW_MNGMT_INFO",""},
{STD_ISO_MESSAGE_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","MESSAGE_NBR",""},
{STD_ISO_MESSAGE_NBR_LAST, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","MESSAGE_NBR_LAST",""},
{VISA_ACTION_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","ACTION_DATE",""},
{VISA_CR_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","CR_NBR",""},
{VISA_CR_REV_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","CR_REV_NBR",""},
{VISA_DB_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","DB_NBR",""},
{VISA_DB_REV_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","DB_REV_NBR",""},
{STD_ISO_TRANSFER_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","TRANSFER_NBR",""},
{STD_ISO_TRANSFER_REV_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","TRANSFER_REV_NBR",""},
{STD_ISO_INQ_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","INQ_NBR",""},
{STD_ISO_AUT_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","AUT_NBR",""},
{STD_ISO_CR_PROC_FEE_AMNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","CR_PROC_FEE_AMNT",""},
{STD_ISO_CR_TANS_FEE_AMNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","CR_TANS_FEE_AMNT",""},
{STD_ISO_DB_PROC_FEE_AMNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","DB_PROC_FEE_AMNT",""},
{STD_ISO_DB_TRANS_FEE_AMNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","DB_TRANS_FEE_AMNT",""},
{VISA_CR_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_AMOUNT",""},
{VISA_CR_REV_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REV_AMOUNT",""},
{VISA_DB_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_AMOUNT",""},
{VISA_DB_REV_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REV_AMOUNT",""},
{VISA_ORIG_DATA, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,42,PP_PRINT,"","ORIG_DATA",""},
{VISA_FILE_UPDATE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","FILE_UPDATE",""},
{VISA_FILE_SECURITY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","FILE_SECURITY",""},
{STD_ISO_RESP_INDICATOR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,5,PP_PRINT,"","RESP_INDICATOR",""},
{STD_ISO_SERVICE_IND, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,7,PP_PRINT,"","SERVICE_IND",""},
{VISA_REPLACE_AMOUNTS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","REPLACE_AMOUNTS",""},
{VISA_MSG_SECURITY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MSG_SECURITY",""},
{VISA_NET_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,17,PP_PRINT,"","NET_AMOUNT",""},
{STD_ISO_PAYEE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"","PAYEE",""},
{VISA_STLMNT_INSTITN, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","STLMNT_INSTITN",""},
{VISA_RECEIVER_ID, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,11,PP_PRINT,"","RECEIVER_ID",""},
{VISA_FILE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,17,PP_PRINT,"","FILE_NAME",""},
{VISA_ACCOUNT_ID1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID1",""},
{VISA_ACCOUNT_ID2, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID2",""},
{VISA_TRANS_DESC, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","TRANS_DESC","B1_F104_PROP"},
{STD_ISO_RESERVED_ISO_1, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_ISO_1",""},
{STD_ISO_RESERVED_ISO_2, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_ISO_2",""},
{STD_ISO_RESERVED_ISO_3, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_ISO_3",""},
{STD_ISO_RESERVED_ISO_4, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_ISO_4",""},
{STD_ISO_RESERVED_ISO_5, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_ISO_5",""},
{STD_ISO_RESERVED_ISO_6, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_ISO_6",""},
{STD_ISO_RESERVED_ISO_7, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_ISO_7",""},
{STD_ISO_RESERVED_NAT_3, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_NAT_3",""},
{STD_ISO_RESERVED_NAT_4, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_NAT_4",""},
{STD_ISO_RESERVED_NAT_5, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","RESERVED_NAT_5",""},
{VISA_ADTNL_TRACE_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,24,PP_PRINT,"","ADTNL_TRACE_DATA",""},
{STD_ISO_CARD_ISSUER_REF_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","CARD_ISSUER_REF_DATA",""},
{STD_ISO_NATIONAL_USE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","NATIONAL_USE",""},
{STD_ISO_INTRA_COUNTRY_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","INTRA_COUNTRY_DATA",""},
{STD_ISO_RES_NAT_USE_10, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_10",""},
{VISA_ORIG_MSG_TYPE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RECORD_DATA",""},
{STD_ISO_ISS_INST_ID_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_B,LU_BYTE,11,PP_PRINT,"","ISS_INST_ID_CODE",""},
{STD_ISO_ADTNL_RECORD_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_RECORD_DATA",""},
{VISA_ADR_VERIF_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_B,LU_BYTE,29,PP_PRINT,"","ADR_VERIF_DATA","B1_F123_PROP"},
{STD_ISO_MEMBER_DEF_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,199,PP_PRINT,"","MEMBER_DEF_DATA",""},
{VISA_SUPPORT_INFO, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","SUPPORT_INFO","B1_F125_PROP"},
{VISA_PRIV_USE_FIELD, FT_STRUCT_BITMAPPED,FF_BIN,AF_EBCDIC,FL_B,LU_BYTE,255,PP_HIDE,"","PRIV_USE_FIELD","B1_F126_PROP"},	/*IZL 06052022 PLUTONL-4675*/	/*PP_PRINT --> PP_HIDE*/
{VISA_RECORD_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,100,PP_PRINT,"","PRIV_DATA_2",""},
{VISA_MAC2, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC2",""},

		},
		"Visa3MsgBMInfoProperties",
	},
	"Base1MsgProperties", /* szPropertiesName*/
	ISO8583_VISA_BASE1,			/* nProtocolId */
	E_FIXED_LENGTH,				/* eHeaderType */
	FF_HEX,					/* eHeaderFormat */
	22,							/* nHeaderLen */
};
/**/
static const BerInfoProperties	VisaF055Prop = {
VISA_F55_NB_FIELDS,
{
{VISA_TAG_ISS_SCRIPT1, FT_SINGLE,FF_HEX,AF_ASCII,FL_LLL,LU_BYTE,256,PP_HIDE,"","ISS_SCRIPT1","",NOT_REPEATABLE},
{VISA_TAG_ISS_SCRIPT2, FT_SINGLE,FF_HEX,AF_ASCII,FL_LLL,LU_BYTE,256,PP_HIDE,"","ISS_SCRIPT2","",NOT_REPEATABLE},
{VISA_TAG_APP_INTER_PROFILE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,FL_LL,2,PP_PRINT,"","APP_INTER_PROFILE","",NOT_REPEATABLE},
{VISA_TAG_DED_FILE_NAME, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,16,PP_PRINT,"","DED_FILE_NAME","",NOT_REPEATABLE},
{VISA_TAG_ISS_AUTHEN_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,16,PP_PRINT,"","ISS_AUTHEN_DATA","",NOT_REPEATABLE},
{VISA_TAG_TVR, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,5,PP_PRINT,"","TVR","",NOT_REPEATABLE},
{VISA_TAG_TRANS_DATE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRANS_DATE","",NOT_REPEATABLE},
{VISA_TAG_TRANS_TYPE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","TRANS_TYPE","",NOT_REPEATABLE},
{VISA_TAG_SEC_PIN_BLOCK, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","SEC_PIN_BLOCK","",NOT_REPEATABLE},
{VISA_TAG_TRANS_CUR_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","TRANS_CUR_CODE","",NOT_REPEATABLE},
{VISA_TAG_TRANS_AMOUNT, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","TRANS_AMOUNT","",NOT_REPEATABLE},
{VISA_TAG_OTHER_AMOUNT, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","OTHER_AMOUNT","",NOT_REPEATABLE},
{VISA_TAG_ISS_APP_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,33,PP_PRINT,"","ISS_APP_DATA","",NOT_REPEATABLE},
{VISA_TAG_TERM_COUNTRY_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","TERM_COUNTRY_CODE","",NOT_REPEATABLE},
{VISA_TAG_APP_CRYPTOGRAM, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,8,PP_HIDE,"","APP_CRYPTOGRAM","",NOT_REPEATABLE},
{VISA_TAG_TERM_CAP, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TERM_CAP","",NOT_REPEATABLE},
{VISA_TAG_ATC, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_HIDE,"","ATC","",NOT_REPEATABLE},
{VISA_TAG_UNPRED_NUMBER, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","UNPRED_NUMBER","",NOT_REPEATABLE},
},

"B1_F055_PROP"
};


/**/
int InitBase1Protocol()
{
	RegisterMsgInfoProp(&Base1MsgProperties);
	return OK;
}
/*END PLUTONL-1822*/


static const TlvInfoProperties	VisaElectComDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_NB_FIELDS,
{
{B1_F34_AUTHEN_DATA, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","AUTHEN_DATA","B1_T01_PROP",NOT_REPEATABLE},
{B1_F34_ACCEPTANCE_ENV_ADD_DATA, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","ACCEPTANCE_ENV_ADD_DATA","B1_T02_PROP",NOT_REPEATABLE},
{B1_F34_EU_PSD2_SCA_CSC, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","EU_PSD2_SCA_CSC","B1_T4A_PROP",NOT_REPEATABLE},
{B1_F34_SUPP_DATA, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","SUPP_DATA","B1_T56_PROP",NOT_REPEATABLE},
},
"B1_F034_PROP"
};

static const TlvInfoProperties	VisaF34T02DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T02_NB_FIELDS,
{
{B1_F34T02_INITIATING_PARTY_ID, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","INITIATING_PARTY_ID","",NOT_REPEATABLE},

{B1_F34T02_PAYFAC_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","Payment Facilitator Street Address",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F34T02_PAYFAC_CITY_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,50,PP_PRINT,"","Payment Facilitator City Name",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F34T02_PAYFAC_STATE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,3,PP_PRINT,"","Payment Facilitator State/Province Code",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F34T02_PAYFAC_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,10,PP_PRINT,"","Payment Facilitator Postal Code",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F34T02_PAYFAC_CTRY_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_LL,LU_BYTE,3,PP_PRINT,"","Payment Facilitator Country Code",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
},
"B1_T02_PROP"
};
/*END IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/
/*Start IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/
static const TlvInfoProperties	VisaF34T4ADataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T4A_NB_FIELDS,
{
{B1_F34T4A_TRST_MER_EXEM, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","TRST_MER_EXEM","",NOT_REPEATABLE},
{B1_F34T4A_LOW_VAL_EXEM, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","LOW_VAL_EXEM","",NOT_REPEATABLE},
{B1_F34T4A_SPC, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","SPC","",NOT_REPEATABLE},
{B1_F34T4A_TRA, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","TRA","",NOT_REPEATABLE},
{B1_F34T4A_DELG_AUTH, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","DELG_AUTH","",NOT_REPEATABLE},
{B1_F34T4A_REASON_HONOR_EXEM, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,80,PP_PRINT,"","REASON_HONOR_EXEM","",NOT_REPEATABLE},
{B1_F34T4A_TRA_SCORE, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","TRA_SCORE","",NOT_REPEATABLE},
},
"B1_T4A_PROP"
};
/*END IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/

static const TlvInfoProperties	VisaF34T56DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T56_NB_FIELDS,
{
{B1_F34T56_SESSION_ID, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,32,PP_PRINT,"","SESSION_ID","",NOT_REPEATABLE},
},
"B1_T56_PROP"
};
static const TlvInfoProperties	VisaTransSpecDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_NB_FIELDS,
{
{B1_F104_PURCHASE_LINE_ITEM_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","PURCHASE_LINE_ITEM_DATA","",NOT_REPEATABLE},
{B1_F104_PAY_FAC_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","PAY_FAC_DATA","B1_F104_T56_PROP",NOT_REPEATABLE},
{B1_F104_BUSINESS_APP_ID, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_BB,LU_BYTE,255,PP_PRINT,"","BUSINESS_APP_ID","B1_F104_T57_PROP",IS_REPEATABLE}, /*PLUTONL-8878 Enh24Q4 AMANS AN 3.20*/
{B1_F104_HEALTHCARE_ELIGIBILITY_INQ, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","HEALTHCARE_ELIGIBILITY_INQ","",NOT_REPEATABLE},
{B1_F104_PROMOTION_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","PROMOTION_DATA","",NOT_REPEATABLE},
{B1_F104_VISA_RISK_ASSESSMENT_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","VISA_RISK_ASSESSMENT_DATA","",NOT_REPEATABLE},
{B1_F104_COMMERCIAL_CARD_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","COMMERCIAL_CARD_DATA","",NOT_REPEATABLE},
{B1_F104_INSTALLMENT_PAYMENT_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","INSTALLMENT_PAYMENT_DATA","",NOT_REPEATABLE},
{B1_F104_SENDER_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","SENDER_DATA","B1_F104_T5F_PROP",NOT_REPEATABLE},
{B1_F104_AIRLINE_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","AIRLINE_DATA","",NOT_REPEATABLE},
{B1_F104_CAR_RENTAL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","CAR_RENTAL_DATA","",NOT_REPEATABLE},
{B1_F104_LODGING_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","LODGING_DATA","",NOT_REPEATABLE},
{B1_F104_NON_INDUSTRY_SPECIFIC_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","NON_INDUSTRY_SPECIFIC_DATA","",NOT_REPEATABLE},
{B1_F104_MASTERCARD_MEMBER_DEF_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","MASTERCARD_MEMBER_DEF_DATA","",NOT_REPEATABLE},
{B1_F104_AMEX_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","AMEX_DATA","",NOT_REPEATABLE},
{B1_F104_MULTIPLE_PAYMENT_FORMS, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","MULTIPLE_PAYMENT_FORMS","",NOT_REPEATABLE},
{B1_F104_TRAVEL_TAG_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","TRAVEL_TAG_DATA","",NOT_REPEATABLE},
{B1_F104_ISSUER_SUPPLIED_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","ISSUER_SUPPLIED_DATA","",NOT_REPEATABLE},
{B1_F104_LOAN_DETAILS, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","LOAN_DETAILS","",NOT_REPEATABLE},
{B1_F104_FREE_FORM_DESCRIPTION_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","FREE_FORM_DESCRIPTION_DATA","B1_F104_T71_PROP",NOT_REPEATABLE},
{B1_F104_ADDITIONAL_SENDER_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","ADDITIONAL_SENDER_DATA","B1_F104_T71_PROP",NOT_REPEATABLE},
{B1_F104_FREE_FORM_TEXT_ORG_CR_TRN, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"","FREE_FORM_TEXT_ORG_CR_TRN","B1_F104_T71_PROP",NOT_REPEATABLE},
},
"B1_F104_PROP"
};

static const TlvInfoProperties	VisaF104T56DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T56_NB_FIELDS,
{
{B1_F104T56_PAY_FAC_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"NULL","PAY_FAC_ID","NULL",NOT_REPEATABLE},
{B1_F104T56_SUB_MER_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"NULL","SUB_MER_ID","NULL",NOT_REPEATABLE},
{B1_F104T56_ISO_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,11,PP_PRINT,"NULL","ISO_ID","NULL",NOT_REPEATABLE},
},
"B1_F104_T56_PROP"
};

/*Start PLUTONL-8878 Enh24Q4 AMANS AN 3.20*/
static const TlvInfoProperties	VisaF104T57DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T57_NB_FIELDS,
{
{B1_F104_T57_BUSINESS_APP_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"LoV","Business Application Identifier","",0,"F104_T57_01_LoV",-1,NOT_REPEATABLE},
{B1_F104_T57_SERVICE_PROC_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"LoV","Service Processing Type","",0,"F104_T57_80_LoV",-1,NOT_REPEATABLE},
{B1_F104_T57_DEFER_OCT_REQ_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","Deferred OCT Date/Time Value","",NOT_REPEATABLE},
{B1_F104_T57_PAY_PURPOSE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,12,PP_PRINT,"","Purpose of Payment","",NOT_REPEATABLE},
{B1_F104_T57_MAX_PROC_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","Maximum Processing Date","",NOT_REPEATABLE}, 
{B1_F104_T57_PT_SRC_FUNDS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"LoV","Source of Funds","",0,"F104_T57_PT_02_LoV",-1,NOT_REPEATABLE},
},
"B1_F104_T57_PROP"
};
/*End PLUTONL-8878 Enh24Q4 AMANS AN 3.20*/

/*Start HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
static const TlvInfoProperties	VisaF34T01DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T01_NB_FIELDS,
{
{B1_F34T01_PROTOCOL_VERSION_NUMBER, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","PROTOCOL_VERSION_NUMBER","",NOT_REPEATABLE},
{B1_F34T01_AUTHEN_DATA_QUALITY_INDC, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","AUTHEN_DATA_QUALITY_INDC","",NOT_REPEATABLE}, /*PLUTONL-8809 AMANS Enh2024Q4 VISA 3.9*/

},
"B1_T01_PROP"
};
/*END HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
static const TlvInfoProperties	VisaF104T5FDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T5F_NB_FIELDS,
{
{B1_F104T5F_SENDER_REF_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"NULL","SENDER_REF_NBR","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_ACCOUNT_NO, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,34,PP_PRINT,"NULL","SENDER_ACCOUNT_NO","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,30,PP_PRINT,"NULL","SENDER_NAME","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_STREET_ADDR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,35,PP_PRINT,"NULL","SENDER_STREET_ADDR","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_CITY_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"NULL","SENDER_CITY_NAME","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_STATE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","SENDER_STATE","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_COUNTRY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","SENDER_COUNTRY","NULL",NOT_REPEATABLE},
{B1_F104T5F_FUNDS_SOURCE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","FUNDS_SOURCE","NULL",NOT_REPEATABLE},
{B1_F104T5F_RECIPIENT_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,30,PP_PRINT,"NULL","RECIPIENT_NAME","NULL",NOT_REPEATABLE},
},
"B1_F104_T5F_PROP"
};

static const TlvInfoProperties	VisaF104T71DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T71_NB_FIELDS,
{
{B1_F104T71_FREE_FORM_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,45,PP_PRINT,"","FREE_FORM_DATA","",NOT_REPEATABLE},
},
"B1_F104_T71_PROP"
};



static const TlvInfoProperties	Base1VerifDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,2,
{
{B1_F123_ADDR_VERIF_DATA,	FT_STRUCT_TLV	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,256	,PP_PRINT	,"NULL"	,"ADDR_VERIF_DATA"	,"B1_F123_T66_PROP"	,NOT_REPEATABLE},
{B1_F123_TOKEN_DATA,		FT_STRUCT_TLV	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,256	,PP_PRINT	,"NULL"	,"TOKEN_DATA"		,"B1_F123_T68_PROP"	,NOT_REPEATABLE},
},
"B1_F123_PROP"
};

static const TlvInfoProperties	Base1AddrVerifDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,2,
{
{B1_F123_T66_POSTAL_CD	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,9	,PP_PRINT	,"NULL"	,"POSTAL_CODE"	,"NULL"	,NOT_REPEATABLE},
{B1_F123_T66_STREE_ADDR	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,40	,PP_PRINT	,"NULL"	,"STREET_ADDR"	,"NULL"	,NOT_REPEATABLE},
},
"B1_F123_T66_PROP"
};

static const TlvInfoProperties	Base1TokenDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,4,
{
{B1_F123_T68_TOKEN		,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,19	,PP_PRINT	,"NULL",	"TOKEN"			,"NULL"	,NOT_REPEATABLE},
{B1_F123_T68_TKN_ASS_LVL	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,2	,PP_PRINT	,"NULL",	"TOKEN_ASS_LVL"	,"NULL"	,NOT_REPEATABLE},
{B1_F123_T68_TKN_REQ_ID	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,11	,PP_PRINT	,"NULL",	"TOKEN_REQ_ID"	,"NULL"	,NOT_REPEATABLE},
{B1_F123_T68_TKN_RANGE	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,9	,PP_PRINT	,"NULL",	"PAN_RANGE"		,"NULL"	,NOT_REPEATABLE},
},
"B1_F123_T68_PROP"
};

/*Start IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/

static const TlvInfoProperties	VisaSupportInfDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F125_NB_FIELDS,
{
{B1_F125_ADD_ORIGINAL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F125_ADD_ORIGINAL_DATA","B1_F123_T03_PROP",NOT_REPEATABLE},

},
"B1_F125_PROP"
};

static const TlvInfoProperties	VisaF125T03DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F125_T03_NB_FIELDS,
{
{B1_F125T03_ORIGINAL_TRA_ID, FT_STRUCT_TLV,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,8,PP_PRINT,"NULL","ORIGINAL_TRA_ID","NULL",NOT_REPEATABLE},
},
"B1_F123_T03_PROP"
};
/*End IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/

/*Start IZL 05052022 PLUTONL-4675*/
static const BitMappedProperties VisaF126DataProp = {
VISA_F126_NB_FIELDS,1,1,8,FF_BIN,
{
{B1_BIT_F126_Reserved1, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_L,LU_BYTE,255,PP_PRINT,"","Reserved1",""},
{B1_BIT_F126_Reserved2, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_L,LU_BYTE,255,PP_PRINT,"","Reserved2",""},
{B1_BIT_F126_Reserved3, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_L,LU_BYTE,255,PP_PRINT,"","Reserved3",""},
{B1_BIT_F126_Reserved4, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_L,LU_BYTE,255,PP_PRINT,"","Reserved4",""},
{B1_BIT_F126_VISA_MERCH_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","Visa Merchant Identifier",""},
{B1_BIT_F126_CH_CERT_SERIAL_NO, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,17,PP_PRINT,"","Cardholder Certificate Serial Number",""},
{B1_BIT_F126_MER_CERT_SERIAL_NO, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,17,PP_PRINT,"","Merchant Certificate Serial Number",""},
{B1_BIT_F126_TRN_ID_XID, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,20,PP_PRINT,"","Transaction ID (XID)",""},
{B1_BIT_F126_CAVV_DATA, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_FIX,LU_BYTE,20,PP_PRINT,"","CAVV Data",""},
{B1_BIT_F126_CVV2_AUTH_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_HIDE,"","CVV2 Authorization Request",""},
{B1_BIT_F126_Reserved5, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_L,LU_BYTE,255,PP_PRINT,"","Reserved5",""},
{B1_BIT_F126_SERVICE_IND, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","Service Indicators",""},
{B1_BIT_F126_POS_ENV, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,1,LU_BYTE,PP_PRINT,"","POS Environment",""},
{B1_BIT_F126_Reserved6, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_L,LU_BYTE,255,PP_PRINT,"","Reserved6",""},
{B1_BIT_F126_MCI_UCAF_COLL_IND, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","MasterCard UCAF Collection Indicator",""},
{B1_BIT_F126_MCI_UCAF_FIELD, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,33,PP_PRINT,"","MasterCard UCAF Field",""},
{B1_BIT_F126_Reserved7, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_L,LU_BYTE,255,PP_PRINT,"","Reserved7",""},
{B1_BIT_F126_AGENT_UNIQE_ACC_RES, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","Agent Unique Account Result",""},
{B1_BIT_F126_DCC_IND, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","Dynamic Currency Conversion Indicator",""},
},
"B1_F126_PROP"
};

/*End IZL 05052022 PLUTONL-4675*/


int RegisterVisaSubFieldsProp()
{
	RegisterBerInfoProp(&VisaF055Prop);	
	RegisterTlvInfoProp(&VisaElectComDataProp);
	RegisterTlvInfoProp(&VisaF34T02DataProp);
	RegisterTlvInfoProp(&VisaF34T4ADataProp);
	RegisterTlvInfoProp(&VisaF34T01DataProp);
	RegisterTlvInfoProp(&VisaF34T56DataProp);
	RegisterTlvInfoProp(&VisaTransSpecDataProp);
	RegisterTlvInfoProp(&VisaF104T56DataProp);
	RegisterTlvInfoProp(&VisaF104T57DataProp);
	RegisterTlvInfoProp(&VisaF104T5FDataProp);
	RegisterTlvInfoProp(&Base1VerifDataProp);
	RegisterTlvInfoProp(&Base1AddrVerifDataProp);
	RegisterTlvInfoProp(&Base1TokenDataProp);
	RegisterTlvInfoProp(&VisaSupportInfDataProp);
	RegisterTlvInfoProp(&VisaF125T03DataProp);
	RegisterBitmappedInfoProp(&VisaF126DataProp);   /*IZL 05052022 PLUTONL-4675*/
	return OK;
}



