#include <stdio.h>
#include <stdlib.h>

#include <define.h>
#include <p7_common.h>
#include <p7_globals.h>
#include <iso8583.h>
#include <cup_define.h>
#include <cup_fields.h>


static MsgInfoProperties	IsoCUPMsgProperties = {
	FF_ALPHA_N,		/* eMsgTypeType */
	4,				/* nMsgTypeLen */
	AF_ASCII,		/* eMsgTypeAlphaFormat */
	"CUP",			/* szProtocolName	*/
	"CUP",			/* szProtocolPrefix */
	{
		128,		/* nNbFields */
		2,			/* nNbBitmaps */
		2,			/* nNbConsBitmaps */
		8,			/* nBitmapLen */
		FF_BIN,		/* eBitmapFmt */
		{
{CUP_BIT_MAP2, 						FT_UNDEF,		FF_BIN,				AF_ASCII,  FL_FIX,  LU_BYTE,  0		,PP_HIDE,   "",   "BIT_MAP2",""},
{CUP_CARD_NBR, 						FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_LL,   LU_BYTE,  19	,PP_PRINT,  "",   "CARD_NBR",""},
{CUP_PROC_CODE, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  6		,PP_PRINT,  "",   "PROC_CODE",""},
{CUP_TRANS_AMOUNT, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  12	,PP_PRINT,  "",   "TRANS_AMOUNT",""},
{CUP_STLMNT_AMOUNT, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  12	,PP_PRINT,  "",   "STLMNT_AMOUNT",""},
{CUP_BILLING_AMOUNT, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  12  	,PP_PRINT,  "",   "BILLING_AMOUNT",""},
{CUP_XMIT_TIME, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "XMIT_TIME",""},
{STD_ISO_BILLING_AMOUNT_FEES, 		FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  8  	,PP_PRINT,  "",   "BILLING_AMOUNT_FEES",""},
{CUP_CNVRSN_RATE, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  8  	,PP_PRINT,  "",   "STLMNT_CNVRSN_RATE",""},
{CUP_BILLING_CNVRSN_RATE, 			FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  8  	,PP_PRINT,  "",   "BILLING_CNVRSN_RATE",""},

{CUP_AUDIT_NBR, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  6  	,PP_PRINT,  "",   "AUDIT_NBR",""},
{CUP_TRANS_TIME, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  6  	,PP_PRINT,  "",   "TRANS_TIME",""},
{CUP_TRANS_DATE, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  4  	,PP_PRINT,  "",   "TRANS_DATE",""},
{CUP_EXPIRY_DATE, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  4  	,PP_PRINT,  "",   "EXPIRY_DATE",""},
{CUP_STLMNT_DATE, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  4  	,PP_PRINT,  "",   "STLMNT_DATE",""},
{CUP_CNVRSN_DATE, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  4  	,PP_PRINT,  "",   "CNVRSN_DATE",""},
{STD_ISO_CAPTURE_DATE, 				FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  4  	,PP_PRINT,  "",   "CAPTURE_DATE",""},
{CUP_MERCHANT_TYPE, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  4  	,PP_PRINT,  "",   "MERCHANT_TYPE",""},
{CUP_ACQR_COUNTRY, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "ACQR_COUNTRY",""},
{STD_ISO_PAN_COUNTRY, 				FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "PAN_COUNTRY",""},

{STD_ISO_FORWD_COUNTRY, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "FORWD_COUNTRY",""},
{CUP_POS_ENTRY_MODE, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "POS_ENTRY_MODE",""},
{CUP_CARD_SEQUENCE_NBR, 			FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "CARD_SEQUENCE_NBR",""},
{STD_ISO_FUNCTION_CODE, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "NETWORK_INT_ID",""},
{CUP_POS_CONDITION, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  2  	,PP_PRINT,  "",   "POS_CONDITION",""},
{CUP_POS_PIN_CAPTURE, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  2  	,PP_PRINT,  "",   "POS_PIN_CAPTURE_CODE",""},
{STD_ISO_AUTHOR_ID_LENGTH, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  1  	,PP_PRINT,  "",   "AUTHOR_ID_LENGTH",""},
{CUP_TRANS_FEE, 					FT_SINGLE,		FF_X_ALPHA_N,		AF_ASCII,  FL_FIX,  LU_BYTE,  9  	,PP_PRINT,  "",   "TRANS_AMOUNT_FEE",""},
{STD_ISO_RECONC_INDICATOR, 			FT_UNDEF,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  9  	,PP_PRINT,  "",   "STLMNT_AMOUNT_FEE",""},
{STD_ISO_ORIGINAL_AMOUNTS, 			FT_UNDEF,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  9  	,PP_PRINT,  "",   "TRANS_PROC_FEE",""},

{STD_ISO_ACQR_REFERENCE_DATA, 		FT_UNDEF,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  9  	,PP_PRINT,  "",   "STLMNT_PROC_FEE",""},
{CUP_ACQR_ID, 						FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_LL,   LU_BYTE,  11  	,PP_PRINT,  "",   "ACQR_ID",""},
{CUP_FORWD_ID, 						FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_LL,   LU_BYTE,  11  	,PP_PRINT,  "",   "FORWD_ID",""},
{STD_ISO_PAN_EXTENDED, 				FT_UNDEF,		FF_ALPHA_ANS,		AF_ASCII,  FL_FIX,  LU_BYTE,  28  	,PP_PRINT,  "",   "PAN_EXTENDED",""},
{CUP_T2_DATA, 						FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LL,   LU_BYTE,  37	,PP_HIDE,   "",   "T2_DATA",""},
{CUP_T3_DATA, 						FT_SINGLE,		FF_Z,				AF_ASCII,  FL_LLL,  LU_BYTE,  104	,PP_HIDE,   "",   "T3_DATA",""},
{CUP_REFERENCE_NBR, 				FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  12  	,PP_PRINT,  "",   "REFERENCE_NBR",""},
{CUP_AUTHOR_ID, 					FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  6  	,PP_PRINT,  "",   "AUTHOR_ID",""},
{CUP_RESPONSE_CODE, 				FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  2  	,PP_PRINT,  "",   "RESPONSE_CODE",""},
{STD_ISO_SERVICE_CODE, 				FT_UNDEF,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "SERVICE_CODE",""},

{CUP_TERMINAL_NBR, 					FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_FIX,  LU_BYTE,  8  	,PP_PRINT,  "",   "TERMINAL_NBR",""},
{CUP_OUTLET_NBR, 					FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_FIX,  LU_BYTE,  15  	,PP_PRINT,  "",   "OUTLET_NBR",""},
{CUP_TERMINAL_ADR, 					FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_FIX,  LU_BYTE,  40  	,PP_PRINT,  "",   "TERMINAL_ADR",""},
{CUP_ADTNL_RESP_DATA, 				FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LL,   LU_BYTE,  25  	,PP_PRINT,  "",   "ADTNL_RESP_DATA",""},
{CUP_T1_DATA, 						FT_SINGLE,		FF_Z,				AF_ASCII,  FL_LL,   LU_BYTE,  79  	,PP_PRINT,  "",   "T1_DATA",""},
{STD_ISO_FEES_AMOUNT, 				FT_UNDEF,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  255  ,PP_PRINT,  "",   "ADTNL_DATA_ISO",""},
{STD_ISO_ADTNL_DATA_NATL, 			FT_UNDEF,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  255  ,PP_PRINT,  "",   "ADTNL_DATA_NATL",""},
{CUP_ADTNL_DATA_PRIV, 				FT_SINGLE,		FF_BIN,				AF_ASCII,  FL_LLL,  LU_BYTE,  512	,PP_HIDE,   "",   "ADTNL_DATA_PRIV",""},
{CUP_TRANS_CRNCY, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "TRANS_CRNCY",""},
{CUP_STLMNT_CRNCY, 					FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "STLMNT_CRNCY",""},

{CUP_BILLING_CRNCY, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "BILLING_CRNCY",""},
{CUP_PIN_DATA, 						FT_SINGLE,		FF_BIN,				AF_ASCII,  FL_FIX,  LU_BYTE,  16	,PP_HIDE,   "",   "PIN_DATA",""},
{CUP_SECURITY_DATA, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  16	,PP_PRINT/*PP_HIDE*/,   "",   "SECURITY_DATA",""},
{CUP_ADTNL_AMOUNTS, 				FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_LLL,  LU_BYTE,  40   ,PP_PRINT,  "",   "ADTNL_AMOUNTS",""},
{CUP_ICC_DATA, 						FT_STRUCT_BER,	FF_BIN,				AF_ASCII,  FL_LLL,  LU_BYTE,  255	,PP_HIDE,   "",   "ICC_DATA","CUP_F055_PROP"},
{STD_ISO_ORIG_DATA,			 		FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_LLL,  LU_BYTE,  512  ,PP_PRINT,  "",   "PAYMENT_ACCOUNT_DATA",""},
{STD_ISO_AUTHORIZATION_CYCLE_CODE, 	FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  100  ,PP_PRINT,  "",   "RES_NATL1",""},
{STD_ISO_AUTHOR_INSTITN_ID_CODE, 	FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  100  ,PP_PRINT,  "",   "RES_NATL2",""},
{STD_ISO_GEOGR_DATA, 			 	FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  600  ,PP_PRINT,  "",   "RES_NATL3",""},
{CUP_ADTNL_POS_INFO, 				FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  100  ,PP_PRINT,  "",   "ADV_REASON_CODE",""},


{CUP_AUTHEN_INFORMATION, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  200  ,PP_PRINT,  "",   "ADTNL_POS_INFO",""},
{STD_ISO_CPS_FIELDS, 				FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  200  ,PP_PRINT,  "",   "CPS_FIELDS",""},
{STD_ISO_NETWORK_DATA, 				FT_SINGLE,		FF_BIN,				AF_ASCII,  FL_LLL,  LU_BYTE,  512 	,PP_PRINT,  "",   "BANKNET_DATA",""},
{STD_ISO_MAC1, 						FT_SINGLE,		FF_BIN,				AF_ASCII,  FL_FIX,  LU_BYTE,  16  	,PP_PRINT,  "",   "MAC1",""},
{STD_ISO_BIT_MAP_2, 				FT_SINGLE,		FF_BIN,				AF_ASCII,  FL_FIX,  LU_BYTE,  8  	,PP_PRINT,  "",   "BIT_MAP_2",""},
{STD_ISO_STLMNT_CODE, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  1  	,PP_PRINT,  "",   "STLMNT_CODE",""},
{STD_ISO_EXT_PAYMENT_CODE, 			FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  1  	,PP_PRINT,  "",   "EXTD_PYMT_CODE",""},
{STD_ISO_RECEIVER_COUNTRY, 			FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "RCV_INST_COUNTRY",""},
{STD_ISO_STLMNT_INST_COUNTRY, 		FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "STLMNT_INST_COUNTRY",""},
{CUP_NW_MNGMT_INFO, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  3  	,PP_PRINT,  "",   "NW_MNGMT_INFO",""},

{STD_ISO_MESSAGE_NBR, 				FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  4  	,PP_PRINT,  "",   "MSG_NBR",""},
{STD_ISO_MESSAGE_NBR_LAST, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  4  	,PP_PRINT,  "",   "MSG_LAST_NBR",""},
{STD_ISO_ACTION_DATE, 				FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  6  	,PP_PRINT,  "",   "ACTION_DATE",""},
{STD_ISO_CR_NBR, 					FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "CR_NBR",""},
{STD_ISO_CR_REV_NBR, 				FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "CR_REV_NBR",""},
{STD_ISO_DB_NBR, 					FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "DB_NBR",""},
{STD_ISO_DB_REV_NBR, 				FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "DB_REV_NBR",""},
{STD_ISO_TRANSFER_NBR, 				FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "TR_NBR",""},
{STD_ISO_TRANSFER_REV_NBR, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "TR_REV_NBR",""},
{STD_ISO_INQ_NBR, 					FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "INQ_NBR",""},


{STD_ISO_AUT_NBR, 					FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  10  	,PP_PRINT,  "",   "AUT_NBR",""},
{STD_ISO_CR_PROC_FEE_AMNT, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  12  	,PP_PRINT,  "",   "CR_PROC_FEE_AMOUNT",""},
{STD_ISO_CR_TANS_FEE_AMNT, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  12  	,PP_PRINT,  "",   "CR_TRANS_FEE_AMOUNT",""},
{STD_ISO_DB_PROC_FEE_AMNT, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  12  	,PP_PRINT,  "",   "DB_PROC_FEE_AMOUNT",""},
{STD_ISO_DB_TRANS_FEE_AMNT, 		FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  12  	,PP_PRINT,  "",   "DB_TRANS_FEE_AMOUNT",""},
{STD_ISO_CR_AMOUNT, 				FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  16  	,PP_PRINT,  "",   "CR_AMOUNT",""},
{STD_ISO_CR_REV_AMOUNT, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  16  	,PP_PRINT,  "",   "CR_REV_AMOUNT",""},
{STD_ISO_DB_AMOUNT, 				FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  16  	,PP_PRINT,  "",   "DB_AMOUNT",""},
{STD_ISO_DB_REV_AMOUNT, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  16  	,PP_PRINT,  "",   "DB_REV_AMOUNT",""},
{CUP_ORIG_DATA, 					FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  42  	,PP_PRINT,  "",   "ORIG_DATA",""},


{STD_ISO_FILE_UPDATE, 				FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  1  	,PP_PRINT,  "",   "FILE_UPDATE",""},
{STD_ISO_FILE_SECURITY, 			FT_UNDEF,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  2  	,PP_PRINT,  "",   "FILE_SECURITY",""},
{STD_ISO_RESP_INDICATOR, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  5  	,PP_PRINT,  "",   "RESP_INDICATOR",""},
{STD_ISO_SERVICE_IND, 				FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_FIX,  LU_BYTE,  7  	,PP_PRINT,  "",   "SERV_INDICATOR",""},
{STD_ISO_REPLACE_AMOUNTS, 			FT_SINGLE,		FF_ALPHA_N,			AF_ASCII,  FL_FIX,  LU_BYTE,  42  	,PP_PRINT,  "",   "REPLACE_AMOUNTS",""},
{CUP_MSG_SECURITY, 					FT_SINGLE,		FF_BIN,				AF_ASCII,  FL_FIX,  LU_BYTE,  16  	,PP_PRINT,  "",   "MSG_SECURITY",""},
{STD_ISO_NET_AMOUNT, 				FT_UNDEF,		FF_ALPHA_AN,		AF_ASCII,  FL_FIX,  LU_BYTE,  17  	,PP_PRINT,  "",   "NET_AMOUNT",""},
{STD_ISO_PAYEE, 					FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_FIX,  LU_BYTE,  25  	,PP_PRINT,  "",   "PAYEE",""},
{STD_ISO_STLMNT_INSTITN, 			FT_UNDEF,		FF_ALPHA_N,			AF_ASCII,  FL_LLL,  LU_BYTE,  11  	,PP_PRINT,  "",   "STLMNT_INSTITN",""},
{CUP_RECEIVER_ID, 					FT_SINGLE,		FF_ALPHA_AN,		AF_ASCII,  FL_LL,   LU_BYTE,  11  	,PP_PRINT,  "",   "RECEIVER_ID",""},

{STD_ISO_FILE_NAME, 				FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  17   ,PP_PRINT,  "",   "FILE_NAME",""},
{CUP_ACCOUNT_ID1, 					FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LL,   LU_BYTE,  28  	,PP_PRINT,  "",   "ACCOUNT_ID1",""},
{STD_ISO_ACCOUNT_ID2, 				FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  28   ,PP_PRINT,  "",   "ACCOUNT_ID2",""},
{STD_ISO_TRANS_DESC, 				FT_STRUCT_TLV,	FF_BIN,				AF_ASCII,  FL_LLL,  LU_BYTE,  512  ,PP_PRINT,  "",   "DIGITAL_PAYMENT_DATA",""},
{STD_ISO_RESERVED_ISO_1, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "RES_MC_USE_1",""},
{STD_ISO_RESERVED_ISO_2, 			FT_UNDEF,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "RES_MC_USE_2",""},
{STD_ISO_RESERVED_ISO_3, 			FT_UNDEF,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "RES_MC_USE_3",""},
{STD_ISO_RESERVED_ISO_4, 			FT_STRUCT_TLV,	FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "MONEYSEND_REF_DATA",""},
{STD_ISO_RESERVED_ISO_5, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "RES_ISO_USE_1",""},
{STD_ISO_RESERVED_ISO_6, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "ADDNTL_DATA_2",""},


{STD_ISO_RESERVED_ISO_7, 			FT_UNDEF,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "RES_ISO_USE_2",""},
{STD_ISO_RESERVED_NAT_3, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  100  ,PP_PRINT,  "",   "ADDNTL_DATA_NAT_USE",""},
{STD_ISO_RESERVED_NAT_4, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  512  ,PP_PRINT,  "",   "RES_NAT_USE_4",""},
{STD_ISO_RESERVED_NAT_5, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "RES_NAT_USE_5",""},
{STD_ISO_ADTNL_TRACE_DATA, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  24   ,PP_PRINT,  "",   "RES_NAT_USE_6",""},
{STD_ISO_CARD_ISSUER_REF_DATA, 		FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  256  ,PP_PRINT,  "",   "RES_NAT_USE_7",""},
{STD_ISO_NATIONAL_USE, 				FT_SINGLE,		FF_BIN,				AF_ASCII,  FL_LLL,  LU_BYTE,  256  ,PP_PRINT,  "",   "RES_NAT_USE_8",""},
{STD_ISO_INTRA_COUNTRY_DATA, 		FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "RES_NAT_USE_9",""},
{STD_ISO_RES_NAT_USE_10, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  999  ,PP_PRINT,  "",   "RES_NAT_USE_10",""},
{STD_ISO_ORIG_MSG_TYPE, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  4    ,PP_PRINT,  "",   "RECORD_DATA",""},

{CUP_SYSTEM_RESERVED, 				FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  100  ,PP_PRINT,  "",   "AUTHOR_AGENT",""},
{CUP_ACQ_INST_RESERVED, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  100  ,PP_PRINT,  "",   "ADTNL_RECORD_DATA",""},
{CUP_ISS_INST_RESERVED, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  100  ,PP_PRINT,  "",   "ADR_VERIF_DATA",""},
{STD_ISO_MEMBER_DEF_DATA, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  100  ,PP_PRINT,  "",   "MEMBER_DEF_DATA",""},
{CUP_SUPPORT_INFO, 					FT_SINGLE,		FF_BIN,				AF_ASCII,  FL_LLL,	 LU_BYTE,  256  ,PP_PRINT,  "",   "NEW_PIN_INFO",""},
{STD_ISO_RESERVED_PRIV_USAGE_4, 	FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  256  ,PP_PRINT,  "",   "PRIV_DATA_1",""},
{STD_ISO_FILE_SEC_CODE, 			FT_SINGLE,		FF_ALPHA_ANS,		AF_ASCII,  FL_LLL,  LU_BYTE,  256  ,PP_PRINT,  "",   "PRIV_DATA_2",""},
{CUP_MAC2, 							FT_UNDEF,		FF_BIN,				AF_ASCII,  FL_FIX,  LU_BYTE,  16  	,PP_PRINT,  "",   "MAC2",""},
},
		"CupMsgBMInfoProperties",
	},
	"IsoCUPMsgProperties", 		/* szPropertiesName*/
	ISO8583_CUP,				/* nProtocolId */
	E_FIXED_LENGTH,				/* eHeaderType */
	FF_HEX,						/* eHeaderFormat */
	46,							/* nHeaderLen */
};


static const BerInfoProperties	CupF055Prop = {
CUP_F55_NB_FIELDS,
{
{CUP_F55_DED_FILE_NAME, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,18,PP_PRINT,"","DED_FILE_NAME","",NOT_REPEATABLE},
{CUP_F55_TERM_APP_VER_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,5,PP_PRINT,"","TERM_APP_VER_NUM","",NOT_REPEATABLE},
{CUP_F55_IFD_SERIAL_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","IFD_SERIAL_NUM","",NOT_REPEATABLE},
{CUP_F55_CRYPTO_INFO_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","CRYPTO_INFO_DATA","",NOT_REPEATABLE},
{CUP_F55_CVM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,6,PP_PRINT,"","CVM","",NOT_REPEATABLE},
{CUP_F55_TERM_TYPE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","TERM_TYPE","",NOT_REPEATABLE},
{CUP_F55_TRANS_SEQ_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,7,PP_PRINT,"","TRANS_SEQ_NUM","",NOT_REPEATABLE},
{CUP_F55_TRANS_CATEG_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","TRANS_CATEG_CODE","",NOT_REPEATABLE},
{CUP_F55_ISS_SCRIPT1, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,256,PP_HIDE,"","ISS_SCRIPT1","",NOT_REPEATABLE},
{CUP_F55_ISS_SCRIPT2, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,256,PP_HIDE,"","ISS_SCRIPT2","",NOT_REPEATABLE},
{CUP_F55_APP_INTER_PROFILE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,2,PP_PRINT,"","APP_INTER_PROFILE","",NOT_REPEATABLE},
{CUP_F55_ISS_AUTHEN_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,10,PP_PRINT,"","ISS_AUTHEN_DATA","",NOT_REPEATABLE},
{CUP_F55_TVR, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,5,PP_PRINT,"","TVR","",NOT_REPEATABLE},
{CUP_F55_TRANS_DATE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,3,PP_PRINT,"","TRANS_DATE","",NOT_REPEATABLE},
{CUP_F55_TRANS_TYPE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,1,PP_PRINT,"","TRANS_TYPE","",NOT_REPEATABLE},
{CUP_F55_TRANS_CUR_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,2,PP_PRINT,"","TRANS_CUR_CODE","",NOT_REPEATABLE},
{CUP_F55_TRANS_AMOUNT, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,6,PP_PRINT,"","TRANS_AMOUNT","",NOT_REPEATABLE},
{CUP_F55_OTHER_AMOUNT, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,6,PP_PRINT,"","OTHER_AMOUNT","",NOT_REPEATABLE},
{CUP_F55_ISS_APP_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,33,PP_PRINT,"","ISS_APP_DATA","",NOT_REPEATABLE},
{CUP_F55_TERM_COUNTRY_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,2,PP_PRINT,"","TERM_COUNTRY_CODE","",NOT_REPEATABLE},
{CUP_F55_APP_CRYPTOGRAM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,8,PP_HIDE,"","APP_CRYPTOGRAM","",NOT_REPEATABLE},
{CUP_F55_TERM_CAP, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,3,PP_PRINT,"","TERM_CAP","",NOT_REPEATABLE},
{CUP_F55_ATC, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,2,PP_HIDE,"","ATC","",NOT_REPEATABLE},
{CUP_F55_UNPRED_NUMBER, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","UNPRED_NUMBER","",NOT_REPEATABLE},

},
"CUP_F055_PROP"
};



int RegisterCupSubFieldsProp()
{
	RegisterBerInfoProp(&CupF055Prop);
	return OK;
}

int InitCupProtocol()
{
	RegisterMsgInfoProp(&IsoCUPMsgProperties);
	return OK;
}





