#include <stdio.h>
#include <iso8583.h>
#include <sid_fields.h>
#include <sid_define.h>



static MsgInfoProperties	Sid3MsgInfoProperties = {
	FF_ALPHA_N,			/* eMsgTypeType */
	4,				/* nMsgTypeLen */
	AF_ASCII,		/* eMsgTypeAlphaFormat */
	"SID3",		/* szProtocolName	*/ 
	"SID3",			/* szProtocolPrefix */
	{
		128,		/* nNbFields */
		2,			/* nNbBitmaps */
		2,			/* nNbConsBitmaps */
		8,			/* nBitmapLen */
		FF_BIN,		/* eBitmapFmt */
		{
{SID_BIT_MAP2, FT_UNDEF,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,0,PP_HIDE,"","BIT_MAP2",""},
{SID_CARD_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,19,PP_HIDE,"","CARD_NBR",""},
{SID_PROC_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","PROC_CODE",""},
{SID_TRANS_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","TRANS_AMOUNT",""},
{SID_STLMNT_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","STLMNT_AMOUNT",""},
{SID_BILLING_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","BILLING_AMOUNT",""},
{SID_XMIT_TIME, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","XMIT_TIME",""},
{SID_BILLING_AMOUNT_FEES, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_AMOUNT_FEES",""},
{SID_STLMNT_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","STLMNT_CNVRSN_RATE",""},
{SID_BILLING_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_CNVRSN_RATE",""},
{SID_AUDIT_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUDIT_NBR",""},
{SID_TRANS_DATE_TIME, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","TRANS_DATE_TIME",""},
{SID_START_EXPIRY_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","START_EXPIRY_DATE",""},
{SID_EXPIRY_DATE,FT_SINGLE /*FT_UNDEF*/,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","EXPIRY_DATE",""},
{SID_STLMNT_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","STLMNT_DATE",""},
{SID_CNVRSN_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","CNVRSN_DATE",""},
{SID_CAPTURE_DATE, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","CAPTURE_DATE",""},
{SID_MERCHANT_TYPE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","MERCHANT_TYPE",""},
{SID_ACQR_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","ACQR_COUNTRY",""},
{SID_PAN_COUNTRY, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","PAN_COUNTRY",""},
{SID_FORWD_COUNTRY, FT_SINGLE/*FT_UNDEF*/,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","FORWD_COUNTRY",""},
{SID_POS_DATA, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","POS_DATA",""},
{SID_CARD_SEQUENCE_NBR,FT_SINGLE /*FT_UNDEF*/,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","CARD_SEQUENCE_NBR",""},
{SID_FUNCTION_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","FUNCTION_CODE",""},
{SID_MSG_REASON, FT_SINGLE/*FT_UNDEF*/,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","MSG_REASON",""},
{SID_ACCEPTOR_ACTIV_CODE, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","ACCEPTOR_ACTIV_CODE",""},
{SID_AUTHOR_ID_LENGTH, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","AUTHOR_ID_LENGTH",""},
{SID_RECONC_DATE, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","RECONC_DATE",""},
{SID_RECONC_INDICATOR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","RECONC_INDICATOR",""},
{SID_ORIGINAL_AMOUNTS, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,24,PP_PRINT,"","ORIGINAL_AMOUNTS",""},
{SID_ACQR_REFERENCE_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,9,PP_PRINT,"","ACQR_REFERENCE_DATA",""},
{SID_ACQR_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","ACQR_ID",""},
{SID_FORWD_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","FORWD_ID",""},
{SID_PAN_EXTENDED, FT_UNDEF,FF_ALPHA_NS,AF_ASCII,FL_LL,LU_BYTE,28,PP_PRINT,"","PAN_EXTENDED",""},
{SID_T2_DATA, FT_SINGLE,FF_Z,AF_ASCII,FL_LL,LU_BYTE,37,PP_HIDE,"","T2_DATA",""},
{SID_T3_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,104,PP_PRINT,"","T3_DATA",""},
{SID_REFERENCE_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","REFERENCE_NBR",""},
{SID_AUTHOR_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUTHOR_ID",""},
{SID_RESPONSE_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESPONSE_CODE",""},
{SID_SERVICE_CODE, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","SERVICE_CODE",""},
{SID_TERMINAL_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","TERMINAL_NBR",""},
{SID_OUTLET_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,15,PP_PRINT,"","OUTLET_NBR",""},
{SID_TERMINAL_ADR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,40,PP_PRINT,"","TERMINAL_ADR",""},
{SID_ADTNL_RESP_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_RESP_DATA",""},
{SID_T1_DATA, FT_SINGLE,FF_Z,AF_ASCII,FL_LL,LU_BYTE,76,PP_HIDE,"","T1_DATA",""},
{SID_FEES_AMOUNT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,204,PP_PRINT,"","FEES_AMOUNT",""},
{SID_ADTNL_DATA_NATL, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_NATL",""},
{SID_ADTNL_DATA_PRIV, FT_STRUCT_TLV/*FT_SINGLE*/,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_HIDE,"","ADTNL_DATA_PRIV","SID_F048_PROP"},
{SID_TRANS_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRANS_CRNCY",""},
{SID_STLMNT_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_CRNCY",""},
{SID_BILLING_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","BILLING_CRNCY",""},
{SID_PIN_DATA, FT_SINGLE,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,16,PP_HIDE,"","PIN_DATA",""},
{SID_SECURITY_DATA, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,99,PP_PRINT/*PP_HIDE*/,"","SECURITY_DATA",""},
{SID_ADTNL_AMOUNTS, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,120,PP_PRINT,"","ADTNL_AMOUNTS",""},
{SID_ICC_DATA, FT_STRUCT_BER/*FT_SINGLE*/,FF_BIN,AF_ASCII,FL_LLL,LU_BYTE,255,PP_HIDE,"","ICC_DATA","SID_F055_PROP"},
{SID_ORIG_DATA, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,35,PP_PRINT,"","ORIG_DATA",""},
{SID_AUTHORIZATION_CYCLE_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","AUTHORIZATION_CYCLE_CODE",""},
{SID_AUTHOR_INSTITN_ID_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,255,PP_PRINT,"","AUTHOR_INSTITN_ID_CODE",""},
{SID_GEOGR_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,14,PP_PRINT,"","GEOGR_DATA",""},
{SID_ADTNL_POS_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_POS_INFO",""},
{SID_NET_POS_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","NET_POS_DATA",""},
{SID_CPS_FIELDS, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","CPS_FIELDS","B1_F062_PROPS"},
{SID_NETWORK_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","NETWORK_DATA",""},
{SID_MAC1, FT_UNDEF,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC1",""},
{SID_RESERVED_ISO, FT_UNDEF,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,0,PP_PRINT,"","RESERVED_ISO",""},
{SID_STLMNT_CODE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"","STLMNT_CODE",""},
{SID_EXT_PAY_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","EXT_PAY_DATA",""},
{SID_RECEIVER_COUNTRY, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","RECEIVER_COUNTRY",""},
{SID_STLMNT_INST_COUNTRY, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_INST_COUNTRY",""},
{SID_NW_MNGMT_INFO, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","NW_MNGMT_INFO",""},
{SID_MESSAGE_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","MESSAGE_NBR",""},
{SID_RECORD_DATA, FT_SINGLE/*FT_UNDEF*/,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","RECORD_DATA",""},
{SID_ACTION_DATE, FT_SINGLE/*FT_UNDEF*/,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","ACTION_DATE",""},
{SID_CR_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","CR_NBR",""},
{SID_CR_REV_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","CR_REV_NBR",""},
{SID_DB_NBR, FT_SINGLE/*FT_UNDEF*/,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","DB_NBR",""},
{SID_DB_REV_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","DB_REV_NBR",""},
{SID_TRANSFER_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","TRANSFER_NBR",""},
{SID_TRANSFER_REV_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","TRANSFER_REV_NBR",""},
{SID_INQ_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","INQ_NBR",""},
{SID_AUT_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","AUT_NBR",""},
{SID_INF_REV_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","INQ_REV_NBR",""},
{SID_PAYMENT_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","PAYMENT_NBR",""},
{SID_PAYMENT_REV_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","PAYMENT_REV_NBR",""},
{SID_FEES_COLLCT_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","FEES_COLLCT_NBR",""},
{SID_CR_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_AMOUNT",""},
{SID_CR_REV_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REV_AMOUNT",""},
{SID_DB_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_AMOUNT",""},
{SID_DB_REV_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REV_AMOUNT",""},
{SID_ADJUST_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,35,PP_PRINT,"","ADJUST_NBR",""},
{SID_TRX_RECEIVER_COUNTRY_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRX_RECEIVER_COUNTRY_CODE",""},
{SID_TRX_ORIGINATOR_COUNTRY_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRX_ORIGINATOR_COUNTRY_CODE",""},
{SID_TRX_RECEIVER_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","TRX_RECEIVER_ID",""},
{SID_TRX_ORIGINATOR_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","TRX_ORIGINATOR_ID",""},
{SID_CARD_ISSUER_REF_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,42,PP_PRINT,"","CARD_ISSUER_REF_DATA",""},
{SID_KEY_MNG_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,17,PP_PRINT,"","KEY_MNG_DATA",""},
{SID_NET_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,17,PP_PRINT,"","NET_AMOUNT",""},
{SID_PAYEE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,25,PP_PRINT,"","PAYEE",""},
{SID_STLMNT_INSTITN, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","STLMNT_INSTITN",""},
{SID_RECEIVER_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","RECEIVER_ID",""},
{SID_FILE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,17,PP_PRINT,"","FILE_NAME",""},
{SID_ACCOUNT_ID1, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID1",""},
{SID_ACCOUNT_ID2, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID2",""},
{SID_TRANS_DESC, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"","TRANS_DESC",""},
{SID_CR_REJ_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REJ_AMOUNT",""},
{SID_DB_REJ_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REJ_AMOUNT",""},
{SID_CR_REJ_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REJ_NUMBER",""},
{SID_DB_REJ_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REJ_NUMBER",""},
{SID_CR_FEES_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,0,PP_PRINT,"","CR_FEES_AMOUNT",""},
{SID_DB_FEES_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,0,PP_PRINT,"","DB_FEES_AMOUNT",""},
{SID_RESERVED_SID_2, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_SID_2",""},
{SID_RESERVED_SID_3, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_SID_3",""},
{SID_RESERVED_SID_4, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_SID_4",""},
{SID_RESERVED_SID_5, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_SID_5",""},
{SID_ADTNL_TRACE_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,24,PP_PRINT,"","ADTNL_TRACE_DATA",""},
{SID_TRANS_FEE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","TRANS_FEE",""},
{SID_STLMNT_FEE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","STLMNT_FEE",""},
{SID_PROCES_FEE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","PROCES_FEE",""},
{SID_ADTNL_TRACE_DATA    , FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","ADTNL_TRACE_DATA    ",""},
{SID_ORIG_MSG_TYPE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","ORIG_MSG_TYPE",""},
{SID_RESERV_NATIONAL_USAGE_6, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERV_NATIONAL_USAGE_6",""},
{SID_RESERV_PRIV_USAGE_1, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERV_PRIV_USAGE_1",""},
{SID_ADR_VERIF_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,29,PP_PRINT,"","ADR_VERIF_DATA",""},
{SID_RESERV_PRIV_USAGE_3, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERV_PRIV_USAGE_3",""},
{SID_SUPPORT_INFO, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"","SUPPORT_INFO",""},
{SID_RESERVED_PRIVE_USAGE_5, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"","RESERVED_PRIVE_USAGE_5",""},
{SID_FILE_SEC_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","FILE_SEC_CODE",""},
{SID_MAC2, FT_SINGLE,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC2",""},
		},
		"Sid3MsgBMInfoProperties",
	},
	"Sid3MsgInfoProperties", /* szPropertiesName*/
	ISO8583_SID,			/* nProtocolId */
	E_FIXED_LENGTH,				/* eHeaderType */
	FF_ALPHA_AN,					/* eHeaderFormat */
	11,							/* nHeaderLen */
};
/*PLUTONL-3131*/
static const TlvInfoProperties	SidF048Prop = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,SID_F48_NB_FIELDS,
{
  {SID_F48_FILE_UP_ERR_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","FILE_UP_ERR_CODE","",NOT_REPEATABLE},
  {SID_F48_MSG_TEXT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,256,PP_PRINT,"","MSG_TEXT","",NOT_REPEATABLE},
  {SID_F48_KEY_TAG, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,32,PP_HIDE,"","ZPK_TAK","",NOT_REPEATABLE},
  {SID_F48_ORIG_TRX_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,15,PP_PRINT,"","ORIG_TRX_ID","",NOT_REPEATABLE},
  {SID_F48_NEW_PIN_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,18,PP_HIDE,"","PVV_OFFSET","",NOT_REPEATABLE},
  {SID_F48_REF_NUM, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,18,PP_PRINT,"","REF_NUM","",NOT_REPEATABLE},
  {SID_F48_PAR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,29,PP_PRINT,"","PAYMENT_ACCOUNT_REFERENCE","",NOT_REPEATABLE},
  {SID_F48_VISA_MERCHANT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","VISA_MERCHANT","",NOT_REPEATABLE},
  {SID_F48_ICVV_RESULT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","ICVV_RESULT","",NOT_REPEATABLE},
  {SID_F48_MERC_ADDTL_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,63,PP_PRINT,"","MERC_ADDTL_DATA","",NOT_REPEATABLE},
  {SID_F48_ARQC_RESULT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","ARQC_RESULT","",NOT_REPEATABLE},
  {SID_F48_CHIP_ADDTL, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"","CHIP_ADDTL","",NOT_REPEATABLE},
  {SID_F48_MERCHANT_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,15,PP_PRINT,"","MERCHANT_ID","",NOT_REPEATABLE},
  {SID_F48_OBS, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,40,PP_PRINT,"","OBS","",NOT_REPEATABLE},
  {SID_F48_TRACE_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,15,PP_PRINT,"","TRACE_ID","",NOT_REPEATABLE},
  {SID_F48_MERCHANT_ACCNUM, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,38,PP_PRINT,"","MERCHANT_ACCNUM","",NOT_REPEATABLE},
  {SID_F48_MC_UCAF, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,28,PP_PRINT,"","UCAF","",NOT_REPEATABLE},
  {SID_F48_ROUTING_NW_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","ROUTING_NW_CODE","",NOT_REPEATABLE},
  {SID_F48_KSN_DESCRIPTION, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","KSN_DESCRIPTION","",NOT_REPEATABLE},
  {SID_F48_KSN, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,20,PP_PRINT,"","KSN","",NOT_REPEATABLE},
  {SID_F48_AAV, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,40,PP_PRINT,"","AAV","",NOT_REPEATABLE},
  {SID_F48_DIGITAL_PAYMT_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","DIGITAL_PAYMT_DATA","",NOT_REPEATABLE},
  {SID_F48_ECOM_CRPT_RESULT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","CRPT_RESULT","",NOT_REPEATABLE},
  {SID_F48_TOKEN_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,151,PP_PRINT,"","TOKEN_DATA","",NOT_REPEATABLE},
  {SID_F48_DCC_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,52,PP_PRINT,"","DCC_DATA","",NOT_REPEATABLE},
  {SID_F48_AFD_REF_NUM, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,32,PP_PRINT,"","AFD_REF_NUM","",NOT_REPEATABLE},
  {SID_F48_ACCPT_POINT_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","ACCPT_POINT_ID","",NOT_REPEATABLE},
  {SID_F48_SCORING_RESULT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","SCORING_RESULT","",NOT_REPEATABLE},
  {SID_F48_ADD_POS_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,21,PP_PRINT,"","ADD_POS_DATA","",NOT_REPEATABLE},
  {SID_F48_AUTH_ADTNL_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,9,PP_PRINT,"","AUTH_ADTNL_INFO","",NOT_REPEATABLE},
  {SID_F48_ECOM_AUTH_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,20,PP_PRINT,"","ECOM_AUTH_INFO","",NOT_REPEATABLE},
  {SID_F48_AUTHORISATION_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,32,PP_HIDE,"","AUTHORISATION_ID","",NOT_REPEATABLE},
  {SID_F48_TRANSACTION_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,32,PP_HIDE,"","TRANSACTION_ID","",NOT_REPEATABLE},
  {SID_F48_TERMINAL_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,45,PP_PRINT,"","TERMINAL_INFO","",NOT_REPEATABLE},
  {SID_F48_RECCURING_IND, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","RECCURING_IND","",NOT_REPEATABLE},
  {SID_F48_XID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,40,PP_PRINT,"","XID","",NOT_REPEATABLE},
  {SID_F48_DINERS_NW_REF_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,15,PP_PRINT,"","DINERS_NW_REF_ID","",NOT_REPEATABLE},
  {SID_F48_ADD_VERIF_REQUEST, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","ADD_VERIF_REQUEST","",NOT_REPEATABLE},
  {SID_F48_ADD_VERIF_RESPONSE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","ADD_VERIF_RESPONSE","",NOT_REPEATABLE},
  {SID_F48_CVV_RESULT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","CVV_RESULT","",NOT_REPEATABLE},
  {SID_F48_EXT_RESP_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","EXT_RESP_CODE","",NOT_REPEATABLE},
  {SID_F48_FRAUD_SCORE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","FRAUD_SCORE","",NOT_REPEATABLE},
  {SID_F48_AMEX_TRX_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,48,PP_PRINT,"","AMEX_TRX_ID","",NOT_REPEATABLE},
  {SID_F48_CVC2, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,4,PP_HIDE,"","CVC2","",NOT_REPEATABLE},
  {SID_F48_NETWORK_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","NETWORK_CODE","",NOT_REPEATABLE},
  {SID_F48_MONEY_TRANSFER_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","MONEY_TRANSFER_DATA","",NOT_REPEATABLE},
  {SID_F48_ADDRESS_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,60,PP_PRINT,"","ADDRESS_DATA","",NOT_REPEATABLE},
  {SID_F48_SALE_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,474,PP_PRINT,"","SALE_INFO","",NOT_REPEATABLE},
  {SID_F48_SALE_ITEMS_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,196,PP_PRINT,"","SALE_ITEMS_DATA","",NOT_REPEATABLE},
  {SID_F48_ECOM_AUTH_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","ECOM_AUTH_DATA","",NOT_REPEATABLE},
  {SID_F48_PSD2, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","PSD2","",NOT_REPEATABLE},
  {SID_F48_SMS_CHARGEBACK_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,58,PP_PRINT,"","SMS_CHARGEBACK_DATA","",NOT_REPEATABLE},
  {SID_F48_SERVER_TRANS_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,36,PP_PRINT,"","SERVER_TRANS_ID","",NOT_REPEATABLE},
  {SID_F48_ACS_TRANS_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,36,PP_PRINT,"","ACS_TRANS_ID","",NOT_REPEATABLE},
  {SID_F48_AUTH_EXMP_IND, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","AUTH_EXMP_IND","",NOT_REPEATABLE},
  {SID_F48_MOBILE_SOLUTION_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","MOBILE_SOLUTION_ID","",NOT_REPEATABLE},
  {SID_F48_NETWORK_MERCHANT_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","NETWORK_MERCHANT_ID","",NOT_REPEATABLE},
  {SID_F48_SECURITY_ADTNL_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","SECURITY_ADTNL_DATA","",NOT_REPEATABLE},


},
"SID_F048_PROP"
};

static const BerInfoProperties	SidF055Prop = {
SID_F55_NB_FIELDS,
{
{SID_F55_ISS_SCRIPT1, FT_SINGLE,FF_HEX,AF_ASCII,FL_LLL,LU_BYTE,128,PP_HIDE,"","ISS_SCRIPT1","",NOT_REPEATABLE},
{SID_F55_ISS_SCRIPT2, FT_SINGLE,FF_HEX,AF_ASCII,FL_LLL,LU_BYTE,128,PP_HIDE,"","ISS_SCRIPT2","",NOT_REPEATABLE},
{SID_F55_APP_INTER_PROFILE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","APP_INTER_PROFILE","",NOT_REPEATABLE},
{SID_F55_DED_FILE_NAME, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,16,PP_PRINT,"","DED_FILE_NAME","",NOT_REPEATABLE},
{SID_F55_ISS_SCRIPT_CMD, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,21,PP_PRINT,"","ISS_SCRIPT_CMD","",NOT_REPEATABLE},
{SID_F55_AUTH_RESP_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,2,PP_PRINT,"","AUTH_RESP_CODE","",NOT_REPEATABLE},
{SID_F55_ISS_AUTHEN_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,16,PP_PRINT,"","ISS_AUTHEN_DATA","",NOT_REPEATABLE},
{SID_F55_TVR, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,5,PP_PRINT,"","TVR","",NOT_REPEATABLE},
{SID_F55_TRANS_DATE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRANS_DATE","",NOT_REPEATABLE},
{SID_F55_TRANS_TYPE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","TRANS_TYPE","",NOT_REPEATABLE},
{SID_F55_TRANS_CUR_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","TRANS_CUR_CODE","",NOT_REPEATABLE},
{SID_F55_PAN_SEQ_NUMBER, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","PAN_SEQ_NUMBER","",NOT_REPEATABLE},
{SID_F55_TRANS_AMOUNT, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","TRANS_AMOUNT","",NOT_REPEATABLE},
{SID_F55_OTHER_AMOUNT, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","OTHER_AMOUNT","",NOT_REPEATABLE},
{SID_F55_APPLICATION, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","APPLICATION","",NOT_REPEATABLE},
{SID_F55_TERM_APP_VER_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","TERM_APP_VER_NUM","",NOT_REPEATABLE},
{SID_F55_TERM_APP_VER_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","TERM_APP_VER_NUM","",NOT_REPEATABLE},
{SID_F55_TAG_ISS_APP_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,32,PP_PRINT,"","ISS_APP_DATA","",NOT_REPEATABLE},
{SID_F55_TERM_COUNTRY_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","TERM_COUNTRY_CODE","",NOT_REPEATABLE},
{SID_F55_IFD_SERIAL_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","IFD_SERIAL_NUM","",NOT_REPEATABLE},
{SID_F55_FFI, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,32,PP_PRINT,"","FFI","",NOT_REPEATABLE},
{SID_F55_APP_CRYPTOGRAM, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,8,PP_HIDE,"","APP_CRYPTOGRAM","",NOT_REPEATABLE},
{SID_F55_CRYPTO_INFO_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","CRYPTO_INFO_DATA","",NOT_REPEATABLE},
{SID_F55_TERM_CAP, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TERM_CAP","",NOT_REPEATABLE},
{SID_F55_CVM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","CVM","",NOT_REPEATABLE},
{SID_F55_TERM_TYPE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","TERM_TYPE","",NOT_REPEATABLE},
{SID_F55_ATC, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,2,PP_HIDE,"","ATC","",NOT_REPEATABLE},
{SID_F55_UNPRED_NUMBER, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","UNPRED_NUMBER","",NOT_REPEATABLE},
{SID_F55_TRANS_SEQ_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","TRANS_SEQ_NUM","",NOT_REPEATABLE},
{SID_F55_TRANS_CATEG_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,5,PP_PRINT,"","TRANS_CATEG_CODE","",NOT_REPEATABLE},
{SID_F55_ISS_SCRIPT_RESULT, FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","ISS_SCRIPT_RESULT","",NOT_REPEATABLE},
},

"SID_F055_PROP"
};

int RegisterSidSubFieldsProp()
{
	
	RegisterBerInfoProp(&SidF055Prop);
	RegisterTlvInfoProp(&SidF048Prop);
	

	return OK;

}
int InitSid3Protocol()
{
	RegisterMsgInfoProp(&Sid3MsgInfoProperties);
	return OK;
}

/*End PROD00070301*/

