#include <stdio.h>
#include <stdlib.h>

#include <define.h>
#include <p7_common.h>
#include <p7_globals.h>
#include <iso8583.h>
#include <mds_fields.h>



static MsgInfoProperties	MdsMsgInfoProperties = {
	FF_ALPHA_N,			/* eMsgTypeType */
	4,				/* nMsgTypeLen */
	AF_EBCDIC,		/* eMsgTypeAlphaFormat */
	"MDS",		/* szProtocolName	*/
	"MDS",			/* szProtocolPrefix */
	{
		128,		/* nNbFields */
		2,			/* nNbBitmaps */
		2,			/* nNbConsBitmaps */
		8,			/* nBitmapLen */
		FF_BIN,		/* eBitmapFmt */
		{
{MDS_BIT_MAP2, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_HIDE,"","BIT_MAP2",""},
{MDS_CARD_NBR, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,19,PP_PRINT,"","CARD_NBR",""},
{MDS_PROC_CODE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","PROC_CODE",""},
{MDS_TRANS_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","TRANS_AMOUNT",""},
{MDS_STLMNT_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","STLMNT_AMOUNT",""},
{MDS_BILLING_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","BILLING_AMOUNT",""},
{MDS_XMIT_TIME, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","XMIT_TIME",""},
{MDS_BILLING_AMOUNT_FEES, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_AMOUNT_FEES",""},
{MDS_STLMNT_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","STLMNT_CNVRSN_RATE",""},
{MDS_BILLING_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_CNVRSN_RATE",""},
{MDS_AUDIT_NBR, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUDIT_NBR",""},
{MDS_TRANS_TIME           , FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","TRANS_TIME           ",""},
{MDS_TRANS_DATE           , FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","TRANS_DATE           ",""},
{MDS_EXPIRY_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","EXPIRY_DATE",""},
{MDS_STLMNT_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","STLMNT_DATE",""},
{MDS_CNVRSN_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","CNVRSN_DATE",""},
{MDS_CAPTURE_DATE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","CAPTURE_DATE",""},
{MDS_MERCHANT_TYPE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","MERCHANT_TYPE",""},
{MDS_ACQR_COUNTRY, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","ACQR_COUNTRY",""},
{MDS_PAN_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","PAN_COUNTRY",""},
{MDS_FORWD_COUNTRY, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","FORWD_COUNTRY",""},
{MDS_POS_ENTRY_MODE       , FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","POS_ENTRY_MODE       ",""},
{MDS_CARD_SEQUENCE_NBR, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","CARD_SEQUENCE_NBR",""},
{MDS_NET_INT_ID, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","NET_INT_ID",""},
{MDS_POS_CONDITION        , FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","POS_CONDITION        ",""},
{MDS_POS_PIN_CAPTURE      , FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","POS_PIN_CAPTURE      ",""},
{MDS_AUTHOR_ID_LENGTH, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","AUTHOR_ID_LENGTH",""},
{MDS_TRANS_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,/*8*/9,PP_PRINT,"","TRANS_FEE",""},/*NAB28042020 PLUTONL-1785*/
{MDS_STLMNT_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","STLMNT_FEE",""},
{MDS_TRANS_PROCES_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","TRANS_PROCES_FEE",""},
{MDS_STLMNT_PROCES_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","STLMNT_PROCES_FEE",""},
{MDS_ACQR_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","ACQR_ID",""},
{MDS_FORWD_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","FORWD_ID",""},
{MDS_PAN_EXTENDED, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","PAN_EXTENDED",""},
{MDS_T2_DATA, FT_SINGLE,FF_Z,AF_EBCDIC,FL_LL,LU_BYTE,37,PP_PRINT,"","T2_DATA",""},
{MDS_T3_DATA, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,4,PP_PRINT,"","T3_DATA",""},
{MDS_REFERENCE_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","REFERENCE_NBR",""},
{MDS_AUTHOR_ID, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUTHOR_ID",""},
{MDS_RESPONSE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","RESPONSE_CODE",""},
{MDS_SERVICE_CODE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","SERVICE_CODE",""},
{MDS_TERMINAL_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","TERMINAL_NBR",""},
{MDS_OUTLET_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"","OUTLET_NBR",""},
{MDS_TERMINAL_ADR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,40,PP_PRINT,"","TERMINAL_ADR",""},
{MDS_ADTNL_RESP_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,25,PP_PRINT,"","ADTNL_RESP_DATA",""},
{MDS_T1_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,76,PP_PRINT,"","T1_DATA",""},
{MDS_ADTNL_DATA_ISO      , FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_ISO      ",""},
{MDS_ADTNL_DATA_NAT, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_NAT",""},
{MDS_ADTNL_DATA_PRIV, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_DATA_PRIV",""},
{MDS_TRANS_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRANS_CRNCY",""},
{MDS_STLMNT_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_CRNCY",""},
{MDS_BILLING_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","BILLING_CRNCY",""},
{MDS_PIN_DATA, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","PIN_DATA",""},
{MDS_SECURITY_DATA, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","SECURITY_DATA",""},
{MDS_ADTNL_AMOUNTS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,120,PP_PRINT,"","ADTNL_AMOUNTS",""},
{MDS_ICC_DATA, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","ICC_DATA",""},
{MDS_PAYMENT_ACCOUNT_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,37,PP_PRINT,"","PAYMENT_ACCOUNT_DATA",""},
{MDS_RESERVED_NAT_1, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,3,PP_PRINT,"","RESERVED_NAT_1",""},
{MDS_AUTHOR_AGENT_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LLL,LU_BYTE,9,PP_PRINT,"","AUTHOR_AGENT_ID",""},
{MDS_RESERVED_NAT_2, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,14,PP_PRINT,"","RESERVED_NAT_2",""},
{MDS_ADVICE_REASON_CODE       , FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,60,PP_PRINT,"","ADVICE_REASON_CODE       ",""},
{MDS_ADTNL_POS_INFO       , FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,26,PP_PRINT,"","ADTNL_POS_INFO       ",""},
{MDS_INT_NET_FACILITY           , FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,50,PP_PRINT,"","INT_NET_FACILITY           ",""},
{MDS_NETWORK_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,49,PP_PRINT,"","NETWORK_DATA",""},
{MDS_MAC1, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC1",""},
{MDS_BIT_MAP_2, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,0,PP_PRINT,"","BIT_MAP_2",""},
{MDS_STLMNT_CODE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","STLMNT_CODE",""},
{MDS_EXT_PAY_CODE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","EXT_PAY_CODE",""},
{MDS_RECEIVER_COUNTRY, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RECEIVER_COUNTRY",""},
{MDS_STLMNT_INST_COUNTRY, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_INST_COUNTRY",""},
{MDS_NW_MNGMT_INFO, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","NW_MNGMT_INFO",""},
{MDS_MESG_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","MESG_NBR",""},
{MDS_MESG_NBR_LAST, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","MESG_NBR_LAST",""},
{MDS_ACTION_DATE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","ACTION_DATE",""},
{MDS_CREDIT_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","CREDIT_NBR",""},
{MDS_CREDIT_REV_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","CREDIT_REV_NBR",""},
{MDS_DEBIT_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","DEBIT_NBR",""},
{MDS_DEBIT_REV_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","DEBIT_REV_NBR",""},
{MDS_TRANSFER_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","TRANSFER_NBR",""},
{MDS_TRANSFER_REV_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","TRANSFER_REV_NBR",""},
{MDS_INQUIRIES_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","INQUIRIES_NBR",""},
{MDS_AUTHOR_NBR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","AUTHOR_NBR",""},
{MDS_CR_PROCESS_FEE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","CR_PROCESS_FEE",""},
{MDS_CR_TRANS_FEE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","CR_TRANS_FEE",""},
{MDS_DB_PROCESS_FEE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","DB_PROCESS_FEE",""},
{MDS_DB_TRANS_FEE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","DB_TRANS_FEE",""},
{MDS_CR_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_AMOUNT",""},
{MDS_CR_REV_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REV_AMOUNT",""},
{MDS_DB_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_AMOUNT",""},
{MDS_DB_REV_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REV_AMOUNT",""},
{MDS_ORIG_DATA            , FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","ORIG_DATA            ",""},
{MDS_FILE_UPDATE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","FILE_UPDATE",""},
{MDS_FILE_SECURITY, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","FILE_SECURITY",""},
{MDS_RESPONSE_IND, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,5,PP_PRINT,"","RESPONSE_IND",""},
{MDS_SERVICE_IND , FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,7,PP_PRINT,"","SERVICE_IND ",""},
{MDS_REPLACE_AMOUNTS, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","REPLACE_AMOUNTS",""},
{MDS_MSG_SECURITY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MSG_SECURITY",""},
{MDS_NET_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,17,PP_PRINT,"","NET_AMOUNT",""},
{MDS_PAYEE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"","PAYEE",""},
{MDS_STLMNT_INSTI_ID, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","STLMNT_INSTI_ID",""},
{MDS_RECEIVER_INSTI_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","RECEIVER_INSTI_ID",""},
{MDS_FILE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,17,PP_PRINT,"","FILE_NAME",""},
{MDS_ACCOUNT_ID1, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID1",""},
{MDS_ACCOUNT_ID2, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID2",""},
{MDS_DIGITAL_PAYMENT_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","DIGITAL_PAYMENT_DATA",""},
{MDS_RESERVED_MCI_1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RESERVED_MCI_1",""},
{MDS_RESERVED_MCI_2, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RESERVED_MCI_2",""},
{MDS_RESERVED_MCI_3, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RESERVED_MCI_3",""},
{MDS_MONEYSEND_REF_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","MONEYSEND_REF_DATA",""},
{MDS_RESERVED_ISO_4, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_ISO_4",""},
{MDS_ADDITIONAL_DATA_2, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADDITIONAL_DATA_2",""},
{MDS_AMOUNT_ASSESS, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LLL,LU_BYTE,12,PP_PRINT,"","AMOUNT_ASSESS",""},
{MDS_ADDITIONAL_DATA_NATL, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,248,PP_PRINT,"","ADDITIONAL_DATA_NATL",""},
{MDS_RESERVED_NATL_3, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_NATL_3",""},
{MDS_RESERVED_NATL_4, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_NATL_4",""},
{MDS_ADTNL_TRACE_DATA, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,24,PP_PRINT,"","ADTNL_TRACE_DATA",""},
{MDS_RESERVED_NATL_6, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_NATL_6",""},
{MDS_RESERVED_NATL_7, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_NATL_7",""},
{MDS_RESERVED_NATL_8, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_NATL_8",""},
{MDS_RESERVED_NATL_9, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_NATL_9",""},
{MDS_ORIG_MSG_TYPE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ORIG_MSG_TYPE",""},
{MDS_AUTH_AGENT_ID, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,0,PP_PRINT,"","AUTH_AGENT_ID",""},
{MDS_RECORD_DATA_ADD, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,100,PP_PRINT,"","RECORD_DATA_ADD",""},
{MDS_ADR_VERIF_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADR_VERIF_DATA",""},
{MDS_MEMBER_DEF_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,199,PP_PRINT,"","MEMBER_DEF_DATA",""},
/*{MDS_SUPPORT_INFO, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_LLL,LU_BYTE,16,PP_PRINT,"","SUPPORT_INFO",""},*//*NAB11022020 PLUTONL-1082*/
{MDS_SUPPORT_INFO, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","SUPPORT_INFO",""}, /*PLUTONL-1082*/
{MDS_PRIV_USE_FIELD, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,50,PP_PRINT,"","PRIV_USE_FIELD",""},
{MDS_RECORD_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,50,PP_PRINT,"","RECORD_DATA",""},
{MDS_MAC2, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC2",""},
},
		"MdsMsgBMInfoProperties",
	},
	"MdsMsgBMInfoProperties", /* szPropertiesName*/
	ISO8583_MCI_MDS,			/* nProtocolId */
	E_FIXED_LENGTH,				/* eHeaderType */
	FF_HEX,					/* eHeaderFormat */
	0,							/* nHeaderLen */
};




int InitMdsProtocol()
{
	RegisterMsgInfoProp(&MdsMsgInfoProperties);
	return OK;
}
