#include <stdio.h>
#include <stdlib.h>

#include <define.h>
#include <p7_common.h>
#include <p7_globals.h>
#include <iso8583.h>
#include <jcb_define.h>
#include <jcb_fields.h>


static MsgInfoProperties	IsoJCBMsgProperties = {
	FF_ALPHA_N,		/* eMsgTypeType */
	4,				/* nMsgTypeLen */
	AF_EBCDIC,		/* eMsgTypeAlphaFormat */
	"JCB",			/* szProtocolName	*/
	"JCB",			/* szProtocolPrefix */
	{
		128,		/* nNbFields */
		2,			/* nNbBitmaps */
		2,			/* nNbConsBitmaps */
		8,			/* nBitmapLen */
		FF_BIN,		/* eBitmapFmt */

		{

{JCB_BIT_MAP2, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,0,PP_HIDE,"","BIT_MAP2",""},
{JCB_CARD_NBR, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,19,PP_HIDE,"","CARD_NBR",""},
{JCB_PROC_CODE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","PROC_CODE","JCB_F03_PROP"},
{JCB_TRANS_AMOUNT, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","TRANS_AMOUNT",""},
{JCB_STLMNT_AMOUNT, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","STLMNT_AMOUNT",""},
{JCB_BILLING_AMOUNT, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,12,PP_PRINT,"","BILLING_AMOUNT",""},
{JCB_XMIT_TIME, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","XMIT_TIME",""},
{JCB_BILLING_AMOUNT_FEES, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,8,PP_PRINT,"","BILLING_AMOUNT_FEES",""},
{JCB_STLMNT_CNVRSN_RATE, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,8,PP_PRINT,"","STLMNT_CNVRSN_RATE",""},
{JCB_BILLING_CNVRSN_RATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,8,PP_PRINT,"","BILLING_CNVRSN_RATE",""},
{JCB_AUDIT_NBR, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","AUDIT_NBR",""},
{JCB_TRANS_TIME, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","TRANS_TIME",""},
{JCB_TRANS_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","TRANS_DATE",""},
{JCB_EXPIRY_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","EXPIRY_DATE",""},
{JCB_STLMNT_DATE, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","STLMNT_DATE",""},
{JCB_CNVRSN_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","CNVRSN_DATE",""},
{JCB_CAPTURE_DATE, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","CAPTURE_DATE",""},
{JCB_MERCHANT_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","MERCHANT_TYPE",""},
{JCB_ACQR_COUNTRY, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","ACQR_COUNTRY",""},
{JCB_PAN_COUNTRY, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","PAN_COUNTRY",""},
{JCB_FORWD_COUNTRY, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","FORWD_COUNTRY",""},
{JCB_POS_ENTRY_MODE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","POS_ENTRY_MODE","JCB_F022_PROP"},
{JCB_CARD_SEQUENCE_NBR, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","CARD_SEQUENCE_NBR",""},
{JCB_NETWORK_INT_ID, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","NETWORK_INT_ID",""},
{JCB_POS_CONDITION, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,2,PP_PRINT,"","POS_CONDITION",""},
{JCB_POS_PIN_CAPTURE_CODE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,2,PP_PRINT,"","POS_PIN_CAPTURE_CODE",""},
{JCB_AUTHOR_ID_LENGTH, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,1,PP_PRINT,"","AUTHOR_ID_LENGTH",""},
{JCB_TRANS_AMOUNT_FEE, FT_SINGLE,FF_X_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","TRANS_AMOUNT_FEE",""},
{JCB_STLMNT_AMOUNT_FEE, FT_UNDEF,FF_X_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,9,PP_PRINT,"","STLMNT_AMOUNT_FEE",""},
{JCB_TRANS_PROC_FEE, FT_UNDEF,FF_X_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,9,PP_PRINT,"","TRANS_PROC_FEE",""},
{JCB_STLMNT_PROC_FEE, FT_UNDEF,FF_X_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,9,PP_PRINT,"","STLMNT_PROC_FEE",""},
{JCB_ACQR_ID, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,11,PP_PRINT,"","ACQR_ID",""},
{JCB_FORWD_ID, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,11,PP_PRINT,"","FORWD_ID",""},
{JCB_PAN_EXTENDED, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,28,PP_PRINT,"","PAN_EXTENDED",""},
{JCB_T2_DATA, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_B,LU_NIBBLES,37,PP_HIDE,"","T2_DATA",""},
{JCB_T3_DATA, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_B,LU_NIBBLES,104,PP_PRINT,"","T3_DATA",""},
{JCB_REFERENCE_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","REFERENCE_NBR",""},
{JCB_AUTHOR_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUTHOR_ID",""},
{JCB_RESPONSE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","RESPONSE_CODE",""},
{JCB_SERVICE_CODE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","SERVICE_CODE",""},
{JCB_TERMINAL_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","TERMINAL_NBR",""},
{JCB_OUTLET_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"","OUTLET_NBR",""},
{JCB_TERMINAL_ADR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,40,PP_PRINT,"","TERMINAL_ADR","JCB_F043_PROP"},
{JCB_ADTNL_RESP_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,99,PP_PRINT,"","ADTNL_RESP_DATA",""},
{JCB_T1_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,76,PP_PRINT,"","T1_DATA",""},
{JCB_ADTNL_DATA_ISO, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,76,PP_PRINT,"","ADTNL_DATA_ISO",""},
{JCB_ADTNL_DATA_NATL, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_NATL",""},
{JCB_ADTNL_DATA_PRIV, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_PRIV","JCB_F048_PROP"},	/*IZL 01092022 PLUTONL-4769*/	/*FF_BIN --> FF_ALPHA_ANS*/
{JCB_TRANS_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRANS_CRNCY",""},
{JCB_STLMNT_CRNCY, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_CRNCY",""},
{JCB_BILLING_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","BILLING_CRNCY",""},
{JCB_PIN_DATA, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_HIDE,"","PIN_DATA",""},
{JCB_SECURITY_DATA, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,16,PP_PRINT,"","SECURITY_DATA",""},
{JCB_ADTNL_AMOUNTS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_B,LU_BYTE,120,PP_PRINT,"","ADTNL_AMOUNTS","JCB_F054_PROP"},
{JCB_ICC_DATA, FT_STRUCT_BER,FF_BIN,AF_EBCDIC,FL_BB,LU_BYTE,255,PP_PRINT,"","ICC_DATA","JCB_F055_PROP"},
{JCB_RES_ISO1, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_ISO1",""},
{JCB_RES_NATL1, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NATL1",""},
{JCB_RES_NATL2, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NATL2",""},
{JCB_RES_NATL3, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NATL3",""},
{JCB_ADV_REASON_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ADV_REASON_CODE","JCB_F060_PROP"},
{JCB_ADTNL_POS_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","ADTNL_POS_INFO","JCB_F061_PROP"},
{JCB_CPS_FIELDS, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","CPS_FIELDS",""},
{JCB_TRANSACTION_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,255,PP_PRINT,"","TRANSACTION_CODE",""},
{JCB_MAC1, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC1",""},
{JCB_BIT_MAP_2, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","BIT_MAP_2",""},
{JCB_STLMNT_CODE, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,1,PP_PRINT,"","STLMNT_CODE",""},
{JCB_EXTD_PYMT_CODE, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,2,PP_PRINT,"","EXTD_PYMT_CODE",""},
{JCB_RCV_INST_COUNTRY, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","RCV_INST_COUNTRY",""},
{JCB_STLMNT_INST_COUNTRY, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","STLMNT_INST_COUNTRY",""},
{JCB_NW_MNGMT_INFO, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,3,PP_PRINT,"","NW_MNGMT_INFO",""},
{JCB_MSG_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","MSG_NBR",""},
{JCB_MSG_LAST_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"","MSG_LAST_NBR",""},
{JCB_ACTION_DATE, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"","ACTION_DATE",""},
{JCB_CR_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","CR_NBR",""},
{JCB_CR_REV_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","CR_REV_NBR",""},
{JCB_DB_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","DB_NBR",""},
{JCB_DB_REV_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","DB_REV_NBR",""},
{JCB_TR_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","TR_NBR",""},
{JCB_TR_REV_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","TR_REV_NBR",""},
{JCB_INQ_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","INQ_NBR",""},
{JCB_AUT_NBR, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","AUT_NBR",""},
{JCB_CR_PROC_FEE_AMOUNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","CR_PROC_FEE_AMOUNT",""},
{JCB_CR_TRANS_FEE_AMOUNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","CR_TRANS_FEE_AMOUNT",""},
{JCB_DB_PROC_FEE_AMOUNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","DB_PROC_FEE_AMOUNT",""},
{JCB_DB_TRANS_FEE_AMOUNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,10,PP_PRINT,"","DB_TRANS_FEE_AMOUNT",""},
{JCB_CR_AMOUNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,16,PP_PRINT,"","CR_AMOUNT",""},
{JCB_CR_REV_AMOUNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,16,PP_PRINT,"","CR_REV_AMOUNT",""},
{JCB_DB_AMOUNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,16,PP_PRINT,"","DB_AMOUNT",""},
{JCB_DB_REV_AMOUNT, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,16,PP_PRINT,"","DB_REV_AMOUNT",""},
{JCB_ORIG_DATA, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,42,PP_PRINT,"","ORIG_DATA",""},
{JCB_FILE_UPDATE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","FILE_UPDATE",""},
{JCB_FILE_SECURITY, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","FILE_SECURITY",""},
{JCB_RESP_INDICATOR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,5,PP_PRINT,"","RESP_INDICATOR",""},
{JCB_SERV_INDICATOR, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,7,PP_PRINT,"","SERV_INDICATOR",""},
{JCB_REPLACE_AMOUNTS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","REPLACE_AMOUNTS","JCB_F095_PROP"},
{JCB_MSG_SECURITY, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MSG_SECURITY",""},
{JCB_NET_AMOUNT, FT_UNDEF,FF_X_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,17,PP_PRINT,"","NET_AMOUNT",""},
{JCB_PAYEE, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"","PAYEE",""},
{JCB_STLMNT_INSTITN, FT_UNDEF,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,11,PP_PRINT,"","STLMNT_INSTITN",""},
{JCB_RECEIVER_ID, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_B,LU_NIBBLES,11,PP_PRINT,"","RECEIVER_ID",""},
{JCB_FILE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,17,PP_PRINT,"","FILE_NAME",""},
{JCB_ACCOUNT_ID1, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID1",""},
{JCB_ACCOUNT_ID2, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID2",""},
{JCB_TRANS_DESC, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,100,PP_PRINT,"","TRANS_DESC",""},
{JCB_RES_MC_USE_1, FT_SINGLE,FF_HEX,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","RES_MC_USE_1",""},
{JCB_RES_MC_USE_2, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_MC_USE_2",""},
{JCB_RES_MC_USE_3, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_MC_USE_3",""},
{JCB_MONEYSEND_REF_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","MONEYSEND_REF_DATA",""},
{JCB_RES_ISO_USE_1, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_ISO_USE_1",""},
{JCB_ADDNTL_DATA_2, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","ADDNTL_DATA_2",""},
{JCB_RES_ISO_USE_2, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_ISO_USE_2",""},
{JCB_ADDNTL_DATA_NAT_USE, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","ADDNTL_DATA_NAT_USE",""},
{JCB_RES_NAT_USE_4, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_4",""},
{JCB_RES_NAT_USE_5, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_5",""},
{JCB_RES_NAT_USE_6, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_6",""},
{JCB_RES_NAT_USE_7, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_7",""},
{JCB_RES_NAT_USE_8, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_8",""},
{JCB_RES_NAT_USE_9, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_9",""},
{JCB_RES_NAT_USE_10, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_10",""},
{JCB_RECORD_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_BB,LU_BYTE,30,PP_PRINT,"","RECORD_DATA",""},
{JCB_AUTHOR_AGENT, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","AUTHOR_AGENT",""},
{JCB_ADTNL_RECORD_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","ADTNL_RECORD_DATA",""},
{JCB_ADR_VERIF_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","ADR_VERIF_DATA",""},
{JCB_MEMBER_DEF_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","MEMBER_DEF_DATA",""},
{JCB_SUPPORT_INFO, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","SUPPORT_INFO",""},
{JCB_PRIV_DATA_1, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_B,LU_BYTE,999,PP_PRINT,"","PRIV_DATA_1",""},
{JCB_NEG_DATA_ACCESS_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_BB,LU_BYTE,6,PP_PRINT,"","NEG_DATA_ACCESS_CODE",""},
{JCB_MAC2, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC2",""},



},
		"JcbMsgBMInfoProperties",
	},
	"IsoJCBMsgProperties", 		/* szPropertiesName*/
	ISO8583_JCB,				/* nProtocolId */
	E_FIXED_LENGTH,				/* eHeaderType */
	FF_HEX,						/* eHeaderFormat */
	0,							/* nHeaderLen */
};


static const BerInfoProperties	JcbF055Prop = {
JCB_F55_NB_FIELDS,
{

{JCB_F55_DED_FILE_NAME, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	16,		LU_BYTE,	PP_PRINT,	"",		"DED_FILE_NAME",	""		},
{JCB_F55_TERM_APP_VER_NUM, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	2,		LU_BYTE,	PP_PRINT,	"",		"TERM_APP_VER_NUM",	""		},
{JCB_F55_IFD_SERIAL_NUM, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	8,		LU_BYTE,	PP_PRINT,	"",		"IFD_SERIAL_NUM",	""		},
{JCB_F55_CRYPTO_INFO_DATA, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	1,		LU_BYTE,	PP_PRINT,	"",		"CRYPTO_INFO_DATA",	""		},
{JCB_F55_CVM, 				FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	3,		LU_BYTE,	PP_PRINT,	"",		"CVM",				""		},
{JCB_F55_TERM_TYPE, 		FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	1,		LU_BYTE,	PP_PRINT,	"",		"TERM_TYPE",		""		},
{JCB_F55_TRANS_SEQ_NUM, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	4,		LU_BYTE,	PP_PRINT,	"",		"TRANS_SEQ_NUM",	""		},
{JCB_F55_ISS_SCRIPT1, 		FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	128,	LU_BYTE,	PP_PRINT,	"",		"ISS_SCRIPT1",		""		},
{JCB_F55_ISS_SCRIPT2, 		FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	128,	LU_BYTE,	PP_PRINT,	"",		"ISS_SCRIPT2",		""		},
{JCB_F55_APP_INTER_PROFILE, FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	2,		LU_BYTE,	PP_PRINT,	"",		"APP_INTER_PROFILE",""		},

{JCB_F55_ISS_AUTHEN_DATA, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	16,		LU_BYTE,	PP_PRINT,	"",		"ISS_AUTHEN_DATA",	""		},
{JCB_F55_TVR, 				FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	5,		LU_BYTE,	PP_PRINT,	"",		"TVR",				""		},
{JCB_F55_TRANS_DATE, 		FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	3,		LU_BYTE,	PP_PRINT,	"",		"TRANS_DATE",		""		},
{JCB_F55_TRANS_TYPE, 		FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	1,		LU_BYTE,	PP_PRINT,	"",		"TRANS_TYPE",		""		},
{JCB_F55_TRANS_CUR_CODE, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	2,		LU_BYTE,	PP_PRINT,	"",		"TRANS_CUR_CODE",	""		},
{JCB_F55_TRANS_AMOUNT, 		FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	6,		LU_BYTE,	PP_PRINT,	"",		"TRANS_AMOUNT",		""		},
{JCB_F55_OTHER_AMOUNT, 		FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	6,		LU_BYTE,	PP_PRINT,	"",		"OTHER_AMOUNT",		""		},
{JCB_F55_ISS_APP_DATA, 		FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	33,		LU_BYTE,	PP_PRINT,	"",		"ISS_APP_DATA",		""		},
{JCB_F55_TERM_COUNTRY_CODE, FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	2,		LU_BYTE,	PP_PRINT,	"",		"TERM_COUNTRY_CODE",""		},
{JCB_F55_APP_CRYPTOGRAM, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	8,		LU_BYTE,	PP_PRINT,	"",		"APP_CRYPTOGRAM",	""		},

{JCB_F55_TERM_CAP, 			FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	3,		LU_BYTE,	PP_PRINT,	"",		"TERM_CAP",			""		},
{JCB_F55_ATC, 				FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	2,		LU_BYTE,	PP_PRINT,	"",		"ATC",				""		},
{JCB_F55_UNPRED_NUMBER, 	FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	4,		LU_BYTE,	PP_PRINT,	"",		"UNPRED_NUMBER",	""		},
{JCB_F55_ICC_APPLICATION_ID,FT_SINGLE,	FF_HEX,	AF_ASCII,	FL_LL,	16,		LU_BYTE,	PP_PRINT,	"",		"ICC_APPLICATION_ID",""		},
},
"JCB_F055_PROP"
};



int RegisterJcbSubFieldsProp()
{
	RegisterBerInfoProp(&JcbF055Prop);
	return OK;
}

int InitJcbProtocol()
{
	RegisterMsgInfoProp(&IsoJCBMsgProperties);
	return OK;
}



