#include <stdio.h>
#include <stdlib.h>

#include <define.h>
#include <p7_common.h>
#include <p7_globals.h>
#include <iso8583.h>
#include <cis_define.h>
#include <cis_fields.h>


/*Start PROD00070301*/
static MsgInfoProperties	CisMsgInfoProperties = {
	FF_ALPHA_N,			/* eMsgTypeType */
	4,				/* nMsgTypeLen */
	AF_EBCDIC,		/* eMsgTypeAlphaFormat */
	"CIS",		/* szProtocolName	*/
	"CIS",			/* szProtocolPrefix */
	{
		128,		/* nNbFields */
		2,			/* nNbBitmaps */
		2,			/* nNbConsBitmaps */
		8,			/* nBitmapLen */
		FF_BIN,		/* eBitmapFmt */
		{
{CIS_BIT_MAP2, FT_UNDEF/*FT_SINGLE*/,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,0,PP_HIDE,"","BIT_MAP2",""},
{CIS_CARD_NBR, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,19,PP_HIDE,"","CARD_NBR",""},
{CIS_PROC_CODE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","PROC_CODE",""},
{CIS_TRANS_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","TRANS_AMOUNT",""},
{CIS_STLMNT_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","STLMNT_AMOUNT",""},
{CIS_BILLING_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","BILLING_AMOUNT",""},
{CIS_XMIT_TIME, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","XMIT_TIME",""},
{CIS_BILLING_AMOUNT_FEES, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_AMOUNT_FEES",""},
{CIS_STLMNT_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","STLMNT_CNVRSN_RATE",""},
{CIS_BILLING_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_CNVRSN_RATE",""},
{CIS_AUDIT_NBR, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUDIT_NBR",""},
{CIS_TRANS_TIME, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","TRANS_TIME",""},
{CIS_TRANS_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","TRANS_DATE",""},
{CIS_EXPIRY_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","EXPIRY_DATE",""},
{CIS_STLMNT_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","STLMNT_DATE",""},
{CIS_CNVRSN_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","CNVRSN_DATE",""},
{CIS_CAPTURE_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","CAPTURE_DATE",""},
{CIS_MERCHANT_TYPE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","MERCHANT_TYPE",""},
{CIS_ACQR_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","ACQR_COUNTRY",""},
{CIS_PAN_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","PAN_COUNTRY",""},
{CIS_FORWD_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","FORWD_COUNTRY",""},
{CIS_POS_ENTRY_MODE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","POS_ENTRY_MODE",""},
{CIS_CARD_SEQUENCE_NBR, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","CARD_SEQUENCE_NBR",""},
{CIS_NETWORK_INT_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","NETWORK_INT_ID",""},
{CIS_POS_CONDITION, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","POS_CONDITION",""},
{CIS_POS_PIN_CAPTURE_CODE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","POS_PIN_CAPTURE_CODE",""},
{CIS_AUTHOR_ID_LENGTH, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","AUTHOR_ID_LENGTH",""},
{CIS_TRANS_AMOUNT_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","TRANS_AMOUNT_FEE",""},
{CIS_STLMNT_AMOUNT_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","STLMNT_AMOUNT_FEE",""},
{CIS_TRANS_PROC_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","TRANS_PROC_FEE",""},
{CIS_STLMNT_PROC_FEE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,9,PP_PRINT,"","STLMNT_PROC_FEE",""},
{CIS_ACQR_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,6,PP_PRINT,"","ACQR_ID",""},
{CIS_FORWD_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,6,PP_PRINT,"","FORWD_ID",""},
{CIS_PAN_EXTENDED, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","PAN_EXTENDED",""},
{CIS_T2_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,37,PP_HIDE,"","T2_DATA",""},
{CIS_T3_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,104,PP_HIDE,"","T3_DATA",""},
{CIS_REFERENCE_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","REFERENCE_NBR",""},
{CIS_AUTHOR_ID, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUTHOR_ID",""},
{CIS_RESPONSE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","RESPONSE_CODE",""},
{CIS_SERVICE_CODE, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","SERVICE_CODE",""},
{CIS_TERMINAL_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","TERMINAL_NBR",""},
{CIS_OUTLET_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"","OUTLET_NBR",""},
{CIS_TERMINAL_ADR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,40,PP_PRINT,"","TERMINAL_ADR",""},
{CIS_ADTNL_RESP_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,25,PP_PRINT,"","ADTNL_RESP_DATA",""},
{CIS_T1_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,76,PP_HIDE,"","T1_DATA",""},
{CIS_ADTNL_DATA_ISO, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_DATA_ISO",""},
{CIS_ADTNL_DATA_NATL, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_DATA_NATL",""},
{CIS_ADTNL_DATA_PRIV, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_HIDE,"","ADTNL_DATA_PRIV","CIS_F048_PROP"},
{CIS_TRANS_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRANS_CRNCY",""},
{CIS_STLMNT_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_CRNCY",""},
{CIS_BILLING_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","BILLING_CRNCY",""},
{CIS_PIN_DATA, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_HIDE,"","PIN_DATA",""},
{CIS_SECURITY_DATA, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","SECURITY_DATA",""},
{CIS_ADTNL_AMOUNTS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,120,PP_PRINT,"","ADTNL_AMOUNTS",""},
{CIS_ICC_DATA, FT_STRUCT_BER,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_HIDE,"","ICC_DATA","CIS_F055_PROP"},
{CIS_PAYMENT_ACCOUNT_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","PAYMENT_ACCOUNT_DATA",""},
{CIS_RES_NATL1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,3,PP_PRINT,"","RES_NATL1",""},
{CIS_RES_NATL2, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,255,PP_PRINT,"","RES_NATL2",""},
{CIS_RES_NATL3, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,14,PP_PRINT,"","RES_NATL3",""},
{CIS_ADV_REASON_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,60,PP_PRINT,"","ADV_REASON_CODE",""},
{CIS_ADTNL_POS_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,26,PP_PRINT,"","ADTNL_POS_INFO",""},
{CIS_CPS_FIELDS, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,100,PP_PRINT,"","CPS_FIELDS",""},
{CIS_BANKNET_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LLL,LU_BYTE,50,PP_PRINT,"","BANKNET_DATA",""},
{CIS_MAC1, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC1",""},
{CIS_BIT_MAP_2, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","BIT_MAP_2",""},
{CIS_STLMNT_CODE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","STLMNT_CODE",""},
{CIS_EXTD_PYMT_CODE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","EXTD_PYMT_CODE",""},
{CIS_RCV_INST_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","RCV_INST_COUNTRY",""},
{CIS_STLMNT_INST_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_INST_COUNTRY",""},
{CIS_NW_MNGMT_INFO, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","NW_MNGMT_INFO",""},
{CIS_MSG_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","MSG_NBR",""},
{CIS_MSG_LAST_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","MSG_LAST_NBR",""},
{CIS_ACTION_DATE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","ACTION_DATE",""},
{CIS_CR_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","CR_NBR",""},
{CIS_CR_REV_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","CR_REV_NBR",""},
{CIS_DB_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","DB_NBR",""},
{CIS_DB_REV_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","DB_REV_NBR",""},
{CIS_TR_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","TR_NBR",""},
{CIS_TR_REV_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","TR_REV_NBR",""},
{CIS_INQ_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","INQ_NBR",""},
{CIS_AUT_NBR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","AUT_NBR",""},
{CIS_CR_PROC_FEE_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","CR_PROC_FEE_AMOUNT",""},
{CIS_CR_TRANS_FEE_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","CR_TRANS_FEE_AMOUNT",""},
{CIS_DB_PROC_FEE_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","DB_PROC_FEE_AMOUNT",""},
{CIS_DB_TRANS_FEE_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,12,PP_PRINT,"","DB_TRANS_FEE_AMOUNT",""},
{CIS_CR_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_AMOUNT",""},
{CIS_CR_REV_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REV_AMOUNT",""},
{CIS_DB_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_AMOUNT",""},
{CIS_DB_REV_AMOUNT, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REV_AMOUNT",""},
{CIS_ORIG_DATA, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","ORIG_DATA",""},
{CIS_FILE_UPDATE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","FILE_UPDATE",""},
{CIS_FILE_SECURITY, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","FILE_SECURITY",""},
{CIS_RESP_INDICATOR, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,5,PP_PRINT,"","RESP_INDICATOR",""},
{CIS_SERV_INDICATOR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,7,PP_PRINT,"","SERV_INDICATOR",""},
{CIS_REPLACE_AMOUNTS, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,42,PP_PRINT,"","REPLACE_AMOUNTS",""},
{CIS_MSG_SECURITY, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MSG_SECURITY",""},
{CIS_NET_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,17,PP_PRINT,"","NET_AMOUNT",""},
{CIS_PAYEE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"","PAYEE",""},
{CIS_STLMNT_INSTITN, FT_UNDEF,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","STLMNT_INSTITN",""},
{CIS_RECEIVER_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"","RECEIVER_ID",""},
{CIS_FILE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,17,PP_PRINT,"","FILE_NAME",""},
{CIS_ACCOUNT_ID1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID1",""},
{CIS_ACCOUNT_ID2, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID2",""},
{CIS_DIGITAL_PAYMENT_DATA, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","DIGITAL_PAYMENT_DATA","CIS_F104_PROP"},
{CIS_RES_MC_USE_1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_MC_USE_1",""},
{CIS_RES_MC_USE_2, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_MC_USE_2",""},
{CIS_RES_MC_USE_3, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_MC_USE_3",""},
{CIS_MONEYSEND_REF_DATA, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","MONEYSEND_REF_DATA","CIS_F108_PROP"},
{CIS_RES_ISO_USE_1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_ISO_USE_1",""},
{CIS_ADDNTL_DATA_2, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADDNTL_DATA_2",""},
{CIS_RES_ISO_USE_2, FT_UNDEF,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_ISO_USE_2",""},
{CIS_ADDNTL_DATA_NAT_USE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,100,PP_PRINT,"","ADDNTL_DATA_NAT_USE",""},
{CIS_RES_NAT_USE_4, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_4",""},
{CIS_RES_NAT_USE_5, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_5",""},
{CIS_RES_NAT_USE_6, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_6",""},
{CIS_RES_NAT_USE_7, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_7",""},
{CIS_RES_NAT_USE_8, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_8",""},
{CIS_RES_NAT_USE_9, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_9",""},
{CIS_RES_NAT_USE_10, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RES_NAT_USE_10",""},
{CIS_RECORD_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","RECORD_DATA",""},
{CIS_AUTHOR_AGENT, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LLL,LU_BYTE,6,PP_PRINT,"","AUTHOR_AGENT",""},
{CIS_ADTNL_RECORD_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_RECORD_DATA",""},
{CIS_ADR_VERIF_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,512,PP_PRINT,"","ADR_VERIF_DATA",""},
{CIS_MEMBER_DEF_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,199,PP_PRINT,"","MEMBER_DEF_DATA",""},
{CIS_NEW_PIN_INFO, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_B,LU_BYTE,8,PP_PRINT,"","NEW_PIN_INFO",""},
{CIS_PRIV_DATA_1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,100,PP_PRINT,"","PRIV_DATA_1",""},
{CIS_PRIV_DATA_2, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LLL,LU_BYTE,100,PP_PRINT,"","PRIV_DATA_2",""},
{CIS_MAC2, FT_UNDEF,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC2",""},

},
		"CisMsgBMInfoProperties",
	},
	"CisMsgInfoProperties", /* szPropertiesName*/
	ISO8583_MCI_CIS,			/* nProtocolId */
	E_FIXED_LENGTH,				/* eHeaderType */
	FF_HEX,					/* eHeaderFormat */
	0,							/* nHeaderLen */
};


static const BerInfoProperties	CisF055Prop = {
CIS_F55_NB_FIELDS,
{
{CIS_F55_DED_FILE_NAME, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,18,PP_PRINT,"","DED_FILE_NAME","",NOT_REPEATABLE},
{CIS_F55_TERM_APP_VER_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,5,PP_PRINT,"","TERM_APP_VER_NUM","",NOT_REPEATABLE},
{CIS_F55_IFD_SERIAL_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","IFD_SERIAL_NUM","",NOT_REPEATABLE},
{CIS_F55_CRYPTO_INFO_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","CRYPTO_INFO_DATA","",NOT_REPEATABLE},
{CIS_F55_CVM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,6,PP_PRINT,"","CVM","",NOT_REPEATABLE},
{CIS_F55_TERM_TYPE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","TERM_TYPE","",NOT_REPEATABLE},
{CIS_F55_TRANS_SEQ_NUM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,7,PP_PRINT,"","TRANS_SEQ_NUM","",NOT_REPEATABLE},
{CIS_F55_TRANS_CATEG_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","TRANS_CATEG_CODE","",NOT_REPEATABLE},
{CIS_F55_ISS_SCRIPT1, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,256,PP_HIDE,"","ISS_SCRIPT1","",NOT_REPEATABLE},
{CIS_F55_ISS_SCRIPT2, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,256,PP_HIDE,"","ISS_SCRIPT2","",NOT_REPEATABLE},
{CIS_F55_APP_INTER_PROFILE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,2,PP_PRINT,"","APP_INTER_PROFILE","",NOT_REPEATABLE},
{CIS_F55_ISS_AUTHEN_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,10,PP_PRINT,"","ISS_AUTHEN_DATA","",NOT_REPEATABLE},
{CIS_F55_TVR, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,5,PP_PRINT,"","TVR","",NOT_REPEATABLE},
{CIS_F55_TRANS_DATE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,3,PP_PRINT,"","TRANS_DATE","",NOT_REPEATABLE},
{CIS_F55_TRANS_TYPE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,1,PP_PRINT,"","TRANS_TYPE","",NOT_REPEATABLE},
{CIS_F55_TRANS_CUR_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,2,PP_PRINT,"","TRANS_CUR_CODE","",NOT_REPEATABLE},
{CIS_F55_TRANS_AMOUNT, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,6,PP_PRINT,"","TRANS_AMOUNT","",NOT_REPEATABLE},
{CIS_F55_OTHER_AMOUNT, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,6,PP_PRINT,"","OTHER_AMOUNT","",NOT_REPEATABLE},
{CIS_F55_ISS_APP_DATA, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,33,PP_PRINT,"","ISS_APP_DATA","",NOT_REPEATABLE},
{CIS_F55_TERM_COUNTRY_CODE, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,2,PP_PRINT,"","TERM_COUNTRY_CODE","",NOT_REPEATABLE},
{CIS_F55_APP_CRYPTOGRAM, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,8,PP_HIDE,"","APP_CRYPTOGRAM","",NOT_REPEATABLE},
{CIS_F55_TERM_CAP, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,3,PP_PRINT,"","TERM_CAP","",NOT_REPEATABLE},
{CIS_F55_ATC, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,2,PP_HIDE,"","ATC","",NOT_REPEATABLE},
{CIS_F55_UNPRED_NUMBER, FT_SINGLE,FF_HEX,AF_ASCII,FL_LL,LU_BYTE,4,PP_PRINT,"","UNPRED_NUMBER","",NOT_REPEATABLE},

},
"CIS_F055_PROP"
};

static const TlvInfoProperties	CisMoneySendDataProp = {
2,3,TLV_LT_ASCII,TLV_LT_ASCII,CIS_F108_NB_FIELDS,
{
{CIS_F108_RECIPIENT_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,254,PP_PRINT,"NULL","RECIPIENT_DATA","CIS_F108_T01_PROP",NOT_REPEATABLE},
{CIS_F108_SENDER_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,254,PP_PRINT,"NULL","SENDER_DATA","CIS_F108_T02_PROP",NOT_REPEATABLE},
{CIS_F108_MONEYSEND_TRANSACTION_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,132,PP_PRINT,"NULL","MONEYSEND_TRANSACTION_DATA","CIS_F108_T03_PROP",NOT_REPEATABLE},
{CIS_F108_MONEYSEND_LANGUAGE_DESCRIPTION, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,61,PP_PRINT,"NULL","MONEYSEND_LANGUAGE_DESCRIPTION","CIS_F108_T04_PROP",NOT_REPEATABLE},
},
"CIS_F108_PROP"
};

static const TlvInfoProperties	CisMoneySendDataT01Prop = {
2,2,TLV_LT_ASCII,TLV_LT_ASCII,CIS_F108T01_NB_FIELDS,
{
{CIS_F108T01_RECIPIENT_FIRST_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,35,PP_PRINT,"NULL","RECIPIENT_FIRST_NAME","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_MIDDLE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","RECIPIENT_MIDDLE_NAME","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_LAST_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,35,PP_PRINT,"NULL","RECIPIENT_LAST_NAME","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,50,PP_PRINT,"NULL","RECIPIENT_STREET_ADDR","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_CITY, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,25,PP_PRINT,"NULL","RECIPIENT_CITY","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_STATE_PROVINCE_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","RECIPIENT_STATE_PROVINCE_CODE","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_COUNTRY, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","RECIPIENT_COUNTRY","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","RECIPIENT_POSTAL_CODE","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_PHONE_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,20,PP_PRINT,"NULL","RECIPIENT_PHONE_NUMBER","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_DOB, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","RECIPIENT_DOB","NULL",NOT_REPEATABLE},
{CIS_F108T01_RECIPIENT_ACCOUNT_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,20,PP_PRINT,"NULL","RECIPIENT_ACCOUNT_NUMBER","NULL",NOT_REPEATABLE},
},
"CIS_F108_T01_PROP"
};

static const TlvInfoProperties	CisMoneySendDataT02Prop = {
2,2,TLV_LT_ASCII,TLV_LT_ASCII,CIS_F108T02_NB_FIELDS,
{
{CIS_F108T02_SENDER_FIRST_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,35,PP_PRINT,"NULL","SENDER_FIRST_NAME","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_MIDDLE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","SENDER_MIDDLE_NAME","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_LAST_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,35,PP_PRINT,"NULL","SENDER_LAST_NAME","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,50,PP_PRINT,"NULL","SENDER_STREET_ADDR","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_CITY, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,25,PP_PRINT,"NULL","SENDER_CITY","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_STATE_PROVINCE_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","SENDER_STATE_PROVINCE_CODE","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_COUNTRY, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","SENDER_COUNTRY","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","SENDER_POSTAL_CODE","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_PHONE_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,20,PP_PRINT,"NULL","SENDER_PHONE_NUMBER","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_DOB, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","SENDER_DOB","NULL",NOT_REPEATABLE},
{CIS_F108T02_SENDER_ACCOUNT_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,20,PP_PRINT,"NULL","SENDER_ACCOUNT_NUMBER","NULL",NOT_REPEATABLE},
},
"CIS_F108_T02_PROP"
};


static const TlvInfoProperties	CisMoneySendDataT03Prop = {
2,2,TLV_LT_ASCII,TLV_LT_ASCII,CIS_F108T03_NB_FIELDS,
{
{CIS_F108T03_UNIQUE_TRANSACTION_REFERENCE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,19,PP_PRINT,"NULL","UNIQUE_TRANSACTION_REFERENCE","NULL",NOT_REPEATABLE},
{CIS_F108T03_ADDITIONAL_MESSAGE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,65,PP_PRINT,"NULL","ADDITIONAL_MESSAGE","NULL",NOT_REPEATABLE},
{CIS_F108T03_FUNDING_SOURCE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","FUNDING_SOURCE","NULL",NOT_REPEATABLE},
{CIS_F108T03_PARTICIPANT_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,30,PP_PRINT,"NULL","PARTICIPANT_ID","NULL",NOT_REPEATABLE},
},
"CIS_F108_T03_PROP"
};


static const TlvInfoProperties	CisMoneySendDataT04Prop = {
2,2,TLV_LT_ASCII,TLV_LT_ASCII,CIS_F108T04_NB_FIELDS,
{
{CIS_F108T04_LANGUAGE_IDENTIFICATION, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","LANGUAGE_IDENTIFICATION","NULL",NOT_REPEATABLE},
{CIS_F108T04_LANGUAGE_DATA, FT_SINGLE,FF_BIN,AF_ASCII,FL_LLL,LU_BYTE,50,PP_PRINT,"NULL","LANGUAGE_DATA","NULL",NOT_REPEATABLE},
},
"CIS_F108_T04_PROP"
};
/*End PROD00025867*/


static const TlvInfoProperties	CISPanMappingDataProp = {
2,2,TLV_LT_ASCII,TLV_LT_ASCII,8,
{
{CIS_F048_T33_T01_ACC_NO_IND,	FT_SINGLE,	FF_ALPHA_AN,	AF_ASCII,FL_FIX,LU_BYTE,	1,	PP_PRINT,"NULL","ACC_NO_IND","NULL",NOT_REPEATABLE},
{CIS_F048_T33_T02_ACC_NO,		FT_SINGLE,	FF_ALPHA_N,		AF_ASCII,FL_FIX,LU_BYTE,	19,	PP_PRINT,"NULL","ACC_NO","NULL",NOT_REPEATABLE},
{CIS_F048_T33_T03_EXP_DT,		FT_SINGLE,	FF_ALPHA_N,		AF_ASCII,FL_FIX,LU_BYTE,	4,	PP_PRINT,"NULL","EXP_DT","NULL",NOT_REPEATABLE},
{CIS_F048_T33_T04_PRODUCT_CD,	FT_SINGLE,	FF_ALPHA_AN,	AF_ASCII,FL_FIX,LU_BYTE,	3,	PP_PRINT,"NULL","PRODUCT_CD","NULL",NOT_REPEATABLE},
{CIS_F048_T33_T05_TOKEN_ASS_LVL, FT_SINGLE,	FF_ALPHA_N,		AF_ASCII,FL_FIX,LU_BYTE,	2,	PP_PRINT,"NULL","TOKEN_ASS_LVL","NULL",NOT_REPEATABLE},
{CIS_F048_T33_T06_TOKEN_REQ_ID, FT_SINGLE,	FF_ALPHA_N,		AF_ASCII,FL_FIX,LU_BYTE,	11,	PP_PRINT,"NULL","TOKEN_REQ_ID","NULL",NOT_REPEATABLE},
{CIS_F048_T33_T07_PAN_RANGE,	FT_SINGLE,	FF_ALPHA_N,		AF_ASCII,FL_FIX,LU_BYTE,	19,	PP_PRINT,"NULL","PAN_RANGE","NULL",NOT_REPEATABLE},
{CIS_F048_T33_T08_STORAGE_TECH, FT_SINGLE,  FF_ALPHA_AN,    AF_ASCII,FL_FIX,LU_BYTE,    2,  PP_PRINT,"NULL","STORAGE_TECH","NULL",NOT_REPEATABLE},  /*ACH20190910 PROD00070986*/

},
"CIS_F048_T33_PROP"
};

static const TlvInfoProperties	CISMultiPurposeMerDataProp = {
2,2,TLV_LT_ASCII,TLV_LT_ASCII,CIS_F048_SE22_LEN,
{
{CIS_F048_SE22_SF01_LOW_RISK_MER_IND,		FT_SINGLE,	FF_ALPHA_AN,	AF_ASCII,FL_FIX,LU_BYTE,	2,	PP_PRINT,"NULL","LOW_RISK_MER_IND","NULL",NOT_REPEATABLE},
{CIS_F048_SE22_SF02_SINGLE_TAP_IND,			FT_SINGLE,	FF_ALPHA_AN,	AF_ASCII,FL_FIX,LU_BYTE,	1,	PP_PRINT,"NULL","SINGLE_TAP_IND","NULL",NOT_REPEATABLE},
{CIS_F048_SE22_SF03_RESPONSE_PIN_REQ,		FT_SINGLE,	FF_ALPHA_AN,	AF_ASCII,FL_FIX,LU_BYTE,	1,	PP_PRINT,"NULL","RESPONSE_PIN_REQ","NULL",NOT_REPEATABLE},
{CIS_F048_SE22_SF04_ISS_PIN_REQ_SIN_TAP,	FT_SINGLE,	FF_ALPHA_AN,	AF_ASCII,FL_FIX,LU_BYTE,	1,	PP_PRINT,"NULL","ISS_PIN_REQ_SIN_TAP","NULL",NOT_REPEATABLE},
},
"CISMultiPurposeMerDataProp"
};

static const TlvInfoProperties	CisDigitalPaymentDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,CIS_F104_NB_FIELDS,
{
{CIS_F104_DIGITAL_PAYMENT_CRYPTO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,28,PP_PRINT,"NULL","DIGITAL_PAYMENT_CRYPTO","NULL",NOT_REPEATABLE},
{CIS_F104_DGITAL_PAYEMENT_ESTIMATED_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","DGITAL_PAYEMENT_ESTIMATED_AMOUNT","NULL",NOT_REPEATABLE},
{CIS_F104_DGITAL_PAYEMENT_REMOTE_COMERCE_ACCEPTOR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,150,PP_PRINT,"NULL","DGITAL_PAYEMENT_REMOTE_COMERCE_ACCEPTOR","NULL",NOT_REPEATABLE},
},
"CIS_F104_PROP"
};

static const TlvInfoProperties	CisF48DataProp = {
2,2,TLV_LT_ASCII,TLV_LT_ASCII,CIS_F48_NB_FIELDS,
{
{CIS_F48_ENC_PIN_BLK_KEY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,16,PP_HIDE,"","ENC_PIN_BLK_KEY","",NOT_REPEATABLE},
{CIS_F48_KEY_EXCH_BLK_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,70,PP_HIDE,"","KEY_EXCH_BLK_DATA","",NOT_REPEATABLE},
{CIS_F48_ROUTING_IND, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","ROUTING_IND","",NOT_REPEATABLE},
{CIS_F48_MCI_HOSTED_MPTP_REQ_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,47,PP_PRINT,"","MCI_HOSTED_MPTP_REQ_DATA","",NOT_REPEATABLE},
{CIS_F48_AUTH_PLATFORM_ADV_DT_TIME, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,10,PP_PRINT,"","AUTH_PLATFORM_ADV_DT_TIME","",NOT_REPEATABLE},
{CIS_F48_PROC_PSEUDO_ICA, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,7,PP_PRINT,"","PROC_PSEUDO_ICA","",NOT_REPEATABLE},
{CIS_F48_SERVICE_PARAMS, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","SERVICE_PARAMS","",NOT_REPEATABLE},
{CIS_F48_CH_VERIF_MTHD, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","CH_VERIF_MTHD","",NOT_REPEATABLE},
{CIS_F48_PAY_INIT_CHANNEL, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","PAY_INIT_CHANNEL","",NOT_REPEATABLE},
{CIS_F48_MCI_CASH_PROGRAM_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,14,PP_PRINT,"","MCI_CASH_PROGRAM_DATA","",NOT_REPEATABLE},
{CIS_F48_WALLET_PROGRAM_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","WALLET_PROGRAM_DATA","",NOT_REPEATABLE},
{CIS_F48_MCI_ASSIGNED_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","MCI_ASSIGNED_ID","",NOT_REPEATABLE},
{CIS_F48_PAN_MAPPING_FILE_INFO, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,43,PP_PRINT,"","PAN_MAPPING_FILE_INFO","CIS_F048_T33_PROP",NOT_REPEATABLE},
{CIS_F48_DYN_CVC3_ATC_INFO, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,11,PP_HIDE,"","DYN_CVC3_ATC_INFO","",NOT_REPEATABLE},
{CIS_F48_CL_NONCARD_FF_REQ_RESP, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","CL_NONCARD_FF_REQ_RESP","",NOT_REPEATABLE},
{CIS_F48_VISA_MVV, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,14,PP_PRINT,"","VISA_MVV","",NOT_REPEATABLE},
{CIS_F48_ADD_MER_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,49,PP_PRINT,"","ADD_MER_DATA","",NOT_REPEATABLE},
{CIS_F48_ACC_CATEGORY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","ACC_CATEGORY","",NOT_REPEATABLE},
{CIS_F48_EXP_MON_ACC_SERV_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,30,PP_PRINT,"","EXP_MON_ACC_SERV_INFO","",NOT_REPEATABLE},
{CIS_F48_ECOM_MER_CH_CERT_SNO, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,40,PP_PRINT,"","ECOM_MER_CH_CERT_SNO","",NOT_REPEATABLE},
{CIS_F48_ECOM_CERT_QUAL_INFO, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,95,PP_PRINT,"","ECOM_CERT_QUAL_INFO","",NOT_REPEATABLE},
{CIS_F48_ECOM_IND, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,7,PP_PRINT,"","ECOM_IND","",NOT_REPEATABLE},
{CIS_F48_UCAF, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,32,PP_PRINT,"","UCAF","",NOT_REPEATABLE},
{CIS_F48_VISA_3DS_XID, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,20,PP_PRINT,"","VISA_3DS_XID","",NOT_REPEATABLE},
{CIS_F48_VISA83DS_SECT_RESP_CD, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","VISA83DS_SECT_RESP_CD","",NOT_REPEATABLE},
{CIS_F48_PRODUCT_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","PRODUCT_ID","",NOT_REPEATABLE},
{CIS_F48_MCI_PAY_GW_IND, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,8,PP_PRINT,"","MCI_PAY_GW_IND","",NOT_REPEATABLE},
{CIS_F48_MOBILE_PROGRAM_IND, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","MOBILE_PROGRAM_IND","",NOT_REPEATABLE},
{CIS_F48_MER_ON_BEHALF_SERVICES, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","MER_ON_BEHALF_SERVICES","",NOT_REPEATABLE},
{CIS_F48_MER_FRAUD_SCORING_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,32,PP_PRINT,"","MER_FRAUD_SCORING_DATA","",NOT_REPEATABLE},
{CIS_F48_SECURITY_SERVICES_ADD_DATA_ISS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","SECURITY_SERVICES_ADD_DATA_ISS","",NOT_REPEATABLE},
{CIS_F48_SECURITY_SERVICES_ADD_DATA_ACQ, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","SECURITY_SERVICES_ADD_DATA_ACQ","",NOT_REPEATABLE},
{CIS_F48_ATM_ADD_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,33,PP_PRINT,"","ATM_ADD_DATA","",NOT_REPEATABLE},
{CIS_F48_POS_DATA_EXT_COND_CD, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,5,PP_PRINT,"","POS_DATA_EXT_COND_CD","",NOT_REPEATABLE},
{CIS_F48_TRACE_ID, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"","TRACE_ID","",NOT_REPEATABLE},
{CIS_F48_TRANSIT_PROGRAM, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","TRANSIT_PROGRAM","",NOT_REPEATABLE},
{CIS_F48_ON_BEHALF_SERVICES, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,40,PP_PRINT,"","ON_BEHALF_SERVICES","",NOT_REPEATABLE},
{CIS_F48_ISS_CHIP_AUTH, FT_SINGLE,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,16,PP_PRINT,"","ISS_CHIP_AUTH","",NOT_REPEATABLE},
{CIS_F48_MCI_INTERNAL_USE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,10,PP_PRINT,"","MCI_INTERNAL_USE","",NOT_REPEATABLE},
{CIS_F48_ADD_PROC_INFO, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,30,PP_PRINT,"","ADD_PROC_INFO","",NOT_REPEATABLE},
{CIS_F48_FRAUD_SCORING_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,32,PP_PRINT,"","FRAUD_SCORING_DATA","",NOT_REPEATABLE},
{CIS_F48_MCI_E_ACCEP_IND, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","MCI_E_ACCEP_IND","",NOT_REPEATABLE},
{CIS_F48_FUNDING_PAY_TRN_TYPE_IND, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","FUNDING_PAY_TRN_TYPE_IND","",NOT_REPEATABLE},
{CIS_F48_PAYMENT_SERVICES_IND, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","PAYMENT_SERVICES_IND","",NOT_REPEATABLE},
{CIS_F48_CVR_TVR_ERR_RESULT, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,50,PP_PRINT,"","CVR_TVR_ERR_RESULT","",NOT_REPEATABLE},
{CIS_F48_PIN_SERVICE_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","PIN_SERVICE_CODE","",NOT_REPEATABLE},
{CIS_F48_AVS_REQ, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","AVS_REQ","",NOT_REPEATABLE},
{CIS_F48_AVS_RESP, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","AVS_RESP","",NOT_REPEATABLE},
{CIS_F48_MER_ADVICE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","MER_ADVICE_CODE","",NOT_REPEATABLE},
{CIS_F48_ACCOUNT_STATUS, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","ACCOUNT_STATUS","",NOT_REPEATABLE},
{CIS_F48_REL_PARTICIPANT_IND, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","REL_PARTICIPANT_IND","",NOT_REPEATABLE},
{CIS_F48_CARD_VAL_CODE_RES, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","CARD_VAL_CODE_RES","",NOT_REPEATABLE},
{CIS_F48_MAG_COMPL_STATUS_IND, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","MAG_COMPL_STATUS_IND","",NOT_REPEATABLE},
{CIS_F48_MAG_COMPL_ERR_IND, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","MAG_COMPL_ERR_IND","",NOT_REPEATABLE},
{CIS_F48_LODGING_AUTO_RENT_IND, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","LODGING_AUTO_RENT_IND","",NOT_REPEATABLE},
{CIS_F48_CPS_TRN_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,19,PP_PRINT,"","CPS_TRN_ID","",NOT_REPEATABLE},
{CIS_F48_CVC2, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_HIDE,"","CVC2","",NOT_REPEATABLE},
{CIS_F48_FLEET_CARD_ID_REQ_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,19,PP_PRINT,"","FLEET_CARD_ID_REQ_DATA","",NOT_REPEATABLE},
{CIS_F48_COM_CARD_INQ_REQ, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"","COM_CARD_INQ_REQ","",NOT_REPEATABLE},
{CIS_F48_MCI_PROMO_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","MCI_PROMO_CODE","",NOT_REPEATABLE},
{CIS_F48_VISA_MARKET_DATA_ID, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","VISA_MARKET_DATA_ID","",NOT_REPEATABLE},
{CIS_F48_PRESTIGIOUS_PROP_IND, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","PRESTIGIOUS_PROP_IND","",NOT_REPEATABLE},
{CIS_F48_MCI_CORP_FLEET_CARD_ID_DRIVER_ID, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","MCI_CORP_FLEET_CARD_ID_DRIVER_ID","",NOT_REPEATABLE},
{CIS_F48_MCI_CORP_FLEET_CARD_VEHICLE_NO, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,6,PP_PRINT,"","MCI_CORP_FLEET_CARD_VEHICLE_NO","",NOT_REPEATABLE},

},
"CIS_F048_PROP"
};

int RegisterCisSubFieldsProp()
{
	RegisterBerInfoProp(&CisF055Prop);
	RegisterTlvInfoProp(&CisDigitalPaymentDataProp);
	RegisterTlvInfoProp(&CisMoneySendDataProp);
	RegisterTlvInfoProp(&CisMoneySendDataT01Prop);
	RegisterTlvInfoProp(&CisMoneySendDataT02Prop);
	RegisterTlvInfoProp(&CisMoneySendDataT03Prop);
	RegisterTlvInfoProp(&CisMoneySendDataT04Prop);
	RegisterTlvInfoProp(&CisF48DataProp);
	RegisterTlvInfoProp(&CISPanMappingDataProp);
	RegisterTlvInfoProp(&CISMultiPurposeMerDataProp);

	return OK;

}

int InitCisProtocol()
{
	RegisterMsgInfoProp(&CisMsgInfoProperties);
	return OK;
}




