#include <stdio.h>
#include <stdlib.h>
#include <define.h>
#include <iso8583.h>
#include <bank_fields.h>


/*START PLUTONL-1822*/
static MsgInfoProperties	IsoHostMsgProperties = {
	FF_ALPHA_N,			/* eMsgTypeType */
	4,				/* nMsgTypeLen */
	AF_ASCII,		/* eMsgTypeAlphaFormat */
	"HOST",		/* szProtocolName	*/
	"HOST",			/* szProtocolPrefix */
	{
		128,		/* nNbFields */
		2,			/* nNbBitmaps */
		2,			/* nNbConsBitmaps */
		8,			/* nBitmapLen */
		FF_BIN,		/* eBitmapFmt */
		{
{BANK_BIT_MAP2, FT_UNDEF,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,0,PP_HIDE,"","BIT_MAP2",""},
{BANK_CARD_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,19,PP_PRINT,"","CARD_NBR",""},
{BANK_PROC_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","PROC_CODE",""},
{BANK_TRANS_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","TRANS_AMOUNT",""},
{BANK_STLMNT_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","STLMNT_AMOUNT",""},
{BANK_BILLING_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","BILLING_AMOUNT",""},
{BANK_XMIT_TIME, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","XMIT_TIME",""},
{BANK_BILLING_AMOUNT_FEES, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_AMOUNT_FEES",""},
{BANK_STLMNT_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","STLMNT_CNVRSN_RATE",""},
{BANK_BILLING_CNVRSN_RATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","BILLING_CNVRSN_RATE",""},
{BANK_AUDIT_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUDIT_NBR",""},
{BANK_TRANS_DATE_TIME, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","TRANS_DATE_TIME",""},
{BANK_START_EXPIRY_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","START_EXPIRY_DATE",""},
{BANK_EXPIRY_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","EXPIRY_DATE",""},
{BANK_STLMNT_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","STLMNT_DATE",""},
{BANK_CNVRSN_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","CNVRSN_DATE",""},
{BANK_CAPTURE_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","CAPTURE_DATE",""},
{BANK_MERCHANT_TYPE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","MERCHANT_TYPE",""},
{BANK_ACQR_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","ACQR_COUNTRY",""},
{BANK_PAN_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","PAN_COUNTRY",""},
{BANK_FORWD_COUNTRY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","FORWD_COUNTRY",""},
{BANK_POS_DATA, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","POS_DATA",""},
{BANK_CARD_SEQUENCE_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","CARD_SEQUENCE_NBR",""},
{BANK_FUNCTION_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","FUNCTION_CODE",""},
{BANK_MSG_REASON, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","MSG_REASON",""},
{BANK_ACCEPTOR_ACTIV_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,4,PP_PRINT,"","ACCEPTOR_ACTIV_CODE",""},
{BANK_AUTHOR_ID_LENGTH, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"","AUTHOR_ID_LENGTH",""},
{BANK_RECONC_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","RECONC_DATE",""},
{BANK_RECONC_INDICATOR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","RECONC_INDICATOR",""},
{BANK_ORIGINAL_AMOUNTS, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","ORIGINAL_AMOUNTS",""},
{BANK_ACQR_REFERENCE_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,9,PP_PRINT,"","ACQR_REFERENCE_DATA",""},
{BANK_ACQR_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","ACQR_ID",""},
{BANK_FORWD_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","FORWD_ID",""},
{BANK_PAN_EXTENDED, FT_SINGLE,FF_ALPHA_NS,AF_ASCII,FL_LL,LU_BYTE,28,PP_PRINT,"","PAN_EXTENDED",""},
{BANK_T2_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,37,PP_PRINT,"","T2_DATA",""},
{BANK_T3_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,104,PP_PRINT,"","T3_DATA",""},
{BANK_REFERENCE_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"","REFERENCE_NBR",""},
{BANK_AUTHOR_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","AUTHOR_ID",""},
{BANK_RESPONSE_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","RESPONSE_CODE",""},
{BANK_SERVICE_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","SERVICE_CODE",""},
{BANK_TERMINAL_NBR, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","TERMINAL_NBR",""},
{BANK_OUTLET_NBR, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,15,PP_PRINT,"","OUTLET_NBR",""},
{BANK_TERMINAL_ADR, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,99,PP_PRINT,"","TERMINAL_ADR",""},
{BANK_ADTNL_RESP_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_RESP_DATA",""},
{BANK_T1_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,76,PP_PRINT,"","T1_DATA",""},
{BANK_FEES_AMOUNT, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,204,PP_PRINT,"","FEES_AMOUNT",""},
{BANK_ADTNL_DATA_NATL, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"","ADTNL_DATA_NATL",""},
{BANK_ADTNL_DATA_PRIV, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_DATA_PRIV","P7AddDataPrivProp"},
{BANK_TRANS_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRANS_CRNCY",""},
{BANK_STLMNT_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_CRNCY",""},
{BANK_BILLING_CRNCY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","BILLING_CRNCY",""},
{BANK_PIN_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","PIN_DATA",""},
{BANK_SECURITY_DATA, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,99,PP_PRINT,"","SECURITY_DATA",""},
{BANK_ADTNL_AMOUNTS, FT_STRUCT_STATIC,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,120,PP_PRINT,"","ADTNL_AMOUNTS","P7AddAmntProp"},
{BANK_ICC_DATA, FT_STRUCT_BER,FF_BIN,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"","ICC_DATA","P7ICCDataProp"},
{BANK_ORIG_DATA, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,45,PP_PRINT,"","ORIG_DATA",""},
{BANK_AUTHORIZATION_CYCLE_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","AUTHORIZATION_CYCLE_CODE",""},
{BANK_AUTHOR_INSTITN_ID_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,255,PP_PRINT,"","AUTHOR_INSTITN_ID_CODE",""},
{BANK_GEOGR_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,14,PP_PRINT,"","GEOGR_DATA",""},
{BANK_ADTNL_POS_INFO, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","ADTNL_POS_INFO",""},
{BANK_NET_POS_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","NET_POS_DATA",""},
{BANK_CPS_FIELDS, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","CPS_FIELDS","P7CPSDataProp"},
{BANK_NETWORK_DATA, FT_UNDEF,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","NETWORK_DATA",""},
{BANK_MAC1, FT_UNDEF,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC1",""},
{STD_ISO_BIT_MAP_2, FT_UNDEF,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,0,PP_PRINT,"","RESERVED_ISO",""},
{BANK_STLMNT_CODE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"","STLMNT_CODE",""},
{STD_ISO_EXT_PAYMENT_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"","EXT_PAY_DATA",""},
{BANK_RECEIVER_COUNTRY, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","RECEIVER_COUNTRY",""},
{BANK_STLMNT_INST_COUNTRY, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","STLMNT_INST_COUNTRY",""},
{BANK_NW_MNGMT_INFO, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","NW_MNGMT_INFO",""},
{BANK_MESSAGE_NBR, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","MESSAGE_NBR",""},
{BANK_RECORD_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"","RECORD_DATA",""},
{BANK_ACTION_DATE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"","ACTION_DATE",""},
{BANK_CR_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","CR_NBR",""},
{BANK_CR_REV_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","CR_REV_NBR",""},
{BANK_DB_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","DB_NBR",""},
{BANK_DB_REV_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","DB_REV_NBR",""},
{BANK_TRANSFER_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","TRANSFER_NBR",""},
{BANK_TRANSFER_REV_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","TRANSFER_REV_NBR",""},
{BANK_INQ_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","INQ_NBR",""},
{BANK_AUT_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","AUT_NBR",""},
{BANK_INF_REV_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","INQ_REV_NBR",""},
{BANK_PAYMENT_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","PAYMENT_NBR",""},
{BANK_PAYMENT_REV_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","PAYMENT_REV_NBR",""},
{BANK_FEES_COLLCT_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"","FEES_COLLCT_NBR",""},
{BANK_CR_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_AMOUNT",""},
{BANK_CR_REV_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REV_AMOUNT",""},
{BANK_DB_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_AMOUNT",""},
{BANK_DB_REV_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REV_AMOUNT",""},
{BANK_ADJUST_NBR, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,35,PP_PRINT,"","ADJUST_NBR",""},
{BANK_TRX_RECEIVER_COUNTRY_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRX_RECEIVER_COUNTRY_CODE",""},
{BANK_TRX_ORIGINATOR_COUNTRY_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"","TRX_ORIGINATOR_COUNTRY_CODE",""},
{BANK_TRX_RECEIVER_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","TRX_RECEIVER_ID",""},
{BANK_TRX_ORIGINATOR_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","TRX_ORIGINATOR_ID",""},
{BANK_REPLACEMENT_AMOUNT, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,42,PP_PRINT,"","CARD_ISSUER_REF_DATA",""},
{BANK_KEY_MNG_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,17,PP_PRINT,"","KEY_MNG_DATA",""},
{BANK_NET_AMOUNT, FT_SINGLE,FF_X_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","NET_AMOUNT",""},
{STD_ISO_PAYEE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,25,PP_PRINT,"","PAYEE",""},
{BANK_STLMNT_INSTITN, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","STLMNT_INSTITN",""},
{BANK_RECEIVER_ID, FT_UNDEF,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"","RECEIVER_ID",""},
{BANK_FILE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,17,PP_PRINT,"","FILE_NAME",""},
{BANK_ACCOUNT_ID1, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID1",""},
{BANK_ACCOUNT_ID2, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,28,PP_PRINT,"","ACCOUNT_ID2",""},
{BANK_TRANS_DESC, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"","TRANS_DESC",""},
{BANK_CR_REJ_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REJ_AMOUNT",""},
{BANK_DB_REJ_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REJ_AMOUNT",""},
{BANK_CR_REJ_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","CR_REJ_NUMBER",""},
{BANK_DB_REJ_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,16,PP_PRINT,"","DB_REJ_NUMBER",""},
{BANK_CR_FEES_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,0,PP_PRINT,"","CR_FEES_AMOUNT",""},
{BANK_DB_FEES_AMOUNT, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,0,PP_PRINT,"","DB_FEES_AMOUNT",""},
{BANK_RESERVED_BANK_2, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_SID_2",""},
{BANK_RESERVED_BANK_3, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_SID_3",""},
{BANK_RESERVED_BANK_4, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_SID_4",""},
{BANK_RESERVED_BANK_5, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERVED_SID_5",""},
{BANK_ADTNL_TRACE_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,24,PP_PRINT,"","ADTNL_TRACE_DATA",""},
{STD_ISO_CARD_ISSUER_REF_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","TRANS_FEE",""},
{STD_ISO_NATIONAL_USE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","STLMNT_FEE",""},
{STD_ISO_INTRA_COUNTRY_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","PROCES_FEE",""},
{STD_ISO_RES_NAT_USE_10, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","ADTNL_TRACE_DATA    ",""},
{BANK_ORIG_MSG_TYPE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","ORIG_MSG_TYPE",""},
{BANK_RESERV_NATIONAL_USAGE_6, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERV_NATIONAL_USAGE_6",""},
{BANK_RESERV_PRIV_USAGE_1, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERV_PRIV_USAGE_1",""},
{BANK_ADR_VERIF_DATA, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,29,PP_PRINT,"","ADR_VERIF_DATA",""},
{BANK_RESERV_PRIV_USAGE_3, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","RESERV_PRIV_USAGE_3",""},
{BANK_SUPPORT_INFO, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"","SUPPORT_INFO",""},
{BANK_RESERVED_PRIVE_USAGE_5, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"","RESERVED_PRIVE_USAGE_5",""},
{BANK_FILE_SEC_CODE, FT_UNDEF,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,0,PP_PRINT,"","FILE_SEC_CODE",""},
{BANK_MAC2, FT_SINGLE,FF_BIN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"","MAC2",""},
		},
		"Host3MsgBMInfoProperties",
	},
	"IsoHostMsgProperties", /* szPropertiesName*/
	ISO8583_HOST,			/* nProtocolId */
	E_FIXED_LENGTH,				/* eHeaderType */
	FF_ALPHA_ANS,					/* eHeaderFormat */
	11,							/* nHeaderLen */
};

int InitHostProtocol()
{
	RegisterMsgInfoProp(&IsoHostMsgProperties);
	return OK;
}
/*END PLUTONL-1822*/

