#include <stdio.h>
#include <stdlib.h>
#include <iso_hps.h>
#include <iso3_hps.h>
#include <define.h>
#include <p7_sid.h>

#include <p7_common.h>
#include <p7_globals.h>
#include <iso8583.h>
#include <tlv_privfields.h>



static fld_info_t    tab_IsoFldInfo[] =
{
	{ NOT_USED,  			0					},	/* BIT_MAP1			 */
	{ ISO_LL_ALPHA,			P7_F002_MAX_LEN		},   /* CARD_NBR 			 */
	{ ISO_FIX_ALPHA,		P7_F003_LEN			},	/* PROC_CODE			 */
	{ ISO_FIX_ALPHA,		P7_F004_LEN			},	/* TRANS_AMOUNT			 */
	{ ISO_FIX_ALPHA,		P7_F005_LEN			},	/* STLMNT_AMOUNT		 */
	{ ISO_FIX_ALPHA,		P7_F006_LEN			},	/* Cardholder Billing Amount	 */
	{ ISO_FIX_ALPHA,		P7_F007_LEN			},	/* XMIT_TIME			 */
	{ ISO_FIX_ALPHA,		P7_F008_LEN			},	/* Cardholder Billing Fee	 */
	{ ISO_FIX_ALPHA,		P7_F009_LEN			},	/* CONVRSN_RATE_STLMNT		 */
	{ ISO_FIX_ALPHA,		P7_F010_LEN			},	/* CONVRSN_RATE_CARD_HLDR_BILLING */

	{ ISO_FIX_ALPHA,		P7_F011_LEN			},	/* AUDIT_NBR			 */
	{ ISO_FIX_ALPHA,		P7_F012_LEN			},	/* TRANS_DATE_TIME               */
	{ ISO_FIX_ALPHA,		P7_F013_LEN			},	/* START_EXPIRY_DATE	 */
	{ ISO_FIX_ALPHA,		P7_F014_LEN			},	/* EXPIRY_DATE			 */
	{ ISO_FIX_ALPHA,		P7_F015_LEN			},	/* STLMNT_DATE			 */ 
	{ ISO_FIX_ALPHA,		P7_F016_LEN			},	/* CNVRSN_DATE			 */
	{ ISO_FIX_ALPHA,		P7_F017_LEN			},	/* CAPTURE_DATE			 */
	{ ISO_FIX_ALPHA,		P7_F018_LEN			},	/* MERCHANT_TYPE		 */
	{ ISO_FIX_ALPHA,		P7_F019_LEN			},	/* ACQR_COUNTRY			 */
	{ ISO_FIX_ALPHA,		P7_F020_LEN			},	/* PAN_COUNTRY			 */

	{ ISO_FIX_ALPHA,		P7_F021_LEN			},	/* FORWD_COUNTRY		 */
	{ ISO_FIX_ALPHA,		P7_F022_LEN			},	/* POS_ENTRY_MODE		 */
	{ ISO_FIX_ALPHA,		P7_F023_LEN			},	/* Card Sequence Number		 */
	{ ISO_FIX_ALPHA,		P7_F024_LEN			},	/* Function Code                 */
	{ ISO_FIX_ALPHA,		P7_F025_LEN			},	/* POS_CONDITION		 */
	{ ISO_FIX_ALPHA,		P7_F026_LEN			},	/* MERCHANT TYPE  		 */
	{ ISO_FIX_ALPHA,		P7_F027_LEN			},	/* Authorization Id Response Lenght */
	{ ISO_FIX_ALPHA,		P7_F028_LEN			},	/* TRANS_FEE			 */
	{ ISO_FIX_ALPHA,		P7_F029_LEN			},	/* Amount Settlement Fee	 */
	{ ISO_LL_ALPHA,			P7_F030_LEN			},	/* Amount Transaction Processing Fee */

	{ ISO_LL_ALPHA,			P7_F031_MAX_LEN		},	/* Amount Setlmnt Processing Fee */
	{ ISO_LL_ALPHA,			P7_F032_MAX_LEN		},	/* ACQR_ID			 */
	{ ISO_LL_ALPHA,			P7_F033_MAX_LEN		},	/* FORWD_ID			 */
	{ ISO_LL_ALPHA,			P7_F034_MAX_LEN		},	/* PAN_EXTENDED			 */
	{ ISO_LL_ALPHA,			P7_F035_MAX_LEN		},	/* T2_DATA			 */
	{ ISO_LLL_ALPHA,		P7_F036_MAX_LEN		},	/* T1_DATA                       */
	{ ISO_FIX_ALPHA,		P7_F037_LEN			},	/* REFERENCE_NBR		 */
	{ ISO_FIX_ALPHA,		P7_F038_LEN			},	/* AUTHOR_ID			 */
	{ ISO_FIX_ALPHA,		P7_F039_LEN			},	/* ACTION CODE  		 */
	{ ISO_FIX_ALPHA,		P7_F040_LEN			},	/* Service Restriction Code	 */

	{ ISO_FIX_ALPHA,		P7_F041_LEN			},	/* TERMINAL_NBR			 */
	{ ISO_FIX_ALPHA,		P7_F042_LEN			},	/* OUTLET_NBR			 */
	{ ISO_LLL_ALPHA,		P7_F043_MAX_LEN		},	/* TERMINAL_ADR			 */
	{ ISO_LLL_ALPHA,		P7_F044_MAX_LEN		},	/* ADTNL_RESP_DATA		 */
	{ ISO_LL_ALPHA,			P7_F045_MAX_LEN		},	/* T1_DATA			 */
	{ ISO_LLL_ALPHA,		P7_F046_MAX_LEN		},	/* Additrional Data Iso		 */
	{ ISO_LLL_ALPHA,		P7_F047_MAX_LEN		},	/* Additrional Data National	 */
	{ ISO_LLL_ALPHA,		P7_F048_MAX_LEN		},	/* ADTNL_DATA_PRIV		 */
	{ ISO_FIX_ALPHA,		P7_F049_LEN			},	/* TRANS_CRNCY			 */
	{ ISO_FIX_ALPHA,		P7_F050_LEN			},	/* STLMNT_CRNCY			 */

	{ ISO_FIX_ALPHA,		P7_F051_LEN			},	/* BILLING_CRNCY		 */
	{ ISO_FIX_ALPHA,		P7_F052_LEN			},	/* PIN_DATA			 */
	{ ISO_LL_ALPHA,			P7_F053_MAX_LEN		},	/* SECURITY_DATA		 */
	{ ISO_LLL_ALPHA,		P7_F054_MAX_LEN		},	/* ADTNL_AMOUNTS		 */
	{ ISO_LLL_BIN,			P7_F055_MAX_LEN		},	/* ICC Information               */
	{ ISO_LL_ALPHA,			P7_F056_MAX_LEN		},	/* Orig Data Elements            */
	{ ISO_FIX_ALPHA,		P7_F057_LEN			},	/* Reserved National		 */
	{ ISO_LL_ALPHA,			P7_F058_MAX_LEN		},	/* Reserved National		 */
	{ ISO_LLL_ALPHA,		P7_F059_MAX_LEN		},	/* GEOGR_DATA			 */
	{ ISO_LLL_ALPHA,		P7_F060_MAX_LEN		},	/* ADTNL_POS_INFO		 */

	{ ISO_LLL_ALPHA,		P7_F061_MAX_LEN		},	/* NETWORK POS DATA		 */
	{ ISO_LLL_ALPHA, 		P7_F062_MAX_LEN		},	/* Redemption Number		 */
	{ ISO_LLL_ALPHA, 		P7_F063_MAX_LEN		},	/* Versions       		 */
	{ NOT_USED,				P7_F064_LEN			},	/* MAC1				 */
	{ NOT_USED,				P7_F065_LEN			},	/* 				 */
	{ ISO_LLL_ALPHA,		P7_F066_LEN			},	/* STLMNT_CODE			 */
	{ ISO_FIX_ALPHA,		P7_F067_LEN			},	/* Extended Payment Code	*/
	{ ISO_FIX_ALPHA,		P7_F068_LEN			},	/* RECEIVER_COUNTRY		 */
	{ ISO_FIX_ALPHA,		P7_F069_LEN			},	/* STLMNT_INST_COUNTRY		 */
	{ ISO_FIX_ALPHA,		P7_F070_LEN			},	/* NW_MNGMT_INFO		 */

	{ ISO_FIX_ALPHA,		P7_F071_LEN			},	/* Message Number		 */
	{ ISO_LLL_ALPHA,		P7_F072_MAX_LEN		},	/* Data Record        		 */
	{ ISO_FIX_ALPHA,		P7_F073_LEN			},	/* ACTION_DATE			 */
	{ ISO_FIX_ALPHA,		P7_F074_LEN			},	/* CR_NBR			 */
	{ ISO_FIX_ALPHA,		P7_F075_LEN			},	/* CR_REV_NBR			 */
	{ ISO_FIX_ALPHA,		P7_F076_LEN			},	/* DB_NBR			 */
	{ ISO_FIX_ALPHA,		P7_F077_LEN			},	/* DB_REV_NBR			 */
	{ ISO_FIX_ALPHA,		P7_F078_LEN			},	/* Transfer Number		 */
	{ ISO_FIX_ALPHA,		P7_F079_LEN			},	/* Transfer Reversal Number	 */
	{ ISO_FIX_ALPHA,		P7_F080_LEN			},	/* Inquiries Number		 */

	{ ISO_FIX_ALPHA,		P7_F081_LEN			},	/* Authorizations Number	 */
	{ ISO_FIX_ALPHA,		P7_F082_LEN			},	/* Credit, Processing Fee Amount */
	{ ISO_FIX_ALPHA,		P7_F083_LEN			},	/* Payment Number                 */
	{ ISO_FIX_ALPHA,		P7_F084_LEN			},	/* Payment Reversal Number     	 */
	{ ISO_FIX_ALPHA,		P7_F085_LEN			},	/* Debit, Transaction Fee Amount */
	{ ISO_FIX_ALPHA,		P7_F086_LEN			},	/* CR_AMOUNT			 */
	{ ISO_FIX_ALPHA,		P7_F087_LEN			},	/* CR_REV_AMOUNT		 */
	{ ISO_FIX_ALPHA,		P7_F088_LEN			},	/* DB_AMOUNT			 */
	{ ISO_FIX_ALPHA,		P7_F089_LEN			},	/* DB_REV_AMOUNT		 */
	{ ISO_FIX_ALPHA,		P7_F090_LEN			},	/* ORIG_DATA			 */

	{ ISO_FIX_ALPHA,		P7_F091_LEN			},	/* FILE_UPDATE			 */
	{ ISO_FIX_ALPHA,		P7_F092_LEN			},	/* FILE_SECURITY		 */
	{ ISO_LL_ALPHA,			P7_F093_MAX_LEN		},	/* Destination Inst ID Code      */
	{ ISO_LL_ALPHA,			P7_F094_MAX_LEN		},	/* Source Inst Id Code           */
	{ ISO_LL_ALPHA,			P7_F095_MAX_LEN		},	/* REPLACE_AMOUNTS		 */
	{ ISO_LLL_ALPHA,		P7_F096_MAX_LEN		},	/* Additional Key Mngmt data     */
	{ ISO_FIX_ALPHA,		P7_F097_LEN			},	/* NET_AMOUNT			 */
	{ ISO_FIX_ALPHA,		P7_F098_LEN			},	/* Payee			 */
	{ ISO_LL_ALPHA,			P7_F099_MAX_LEN		},	/* STLMNT_INSTITN		 */
	{ ISO_LL_ALPHA,			P7_F100_MAX_LEN		},	/* RECEIVER_ID			 */

	{ ISO_LL_ALPHA,			P7_F101_MAX_LEN		},	/* FILE_NAME			 */
	{ ISO_LL_ALPHA,			P7_F102_MAX_LEN		},	/* ACCOUNT_ID1			 */
	{ ISO_LL_ALPHA,			P7_F103_MAX_LEN		},	/* ACCOUNT_ID2			 */
	{ ISO_LLL_ALPHA,		P7_F104_MAX_LEN		},	/* Transaction Description	 */
	{ ISO_FIX_ALPHA,		P7_F105_LEN			},	/* Reserved Iso			 */
	{ ISO_FIX_ALPHA,		P7_F106_LEN			},	/* Reserved Iso			 */
	{ ISO_FIX_ALPHA,		P7_F107_LEN			},	/* Reserved Iso			 */
	{ ISO_FIX_ALPHA,		P7_F108_LEN			},	/* Reserved Iso			 */
	{ ISO_LL_ALPHA,			P7_F109_MAX_LEN		},	/* Reserved Iso			 */
	/*{ ISO_LL_ALPHA,			P7_F110_MAX_LEN		},*/	/* Reserved Iso			 */
	{ ISO_LLL_BIN,			999		},			/* PPWM uses this field to store ICC data */

	{ ISO_LLL_ALPHA,		P7_F111_MAX_LEN		},	/* Reserved Iso			 */
	{ ISO_LLL_ALPHA,		999		},	/* Reserved National		ABE20072023  999 au lieu de P7_F112_MAX_LEN */
	{ ISO_LLL_ALPHA,		P7_F113_MAX_LEN		},	/* Reserved National		 */
	{ ISO_LLL_ALPHA,		P7_F114_MAX_LEN		},	/* Reserved National		 */
	{ ISO_LLL_ALPHA,		P7_F115_MAX_LEN		},	/* ADTNL_TRACE_DATA		 */
	{ ISO_LLL_ALPHA,		P7_F116_MAX_LEN		},	/* Reserved National		 */
	{ ISO_LLL_ALPHA,		P7_F117_MAX_LEN		},	/* Reserved National		 */
	{ ISO_LLL_ALPHA,		P7_F118_MAX_LEN		},	/* Intra Country Data		 */
	{ ISO_LLL_ALPHA,		P7_F119_MAX_LEN		},	/* Reserved National		 */
	{ ISO_LLL_ALPHA,		P7_F120_MAX_LEN		},	/* Original Message Type Id	 */

	{ ISO_LLL_ALPHA,		P7_F121_MAX_LEN		},	/* Issuing Institution Id	 */
	{ ISO_LLL_ALPHA,		P7_F122_MAX_LEN		},	/* Remaining Open to Use	 */
	{ ISO_LLL_ALPHA,		P7_F123_MAX_LEN		},	/* ADR_VERIF_DATA		 */
	{ ISO_LLL_ALPHA,		P7_F124_MAX_LEN		},	/* Free Form Text - Japan	 */
	{ ISO_LLL_ALPHA,		P7_F125_MAX_LEN		},	/* SUPPORT_INFO			 */
	{ ISO_LLL_ALPHA,		P7_F126_MAX_LEN		},	/* Reserved Private		 */
	{ ISO_LLL_ALPHA,		P7_F127_MAX_LEN		},	/* File Record Action and Data	 */
	{ ISO_FIX_BIN,			P7_F128_LEN			},	/* MAC2				 */

};

static tag_info_t  tab_IsoTagInfo[] = 
{
	{ "5700",ISO_TAG_VAR_HEX , 0},/* Track 2 Equivalent Data               */ /*SWI01122008 Enh Visa iCVV Mandate*/
	{ "7100",ISO_TAG_VAR_HEX , 0},/* Issuer Script Template 1              */
	{ "7200",ISO_TAG_VAR_HEX , 0},/* Issuer Script Template 2              */
	{ "8600",ISO_TAG_VAR_HEX , 0},/* Issuer Script command                 */
	{ "8200",ISO_TAG_VAR_HEX , 0},/* Application Interchange Profile       */
	{ "8400",ISO_TAG_VAR_HEX , 0},/* Dedicated File Name                   */
	{ "4F00",ISO_TAG_VAR_HEX , 0},/* ICC Application Id                    */
	{ "8A00",ISO_TAG_VAR_HEX , 0},/* Authorization Response Code           */
	{ "9500",ISO_TAG_VAR_HEX , 0},/* Terminal Verification Results         */
	{ "9A00",ISO_TAG_VAR_HEX , 0},/* Transaction Date                      */
	{ "9C00",ISO_TAG_VAR_HEX , 0},/* Transaction TYPE                      */
	{ "5F24",ISO_TAG_VAR_HEX , 0},/* Application expiry date               *//*SNO301115*/
	{ "5F2A",ISO_TAG_VAR_HEX , 0},/* Transaction Currency Code             */
	{ "5F34",ISO_TAG_VAR_HEX , 0},/* PAN Sequence Numnber                  */
	{ "9F02",ISO_TAG_VAR_HEX , 0},/* Transaction Amount                    */
	{ "9F03",ISO_TAG_VAR_HEX , 0},/* Other Amount                          */
	{ "9F09",ISO_TAG_VAR_HEX , 0},/* Terminal Application Version Number   */
	{ "9F0A",ISO_TAG_VAR_HEX , 0},/* Application Selection Registered Proprietary Data */ /* MTR - Enh 4.11 */
	{ "9F10",ISO_TAG_VAR_HEX , 0},/*  Issuer Application Data              */
	{ "9F1A",ISO_TAG_VAR_HEX , 0},/* Terminal Country Code                 */
	{ "9F1E",ISO_TAG_VAR_ALPHA , 0},/* Interface Device Serial Number        */
	{ "9F26",ISO_TAG_VAR_HEX , 0},/* Application cryptogram                */
	{ "9F27",ISO_TAG_VAR_HEX , 0},/* Cryptogram Information Data           */
	{ "9F33",ISO_TAG_VAR_HEX , 0},/* Terminal Capabilities                 */
	{ "9F34",ISO_TAG_VAR_HEX , 0},/* Cardholder Verification Method        */
	{ "9F35",ISO_TAG_VAR_HEX , 0},/* Terminal Type                         */
	{ "9F36",ISO_TAG_VAR_HEX , 0},/* Application Transaction Counter       */
	{ "9F37",ISO_TAG_VAR_HEX , 0},/* Unpredictable Number                  */
	{ "9F41",ISO_TAG_VAR_HEX , 0},/* Transaction Sequence Number           */
	{ "9F53",ISO_TAG_VAR_HEX , 0},/* Transaction Category Code             */
	{ "9100",ISO_TAG_VAR_HEX , 0},/* Issuer Authentication Data            */
	{ "9F54",ISO_TAG_VAR_HEX , 0},/* Application cryptogram  ARPC          */
	/***********LHI 25 08 2006**********************************************/
   { "5A00",ISO_TAG_VAR_HEX , 0},/* Application PAN		TBO	  */
	{ "9F06",ISO_TAG_VAR_HEX , 0},  /* Application Identifier   		  */
	{ "9F12",ISO_TAG_VAR_ALPHA , 0},/* Application Prefered Name		  */
	{ "5700",ISO_TAG_VAR_HEX , 0}, /* Application Track2   	  	  */
   { "8C00",ISO_TAG_VAR_HEX , 0},/* Security Attributes 	TBO 	  */
	{ "5000",ISO_TAG_VAR_ALPHA , 0}, /*  Application Label 	 	  */ 
	/****END LHI************************************************************/
	{ "5000",ISO_TAG_VAR_ALPHA , 0},		/*  Application Label 	 									*/ 

	{ "8E00",ISO_TAG_VAR_HEX , 0},		/* CVM list (Cardholder Verification Method list) */
	{ "5F25",ISO_TAG_VAR_HEX , 0},		/* Application effective date	*/
	{ "9F07",ISO_TAG_VAR_HEX , 0},		/* Application usage control	*/
	{ "9F0D",ISO_TAG_VAR_HEX , 0},		/* Issuer action code default	*/
	{ "9F0E",ISO_TAG_VAR_HEX , 0},		/* Issuer action code denial	*/
	{ "9F0F",ISO_TAG_VAR_HEX , 0},		/* Issuer action code on-line	*/
	{ "9F5B",ISO_TAG_VAR_HEX , 0},		/* Issuer script results		*/

    { "9F6E", ISO_TAG_VAR_HEX , 0},		/* ISO_TAG_FFI */ /*SWI06032016 ENH15.1*/
	{ "9F7C", ISO_TAG_VAR_HEX , 0},

	{ "9F33", ISO_TAG_VAR_HEX , 0},
	{ "C000", ISO_TAG_VAR_HEX , 0},
	{ "9F1F", ISO_TAG_VAR_HEX , 0},

	{ "DF68", ISO_TAG_VAR_HEX , 0},		/*  Kernel ID utilise										*/
	{ "DF80", ISO_TAG_VAR_HEX , 0},		/*  Resultats des traitements effectues sur le microcircuit */
	{ "DF81", ISO_TAG_VAR_HEX , 0},		/*  Type d'application carte								*/
	{ "DF85", ISO_TAG_VAR_HEX , 0},		/*  Resultat du Traitement du Terminal (RTT)				*/
	{ "DF86", ISO_TAG_VAR_HEX , 0},		/*  Dispositif sans contact									*/
	{ "DFC0", ISO_TAG_VAR_HEX , 0},		/*  Mode d'acquisition EMV									*/
	{ "DFD0", ISO_TAG_VAR_HEX , 0},		/*  Card Authentication Results Code						*/
	{ "5F24", ISO_TAG_VAR_HEX , 0}, 	/* APPLICATION EXPIRATION DATE */ /* MTR Enh4.12 */
};

/*Start AMER20190219 PROD00065991: VISA Enh19.Q2 Art2.4*/
#define P7_F048_P21_NB_FIELDS		25 /*3*/		/*AMER20190228 PROD00066569: Enh5.00 1070*/     /*6-->8 IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/ /* 8 --> 18 PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	/* 18 --> 19 start SDR20230714 PLUTONL-6643 Enh23Q4 VISA Art 3.5*/ /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
static const TlvInfoProperties	ISSPayFacDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_F048_P21_NB_FIELDS,
{
{P7_F048P21_PAYFAC_ID, 						FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,11,PP_PRINT,"NULL","PAY_FAC_ID","NULL",NOT_REPEATABLE},
{P7_F048P21_ISO_ID, 						FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,11,PP_PRINT,"NULL","ISO_ID","NULL",NOT_REPEATABLE},
{P7_F048P21_SUB_MER_ID, 					FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,15,PP_PRINT,"NULL","SUB_MER_ID","NULL",NOT_REPEATABLE},
{P7_F048P21_MARKET_PLACE_ID, 				FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,11,PP_PRINT,"NULL","MARKET_PLACE_ID","NULL",NOT_REPEATABLE},	/*AMER20190228 PROD00066569: Enh5.00 1070*/
{P7_F048P21_MERCHANT_ID, 					FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,15,PP_PRINT,"NULL","MERCHANT_ID","NULL",NOT_REPEATABLE},
{P7_F048P21_MERCHANT_ORIGINE_COUNTRY, 		FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","MERCHANT_ORIGINE_COUNTRY","NULL",NOT_REPEATABLE},/* HAL25022021 PLUTONL-2632 ART 4224 2021.Q2 */																																																		
{P7_F048P21_ACC_LEGAL_BUSINESS_NAME, 		FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,25,PP_PRINT,"NULL","ACCEPTOR LEGAL BUSINESS NAME","NULL",NOT_REPEATABLE},    /*ZKO 05042022 PLUTONL-4550 ENH 22.Q2 VISA Art3.2*//*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{P7_F048P21_PAY_FACILITATOR_NAME, 			FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,25,PP_PRINT,"NULL","SUB_MPAY_FACILITATOR_NAMEER_ID","NULL",NOT_REPEATABLE},  /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{P7_F048P21_MCI_MSG_FORMAT_VERSION_CODE, 	FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","MCI_MSG_FORMAT_VERSION_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_STREET_ADDR, 				FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,48,PP_PRINT,"NULL","ACC_STREET_ADDR","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_CTRY_SUB_CODE, 				FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","ACC_CTRY_SUB_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_URL_ADDR, 					FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,255,PP_PRINT,"NULL","ACC_URL_ADDR","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_CUSTOMER_SERVICE_PHONE_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"NULL","ACC_CUSTOMER_SERVICE_PHONE_NBR","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_PHONE_NBR, 					FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"NULL","ACC_PHONE_NBR","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_ADD_CONTACT_INFO, 			FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"NULL","ACC_ADD_CONTACT_INFO","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_TAX_ID, 					FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,25,PP_PRINT,"NULL","ACC_TAX_ID","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_PARTNER_ID, 				FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,21,PP_PRINT,"NULL","ACC_PARTNER_ID","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_ACC_POSTAL_CODE, 				FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,6,PP_PRINT,"NULL","ACC_POSTAL_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-5548   AN6022  Enh 2023Q2 AHA20221221*/	
{P7_F048P21_PAYFAC_STREET_ADDR, 			FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,99,PP_PRINT,"NULL","PAYFAC_STREET_ADDR","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{P7_F048P21_PAYFAC_CITY_NAME,				FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,50,PP_PRINT,"NULL","PAYFAC_CITY_NAME","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{P7_F048P21_PAYFAC_STATE_CODE, 				FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","PAYFAC_STATE_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{P7_F048P21_PAYFAC_POSTAL_CODE, 			FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","PAYFAC_POSTAL_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{P7_F048P21_PAYFAC_CTRY_CODE,				FT_SINGLE,FF_ALPHA_A,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","PAYFAC_CTRY_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
},
"ISSPayFacDataProp"
};

/******************************************************************************/
void IniIsoPayFacDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &ISSPayFacDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
/*End AMER20190219 PROD00065991: VISA Enh19.Q2 Art2.4*/

#define P7_F048_S20_NB_FIELDS		42 /*HAL15072020 PLUTONL-2111 ENHS 20.Q4 ART4022 from 32 to 34*/ /*AEA20210712 Enh21.Q4 Art2.9*/    /*35-->42 IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/

static const TlvInfoProperties	ISSMoneyTransferDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_F048_S20_NB_FIELDS,
{
{P7_F048S20_PAYMENT_TYPE, 	FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","PAYMENT_TYPE","NULL",NOT_REPEATABLE},
{P7_F048S20_FUNDS_SOURCE, 	FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","FUNDS_SOURCE","NULL",NOT_REPEATABLE},
{P7_F048S20_TRX_REF_NBR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","SENDER_REF_NBR","NULL",NOT_REPEATABLE},
{P7_F048S20_SENDER_ACCOUNT_NO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","SENDER_ACCOUNT_NO","NULL",NOT_REPEATABLE},
{P7_F048S20_SENDER_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,48,PP_PRINT,"NULL","SENDER_NAME","NULL",NOT_REPEATABLE},
{P7_F048S20_SENDER_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,60,PP_PRINT,"NULL","SENDER_STREET_ADDR","NULL",NOT_REPEATABLE},
{P7_F048S20_SENDER_CITY_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","SENDER_CITY_NAME","NULL",NOT_REPEATABLE},
{P7_F048S20_SENDER_STATE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","SENDER_STATE","NULL",NOT_REPEATABLE},
{P7_F048S20_SENDER_COUNTRY, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","SENDER_COUNTRY","NULL",NOT_REPEATABLE},
{P7_F048S20_SENDER_PHONE_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,20,PP_PRINT,"NULL","SENDER_PHONE_NBR","NULL",NOT_REPEATABLE},
{P7_F048S20_SENDER_DOB, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","SENDER_DOB","NULL",NOT_REPEATABLE},
{P7_F048S20_MESSAGE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,64,PP_PRINT,"NULL","MESSAGE","NULL",NOT_REPEATABLE},
{P7_F048S20_RECIPIENT_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,48,PP_PRINT,"NULL","RECIPIENT_NAME","NULL",NOT_REPEATABLE},
{ P7_F048S20_SENDER_FIRST_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","SENDER_FIRST_NAME","NULL",NOT_REPEATABLE},
{ P7_F048S20_SENDER_MIDDLE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","SENDER_MIDDLE_NAME","NULL",NOT_REPEATABLE},
{ P7_F048S20_SENDER_LAST_NAME , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","SENDER_LAST_NAME","NULL",NOT_REPEATABLE},
{ P7_F048S20_SENDER_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","SENDER_POSTAL_CODE","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_FIRST_NAME  , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_FIRST_NAME","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_MIDDLE_NAME      , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_MIDDLE_NAME","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_LAST_NAME        , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_LAST_NAME ","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_STREET_ADDR    , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_STREET_ADDR","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_CITY_NAME , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_CITY_NAME","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_STATE  , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_STATE ","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_COUNTRY   , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_COUNTRY","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_POSTAL_COD","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_PHONE_NUMBER, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_PHONE_NUMBER","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_DOB, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECIPIENT_DOB","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_ACCOUNT_NUMBER , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,50,PP_PRINT,"NULL","RECIPIENT_ACCOUNT_NUMBER","NULL",NOT_REPEATABLE},/*HAL15072020 PLUTONL-2111 ENHS 20.Q4 ART4022*/
{ P7_F048S20_SENDER_ID   , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,30,PP_PRINT,"NULL","SENDER_ID","NULL",NOT_REPEATABLE},
{ P7_F048S20_LANGUAGE_ID  , FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","LANGUAGE_ID","NULL",NOT_REPEATABLE},
{ P7_F048S20_ADD_SENDER_DATA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","ADD_SENDER_DATA","NULL",NOT_REPEATABLE},
{ P7_F048S20_IBAN, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","IBAN","NULL",NOT_REPEATABLE},
{ P7_F048S20_RECIPIENT_ACCOUNT_TYPE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","RECIPIENT_ACCOUNT_NUMBER_TYPE","NULL",NOT_REPEATABLE},/*HAL15072020 PLUTONL-2111 ENHS 20.Q4 ART4022*/
{ P7_F048S20_SENDER_ACCOUNT_TYPE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","SENDER_ACCOUNT_NUMBER_TYPE","NULL",NOT_REPEATABLE},	  /*HAL15072020 PLUTONL-2111 ENHS 20.Q4 ART4022*/
{ P7_F048S20_PAYMENT_PURPOSE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LL,LU_BYTE,36/*12*/,PP_PRINT,"NULL","PAYMENT_PURPOSE","NULL",NOT_REPEATABLE},/*PLUTONL-4280 :Enh5.03 :1368*/	/*AEA20210712 Enh21.Q4 Art2.9*/
{ P7_F048S20_SENDER_ID_TYPE_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","SENDER_ID_TYPE_CODE","NULL",NOT_REPEATABLE}, /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{ P7_F048S20_SENDER_ID_SUBTYPE_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","SENDER_ID_SUBTYPE_CODE","NULL",NOT_REPEATABLE}, /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{ P7_F048S20_SENDER_ID_ISS_CNTRY_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","SENDER_ID_ISS_CNTRY_CODE","NULL",NOT_REPEATABLE}, /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{ P7_F048S20_RECEIVER_ID_TYPE_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECEIVER_ID_TYPE_CODE","NULL",NOT_REPEATABLE}, /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{ P7_F048S20_RECEIVER_ID_SUBTYPE_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECEIVER_ID_SUBTYPE_CODE","NULL",NOT_REPEATABLE}, /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{ P7_F048S20_RECEIVER_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECEIVER_ID","NULL",NOT_REPEATABLE}, /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{ P7_F048S20_RECEIVER_ID_ISS_COUNTRY_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,36,PP_PRINT,"NULL","RECEPIENT_ID_ISS_COUNTRY_CODE","NULL",NOT_REPEATABLE}, /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
},
"ISSMoneyTransferDataProp"
};

/******************************************************************************/
void IniIsoMoneyTransDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &ISSMoneyTransferDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
#define P7_CB_DATA_NB_FIELDS			26

static const TlvInfoProperties	CBDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_CB_DATA_NB_FIELDS,
{
{CB_FIELD_ERROR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","FIELD_ERROR","NULL",NOT_REPEATABLE},
{CB_FIELD_CONV, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","FIELD_CONV","NULL",NOT_REPEATABLE},
{CB_CVV_CTRL_RESULT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","CVV_CTRL_RESULT","NULL",NOT_REPEATABLE},
{CB_REASON_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","REASON_CODE","NULL",NOT_REPEATABLE},
{CB_TRX_ENV, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","TRX_ENV","NULL",NOT_REPEATABLE},
{CB_INVOICE_TYPE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","INVOICE_TYPE","NULL",NOT_REPEATABLE},
{CB_AUT_FORCING_CD, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","AUT_FORCING_CD","NULL",NOT_REPEATABLE},
{CB_SA_GEN_TRX_NO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","SA_GEN_TRX_NO","NULL",NOT_REPEATABLE},
{CB_TRX_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","TRX_ID","NULL",NOT_REPEATABLE},
{CB_SIRET_NUMBER, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","SIRET_NUMBER","NULL",NOT_REPEATABLE},
{CB_SITE_TYPE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","SITE_TYPE","NULL",NOT_REPEATABLE},
{CB_ACCEPTOR_CONTRACT_NO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","ACCEPTOR_CONTRACT_NO","NULL",NOT_REPEATABLE},
{CB_SA_ARCH, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","SA_ARCH","NULL",NOT_REPEATABLE},
{CB_APP_STATUS, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","APP_STATUS","NULL",NOT_REPEATABLE},
{CB_TASA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","TASA","NULL",NOT_REPEATABLE},
{CB_IDPA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","IDPA","NULL",NOT_REPEATABLE},
{CB_IDSA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","IDSA","NULL",NOT_REPEATABLE},
{CB_PA_LOGICAL_NO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","PA_LOGICAL_NO","NULL",NOT_REPEATABLE},
{CB_SA_LOGICAL_NO, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","SA_LOGICAL_NO","NULL",NOT_REPEATABLE},
{CB_ITP_PA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","ITP_PA","NULL",NOT_REPEATABLE},
{CB_ITP_SA, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","ITP_SA","NULL",NOT_REPEATABLE},
{CB_TAC_DEFAULT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","TAC_DEFAULT","NULL",NOT_REPEATABLE},
{CB_TAC_DENIAL, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","TAC_DENIAL","NULL",NOT_REPEATABLE},
{CB_TAC_ONLINE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","TAC_ONLINE","NULL",NOT_REPEATABLE},
{CB_ACCEPT_CERT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","ACCEPT_CERT","NULL",NOT_REPEATABLE},
{CB_CARD_APP_TYPE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,100,PP_PRINT,"NULL","CARD_APP_TYPE","NULL",NOT_REPEATABLE},

},
"CBDataProp"
};

/******************************************************************************/
void IniCBDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &CBDataProp;
	ResetTlvInfo(pkTlvInfo);
}

/******************************************************************************/
#define P7_TKN_DATA_NB_FIELDS			15	 /*14-->15 IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art2.2*/	

static const TlvInfoProperties	TknDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_TKN_DATA_NB_FIELDS,
{

{P7_F048P55_TOKEN, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,19,PP_PRINT,"NULL","TOKEN","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_REF_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","TKN_REF_ID","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_REQ_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,24,PP_PRINT,"NULL","TKN_REQ_ID","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_ASSURANCE_LVL, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","TKN_ASSURANCE_LVL","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_STATUS, FT_SINGLE,FF_ALPHA_A,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","TKN_STATUS","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_EXP_DT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,4,PP_PRINT,"NULL","TKN_EXP_DT","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","TKN_TYPE","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_DEVICE_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","TKN_DEVICE_TYPE","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_PAN, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,19,PP_PRINT,"NULL","TKN_PAN","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_PAN_SEQ_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","TKN_PAN_SEQ_NBR","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_PAN_STATUS, FT_SINGLE,FF_ALPHA_A,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","TKN_PAN_STATUS","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_PAN_EXP_DT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,4,PP_PRINT,"NULL","TKN_PAN_EXP_DT","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_PAN_REF_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","TKN_PAN_REF_ID","NULL",NOT_REPEATABLE},
{P7_F048P55_TKN_PAN_ISSUER_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,6,PP_PRINT,"NULL","TKN_PAN_ISSUER_ID","NULL",NOT_REPEATABLE},
{P7_F048P55_AUTO_FILL, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","AUTO_FILL","NULL",NOT_REPEATABLE},	/*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art2.2*/	
},
"TknDataProp"
};

/******************************************************************************/
void IniTknDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &TknDataProp;
	ResetTlvInfo(pkTlvInfo);
}

/******************************************************************************/
#define P7_DIGIT_DATA_NB_FIELDS			25

static const TlvInfoProperties	DigitDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_DIGIT_DATA_NB_FIELDS,
{

{P7_F048S25_PAN_SOURCE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","PAN_SOURCE","NULL",NOT_REPEATABLE},
{P7_F048S25_PAY_APP_INSTANCE_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,48,PP_PRINT,"NULL","PAY_APP_INSTANCE_ID","NULL",NOT_REPEATABLE},
{P7_F048S25_NBR_ACTIVE_TKNS, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NBR_ACTIVE_TKNS","NULL",NOT_REPEATABLE},
{P7_F048S25_TKN_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","TKN_TYPE","NULL",NOT_REPEATABLE},
{P7_F048S25_DEVICE_SRC_IP_ADR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","DEVICE_SRC_IP_ADR","NULL",NOT_REPEATABLE},
{P7_F048S25_WP_TKN_RECMD, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","WP_TKN_RECMD","NULL",NOT_REPEATABLE},
{P7_F048S25_WP_TKN_RECMD_VERSION, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","WP_TKN_RECMD_VERSION","NULL",NOT_REPEATABLE},
{P7_F048S25_WP_DEVICE_SCORE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","WP_DEVICE_SCORE","NULL",NOT_REPEATABLE},/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
{P7_F048S25_WP_ACCOUNT_SCORE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","WP_ACCOUNT_SCORE","NULL",NOT_REPEATABLE},/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
{P7_F048S25_DEVICE_LOCATION, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,9,PP_PRINT,"NULL","DEVICE_LOCATION","NULL",NOT_REPEATABLE},
{P7_F048S25_MOB_NBR_LAST_DIGITS, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,4,PP_PRINT,"NULL","MOB_NBR_LAST_DIGITS","NULL",NOT_REPEATABLE},
{P7_F048S25_ACTIVATION_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,8,PP_PRINT,"NULL","ACTIVATION_CODE","NULL",NOT_REPEATABLE},
{P7_F048S25_ACTIVATION_CODE_EXP_DT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","ACTIVATION_CODE_EXP_DT","NULL",NOT_REPEATABLE},
{P7_F048S25_CSMR_ACTIV_METHD_PREF, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,165,PP_PRINT,"NULL","CSMR_ACTIV_METHD_PREF","NULL",NOT_REPEATABLE},
{P7_F048S25_DEVICE_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,20,PP_PRINT,"NULL","DEVICE_NAME","NULL",NOT_REPEATABLE},
{P7_F048S25_FINAL_TKN_DECISION, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","FINAL_TKN_DECISION","NULL",NOT_REPEATABLE},
{P7_F048S25_FINAL_TKN_DECISION_IND, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","FINAL_TKN_DECISION_IND","NULL",NOT_REPEATABLE},
{P7_F048S25_TC_IDENTIFIER, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","TC_IDENTIFIER","NULL",NOT_REPEATABLE},
{P7_F048S25_TC_DT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","TC_DT","NULL",NOT_REPEATABLE},
{P7_F048S25_TKN_UNQ_REF, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,48,PP_PRINT,"NULL","TKN_UNQ_REF","NULL",NOT_REPEATABLE},
{P7_F048S25_PAN_UNQ_REF, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,48,PP_PRINT,"NULL","PAN_UNQ_REF","NULL",NOT_REPEATABLE},
{P7_F048S25_TKN_EVENT_IND, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","TKN_EVENT_IND","NULL",NOT_REPEATABLE},
{P7_F048S25_TKN_EVENT_RSN_CODE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","TKN_EVENT_RSN_CODE","NULL",NOT_REPEATABLE},
{P7_F048S25_EVENT_REQUESTOR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","EVENT_REQUESTOR","NULL",NOT_REPEATABLE},
{P7_F048S25_TKN_DATA_ACTV_MTHD, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,283,PP_PRINT,"NULL","TKN_DATA_ACTV_MTHD","NULL",NOT_REPEATABLE},

},
"DigitDataProp"
};

/******************************************************************************/
void IniDigitDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &DigitDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
#define P7_SALE_INFO_DATA_NB_FIELDS			23	/*AMER20190313 PROD00066569: Enh5.00 1073: 19 -> 22*/  /*  22->23 PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/

static const TlvInfoProperties	SaleInfoDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_SALE_INFO_DATA_NB_FIELDS,
{
{P7_F048S22_BILLING_POSTAL_CODE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","BILLING_POSTAL_CODE","NULL",NOT_REPEATABLE},
{P7_F048S22_BILLING_ADDRESS, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,40,PP_PRINT,"NULL","BILLING_ADDRESS","NULL",NOT_REPEATABLE},
{P7_F048S22_BILLING_FIRST_NAME, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","BILLING_FIRST_NAME","NULL",NOT_REPEATABLE},
{P7_F048S22_BILLING_LAST_NAME, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","BILLING_LAST_NAME","NULL",NOT_REPEATABLE},
{P7_F048S22_BILLING_PHONE_NBR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","BILLING_PHONE_NBR","NULL",NOT_REPEATABLE},
{P7_F048S22_BILLING_COUNTRY_CODE , FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","BILLING_COUNTRY_CODE ","NULL",NOT_REPEATABLE},
{P7_F048S22_SHIPPING_METHOD, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","SHIPPING_METHOD","NULL",NOT_REPEATABLE},
{P7_F048S22_SHIP_TO_POSTAL_CODE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","SHIP_TO_POSTAL_CODE","NULL",NOT_REPEATABLE},
{P7_F048S22_SHIP_TO_ADDRESS, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,50,PP_PRINT,"NULL","SHIP_TO_ADDRESS","NULL",NOT_REPEATABLE},
{P7_F048S22_SHIP_TO_FIRST_NAME, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","SHIP_TO_FIRST_NAME","NULL",NOT_REPEATABLE},
{P7_F048S22_SHIP_TO_LAST_NAME, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","SHIP_TO_LAST_NAME","NULL",NOT_REPEATABLE},
{P7_F048S22_SHIP_TO_PHONE_NUMBER, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","SHIP_TO_PHONE_NUMBER","NULL",NOT_REPEATABLE},
{P7_F048S22_SHIP_TO_COUNTRY_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","SHIP_TO_COUNTRY_CODE","NULL",NOT_REPEATABLE},
{P7_F048S22_CUSTOMER_EMAIL, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,60,PP_PRINT,"NULL","CUSTOMER_EMAIL","NULL",NOT_REPEATABLE},
{P7_F048S22_CUSTOMER_IP, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,39,PP_PRINT,"NULL","CUSTOMER_IP","NULL",NOT_REPEATABLE},	/*AMER20190313 PROD00066569: Enh5.00 1073: 15 -> 39*/
{P7_F048S22_CUSTOMER_HTTP_BROWSER_TYPE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,60,PP_PRINT,"NULL","CUSTOMER_HTTP_BROWSER_TYPE","NULL",NOT_REPEATABLE},
{P7_F048S22_MERCHANT_HOSTNAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,60,PP_PRINT,"NULL","MERCHANT_HOSTNAME","NULL",NOT_REPEATABLE},
{P7_F048S22_MERCHANT_ANI, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","MERCHANT_ANI","NULL",NOT_REPEATABLE},
{P7_F048S22_MERCHANT_II_DIGITS, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","MERCHANT_II_DIGITS","NULL",NOT_REPEATABLE},
{P7_F048S22_MERCHANT_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,40,PP_PRINT,"NULL","MERCHANT_NAME","NULL",NOT_REPEATABLE},	/*AMER20190313 PROD00066569: Enh5.00 1073*/	
{P7_F048S22_AUTH_DATE_TIME, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,14,PP_PRINT,"NULL","AUTH_DATE_TIME","NULL",NOT_REPEATABLE},	/*AMER20190313 PROD00066569: Enh5.00 1073*/	
{P7_F048S22_PURCHASE_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","PURCHASE_AMOUNT","NULL",NOT_REPEATABLE},	/*AMER20190313 PROD00066569: Enh5.00 1073*/	
{P7_F048S22_CH_SHIP_HASH, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,64,PP_PRINT,"NULL","CH_SHIP_HASH","NULL",NOT_REPEATABLE},	/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/  /* + */ /*SKA17032023 PLUTONL-6018 Enh 2023Q2*/
{P7_F048S22_ACC_OWNER_NATIONALITY, FT_SINGLE,FF_ALPHA_A,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","ACC_OWNER_NATIONALITY","NULL",NOT_REPEATABLE},/*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{P7_F048S22_ACC_OWNER_CTRY_OF_BIRTH, FT_SINGLE,FF_ALPHA_A,AF_ASCII,FL_LLL,LU_BYTE,3,PP_PRINT,"NULL","ACC_OWNER_CTRY_OF_BIRTH","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{P7_F048S22_ACC_OWNER_OCCUPATION, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,35,PP_PRINT,"NULL","ACC_OWNER_OCCUPATION","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{P7_F048S22_ACC_OWNER_DATE_OF_BIRTH, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,8,PP_PRINT,"NULL","ACC_OWNER_DATE_OF_BIRTH","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{P7_F048S22_ACC_OWNER_EMAIL_ADDS, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,99,PP_PRINT,"NULL","ACC_OWNER_EMAIL_ADDS","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
},
"SaleInfoDataProp"
};

/******************************************************************************/
void IniSaleInfoDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SaleInfoDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
#define P7_SALE_ITEMS_DATA_NB_FIELDS			13

static const TlvInfoProperties	SaleItemsDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_SALE_ITEMS_DATA_NB_FIELDS,
{
{P7_F048S23_ITEM_IDENTIFICATION, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","ITEM_IDENTIFICATION","NULL",NOT_REPEATABLE},
{P7_F048S23_PRODUCT_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"NULL","PRODUCT_CODE","NULL",NOT_REPEATABLE},
{P7_F048S23_ADD_PRODUCT_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"NULL","ADD_PRODUCT_CODE","NULL",NOT_REPEATABLE},
{P7_F048S23_INT_PRODUCT_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,5,PP_PRINT,"NULL","INT_PRODUCT_CODE","NULL",NOT_REPEATABLE},
{P7_F048S23_UNIT_OF_MEASURE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,4,PP_PRINT,"NULL","UNIT_OF_MEASURE","NULL",NOT_REPEATABLE},
{P7_F048S23_PRODUCT_QUANTITY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,6,PP_PRINT,"NULL","PRODUCT_QUANTITY","NULL",NOT_REPEATABLE},
{P7_F048S23_UNIT_PRICE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","UNIT_PRICE","NULL",NOT_REPEATABLE},
{P7_F048S23_PRODUCT_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","PRODUCT_AMOUNT","NULL",NOT_REPEATABLE},
{P7_F048S23_VALUE_ADDED_TAX, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","VALUE_ADDED_TAX","NULL",NOT_REPEATABLE},
{P7_F048S23_TAX_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","TAX_TYPE","NULL",NOT_REPEATABLE},
{P7_F048S23_PRODUCT_DESCRIPTION, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","PRODUCT_DESCRIPTION","NULL",NOT_REPEATABLE},
{P7_F048S23_DELIVERY_LOCATION, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"NULL","DELIVERY_LOCATION","NULL",NOT_REPEATABLE},
{P7_F048S23_DELIVERY_SERVICE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,1,PP_PRINT,"NULL","DELIVERY_SERVICE","NULL",NOT_REPEATABLE},

},
"SaleItemsDataProp"
};


/******************************************************************************/
/*ZKOStart21092018*/
#define P7_F048_S30_NB_FIELDS		44


static const TlvInfoProperties	ISSFleetDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_F048_S30_NB_FIELDS,
{
/*
{P7_F048S30_INVOICE_NBR, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"NULL","P7_F048S30_INVOICE_NBR","NULL",NOT_REPEATABLE},
{P7_F048S30_MILEAGE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","P7_F048S30_MILEAGE","NULL",NOT_REPEATABLE},
{P7_F048S30_PRODUCT_CODE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","P7_F048S30_PRODUCT_CODE","NULL",NOT_REPEATABLE},
{P7_F048S30_VEHICLE_REG_NBR, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,17,PP_PRINT,"NULL","P7_F048S30_VEHICLE_REG_NBR","NULL",NOT_REPEATABLE},
{P7_F048S30_FUEL_QUANTITY, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"NULL","P7_F048S30_FUEL_QUANTITY","NULL",NOT_REPEATABLE},
{P7_F048S30_FUEL_AMOUNT, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","P7_F048S30_FUEL_AMOUNT","NULL",NOT_REPEATABLE},
{P7_F048S30_OIL_QUANTITY, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"NULL","P7_F048S30_OIL_QUANTITY","NULL",NOT_REPEATABLE},
{P7_F048S30_OIL_AMOUNT, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","P7_F048S30_OIL_AMOUNT","NULL",NOT_REPEATABLE},
{P7_F048S30_TYRES_QUANTITY, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,10,PP_PRINT,"NULL","P7_F048S30_TYRES_QUANTITY","NULL",NOT_REPEATABLE},
{P7_F048S30_TYRES_AMOUNT, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","P7_F048S30_TYRES_AMOUNT","NULL",NOT_REPEATABLE},
{P7_F048S30_BATTERIES_AMOUNT, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","P7_F048S30_BATTERIES_AMOUNT","NULL",NOT_REPEATABLE},
{P7_F048S30_SUNDRY_AMOUNT, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","P7_F048S30_SUNDRY_AMOUNT","NULL",NOT_REPEATABLE},
{P7_F048S30_GARAGE_AMOUNT, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","P7_F048S30_GARAGE_AMOUNT","NULL",NOT_REPEATABLE},
*/
{P7_F048S30_PURCHASE_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","PURCHASE_TYPE","NULL",NOT_REPEATABLE},
{P7_F048S30_SERVICE_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","SERVICE_TYPE","NULL",NOT_REPEATABLE},
{P7_F048S30_FUEL_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","FUEL_TYPE","NULL",NOT_REPEATABLE},
{P7_F048S30_UNIT_MEASURE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","UNIT_MEASURE","NULL",NOT_REPEATABLE},
{P7_F048S30_QUANTITY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","QUANTITY","NULL",NOT_REPEATABLE},
{P7_F048S30_UNIT_COST, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","UNIT_COST","NULL",NOT_REPEATABLE},
{P7_F048S30_GROSS_FUEL_PRICE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","GROSS_FUEL_PRICE","NULL",NOT_REPEATABLE},
{P7_F048S30_NET_FUEL_PRICE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","NET_FUEL_PRICE","NULL",NOT_REPEATABLE},
{P7_F048S30_GROSS_NON_FUEL_PRICE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","GROSS_NON_FUEL_PRICE","NULL",NOT_REPEATABLE},
{P7_F048S30_NET_NON_FUEL_PRICE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","NET_NON_FUEL_PRICE","NULL",NOT_REPEATABLE},
{P7_F048S30_ODOMETER, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,18,PP_PRINT,"NULL","ODOMETER","NULL",NOT_REPEATABLE},
{P7_F048S30_VAT_TAX_RATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,4,PP_PRINT,"NULL","VAT_TAX_RATE","NULL",NOT_REPEATABLE},
{P7_F048S30_MISC_FUEL_TAX_EX_STATUS, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","MISC_FUEL_TAX_EX_STATUS","NULL",NOT_REPEATABLE},
{P7_F048S30_MISC_FUEL_TAX, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","MISC_FUEL_TAX","NULL",NOT_REPEATABLE},
{P7_F048S30_MISC_NON_FUEL_TAX_EX_STATUS, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","MISC_NON_FUEL_TAX_EX_STATUS","NULL",NOT_REPEATABLE},
{P7_F048S30_MISC_NON_FUEL_TAX, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","MISC_NON_FUEL_TAX","NULL",NOT_REPEATABLE},
{P7_F048S30_LOCAL_TAX_INCLUDED, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","LOCAL_TAX_INCLUDED","NULL",NOT_REPEATABLE},
{P7_F048S30_LOCAL_TAX, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","LOCAL_TAX","NULL",NOT_REPEATABLE},
{P7_F048S30_NATIONAL_TAX_INCLUDED, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","NATIONAL_TAX_INCLUDED","NULL",NOT_REPEATABLE},
{P7_F048S30_NATIONAL_TAX, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","NATIONAL_TAX","NULL",NOT_REPEATABLE},
{P7_F048S30_OTHER_TAX, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,12,PP_PRINT,"NULL","OTHER_TAX","NULL",NOT_REPEATABLE},
{P7_F048S30_MER_VAT_REGISTRATION, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,20,PP_PRINT,"NULL","MER_VAT_REGISTRATION","NULL",NOT_REPEATABLE},
{P7_F048S30_CUSTOMER_VAT_REG_NUMBER, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,13,PP_PRINT,"NULL","CUSTOMER_VAT_REG_NUMBER","NULL",NOT_REPEATABLE},
{P7_F048S30_CUSTOMER_REFERENCE_NUMBER, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,17,PP_PRINT,"NULL","CUSTOMER_REFERENCE_NUMBER","NULL",NOT_REPEATABLE},
{P7_F048S30_MESSAGE_IDENTIFIER, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,15,PP_PRINT,"NULL","MESSAGE_IDENTIFIER","NULL",NOT_REPEATABLE},
{P7_F048S30_ADDITIONAL_DATA_INDICATOR, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","ADDITIONAL_DATA_INDICATOR","NULL",NOT_REPEATABLE},
{P7_F048S30_SUMMARY_COMMODITY_CODE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,4,PP_PRINT,"NULL","SUMMARY_COMMODITY_CODE","NULL",NOT_REPEATABLE},
{P7_F048S30_NON_FUEL_PRODUCT_CODE_1, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NON_FUEL_PRODUCT_CODE_1","NULL",NOT_REPEATABLE},
{P7_F048S30_NON_FUEL_PRODUCT_CODE_2, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NON_FUEL_PRODUCT_CODE_2","NULL",NOT_REPEATABLE},
{P7_F048S30_NON_FUEL_PRODUCT_CODE_3, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NON_FUEL_PRODUCT_CODE_3","NULL",NOT_REPEATABLE},
{P7_F048S30_NON_FUEL_PRODUCT_CODE_4, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NON_FUEL_PRODUCT_CODE_4","NULL",NOT_REPEATABLE},
{P7_F048S30_NON_FUEL_PRODUCT_CODE_5, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NON_FUEL_PRODUCT_CODE_5","NULL",NOT_REPEATABLE},
{P7_F048S30_NON_FUEL_PRODUCT_CODE_6, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NON_FUEL_PRODUCT_CODE_6","NULL",NOT_REPEATABLE},
{P7_F048S30_NON_FUEL_PRODUCT_CODE_7, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NON_FUEL_PRODUCT_CODE_7","NULL",NOT_REPEATABLE},
{P7_F048S30_NON_FUEL_PRODUCT_CODE_8, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","NON_FUEL_PRODUCT_CODE_8","NULL",NOT_REPEATABLE},
{P7_F048S30_FUEL_BRAND, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,4,PP_PRINT,"NULL","FUEL_BRAND","NULL",NOT_REPEATABLE},
{P7_F048S30_FUEL_TRANS_VAL_RESULTS, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,5,PP_PRINT,"NULL","FUEL_TRANS_VAL_RESULTS","NULL",NOT_REPEATABLE},
{P7_F048S30_FUEL_ACCEPTANCE_MODE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","FUEL_ACCEPTANCE_MODE","NULL",NOT_REPEATABLE},
{P7_F048S30_DRIVER_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,20,PP_PRINT,"NULL","DRIVER_ID","NULL",NOT_REPEATABLE},
{P7_F048S30_JOB_NUMBER, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,10,PP_PRINT,"NULL","JOB_NUMBER","NULL",NOT_REPEATABLE},
{P7_F048S30_FLEET_NUMBER, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,8,PP_PRINT,"NULL","FLEET_NUMBER","NULL",NOT_REPEATABLE},
{P7_F048S30_VRN, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,20,PP_PRINT,"NULL","VRN","NULL",NOT_REPEATABLE},
{P7_F048S30_PRODUCT_QUALIFIER, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,6,PP_PRINT,"NULL","PRODUCT_QUALIFIER","NULL",NOT_REPEATABLE},
{P7_F048S30_EXPANDED_FUEL_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_LLL,LU_BYTE,4,PP_PRINT,"NULL","EXPANDED_FUEL_TYPE","NULL",NOT_REPEATABLE},
},
"ISSFleetDataProp"
};

/******************************************************************************/
void IniIsoFleetDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &ISSFleetDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
/*ZKOEnd21092018*/

/******************************************************************************/
/*ZKOStart25092018*/
#define P7_F048_S24_NB_FIELDS		7	/*6--> 7 IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/	/*4 --> 6 IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/


static const TlvInfoProperties	ISSInstallmentLoanProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_F048_S24_NB_FIELDS,
{

{P7_F048S24_MONTHLY_RPYMNT_AMNT, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","MONTHLY_RPYMNT_AMNT","NULL",NOT_REPEATABLE},
{P7_F048S24_INTEREST_RATE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","INTEREST_RATE","NULL",NOT_REPEATABLE},
{P7_F048S24_FIRST_RPYMNT_DATE, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","FIRST_RPYMNT_DATE","NULL",NOT_REPEATABLE},
{P7_F048S24_NBR_INSTALMENTS, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","NBR_INSTALMENTS","NULL",NOT_REPEATABLE},	/*IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{P7_F048S24_FREQ_RECUR_PAY, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","FREQ_RECUR_PAY","NULL",NOT_REPEATABLE},	/*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/
{P7_F048S24_REGISTRATION_REF_NBR, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,35,PP_PRINT,"NULL","REGISTRATION_REF_NBR","NULL",NOT_REPEATABLE},	/*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/
{P7_F048S24_VALIDATION_IND, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","VALIDATION_IND","NULL",NOT_REPEATABLE},	/*IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
},
"ISSInstallmentLoanProp"
};
/*Start HAL PROD00073823 20200402 Enh Q2.2020 Art 2941*/
#define P7_ECOM_AUTHENTIF_DATA_NB_FIELDS			4	/*2-->3*/ /*PLUTONL-8809 AMANS Enh2024Q4 VISA 3.9*/

static const TlvInfoProperties	EcomAuthentificationInfoDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_ECOM_AUTHENTIF_DATA_NB_FIELDS,
{
{P7_F048S26_ECOM_AUT_DATA_ESTIMATED_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","P7_F048S26_ECOM_AUT_DATA_ESTIMATED_AMOUNT","NULL",NOT_REPEATABLE},
{P7_F048S26_ECOM_AUT_DATA_MERCHANT_ACRONYM, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,150,PP_PRINT,"NULL","P7_F048S26_ECOM_AUT_DATA_MERCHANT_ACRONYM","NULL",NOT_REPEATABLE},
{P7_F048S26_ECOM_AUT_DATA_SESSION_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,32,PP_PRINT,"NULL","P7_F048S26_ECOM_AUT_DATA_SESSION_ID","NULL",NOT_REPEATABLE},/* HAL  20201803 Enh Q2.2020 Art 9.3.3*/
{P7_F048S26_AUTHEN_DATA_QUALITY_INDC, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","AUTHEN_DATA_QUALITY_INDC","NULL",NOT_REPEATABLE}, /*PLUTONL-8809 AMANS Enh2024Q4 VISA 3.9*/

},
"EcomAuthentificationInfoDataProp"
};
/******************************************************************************/
void InitEcomAuthentificationInfoDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &EcomAuthentificationInfoDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*****************************************************************************/
/*End HAL PROD00073823 20200402 Enh Q2.2020 Art 2941*/

/*Start HAL  20201803 Enh Q2.2020 Art 9.3.3*/
#define P7_EXEMPTION_AUTH_DATA_NB_FIELDS			4

static const TlvInfoProperties	ExempAuthInfoDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_EXEMPTION_AUTH_DATA_NB_FIELDS,
{
{P7_F048_S27_AUTH_EXEMPTION_INDIC, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,16,PP_PRINT,"NULL","P7_F048_S27_AUTH_EXEMPTION_INDIC","NULL",NOT_REPEATABLE},
{P7_F048_S27_AUTH_EXEMPTION_RES, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,8,PP_PRINT,"NULL","P7_F048_S27_AUTH_EXEMPTION_RES","NULL",NOT_REPEATABLE},	/*AEA20210712 Enh21.Q4 Art9.3.3*/
{P7_F048_S27_REASON_HONOR_EXEM, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,80,PP_PRINT,"NULL","P7_F048_S27_REASON_HONOR_EXEM","NULL",NOT_REPEATABLE},
{P7_F048_S27_TRA_SCORE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LLL,LU_BYTE,2,PP_PRINT,"NULL","P7_F048_S27_TRA_SCORE","NULL",NOT_REPEATABLE},/*ENHS 2020Q2 ART 9.3.4*/

},
"ExempAuthInfoDataProp"
};
/******************************************************************************/

void InitExempAuthInfoDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &ExempAuthInfoDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*****************************************************************************/
/*AND ASO20200326 PROD00074655: Enh5.01*/

/* START ASO20200326 PROD00074655: Enh5.01*/

#define P7_INITIAL_ECOM_TRX_DATA			12	/* NBO-HABIL501 */
#define P7_3DS_DATA							8  /*6*/	/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*//*PLUTONL-4280 :Enh5.03 :1372*/
static const TlvInfoProperties	InitialEcomRexInfoDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_INITIAL_ECOM_TRX_DATA,
{
{P7_F048_S28_3DS_PROTOCOL_VERSION, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","P7_F048_S28_3DS_PROTOCOL_VERSION","NULL",NOT_REPEATABLE},
{P7_F048_S28_ACS_TRX_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,36,PP_PRINT,"NULL","P7_F048_S28_ACS_TRX_ID","NULL",NOT_REPEATABLE},
{P7_F048_S28_DS_TRX_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,36,PP_PRINT,"NULL","P7_F048_S28_DS_TRX_ID","NULL",NOT_REPEATABLE},
{P7_F048_S28_MERCHANT_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,40,PP_PRINT,"NULL","P7_F048_S28_MERCHANT_NAME","NULL",NOT_REPEATABLE},
{P7_F048_S28_AUTHENTICATION_DATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,14,PP_PRINT,"NULL","P7_F048_S28_AUTHENTICATION_DATE","NULL",NOT_REPEATABLE},
{P7_F048_S28_AUTHENTICATION_AMOUNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","P7_F048_S28_AUTHENTICATION_AMOUNT","NULL",NOT_REPEATABLE},
{P7_F048_S28_ECOM_TRX_SECURITY_TYPE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","P7_F048_S28_ECOM_TRX_SECURITY_TYPE","NULL",NOT_REPEATABLE},
{P7_F048_S28_CARDHOLDER_AUTHENTICATION_METHOD, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","P7_F048_S28_CARDHOLDER_AUTHENTICATION_METHOD","NULL",NOT_REPEATABLE},
{P7_F048_S28_ECOM_CRYPTOGRAM_CALCULATION_METHOD, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","P7_F048_S28_ECOM_CRYPTOGRAM_CALCULATION_METHOD","NULL",NOT_REPEATABLE},
/* NBO-HABIL501 */
{P7_F048_S28_RESULT_SECURED_REMOTE_PAYMENT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","P7_F048_S28_RESULT_SECURED_REMOTE_PAYMENT","NULL",NOT_REPEATABLE},
{P7_F048_S28_RESULT_SECURED_REMOTE_PAYMENT_EXT, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,20,PP_PRINT,"NULL","P7_F048_S28_RESULT_SECURED_REMOTE_PAYMENT_EXT","NULL",NOT_REPEATABLE},
{P7_F048_S28_AUTHENTICATION_VALUE, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,80,PP_PRINT,"NULL","P7_F048_S28_AUTHENTICATION_VALUE","NULL",NOT_REPEATABLE},
/* NBO-HABIL501 */

},
"InitialEcomRexInfoDataProp"
};
/******************************************************************************/
void InitInitialEcomTrxInfoDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &InitialEcomRexInfoDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*****************************************************************************/
/*Start PLUTONL-4280 :Enh5.03 :1372*/
static const TlvInfoProperties	Info3DSDataProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_3DS_DATA,
{
{P7_F048_S29_3DS_Browser_IP_Address, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,45,PP_PRINT,"NULL","P7_F048_S29_3DS_Browser_IP_Address","NULL",NOT_REPEATABLE},
{P7_F048_S29_3DS_APP_IP_Address, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,45,PP_PRINT,"NULL","P7_F048_S29_3DS_APP_IP_Address","NULL",NOT_REPEATABLE},
{P7_F048_S29_SHIPPING_INDICATOR, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","P7_F048_S29_SHIPPING_INDICATOR","NULL",NOT_REPEATABLE},
{P7_F048_S29_DEVICE_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL/*FL_FIX*/,LU_BYTE,64,PP_PRINT,"NULL","P7_F048_S29_DEVICE_ID","NULL",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
{P7_F048_S29_DEVICE_TYPE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","P7_F048_S29_DEVICE_TYPE","NULL",NOT_REPEATABLE},
{P7_F048_S29_SDK_APP_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL/*FL_FIX*/,LU_BYTE,37,PP_PRINT,"NULL","P7_F048_S29_SDK_APP_ID","NULL",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
{P7_F048_S29_THIRD_PARTY_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_LL,LU_BYTE,64,PP_PRINT,"NULL","P7_F048_S29_THIRD_PARTY_ID","NULL",NOT_REPEATABLE},/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
{P7_F048_S29_THIRD_PARTY_RISK_SCORE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,5,PP_PRINT,"NULL","P7_F048_S29_THIRD_PARTY_RISK_SCORE","NULL",NOT_REPEATABLE},/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/


},
"Info3DSDataProp"
};
void InitInfo3DSDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &Info3DSDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*****************************************************************************/
/*End PLUTONL-4280 :Enh5.03 :1372*/
/*****************************************************************************/
/*START ASO20210426 : Enh5.02 1288*/
#define P7_FOREIGN_RATE_INFO_LEN			9

static const TlvInfoProperties	ForeignRateInfo = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,P7_FOREIGN_RATE_INFO_LEN,
{
{P7_F048_S31_PERS_FX_EXCH_RATE_PROVIDER, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,70,PP_PRINT,"NULL","P7_F048_S31_PERS_FX_EXCH_RATE_PROVIDER","NULL",IS_REPEATABLE},
{P7_F048_S31_PERS_FX_RATE_TABLE_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,5,PP_PRINT,"NULL","P7_F048_S31_PERS_FX_RATE_TABLE_ID","NULL",IS_REPEATABLE},
{P7_F048_S31_PERS_FX_EXCH_RATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","P7_F048_S31_PERS_FX_EXCH_RATE","NULL",IS_REPEATABLE},
{P7_F048_S31_PERS_FX_ELIGIBILITY_INDICATOR, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","P7_F048_S31_PERS_FX_ELIGIBILITY_INDICATOR","NULL",IS_REPEATABLE},
{P7_F048_S31_ECB_FX_EXCH_RATE_PROVIDER, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,70,PP_PRINT,"NULL","P7_F048_S31_ECB_FX_EXCH_RATE_PROVIDER","NULL",IS_REPEATABLE},
{P7_F048_S31_ECB_FX_RATE_TABLE_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,5,PP_PRINT,"NULL","P7_F048_S31_ECB_FX_RATE_TABLE_ID","NULL",IS_REPEATABLE},
{P7_F048_S31_ECB_FX_EXCH_RATE, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","P7_F048_S31_ECB_FX_EXCH_RATE","NULL",IS_REPEATABLE},
{P7_F048_S31_ECB_FX_RATE_DIFF_SIGN, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","P7_F048_S31_ECB_FX_RATE_DIFF_SIGN","NULL",IS_REPEATABLE},/*PLUTONL-4280 :Enh5.03 :1362*/
{P7_F048_S31_ECB_FX_EXCH_PERC_DIFF, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"NULL","P7_F048_S31_ECB_FX_EXCH_PERC_DIFF","NULL",IS_REPEATABLE},/*PLUTONL-4280 :Enh5.03 :1362*/



},
"ForeignRateInfo"
};
/******************************************************************************/
void InitForeignRateInfoDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &ForeignRateInfo;
	ResetTlvInfo(pkTlvInfo);
}
/*****************************************************************************/
/*End HAL  20201803 Enh Q2.2020 Art 9.3.3*/

/******************************************************************************/
void IniIsoInstallmentLoanTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &ISSInstallmentLoanProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
/*ZKOEnd25092018*/
/******************************************************************************/
void IniSaleItemsDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SaleItemsDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
/*Start AMER20210402 PLUTONL-2947*/
#define PRIV_ORIG_DATA_ELMNT_NB_FIELDS			2

static const TlvInfoProperties	PrivOrigDataElmntProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,PRIV_ORIG_DATA_ELMNT_NB_FIELDS,
{
{P7_K20_ORIG_DATA_STRATEGIES, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,9,PP_PRINT,"NULL","ORIG_DATA_STRATEGIES","NULL",NOT_REPEATABLE},
{P7_K20_ORIG_DATA_ELMNT, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LLL,LU_BYTE,999,PP_PRINT,"NULL","ORIG_DATA_ELMNT","NULL",NOT_REPEATABLE},
},
"PrivOrigDataElmntProp"
};
/******************************************************************************/
void InitPrivOrigDataElmntProp(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &PrivOrigDataElmntProp;
	ResetTlvInfo(pkTlvInfo);
}

/******************************************************************************/
#define PRIV_SUB_ORIG_DATA_ELMNT_NB_FIELDS			7 

static const TlvInfoProperties	OrigDataElmntProp = {
3,3,TLV_LT_ASCII,TLV_LT_ASCII,PRIV_SUB_ORIG_DATA_ELMNT_NB_FIELDS,
{
{P7_K20_002_CARD_NUMBER   , FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,19,PP_HIDE,"NULL","CARD_NUMBER","NULL",NOT_REPEATABLE},/*NAB2111*/
{P7_K20_007_ORIG_XMIT_TIME, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,12,PP_PRINT,"NULL","ORIG_XMIT_TIME","NULL",NOT_REPEATABLE},
{P7_K20_011_ORIG_STAN, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"NULL","ORIG_STAN","NULL",NOT_REPEATABLE},
{P7_K20_032_ORIG_ACQ_ID, FT_SINGLE,FF_ALPHA_N,AF_ASCII,FL_LL,LU_BYTE,6,PP_PRINT,"NULL","ORIG_ACQ_ID","NULL",NOT_REPEATABLE},
{P7_K20_038_AUTHOR_ID, FT_SINGLE,FF_ALPHA_AN,AF_ASCII,FL_FIX,LU_BYTE,6,PP_PRINT,"NULL","AUTHOR_ID","NULL",NOT_REPEATABLE},
{P7_K20_042_CARD_ACCEPT_ID, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,15,PP_PRINT,"NULL","CARD_ACCEP_ID","NULL",NOT_REPEATABLE},
{P7_K20_200_ORIG_BANK_REF, FT_SINGLE,FF_ALPHA_ANS,AF_ASCII,FL_FIX,LU_BYTE,9,PP_PRINT,"NULL","ORIG_BANK_REF","NULL",NOT_REPEATABLE},
},
"OrigDataElmntProp"
};
/******************************************************************************/
void InitOrigDataElmntProp(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &OrigDataElmntProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
/*End AMER20210402 PLUTONL-2947*/

void  InitIsoIcTag  (TSTagIso * msgInfo)
{
	int i;

	for (i = 0; i < MAX_ISO_CHIP_TAG; i++)
	{
		msgInfo->nPosTag [i] = 0;
		msgInfo->nPresent[i] = NOT_PRESENT;
	}
	msgInfo->nLength = 0;
	memset(msgInfo->sChipData,   '\0', sizeof(msgInfo->sChipData));
}

void  InitIsoInfo(TSIsoInfo *msgInfo)
{
	int i;

	for (i=0; i < MAX_ISO_FIELDS+1; i++)
		msgInfo->nFieldPos[i] = 0;
	for (i=0; i < ISO_BITMAP_LEN; i++)
		msgInfo->sBitMap[i] = 0x00;
	msgInfo->nLength = 0;
	msgInfo->nMsgType = 0;
	memset(msgInfo->sData,   '\0', sizeof(msgInfo->sData));
	msgInfo->msgId = 0; /*NAB17122020 PLUTONL-2587*/

}

int GetIsoFieldType(int field_no)
{
	return(tab_IsoFldInfo[field_no].type);
}

int GetIsoFieldLength(int field_no)
{
	return(tab_IsoFldInfo[field_no].length);
}

int GetIsoTagIndice ( char * szTagName)
{
	int nIndice, nSize;
	char sLine[MAX_LINE_TRC];


	nSize = sizeof(tab_IsoTagInfo) /sizeof(tag_info_t);
	nIndice = 0;

	do
	{
		if (memcmp(szTagName, tab_IsoTagInfo[nIndice].sTagName, 4) == 0)
		{
			return(nIndice);
		}
		nIndice++;
	}while (nIndice < nSize);
	return(-1);
}

int GetIsoTagType ( int nIndice )
{
	return ( tab_IsoTagInfo[nIndice].nType);
}

int GetIsoTagLength ( int nIndice )
{
	return ( tab_IsoTagInfo[nIndice].nLength);
}