#include <stdio.h>
#include <stdlib.h>
#include <iso_sms.h>
#include <header_sms.h>
#include <define.h>
#include <sms_define.h>
#include <p7_common.h>
#include <p7_globals.h>
#include <iso8583.h>

fld_info_t    tab_SmsFldInfo[] =
{
   { SMS_FIX_BITMAP,  0},	/* BIT_MAP2			 */
   { SMS_VAR_BCD,	 19},   /* CARD_NBR 			 */
   { SMS_FIX_BCD,	  6},	/* PROC_CODE			 */
   { SMS_FIX_BCD,	 12},	/* TRANS_AMOUNT			 */
   { SMS_FIX_BCD,	 12},	/* STLMNT_AMOUNT		 */
   { SMS_FIX_BCD,	 12},	/* Cardholder Billing Amount	 */
   { SMS_FIX_BCD,	 10},	/* XMIT_TIME			 */
   { SMS_FIX_BCD,	  8},	/* Cardholder Billing Fee	 */
   { SMS_FIX_BCD,	  8},	/* CONVRSN_RATE_STLMNT		 */
   { SMS_FIX_BCD,	  8},	/* CONVRSN_RATE_CARD_HLDR_BILLING */

   { SMS_FIX_BCD,	  6},	/* AUDIT_NBR			 */
   { SMS_FIX_BCD,	  6},	/* TRANS_TIME			 */
   { SMS_FIX_BCD,	  4},	/* TRANS_DATE			 */
   { SMS_FIX_BCD,	  4},	/* EXPIRY_DATE			 */
   { SMS_FIX_BCD,	  4},	/* STLMNT_DATE			 */
   { SMS_FIX_BCD,	  4},	/* CNVRSN_DATE			 */
   { SMS_FIX_BCD,	  4},	/* CAPTURE_DATE			 */
   { SMS_FIX_BCD,	  4},	/* MERCHANT_TYPE		 */
   { SMS_FIX_BCD,	  3},	/* ACQR_COUNTRY			 */
   { SMS_FIX_BCD,	  3},	/* PAN_COUNTRY			 */

   { SMS_FIX_BCD,	  3},	/* FORWD_COUNTRY		 */
   { SMS_FIX_BCD,	  4},	/* POS_ENTRY_MODE		 */
   { SMS_FIX_BCD,	  3},	/* Card Sequence Number		 */
   { SMS_FIX_BCD,	  3},	/* Network International Identifier  */
   { SMS_FIX_BCD,	  2},	/* POS_CONDITION		 */
   { SMS_FIX_BCD,	  2},	/* POS_PIN_CAPTURE		 */
   { SMS_FIX_BCD,	  1},	/* Authorization Id Response Lenght */
   { SMS_FIX_ALPHA,	  9},	/* TRANS_FEE			 */
   { SMS_FIX_ALPHA,	  9},	/* Amount Settlement Fee	 */
   { SMS_FIX_ALPHA,	  9},	/* Amount Transaction Processing Fee */
	
   { SMS_FIX_ALPHA,	  9},	/* Amount Setlmnt Processing Fee */
   { SMS_VAR_BCD,	 11},	/* ACQR_ID			 */
   { SMS_VAR_BCD,	 11},	/* FORWD_ID			 */
   { SMS_VAR2_BIN,	65535},	/* PAN_EXTENDED			 */
   /*** { SMS_VAR_BCD,	 37},***/	/* T2_DATA			 */
   { SMS_VAR_HEX,	 37},	/* T2_DATA			 */
   { SMS_VAR_BCD,	104},	/* Track 3 Data			 */
   { SMS_FIX_ALPHA,	 12},	/* REFERENCE_NBR		 */
   { SMS_FIX_ALPHA,	  6},	/* AUTHOR_ID			 */
   { SMS_FIX_ALPHA,	  2},	/* RESPONSE_CODE		 */
   { SMS_FIX_ALPHA,	  3},	/* Service Restriction Code	 */

   { SMS_FIX_ALPHA,	  8},	/* TERMINAL_NBR			 */
   { SMS_FIX_ALPHA,	 15},	/* OUTLET_NBR			 */
   { SMS_FIX_ALPHA,	 40},	/* TERMINAL_ADR			 */
   { SMS_VAR_ALPHA,	 25},	/* ADTNL_RESP_DATA		 */
   { SMS_VAR_ALPHA,	 77},	/* T1_DATA			 */
   { SMS_VAR_ALPHA,	255},	/* Additrional Data Iso		 */
   { SMS_VAR_ALPHA,	255},	/* Additrional Data National	 */
   { SMS_VAR_ALPHA,	255},	/* ADTNL_DATA_PRIV		 */
   { SMS_FIX_BCD,	  3},	/* TRANS_CRNCY			 */
   { SMS_FIX_BCD,	  3},	/* STLMNT_CRNCY			 */

   { SMS_FIX_BCD,	  3},	/* BILLING_CRNCY		 */
   { SMS_FIX_HEX,	 16},	/* PIN_DATA			 */
   { SMS_FIX_BCD,	 16},	/* SECURITY_DATA		 */
   { SMS_VAR_ALPHA,	120},	/* ADTNL_AMOUNTS		 */
   { SMS_VAR_BIN,	255},	/* Reserved Iso			 */
   { SMS_VAR2_BIN,	255},  /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2*/
   { SMS_VAR_ALPHA,	255},	/* Reserved Iso			 */
   { SMS_VAR_ALPHA,	255},	/* Reserved National		 */
   { SMS_VAR_ALPHA,	255},	/* Reserved National		 */
   { SMS_VAR_ALPHA,	 14},	/* GEOGR_DATA			 */
   { SMS_VAR_SBCD,	  6},	/* ADTNL_POS_INFO		 */
	
   { SMS_VAR_SBCD,	 36},	/* OTHER_AMOUNTS		 */
   { SMS_VAR_BITMAP, 59},	/* CPS_FIELDS			 */
   { SMS_VAR_BITMAP, 255},	/* PRIV_USE_FIELDS		 */
   { SMS_FIX_BIN,	  8},	/* MAC1				 */
   { NOT_USED,	  0},	/* 				 */
   { SMS_FIX_BCD,	  1},	/* STLMNT_CODE			 */
   { SMS_FIX_BCD,	  1},	/* Extended Payment Code	*/
   { SMS_FIX_BCD,	  3},	/* RECEIVER_COUNTRY		 */
   { SMS_FIX_BCD,	  3},	/* STLMNT_INST_COUNTRY		 */
   { SMS_FIX_BCD,	  3},	/* NW_MNGMT_INFO		 */

   { SMS_FIX_BCD,         4},   /* Message Number                */
   { SMS_FIX_BCD,         4},   /* Message number Last           */
   { SMS_FIX_BCD,         6},   /* ACTION_DATE                   */
   { SMS_FIX_BCD,         10},  /* CR_NBR                        */
   { SMS_FIX_BCD,         10},  /* CR_REV_NBR                    */
   { SMS_FIX_BCD,         10},  /* DB_NBR                        */
   { SMS_FIX_BCD,         10},  /* DB_REV_NBR                    */
   { SMS_FIX_BCD,        10},   /* Transfer Number               */
   { SMS_FIX_BCD,        10},   /* Transfer Reversal Number      */
   { SMS_FIX_BCD,        10},   /* Inquiries Number              */

   { SMS_FIX_BCD,	 10},	/* Authorizations Number	 */
   { SMS_FIX_BCD,	 12},	/* Credit, Processing Fee Amount */
   { SMS_FIX_BCD,	 12},	/* Credit, Transaction Fee Amount */
   { SMS_FIX_BCD,	 12},	/* Debit, Processing Fee Amount	 */
   { SMS_FIX_BCD,	 12},	/* Debit, Transaction Fee Amount */
   { SMS_FIX_BCD,	 16},	/* CR_AMOUNT			 */
   { SMS_FIX_BCD,	 16},	/* CR_REV_AMOUNT		 */
   { SMS_FIX_BCD,	 16},	/* DB_AMOUNT			 */
   { SMS_FIX_BCD,	 16},	/* DB_REV_AMOUNT		 */
   { SMS_FIX_BCD,	 42},	/* ORIG_DATA			 */

   { SMS_FIX_ALPHA,	  1},	/* FILE_UPDATE			 */
   { SMS_FIX_ALPHA,	  2},	/* FILE_SECURITY		 */
   { SMS_FIX_ALPHA,	  5},	/* Response Indicator		 */
   { SMS_FIX_ALPHA,	  7},	/* Service Indicator		 */
   { SMS_FIX_ALPHA,	 42},	/* REPLACE_AMOUNTS		 */
   { SMS_FIX_BIN,	  8},	/* MSG_SECURITY			 */
   { SMS_FIX_ALPHA,	 17},	/* NET_AMOUNT			 */
   { NOT_USED,	  0},		/*      			 */
   { SMS_VAR_BCD,	 11},	/* STLMNT_INSTITN		 */
   { SMS_VAR_BCD,	 11},	/* RECEIVER_ID			 */

   { SMS_VAR_ALPHA,	 17},	/* FILE_NAME			 */
   { SMS_VAR_ALPHA,	 28},	/* ACCOUNT_ID1			 */
   { SMS_VAR_ALPHA,	 28},	/* ACCOUNT_ID2			 */ /* 103 */
   { SMS_VAR_BIN,	255},	/* Transaction Description	 */
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { SMS_VAR2_BIN,	  1537},/*Additional Data */   /* FZL20220822 PLUTONL-4979*/

   { NOT_USED,	  0},	/* Reserved Iso			 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { SMS_VAR_ALPHA,	 24},	/* ADTNL_TRACE_DATA		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { NOT_USED,	  0},	/* Intra Country Data		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { SMS_VAR_BCD,	  4},	/* ORIGINAL MESSAGE TYPE ID	 */

   { NOT_USED,	  0},	/* Issuing Institution Id	 */
   { NOT_USED,	  0},	/* Remaining Open to Use	 */
   { SMS_VAR_ALPHA,	 29},	/* ADR_VERIF_DATA		 */
   { NOT_USED,	  0},	/* Free Form Text - Japan	 */
   { SMS_VAR_BIN,	255},	/* SUPPORT_INFO			 */
   /* { NOT_USED,	  0} ,*/	/* Reserved Private		 */
   { SMS_VAR_BITMAP,	 255},   /* SMS PRIVATE USE FIELD */
   { SMS_VAR_ALPHA,	  255},	/* FILE RECORD ACTION AND DATA	 */
   { SMS_FIX_BIN,	  8},	/* MAC2				 */
   { NOT_USED,	  0},	/* Field 129			 */
   { SMS_FIX_HEX,	  6},	/* Terminal Capability Profile   */ /* 130 */

   { SMS_FIX_HEX,	  10},	/* Terminal Verification Results */
   { SMS_FIX_HEX,	  8	},	/* Unpredictable Number          */
   { SMS_FIX_HEX,	  16},	/* Terminal Serial Number        */
   { SMS_VAR_SHEX,	 16},	/* Sms Discretionary Data       */
   { SMS_VAR_ALPHA,	 39},	/* Issuer Discretionary Data     */
   { SMS_FIX_HEX,	 16},	/* Issuer Discretionary Data     */
   { SMS_FIX_HEX,	  4},	/* Application Trans. Counter    */
   { SMS_FIX_HEX,	  4},	/* Application Inter. Profile    */
   { SMS_FIX_HEX,	 20},	/* ARPC + Response Code          */
   { NOT_USED,	  0},	/* Field 140			 */

   { NOT_USED,	  0},	/* Field 141			 */
   { SMS_VAR_SBCD,	510},	/* Issuer Script                 */
   { SMS_VAR_HEX,	 40},	/* Issuer Script Results         */
   { SMS_FIX_BCD,	  2},	/* Cryptogram Trans Type         */
   { SMS_FIX_BCD,	  4},	/* Terminal Country Code         */
   { SMS_FIX_BCD,	  6},	/* Terminal Trans  Date          */
   { SMS_FIX_BCD,	 12},	/* Cryptogram Amount             */
   { SMS_FIX_BCD,	  4},	/* Cryptogram Currency Code      */
   { SMS_FIX_BCD,	 12},	/* Cryptogram Cash Back          */
   { SMS_FIX_HEX,	 16},	/* Cardholder Card Scheme Crypto.*/

   { NOT_USED,	  0},	/* Field 151			 */
   { NOT_USED,	  0},	/* Field 152			 */
   { NOT_USED,	  0},	/* Field 153			 */
   { NOT_USED,	  0},	/* Field 154			 */
   { NOT_USED,	  0},	/* Field 155			 */
   { NOT_USED,	  0},	/* Field 156			 */
   { NOT_USED,	  0},	/* Field 157			 */
   { NOT_USED,	  0},	/* Field 158			 */
   { NOT_USED,	  0},	/* Field 159			 */
   { NOT_USED,	  0},	/* Field 160			 */

   { NOT_USED,	  0},	/* Field 161			 */
   { NOT_USED,	  0},	/* Field 162			 */
   { NOT_USED,	  0},	/* Field 163			 */
   { NOT_USED,	  0},	/* Field 164			 */
   { NOT_USED,	  0},	/* Field 165			 */
   { NOT_USED,	  0},	/* Field 166			 */
   { NOT_USED,	  0},	/* Field 167			 */
   { NOT_USED,	  0},	/* Field 168			 */
   { NOT_USED,	  0},	/* Field 169			 */
   { NOT_USED,	  0},	/* Field 170			 */

   { NOT_USED,	  0},	/* Field 171			 */
   { NOT_USED,	  0},	/* Field 172			 */
   { NOT_USED,	  0},	/* Field 173			 */
   { NOT_USED,	  0},	/* Field 174			 */
   { NOT_USED,	  0},	/* Field 175			 */
   { NOT_USED,	  0},	/* Field 176			 */
   { NOT_USED,	  0},	/* Field 177			 */
   { NOT_USED,	  0},	/* Field 178			 */
   { NOT_USED,	  0},	/* Field 179			 */
   { NOT_USED,	  0},	/* Field 180			 */

   { NOT_USED,	  0},	/* Field 181			 */
   { NOT_USED,	  0},	/* Field 182			 */
   { NOT_USED,	  0},	/* Field 183			 */
   { NOT_USED,	  0},	/* Field 184			 */
   { NOT_USED,	  0},	/* Field 185			 */
   { NOT_USED,	  0},	/* Field 186			 */
   { NOT_USED,	  0},	/* Field 187			 */
   { NOT_USED,	  0},	/* Field 188			 */
   { NOT_USED,	  0},	/* Field 189			 */
   { NOT_USED,	  0},	/* Field 190			 */

   { NOT_USED,	  0},	/* Field 191			 */
   { SMS_FIX_BIN,	  8},	/* Message Authentication Code   */
};

tag_info_t  tab_SmsTagInfo[] =
{
   { "7100",  SMS_TAG_VAR_BCD,   0},/* Issuer Script Template 1              */
   { "7200",  SMS_TAG_VAR_BCD,   0},/* Issuer Script Template 2              */
   { "8200",  SMS_TAG_VAR_HEX,   2},/* Application Interchange Profile       */
   { "8400",  SMS_TAG_VAR_HEX /*SMS_TAG_VAR_BCD*/,   0},/* Dedicated File Name */ /*NAB27112020 PLUTONL-2540*/
   { "9100",  SMS_TAG_VAR_HEX,   0},/* Issuer Authentication Data            */
   { "9500",  SMS_TAG_VAR_BCD,   5},/* Terminal Verification Results         */
   { "9A00",  SMS_TAG_VAR_BCD,   6},/* Transaction Date                      */
   { "9C00",  SMS_TAG_VAR_BCD,   2},/* Transaction TYPE                      */
   { "C000",  SMS_TAG_VAR_HEX,   8},/* Secondary PIN Block             	  	 */	/*AMER20180307 PROD00054205: Enh18.Q2 Art 8.1.1*/
   { "5F2A",  SMS_TAG_VAR_BCD,   3},/* Transaction Currency Code             */
   { "9F02",  SMS_TAG_VAR_BCD,  12},/* Transaction Amount                    */
   { "9F03",  SMS_TAG_VAR_BCD,  12},/* Other Amount                          */
   { "9F09",  SMS_TAG_VAR_BCD,   2},/* Terminal Application Version Number   */
   { "9F10",  SMS_TAG_VAR_HEX,   0},/*  Issuer Application Data              */
   { "9F1A",  SMS_TAG_VAR_BCD,   3},/* Terminal Country Code                 */
   { "9F1E",  SMS_TAG_VAR_ALPHA, 8},/* Interface Device Serial Number        */
   { "9F26",  SMS_TAG_VAR_HEX,   8},/* Application cryptogram                */
   { "9F27",  SMS_TAG_VAR_BCD,   1},/* Cryptogram Information Data           */
   { "9F33",  SMS_TAG_VAR_HEX,   3},/* Terminal Capabilities                 */
   { "9F34",  SMS_TAG_VAR_BCD,   3},/* Cardholder Verification Method        */
   { "9F35",  SMS_TAG_VAR_BCD,   2},/* Terminal Type                         */
   { "9F36",  SMS_TAG_VAR_HEX,   2},/* Application Transaction Counter       */
   { "9F37",  SMS_TAG_VAR_HEX,   4},/* Unpredictable Number                  */
   { "9F41",  SMS_TAG_VAR_BCD,   0},/* Transaction Sequence Number           */
   { "9F53",  SMS_TAG_VAR_BCD, 1},/* Transaction Category Code             */
   { "9F6E",  SMS_TAG_VAR_HEX,   1},/* Form Factor Indicator             	  */	/*AMER20180307 PROD00054205: Enh18.Q2 Art 3.6*/
};

/*Start IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/

static const TlvInfoProperties	SmsElectComDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,SMS_F34_NB_FIELDS,
{
{SMS_F34_ACCEPTANCE_ENV_ADD_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","SMS_F34_ACCEPTANCE_ENV_ADD_DATA","NULL",NOT_REPEATABLE},
{SMS_F34_EU_PSD2_SCA_CSC, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","SMS_F34_EU_PSD2_SCA_CSC","NULL",NOT_REPEATABLE}, /*IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/
{SMS_F34_SUPP_DATA,FT_STRUCT_BER/*FT_STRUCT_TLV*/,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","SMS_F34_SUPP_DATA","NULL",NOT_REPEATABLE},/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*//*HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
{SMS_F34_AUTHEN_DATA,FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","AUTHEN_DATA","NULL",NOT_REPEATABLE}, /*PLUTONL-8809 AMANS Enh2024Q4 VISA 3.9*/
},
"SmsElectComDataProp"
};

static const TlvInfoProperties	SmsF34T02DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F34_T02_NB_FIELDS,
{
{SMS_F34T02_INITIATING_PARTY_ID, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","INITIATING_PARTY_ID","NULL",NOT_REPEATABLE},
{SMS_F34T02_AUTH_OUTAGE_INDICATOR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","SMS_F34T02_AUTH_OUTAGE_INDICATOR","NULL",NOT_REPEATABLE},	/*AEA20210712 Enh21.Q4 Art9.1.2*/
{SMS_F34T02_ACC_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"NULL","ACC_STREET_ADDR","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{SMS_F34T02_ACQ_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,80,PP_PRINT,"NULL","ACQ_NAME","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/ 
{SMS_F34T02_ACQ_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"NULL","ACQ_STREET_ADDR","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/ 
{SMS_F34T02_ACQ_CITY_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,50,PP_PRINT,"NULL","ACQ_CITY_NAME","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/ 
{SMS_F34T02_ACQ_STATE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","ACQ_STATE_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/ 
{SMS_F34T02_ACQ_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,10,PP_PRINT,"NULL","ACQ_POSTAL_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/ 
{SMS_F34T02_ACQ_COUNTRY_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","ACQ_COUNTRY_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/ 
{SMS_F34T02_PAYFAC_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"NULL","PAYFAC_STREET_ADDR","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{SMS_F34T02_PAYFAC_CITY_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,50,PP_PRINT,"NULL","PAYFAC_CITY_NAME","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{SMS_F34T02_PAYFAC_STATE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,3,PP_PRINT,"NULL","PAYFAC_STATE_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{SMS_F34T02_PAYFAC_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,10,PP_PRINT,"NULL","PAYFAC_POSTAL_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{SMS_F34T02_PAYFAC_CTRY_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","PAYFAC_CTRY_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
},
"SmsF34T02DataProp"
};

/*END IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/

static const TlvInfoProperties	SmsVerifDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,2,
{
{SMS_F123_ADDR_VERIF_DATA,	FT_STRUCT_TLV	,FF_BIN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,256	,PP_PRINT	,"NULL"	,"ADDR_VERIF_DATA"	,SMS_F123_T66_PROP	,NOT_REPEATABLE},
{SMS_F123_TOKEN_DATA,		FT_STRUCT_TLV	,FF_BIN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,256	,PP_PRINT	,"NULL"	,"TOKEN_DATA"		,SMS_F123_T68_PROP	,NOT_REPEATABLE},
},
"SmsVerifDataProp"
};

static const TlvInfoProperties	SmsAddrVerifDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F123_T66_NB_FIELDS, /*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
{
{SMS_F123_T66_POSTAL_CD	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,9	,PP_PRINT	,"NULL"	,"POSTAL_CODE"	,"NULL"	,NOT_REPEATABLE},
{SMS_F123_T66_STREE_ADDR	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,40	,PP_PRINT	,"NULL"	,"STREET_ADDR"	,"NULL"	,NOT_REPEATABLE},
{SMS_F123_T66_CH_SHIP_HASH	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,32	,PP_PRINT	,"NULL"	,"CARDHOLDER_SHIPPING_HASH"	,"NULL"	,NOT_REPEATABLE},/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
},
"SmsAddrVerifDataProp"
};


static const TlvInfoProperties	SmsTokenDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F123_T68_NB_FIELDS,     /*8-->9 IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art2.2*/ /* PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221  change nb of fields from 9->10*/
{
{SMS_F123_T68_TOKEN		,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_LL	,LU_BYTE	,19	,PP_PRINT	,"NULL",	"TOKEN"			,"NULL"	,NOT_REPEATABLE},
{SMS_F123_T68_TKN_ASS_LVL	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,2	,PP_PRINT	,"NULL",	"TOKEN_ASS_LVL"	,"NULL"	,NOT_REPEATABLE},
{SMS_F123_T68_TKN_REQ_ID	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,11	,PP_PRINT	,"NULL",	"TOKEN_REQ_ID"	,"NULL"	,NOT_REPEATABLE},
{SMS_F123_T68_TKN_RANGE	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,9	,PP_PRINT	,"NULL",	"PAN_RANGE"		,"NULL"	,NOT_REPEATABLE},
{SMS_F123_T68_TKN_REFERENCE_ID		,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,32	,PP_PRINT	,"NULL",	"TKN_REFERENCE_ID"			,"NULL"	,NOT_REPEATABLE}, /*HAL2402 PLUTONL-4391*/
{SMS_F123_T68_TKN_EXPIRATION_DATE	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,4	,PP_PRINT	,"NULL",	"TKN_EXPIRATION_DATE"	,"NULL"	,NOT_REPEATABLE},       /*HAL2402 PLUTONL-4391*/
{SMS_F123_T68_TKN_TYPE	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,2	,PP_PRINT	,"NULL",	"TKN_TYPE"	,"NULL"	,NOT_REPEATABLE},                            /*HAL2402 PLUTONL-4391*/
{SMS_F123_T68_TKN_STATUS	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,1	,PP_PRINT	,"NULL",	"TKN_STATUS"		,"NULL"	,NOT_REPEATABLE},                      /*HAL2402 PLUTONL-4391*/
{SMS_F123_T68_AUTO_FILL_IND	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,1	,PP_PRINT	,"NULL",	"AUTO_FILL_IND"		,"NULL"	,NOT_REPEATABLE}, /*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art2.2*/
{SMS_F123_T68_TKN_AUTHENTICATION_AMNT	,FT_SINGLE	,FF_ALPHA_N	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,6	,PP_PRINT	,"NULL",	"TKN_AUTHENTICATION_AMNT"		,"NULL"	,NOT_REPEATABLE}, /* PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221  */
},
"SmsTokenDataProp"
};


/*Start IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/
static const TlvInfoProperties	SmsF34T4ADataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F34_T4A_NB_FIELDS,
{
{SMS_F34T4A_TRST_MER_EXEM, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","TRUSTED_MERCHANT_EXEMPTION","NULL",NOT_REPEATABLE},
{SMS_F34T4A_LOW_VAL_EXEM, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","LOW_VALUE_EXEMPTION","NULL",NOT_REPEATABLE},
{SMS_F34T4A_SPC, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","SECURE_CORPORATE_PAYMENT","NULL",NOT_REPEATABLE},
{SMS_F34T4A_TRA, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","TRANSACTION_RISK_ANALYSIS","NULL",NOT_REPEATABLE},
{SMS_F34T4A_DELG_AUTH, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","VISA_DELEGATED_AUTHENTICATION_PROGRAM","NULL",NOT_REPEATABLE},
{SMS_F34T4A_REASON_HONOR_EXEM, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,80,PP_PRINT,"NULL","SMS_F34T4A_REASON_HONOR_EXEM","NULL",NOT_REPEATABLE}, /*HAL 20201803 ENHS ART 9.3.3*/

},
"SmsF34T4ADataProp"
};
/*END IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/
 /*Start HAL  20202003 ENHS 2020Q2 ART 9.3.4*/
/*Start NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
/*static const TlvInfoProperties	SmsF34T56DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F34_T56_NB_FIELDS,
{
{SMS_F34T56_SESSION_ID, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,32,PP_PRINT,"NULL","SMS_F34T56_SESSION_ID","NULL",NOT_REPEATABLE},
/**},
"SmsF34T56DataProp"
};*/
static const BerInfoProperties	SmsF34T56DataProp = {
SMS_F34_T56_NB_FIELDS,
{
{SMS_F034_T56_CONSUMER_DEVICE_IP,  FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,39,PP_PRINT,"","Consumer Device IP Address","",0,"",-1,NOT_REPEATABLE},
{SMS_F34T56_IP_ADDR_VELOCITY_COUNT,  FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","IP_ADDR_VELOCITY_COUNT","",0,"",-1,NOT_REPEATABLE},
{SMS_F34T56_DEVICE_ID_VELOCITY_COUNT,  FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","DEVICE_ID_VELOCITY_COUNT","",0,"",-1,NOT_REPEATABLE},
{SMS_F34T56_VISA_RISK_AUTHEN_SCORE,  FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","RISK_AUTHEN_SCORE","",0,"",-1,NOT_REPEATABLE},
{SMS_F34T56_CAVV_VERSION_NUMBER,  FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","CAVV_VERSION_NUMBER","",0,"",-1,NOT_REPEATABLE},
{SMS_F34T56_CAVV_TYPE,  FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","CAVV_TYPE","",0,"",-1,NOT_REPEATABLE},
{SMS_F34T56_SESSION_ID, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,32,PP_PRINT,"NULL","SMS_F34T56_SESSION_ID","NULL",NOT_REPEATABLE},
{SMS_F34T56_THIRD_PARTY_ID, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,64,PP_PRINT,"","THIRD_PARTY_ID","",NOT_REPEATABLE},
{SMS_F34T56_THIRD_PARTY_RISK_SCORE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,5,PP_PRINT,"","THIRD_PARTY_RISK_SCORE","",NOT_REPEATABLE},/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/

},
"SmsF34T56DataProp"
};
/*End NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
/*End HAL  20202003 ENHS 2020Q2 9.3.4*/
static const TlvInfoProperties	SmsTransSpecDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,SMS_F104_NB_FIELDS,
{
{SMS_F104_PURCHASE_LINE_ITEM_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","PURCHASE_LINE_ITEM_DATA","NULL",NOT_REPEATABLE},
/*{SMS_F104_DIAL_TERMINAL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","DIAL_TERMINAL_DATA","NULL",NOT_REPEATABLE},*/
{SMS_F104_PAY_FAC_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","PAY_FAC_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_BUSINESS_APP_ID, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","BUSINESS_APP_ID","NULL",NOT_REPEATABLE},
{SMS_F104_HEALTHCARE_ELIGIBILITY_INQ, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","HEALTHCARE_ELIGIBILITY_INQ","NULL",NOT_REPEATABLE},
{SMS_F104_PROMOTION_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","PROMOTION_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_VISA_RISK_ASSESSMENT_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","VISA_RISK_ASSESSMENT_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_COMMERCIAL_CARD_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","COMMERCIAL_CARD_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_INSTALLMENT_PAYMENT_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","INSTALLMENT_PAYMENT_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_SENDER_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","SENDER_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_AIRLINE_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","AIRLINE_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_CAR_RENTAL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","CAR_RENTAL_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_LODGING_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","LODGING_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_NON_INDUSTRY_SPECIFIC_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","NON_INDUSTRY_SPECIFIC_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_MASTERCARD_MEMBER_DEF_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","MASTERCARD_MEMBER_DEF_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_AMEX_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","AMEX_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_MULTIPLE_PAYMENT_FORMS, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","MULTIPLE_PAYMENT_FORMS","NULL",NOT_REPEATABLE},
{SMS_F104_TRAVEL_TAG_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","TRAVEL_TAG_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_ISSUER_SUPPLIED_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","ISSUER_SUPPLIED_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_LOAN_DETAILS, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","LOAN_DETAILS","NULL",NOT_REPEATABLE},
{SMS_F104_FREE_FORM_DESCRIPTION_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","FREE_FORM_DESCRIPTION_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_ADDITIONAL_SENDER_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","ADDITIONAL_SENDER_DATA","NULL",NOT_REPEATABLE},
{SMS_F104_FREE_FORM_TEXT_ORG_CR_TRN, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","FREE_FORM_TEXT_ORG_CR_TRN","NULL",NOT_REPEATABLE},
{SMS_F104_RECURRING_PAY, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","RECURRING_PAY","NULL",NOT_REPEATABLE},   /*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/

},
"SmsTransSpecDataProp"
};

static const TlvInfoProperties	SmsF104T56DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F104_T56_NB_FIELDS,
{
{SMS_F104T56_PAY_FAC_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"NULL","PAY_FAC_ID","NULL",NOT_REPEATABLE},
{SMS_F104T56_SUB_MER_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"NULL","SUB_MER_ID","NULL",NOT_REPEATABLE},
{SMS_F104T56_ISO_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,11,PP_PRINT,"NULL","ISO_ID","NULL",NOT_REPEATABLE},
},
"SmsF104T56DataProp"
};

/*Start PLUTONL-8878 Enh24Q4 AMANS AN 3.20*/
static const TlvInfoProperties	SmsF104T57DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F104_T57_NB_FIELDS,
{
{SMS_F104_T57_BUSINESS_APP_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","BUSINESS_APP_ID","",NOT_REPEATABLE},
{SMS_F104_T57_SERVICE_PROC_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","SERVICE_PROC_TYPE","",NOT_REPEATABLE},
{SMS_F104_T57_DEFER_OCT_REQ_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"NULL","DEFER_OCT_REQ_TYPE","",NOT_REPEATABLE},
{SMS_F104_T57_PAY_PURPOSE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,12,PP_PRINT,"NULL","PAY_PURPOSE","",NOT_REPEATABLE},	/*AEA20210712 Enh21.Q4 Art2.9*/
{SMS_F104_T57_MAX_PROC_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"NULL","MAX_PROC_DATE","",NOT_REPEATABLE},
{SMS_F104_T57_PT_SRC_FUNDS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","FUNDS_SOURCE","",NOT_REPEATABLE},
},
"SmsF104T57DataProp"
};
/*End PLUTONL-8878 Enh24Q4 AMANS AN 3.20*/


static const TlvInfoProperties	SmsF104T5FDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F104_T5F_NB_FIELDS,
{
{SMS_F104T5F_SENDER_REF_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"NULL","SENDER_REF_NBR","NULL",NOT_REPEATABLE},
{SMS_F104T5F_SENDER_ACCOUNT_NO, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,34,PP_PRINT,"NULL","SENDER_ACCOUNT_NO","NULL",NOT_REPEATABLE},
{SMS_F104T5F_SENDER_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,30,PP_PRINT,"NULL","SENDER_NAME","NULL",NOT_REPEATABLE},
{SMS_F104T5F_SENDER_STREET_ADDR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,35,PP_PRINT,"NULL","SENDER_STREET_ADDR","NULL",NOT_REPEATABLE},
{SMS_F104T5F_SENDER_CITY_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"NULL","SENDER_CITY_NAME","NULL",NOT_REPEATABLE},
{SMS_F104T5F_SENDER_STATE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","SENDER_STATE","NULL",NOT_REPEATABLE},
{SMS_F104T5F_SENDER_COUNTRY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","SENDER_COUNTRY","NULL",NOT_REPEATABLE},
{SMS_F104T5F_FUNDS_SOURCE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","FUNDS_SOURCE","NULL",NOT_REPEATABLE},
{SMS_F104T5F_RECIPIENT_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,30,PP_PRINT,"NULL","RECIPIENT_NAME","NULL",NOT_REPEATABLE},
},
"SmsF104T5FDataProp"
};

static const TlvInfoProperties	SmsF104T71DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F104_T71_NB_FIELDS,
{
{SMS_F104T71_FREE_FORM_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,45,PP_PRINT,"","FREE_FORM_DATA","",NOT_REPEATABLE},
},
"SmsF104T71DataProp"
};

/*Start IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/
static const TlvInfoProperties	SmsF104T18DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F104_T18_NB_FIELDS,
{
{SMS_F104T18_RECURRING_PAY_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,SMS_F104T18_RECURRING_PAY_TYPE_LEN,PP_PRINT,"NULL","RECURRING_PAY_TYPE","NULL",NOT_REPEATABLE}, /*FF_ALPHA_N---> FF_BCD  FZL 03102022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{SMS_F104T18_PAY_AMNT_IND_PER_TRANS, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,SMS_F104T18_PAY_AMNT_IND_PER_TRANS_LEN,PP_PRINT,"NULL","PAY_AMNT_IND_PER_TRANS","NULL",NOT_REPEATABLE}, /*FF_ALPHA_N---> FF_BCD FZL 03102022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{SMS_F104T18_NBR_RECURRING_PAY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,SMS_F104T18_NBR_RECURRING_PAY_LEN,PP_PRINT,"NULL","NBR_RECURRING_PAY","NULL",NOT_REPEATABLE}, /*FF_ALPHA_N---> FF_BCD FZL 03102022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{SMS_F104T18_FREQ_RECURRING_PAY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,SMS_F104T18_FREQ_RECURRING_PAY_LEN,PP_PRINT,"NULL","FREQ_RECURRING_PAY","NULL",NOT_REPEATABLE}, /*FF_ALPHA_N---> FF_BCD FZL 03102022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{SMS_F104T18_REGISTR_REF_NBR, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,SMS_F104T18_REGISTR_REF_NBR_LEN,PP_PRINT,"NULL","REGISTR_REF_NBR","NULL",NOT_REPEATABLE}, /*FF_ALPHA_N---> FF_BCD FZL 03102022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{SMS_F104T18_MAX_RECURRING_PAY_AMNT, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,SMS_F104T18_MAX_RECURRING_PAY_AMNT_LEN,PP_PRINT,"NULL","MAX_RECURRING_PAY_AMNT","NULL",NOT_REPEATABLE}, /*FF_ALPHA_N---> FF_BCD  FZL 03102022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{SMS_F104T18_VALIDATION_IND, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,SMS_F104T18_VALIDATION_IND_LEN,PP_PRINT,"NULL","VALIDATION_IND","NULL",NOT_REPEATABLE}, /*FF_ALPHA_N---> FF_BCD  FZL 03102022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
},
"SmsF104T18DataProp"
};
/*End IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/

/* Start FZL20220829 PLUTONL-4979 */
static const TlvInfoProperties	SMSF110DataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,SMS_F110_NB_FIELDS,
{
{SMS_F110T04_KEY_DATA, FT_STRUCT_TLV,FF_BIN,AF_ASCII,FL_LL,LU_BYTE,1537,PP_HIDE,"NULL","SMS_F110_T04_PROP","NULL",NOT_REPEATABLE}

},
"VisaF110DataProp"
};
/* field 110 tag 04 details */
static const TlvInfoProperties	SMSF110T04DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F110_T04_NB_FIELDS,
{
{SMS_F110_T04_CONTROL,  FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","Control","NULL",NOT_REPEATABLE},
{SMS_F110_T04_KEY_IDENT,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,11,PP_PRINT,"","key set identifier","NULL",NOT_REPEATABLE},
{SMS_F110_T04_ALGO,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,2,PP_PRINT,"","Algorithm","NULL",NOT_REPEATABLE},
{SMS_F110_T04_KEY_PROTECT,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,2,PP_PRINT,"","key protection","NULL",NOT_REPEATABLE},
{SMS_F110_T04_KEY_IND,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,2,PP_PRINT,"","key index","NULL",NOT_REPEATABLE},
{SMS_F110_T04_ENCT_DATA ,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,512,PP_PRINT,"","Encryption Data","NULL",NOT_REPEATABLE},
{SMS_F110_T04_CHECK_VALUE,  FT_SINGLE,FF_HEX,AF_EBCDIC,FL_BB,LU_BYTE,128,PP_PRINT,"","key checksum value","NULL",NOT_REPEATABLE},

},
"VisaF110T04DataProp"
};
/* end FZL20220829 PLUTONL-4979 */

/*Start IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/

static const TlvInfoProperties	SmsSupportInfDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,SMS_F125_NB_FIELDS,
{
{SMS_F125_ADD_ORIGINAL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","SMS_F125_ADD_ORIGINAL_DATA","NULL",NOT_REPEATABLE},

},
"SmsSupportInfDataProp"
};

static const TlvInfoProperties	SmsF125T03DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F125_T03_NB_FIELDS,
{
{SMS_F125T03_ORIGINAL_TRA_ID, FT_STRUCT_TLV,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,8,PP_PRINT,"NULL","ORIGINAL_TRA_ID","NULL",NOT_REPEATABLE},
},
"SmsF125T03DataProp"
};
/*End IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/

/*Start HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
static const TlvInfoProperties	SmsF34T01DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F34_T01_NB_FIELDS,
{
{SMS_F34T01_PROTOCOL_VERSION_NUMBER, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,8,PP_PRINT,"NULL","SMS_F34T02_PROTOCOL_VERSION_NUMBER","NULL",NOT_REPEATABLE},
/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
{SMS_F034_T01_3DS_BROWSER_IP, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,45,PP_PRINT,"","3DS Browser IP Address","",0,"",-1,NOT_REPEATABLE},
{SMS_F034_T01_3DS_APP_IP_ADDRESS, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,45,PP_PRINT,"NULL","3DS_APP_IP_ADDRESS","NULL",NOT_REPEATABLE},  /*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
{SMS_F034_SHIPPING_INDICATOR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","SHIPPING_INDICATOR","NULL",NOT_REPEATABLE},  /*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
{SMS_F34T01_AUTHENTICATION_PROGRAM, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,2,PP_PRINT,"NULL","SMS_F34T01_AUTHENTICATION_PROGRAM","NULL",NOT_REPEATABLE}, /*PLUTONL-5548 Enh 2023Q2  Visa 1.2 AHA20221221*/
{SMS_F34T01_AUTHEN_DATA_QUALITY_INDC, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","AUTHEN_DATA_QUALITY_INDC","NULL",NOT_REPEATABLE}, /*PLUTONL-8809 AMANS Enh2024Q4 VISA 3.9*/
},
"SmsF34T01DataProp"
};
/*END HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/

/*Start IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.1*/
static const TlvInfoProperties	SmsF125T02DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,SMS_F125_T02_NB_FIELDS,
{
{SMS_F125T02_WP_DEVICE_SCORE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","WP_DEVICE_SCORE","NULL",NOT_REPEATABLE},/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
{SMS_F125T02_WP_ACCOUNT_SCORE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","WP_ACCOUNT_SCORE","NULL",NOT_REPEATABLE},/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
},
"SmsF125T02DataProp"
};
/*End IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.1*/

/*Start PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
static const TlvInfoProperties	SmsF056DataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,SMS_F056_NB_FIELDS,
{
{SMS_F056_ACCOUNT_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","ACCOUNT_DATA","",NOT_REPEATABLE},
{SMS_F056_CONTACT_INFO, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","CONTACT_INFO","",NOT_REPEATABLE},
{SMS_F056_CUSTOMER_ID_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","CUSTOMER_ID_DATA","",NOT_REPEATABLE},
{SMS_F056_ACCOUNT_OWNER_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","ACCOUNT_OWNER_DATA","",NOT_REPEATABLE},
},
"SmsF056DataProp"
};

static const TlvInfoProperties	SmsF056T05DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,9,
{
{SMS_F056T05_ACCOUNT_OWNER_NAME_GIVEN, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACCOUNT_OWNER_NAME_GIVEN","NULL",NOT_REPEATABLE},
{SMS_F056T05_ACCOUNT_OWNER_NAME_MIDDLE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACCOUNT_OWNER_NAME_MIDDLE","NULL",NOT_REPEATABLE},
{SMS_F056T05_ACCOUNT_OWNER_NAME_LAST, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACCOUNT_OWNER_NAME_LAST","NULL",NOT_REPEATABLE},
{SMS_F056T05_ACC_OWNER_NATIONALITY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,3,PP_PRINT,"NULL","ACC_OWNER_NATIONALITY","NULL",NOT_REPEATABLE},
{SMS_F056T05_ACC_OWNER_CTRY_OF_BIRTH, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,3,PP_PRINT,"NULL","ACC_OWNER_CTRY_OF_BIRTH","NULL",NOT_REPEATABLE}, 
{SMS_F056T05_ACC_OWNER_OCCUPATION, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACC_OWNER_OCCUPATION","NULL",NOT_REPEATABLE},
{SMS_F056T05_ACC_OWNER_DATE_OF_BIRTH, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,8,PP_PRINT,"NULL","ACC_OWNER_DATE_OF_BIRTH","NULL",NOT_REPEATABLE},
{SMS_F056T05_ACC_OWNER_EMAIL_ADDS, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"NULL","ACC_OWNER_EMAIL_ADDS","NULL",NOT_REPEATABLE},
},
"SmsF056T05DataProp"
};
/*End PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/

void  InitSmsInfo(TSSmsInfo *msgInfo)
{
   int i;

   for (i=0; i < MAX_SMS_FIELDS+1; i++)
      msgInfo->nFieldPos[i] = 0;
   for (i=0; i < SMS_BITMAP_LEN; i++)
      msgInfo->sBitMap[i] = 0x00;
   msgInfo->nLength = 0;
   msgInfo->nMsgType = 0;
   memset(msgInfo->sData,   '\0', MAX_SMS_DATA_LEN);
   memset(( char *) & (msgInfo->sHeader), '\0', sizeof(TSSmsHeader));
}

int GetSmsFieldType(int field_no)
{
   return(tab_SmsFldInfo[field_no].type);
}

int GetSmsFieldLength(int field_no)
{
   return(tab_SmsFldInfo[field_no].length);
}

/** DREL 14052006 **/

void  InitSmsIcTag  (TSTagSms * msgInfo)
{
   int i;

   for (i = 0; i < MAX_SMS_CHIP_TAG; i++)
   {
      msgInfo->nPosTag [i] = 0;
      msgInfo->nPresent[i] = NOT_PRESENT;
   }
   msgInfo->nLength = 0;
   memset(msgInfo->sChipData,   '\0', MAX_SMS_CHIP_LEN);
}
int GetSmsTagIndice ( char * szTagName)
{
   int nIndice, nSize;

   nSize = sizeof(tab_SmsTagInfo) /sizeof(tag_info_t);
   nIndice = 0;

   do
   {
      if (memcmp(szTagName, tab_SmsTagInfo[nIndice].sTagName, 4) == 0)
         return(nIndice);
      nIndice++;
   }while (nIndice < nSize);
   return(-1);
}
int GetSmsTagType ( int nIndice )
{
   return ( tab_SmsTagInfo[nIndice].nType);
}
int GetSmsTagLength ( int nIndice )
{
   return ( tab_SmsTagInfo[nIndice].nLength);
}
/** DREL 14052006 **/
/******************************************************************************/
/*void InitSmsSupplementalData (TlvInfo* pkTlvInfo)		/*HAL  20202003 ENHS 2020Q2 ART 9.3.4*/
/*{
	pkTlvInfo->pkProperties = &SmsF34T56DataProp;
	ResetTlvInfo(pkTlvInfo);
}*/
void InitSmsSupplementalData  (BerInfo* pkBerInfo) /*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/		
{
	pkBerInfo->pkProperties = &SmsF34T56DataProp;
	ResetBerInfo(pkBerInfo);
}
/******************************************************************************/
void InitSmsElectComDataTlv(TlvInfo* pkTlvInfo)    /*IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/
{
	pkTlvInfo->pkProperties = &SmsElectComDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsAccEnvAddDataTlv(TlvInfo* pkTlvInfo)		/*IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/
{
	pkTlvInfo->pkProperties = &SmsF34T02DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsEuPsd2ScaCsc(TlvInfo* pkTlvInfo)    /*IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/
{
	pkTlvInfo->pkProperties = &SmsF34T4ADataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsTransSpecDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsTransSpecDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsPayFacDataTlv(TlvInfo* pkTlvInfo)		/*AMER20190219 PROD00065991: VISA Enh19.Q2 Art2.4*/
{
	pkTlvInfo->pkProperties = &SmsF104T56DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsAppIdentDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsF104T57DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsSenderDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsF104T5FDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsAddSenderDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsF104T71DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsSupportInfDataTlv(TlvInfo* pkTlvInfo)    		/*IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/
{
	pkTlvInfo->pkProperties = &SmsSupportInfDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsAddOriginalDataTlv(TlvInfo* pkTlvInfo)		/*IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/
{
	pkTlvInfo->pkProperties = &SmsF125T03DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsRecurringPayDataTlv(TlvInfo* pkTlvInfo)  /*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/
{
	pkTlvInfo->pkProperties = &SmsF104T18DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsAdditionalDataTlv(TlvInfo* pkTlvInfo)		/* FZL20220822 PLUTONL-4979*/
{
	pkTlvInfo->pkProperties = &SMSF110DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/********************************************************************************/
void InitSmsKeyDataTlv(TlvInfo* pkTlvInfo)          /* FZL20220822 PLUTONL-4979*/
{
	pkTlvInfo->pkProperties = &SMSF110T04DataProp;
	ResetTlvInfo(pkTlvInfo);
}

void InitSmsVerifDataTlvInfo(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsVerifDataProp;
	ResetTlvInfo(pkTlvInfo);
}

/******************************************************************************/
void InitSmsTokenDataTlvInfo(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsTokenDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsEcomAddDataTlv(TlvInfo* pkTlvInfo)		/*HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
{
	pkTlvInfo->pkProperties = &SmsF34T01DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsAddrVerifDataTlvInfo(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsAddrVerifDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsWalletProviderDataTlv(TlvInfo* pkTlvInfo)		/*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.1*/
{
	pkTlvInfo->pkProperties = &SmsF125T02DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
/*Start PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
void InitSmsCustmRelatdDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsF056DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitSmsAccOwnerDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &SmsF056T05DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*End PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/