#include <stdio.h>
#include <stdlib.h>

#include <header_visa.h>
#include <define.h>
#include <visa_define.h>
#include <p7_common.h>
#include <p7_globals.h>
#include <iso8583.h>
#include <iso_visa.h>

static fld_info_t    tab_VisaFldInfo[] =
{
   { VISA_FIX_BITMAP,  0},	/* BIT_MAP2			 */
   { VISA_VAR_BCD,	 19},   /* CARD_NBR 			 */
   { VISA_FIX_BCD,	  6},	/* PROC_CODE			 */
   { VISA_FIX_BCD,	 12},	/* TRANS_AMOUNT			 */
   { VISA_FIX_BCD,	 12},	/* STLMNT_AMOUNT		 */
   { VISA_FIX_BCD,	 12},	/* Cardholder Billing Amount	 */
   { VISA_FIX_BCD,	 10},	/* XMIT_TIME			 */
   { VISA_FIX_BCD,	  8},	/* Cardholder Billing Fee	 */
   { VISA_FIX_BCD,	  8},	/* CONVRSN_RATE_STLMNT		 */
   { VISA_FIX_BCD,	  8},	/* CONVRSN_RATE_CARD_HLDR_BILLING */

   { VISA_FIX_BCD,	  6},	/* AUDIT_NBR			 */
   { VISA_FIX_BCD,	  6},	/* TRANS_TIME			 */
   { VISA_FIX_BCD,	  4},	/* TRANS_DATE			 */
   { VISA_FIX_BCD,	  4},	/* EXPIRY_DATE			 */
   { VISA_FIX_BCD,	  4},	/* STLMNT_DATE			 */
   { VISA_FIX_BCD,	  4},	/* CNVRSN_DATE			 */
   { VISA_FIX_BCD,	  4},	/* CAPTURE_DATE			 */
   { VISA_FIX_BCD,	  4},	/* MERCHANT_TYPE		 */
   { VISA_FIX_BCD,	  3},	/* ACQR_COUNTRY			 */
   { VISA_FIX_BCD,	  3},	/* PAN_COUNTRY			 */

   { VISA_FIX_BCD,	  3},	/* FORWD_COUNTRY		 */
   { VISA_FIX_BCD,	  4},	/* POS_ENTRY_MODE		 */
   { VISA_FIX_BCD,	  3},	/* Card Sequence Number		 */
   { VISA_FIX_BCD,	  3},	/* Network International Identifier  */
   { VISA_FIX_BCD,	  2},	/* POS_CONDITION		 */
   { VISA_FIX_BCD,	  2},	/* POS_PIN_CAPTURE		 */
   { VISA_FIX_BCD,	  1},	/* Authorization Id Response Lenght */
   { VISA_FIX_ALPHA,	  9},	/* TRANS_FEE			 */
   { VISA_FIX_ALPHA,	  9},	/* Amount Settlement Fee	 */
   { VISA_FIX_ALPHA,	  9},	/* Amount Transaction Processing Fee */
	
   { VISA_FIX_ALPHA,	  9},	/* Amount Setlmnt Processing Fee */
   { VISA_VAR_BCD,	 11},	/* ACQR_ID			 */
   { VISA_VAR_BCD,	 11},	/* FORWD_ID			 */
   { VISA_VAR2_BIN,	65535},	/* PAN_EXTENDED			 */
   /*** { VISA_VAR_BCD,	 37},***/	/* T2_DATA			 */
   { VISA_VAR_HEX,	 37},	/* T2_DATA			 */
   { VISA_VAR_BCD,	104},	/* Track 3 Data			 */
   { VISA_FIX_ALPHA,	 12},	/* REFERENCE_NBR		 */
   { VISA_FIX_ALPHA,	  6},	/* AUTHOR_ID			 */
   { VISA_FIX_ALPHA,	  2},	/* RESPONSE_CODE		 */
   { VISA_FIX_ALPHA,	  3},	/* Service Restriction Code	 */

   { VISA_FIX_ALPHA,	  8},	/* TERMINAL_NBR			 */
   { VISA_FIX_ALPHA,	 15},	/* OUTLET_NBR			 */
   { VISA_FIX_ALPHA,	 40},	/* TERMINAL_ADR			 */
   { VISA_VAR_ALPHA,	 25},	/* ADTNL_RESP_DATA		 */
   { VISA_VAR_ALPHA,	 77},	/* T1_DATA			 */
   { VISA_VAR_ALPHA,	255},	/* Additrional Data Iso		 */
   { VISA_VAR_ALPHA,	255},	/* Additrional Data National	 */
   { VISA_VAR_ALPHA,	255},	/* ADTNL_DATA_PRIV		 */
   { VISA_FIX_BCD,	  3},	/* TRANS_CRNCY			 */
   { VISA_FIX_BCD,	  3},	/* STLMNT_CRNCY			 */

   { VISA_FIX_BCD,	  3},	/* BILLING_CRNCY		 */
   { VISA_FIX_HEX,	 16},	/* PIN_DATA			 */
   { VISA_FIX_BCD,	 16},	/* SECURITY_DATA		 */
   { VISA_VAR_ALPHA,	120},	/* ADTNL_AMOUNTS		 */
   { VISA_VAR_BIN,	255},	/* Reserved Iso			 */
   { VISA_VAR_BIN,	255},	/* Reserved Iso			 */    /*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/ /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2*/   
      { VISA_VAR_ALPHA,	255},	/* Reserved National		 */
   { VISA_VAR_ALPHA,	255},	/* Reserved National		 */
   { VISA_VAR_ALPHA,	 14},	/* GEOGR_DATA			 */
   { VISA_VAR_SBCD,	  6},	/* ADTNL_POS_INFO		 */
   
	
   { VISA_VAR_SBCD,	 36},	/* OTHER_AMOUNTS		 */
   { VISA_VAR_BITMAP, 59},	/* CPS_FIELDS			 */
   { VISA_VAR_BITMAP, 255},	/* PRIV_USE_FIELDS		 */
   { VISA_FIX_BIN,	  8},	/* MAC1				 */
   { NOT_USED,	  0},	/* 				 */
   { VISA_FIX_BCD,	  1},	/* STLMNT_CODE			 */
   { VISA_FIX_BCD,	  1},	/* Extended Payment Code	*/
   { VISA_FIX_BCD,	  3},	/* RECEIVER_COUNTRY		 */
   { VISA_FIX_BCD,	  3},	/* STLMNT_INST_COUNTRY		 */
   { VISA_FIX_BCD,	  3},	/* NW_MNGMT_INFO		 */

   { VISA_FIX_BCD,	  4},	/* Message Number		 */
   { VISA_FIX_BCD,	  4},	/* Message number Last		 */
   { VISA_FIX_BCD,	  6},	/* ACTION_DATE			 */
   { NOT_USED,	  0},	/* CR_NBR			 */
   { NOT_USED,	  0},	/* CR_REV_NBR			 */
   { NOT_USED,	  0},	/* DB_NBR			 */
   { NOT_USED,	  0},	/* DB_REV_NBR			 */
   { VISA_FIX_BCD,	 10},	/* Transfer Number		 */
   { VISA_FIX_BCD,	 10},	/* Transfer Reversal Number	 */
   { VISA_FIX_BCD,	 10},	/* Inquiries Number		 */

   { VISA_FIX_BCD,	 10},	/* Authorizations Number	 */
   { VISA_FIX_BCD,	 12},	/* Credit, Processing Fee Amount */
   { VISA_FIX_BCD,	 12},	/* Credit, Transaction Fee Amount */
   { VISA_FIX_BCD,	 12},	/* Debit, Processing Fee Amount	 */
   { VISA_FIX_BCD,	 12},	/* Debit, Transaction Fee Amount */
   { VISA_FIX_BCD,	 16},	/* CR_AMOUNT			 */
   { VISA_FIX_BCD,	 16},	/* CR_REV_AMOUNT		 */
   { VISA_FIX_BCD,	 16},	/* DB_AMOUNT			 */
   { VISA_FIX_BCD,	 16},	/* DB_REV_AMOUNT		 */
   { VISA_FIX_BCD,	 42},	/* ORIG_DATA			 */

   { VISA_FIX_ALPHA,	  1},	/* FILE_UPDATE			 */
   { VISA_FIX_ALPHA,	  2},	/* FILE_SECURITY		 */
   { VISA_FIX_ALPHA,	  5},	/* Response Indicator		 */
   { VISA_FIX_ALPHA,	  7},	/* Service Indicator		 */
   { VISA_FIX_ALPHA,	 42},	/* REPLACE_AMOUNTS		 */
   { VISA_FIX_BIN,	  8},	/* MSG_SECURITY			 */
   { VISA_FIX_ALPHA,	 17},	/* NET_AMOUNT			 */
   { NOT_USED,	  0},		/*      			 */
   { VISA_VAR_BCD,	 11},	/* STLMNT_INSTITN		 */
   { VISA_VAR_BCD,	 11},	/* RECEIVER_ID			 */

   { VISA_VAR_ALPHA,	 17},	/* FILE_NAME			 */
   { VISA_VAR_ALPHA,	 28},	/* ACCOUNT_ID1			 */
   { VISA_VAR_ALPHA,	 28},	/* ACCOUNT_ID2			 */ /* 103 */
   { VISA_VAR_BIN,	255},	/* Transaction Description	 */
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { NOT_USED,	  0},	/* Reserved Iso			 */  
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { NOT_USED,	  0},	/* Reserved Iso			 */
   { VISA_VAR2_BIN,	  1537},/*Additional Data */   /* FZL20220822 PLUTONL-4979*/

   { VISA_VAR2_BIN,	  1535}, /*Additional Transaction Spec Data*/ /*PLUTONL-9204 AMANS Enh24Q4 VISA AN 1.1*/
   { NOT_USED,	  0},	/* Reserved National		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { VISA_VAR_ALPHA,	 24},	/* ADTNL_TRACE_DATA		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { NOT_USED,	  0},	/* Intra Country Data		 */
   { NOT_USED,	  0},	/* Reserved National		 */
   { VISA_VAR_BCD,	  4},	/* ORIGINAL MESSAGE TYPE ID	 */

   { NOT_USED,	  0},	/* Issuing Institution Id	 */
   { NOT_USED,	  0},	/* Remaining Open to Use	 */
   { VISA_VAR_BIN,	 255},	/* ADR_VERIF_DATA		 */ /*HAL2402 PLUTONL-4391*/
   { NOT_USED,	  0},	/* Free Form Text - Japan	 */
   { VISA_VAR_BIN,	255},	/* SUPPORT_INFO			 */
   /* { NOT_USED,	  0} ,*/	/* Reserved Private		 */
   { VISA_VAR_BITMAP,	 255},   /* VISA PRIVATE USE FIELD */
   { VISA_VAR_ALPHA,	  255},	/* FILE RECORD ACTION AND DATA	 */
   { VISA_FIX_BIN,	  8},	/* MAC2				 */
   { NOT_USED,	  0},	/* Field 129			 */
   { VISA_FIX_HEX,	  6},	/* Terminal Capability Profile   */ /* 130 */

   { VISA_FIX_BCD,	  10},	/* Terminal Verification Results */
   { VISA_FIX_BCD,	  8	},	/* Unpredictable Number          */
   { VISA_FIX_BCD,	  16},	/* Terminal Serial Number        */
   { VISA_VAR_BIN,	 16},	/* Visa Discretionary Data       */
   { VISA_VAR_ALPHA,	 39},	/* Issuer Discretionary Data     */
   { VISA_FIX_HEX,	 16},	/* Issuer Discretionary Data     */
   { VISA_FIX_HEX,	  4},	/* Application Trans. Counter    */
   { VISA_FIX_HEX,	  4},	/* Application Inter. Profile    */
   { VISA_FIX_HEX,	 20},	/* ARPC + Response Code          */
   { NOT_USED,	  0},	/* Field 140			 */

   { NOT_USED,	  0},	/* Field 141			 */
   { VISA_VAR_HEX,	510},	/* Issuer Script                 */
   { VISA_VAR_HEX,	 40},	/* Issuer Script Results         */
   { VISA_FIX_BCD,	  2},	/* Cryptogram Trans Type         */
   { VISA_FIX_BCD,	  4},	/* Terminal Country Code         */
   { VISA_FIX_BCD,	  6},	/* Terminal Trans  Date          */
   { VISA_FIX_BCD,	 12},	/* Cryptogram Amount             */
   { VISA_FIX_BCD,	  4},	/* Cryptogram Currency Code      */
   { VISA_FIX_BCD,	 12},	/* Cryptogram Cash Back          */
   { VISA_FIX_HEX,	 16},	/* Cardholder Card Scheme Crypto.*/

   { NOT_USED,	  0},	/* Field 151			 */
   { NOT_USED,	  0},	/* Field 152			 */
   { NOT_USED,	  0},	/* Field 153			 */
   { NOT_USED,	  0},	/* Field 154			 */
   { NOT_USED,	  0},	/* Field 155			 */
   { NOT_USED,	  0},	/* Field 156			 */
   { NOT_USED,	  0},	/* Field 157			 */
   { NOT_USED,	  0},	/* Field 158			 */
   { NOT_USED,	  0},	/* Field 159			 */
   { NOT_USED,	  0},	/* Field 160			 */

   { NOT_USED,	  0},	/* Field 161			 */
   { NOT_USED,	  0},	/* Field 162			 */
   { NOT_USED,	  0},	/* Field 163			 */
   { NOT_USED,	  0},	/* Field 164			 */
   { NOT_USED,	  0},	/* Field 165			 */
   { NOT_USED,	  0},	/* Field 166			 */
   { NOT_USED,	  0},	/* Field 167			 */
   { NOT_USED,	  0},	/* Field 168			 */
   { NOT_USED,	  0},	/* Field 169			 */
   { NOT_USED,	  0},	/* Field 170			 */

   { NOT_USED,	  0},	/* Field 171			 */
   { NOT_USED,	  0},	/* Field 172			 */
   { NOT_USED,	  0},	/* Field 173			 */
   { NOT_USED,	  0},	/* Field 174			 */
   { NOT_USED,	  0},	/* Field 175			 */
   { NOT_USED,	  0},	/* Field 176			 */
   { NOT_USED,	  0},	/* Field 177			 */
   { NOT_USED,	  0},	/* Field 178			 */
   { NOT_USED,	  0},	/* Field 179			 */
   { NOT_USED,	  0},	/* Field 180			 */

   { NOT_USED,	  0},	/* Field 181			 */
   { NOT_USED,	  0},	/* Field 182			 */
   { NOT_USED,	  0},	/* Field 183			 */
   { NOT_USED,	  0},	/* Field 184			 */
   { NOT_USED,	  0},	/* Field 185			 */
   { NOT_USED,	  0},	/* Field 186			 */
   { NOT_USED,	  0},	/* Field 187			 */
   { NOT_USED,	  0},	/* Field 188			 */
   { NOT_USED,	  0},	/* Field 189			 */
   { NOT_USED,	  0},	/* Field 190			 */

   { NOT_USED,	  0},	/* Field 191			 */
   { VISA_FIX_BIN,	  8},	/* Message Authentication Code   */
};

void  InitVisaInfo(TSVisaInfo *msgInfo)
{
   int i;

   for (i=0; i < MAX_VISA_FIELDS+1; i++)
      msgInfo->nFieldPos[i] = 0;
   for (i=0; i < VISA_BITMAP_LEN; i++)
      msgInfo->sBitMap[i] = 0x00;
   msgInfo->nLength = 0;
   msgInfo->nMsgType = 0;
   memset(msgInfo->sData,   '\0', MAX_VISA_DATA_LEN);
   memset(( char *) & (msgInfo->sHeader), '\0', sizeof(TSVisaHeader));
   msgInfo->msgId = 0;/*PLUTONL-3762*/
   msgInfo->kCtime.tv_sec = 0;  /*ZKO10032022 PLUTONL-4411*/
   msgInfo->kCtime.tv_usec = 0; /*ZKO10032022 PLUTONL-4411*/
}

int GetVisaFieldType(int field_no)
{
   return(tab_VisaFldInfo[field_no].type);
}

int GetVisaFieldLength(int field_no)
{
   return(tab_VisaFldInfo[field_no].length);
}

/*Start IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/

static const TlvInfoProperties	VisaElectComDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_NB_FIELDS,
{
{B1_F34_ACCEPTANCE_ENV_ADD_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F34_ACCEPTANCE_ENV_ADD_DATA","NULL",NOT_REPEATABLE},
{B1_F34_EU_PSD2_SCA_CSC, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F34_EU_PSD2_SCA_CSC","NULL",NOT_REPEATABLE}, /*IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/
{B1_F34_AUTHEN_DATA,FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F34_AUTHEN_DATA","NULL",NOT_REPEATABLE},/*HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
{B1_F34_SUPP_DATA,FT_STRUCT_BER,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F34_SUPP_DATA","NULL",NOT_REPEATABLE},/*HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
{B1_F34_ADD_SERVICE_REQUEST_DATA,FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F34_ADD_SERVICE_REQUEST_DATA","NULL",NOT_REPEATABLE},/*PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/
{B1_F34_ADD_SERVICE_RESULT_DATA,FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F34_ADD_SERVICE_RESULT_DATA","NULL",NOT_REPEATABLE},/*PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/
{B1_F34_DEVICE_PLATFORM_DATA,FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F34_DEVICE_PLATFORM_DATA","NULL",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
{B1_F34_DEVICE_COMMON_DATA,FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","B1_F34_DEVICE_COMMON_DATA","NULL",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/

},
"VisaElectComDataProp"
};

static const TlvInfoProperties	VisaF34T02DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T02_NB_FIELDS,
{
{B1_F34T02_INITIATING_PARTY_ID, FT_STRUCT_TLV,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","INITIATING_PARTY_ID","NULL",NOT_REPEATABLE},
{B1_F34T02_AUTH_OUTAGE_INDICATOR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","AUTH_OUTAGE_INDICATOR","NULL",NOT_REPEATABLE},	/*AEA20210712 Enh21.Q4 Art9.1.2*/
{B1_F34T02_CRDNTL_MER_RELATIONSHIP_IND, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","PAY_CREDNTL_MERCH_RLT_IND","NULL",NOT_REPEATABLE},	/*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art2.2*/
/*start SDR20230714 PLUTONL-6643 Enh23Q4 VISA Art 3.5*/
{B1_F34T02_ACC_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"NULL","ACC_STREET_ADDR","NULL",NOT_REPEATABLE},
{B1_F34T02_ACQ_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,80,PP_PRINT,"NULL","ACQ_NAME","NULL",NOT_REPEATABLE},
{B1_F34T02_ACQ_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"NULL","ACQ_STREET_ADDR","NULL",NOT_REPEATABLE},
{B1_F34T02_ACQ_CITY_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,50,PP_PRINT,"NULL","ACQ_CITY_NAME","NULL",NOT_REPEATABLE},
{B1_F34T02_ACQ_STATE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","ACQ_STATE_CODE","NULL",NOT_REPEATABLE},
{B1_F34T02_ACQ_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,10,PP_PRINT,"NULL","ACQ_POSTAL_CODE","NULL",NOT_REPEATABLE},
{B1_F34T02_ACQ_COUNTRY_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","ACQ_COUNTRY_CODE","NULL",NOT_REPEATABLE},
/*end SDR20230714 PLUTONL-6643 Enh23Q4 VISA Art 3.5*/
{B1_F34T02_PAYFAC_STREET_ADDR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"NULL","PAYFAC_STREET_ADDR","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F34T02_PAYFAC_CITY_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,50,PP_PRINT,"NULL","PAYFAC_CITY_NAME","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F34T02_PAYFAC_STATE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,3,PP_PRINT,"NULL","PAYFAC_STATE_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F34T02_PAYFAC_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,10,PP_PRINT,"NULL","PAYFAC_POSTAL_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F34T02_PAYFAC_CTRY_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","PAYFAC_CTRY_CODE","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
},
"VisaF34T02DataProp"
};
/*END IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/
/*Start IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/
static const TlvInfoProperties	VisaF34T4ADataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T4A_NB_FIELDS,
{
{B1_F034T4A_TRST_MER_EXEM_IND,  FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","Trusted Merchant Exemption Indicator","",NOT_REPEATABLE},
{B1_F034T4A_LOW_VAL_EXEM_IND,  FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","Low Value Exemption Indicator","",NOT_REPEATABLE},
{B1_F034T4A_SCP_IND,  FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","Secure Corporate Payment (SCP) Indicator","",NOT_REPEATABLE},
{B1_F034T4A_TRA_EXEM_IND,  FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","Transaction Risk Analysis (TRA) Exemption Indicator","",NOT_REPEATABLE},
{B1_F034T4A_DELEGATED_AUTH_IND,  FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","Delegated Authentication Indicator","",NOT_REPEATABLE},
{B1_F034T4A_REASONS_NOT_HONORING_EXEM,  FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,80,PP_PRINT,"","Reasons For Not Honoring Exemptions","",NOT_REPEATABLE},
{B1_F034T4A_TRA_SCORE,  FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","TRA Score","",NOT_REPEATABLE},
},
"VisaF34T4ADataProp"
};
/*END IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/

/*Start HAL  20202003 ENHS 2020Q2 ART 9.3.4*/
static const BerInfoProperties	VisaF34T56DataProp = {
VISA_F34_T56_NB_FIELDS,
{
   {B1_F34T56_SESSION_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,32,PP_PRINT,"","Session ID","",NOT_REPEATABLE},
   {B1_F34T56_CAVV_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","CAVV Type","",NOT_REPEATABLE},
   {B1_F34T56_CAVV_VERSION_NUMBER, FT_SINGLE,FF_BCD/*FF_ALPHA_N*/,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","CAVV Version Number","",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
   {B1_F34T56_VISA_RISK_AUTHEN_SCORE, FT_SINGLE,FF_BCD/*FF_ALPHA_N*/,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","Visa Risk-based Authentication Score","",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
   {B1_F34T56_DEVICE_ID_VELOCITY_COUNT, FT_SINGLE,FF_BCD/*FF_ALPHA_N*/,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","Device ID Velocity","",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
   {B1_F34T56_IP_ADDR_VELOCITY_COUNT, FT_SINGLE,FF_BCD/*FF_ALPHA_N*/,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","IP Address Velocity Count","",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
   {B1_F034_T56_VCAS_SCORE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"","VCAS_SCORE","",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
{B1_F34T56_THIRD_PARTY_ID, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,64,PP_PRINT,"","THIRD_PARTY_ID","",NOT_REPEATABLE},/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
{B1_F34T56_THIRD_PARTY_RISK_SCORE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,5,PP_PRINT,"","THIRD_PARTY_RISK_SCORE","",NOT_REPEATABLE},/*NAB PLUTONL-9857-Enh 2025Q2 VISA 3.8*/
   {B1_F034_T56_CONSUMER_DEVICE_IP, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,39,PP_PRINT,"","CONSUMER_DEVICE_IP","",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
   {B1_F034_T56_SECURE_REMOTE_COMMERCE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"","SECURE_REMOTE_COMMERCE","",NOT_REPEATABLE},/*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
},
"VisaF34T56DataProp"
};
/*End HAL  20202003 ENHS 2020Q2 9.3.4*/
/*end IBE PLUTONL-5640*/

static const TlvInfoProperties	VisaTransSpecDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_NB_FIELDS,
{
{B1_F104_PURCHASE_LINE_ITEM_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","PURCHASE_LINE_ITEM_DATA","NULL",NOT_REPEATABLE},
/*{B1_F104_DIAL_TERMINAL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","DIAL_TERMINAL_DATA","NULL",NOT_REPEATABLE},*/
{B1_F104_PAY_FAC_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","PAY_FAC_DATA","NULL",NOT_REPEATABLE},
{B1_F104_BUSINESS_APP_ID, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","BUSINESS_APP_ID","NULL",NOT_REPEATABLE},
{B1_F104_HEALTHCARE_ELIGIBILITY_INQ, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","HEALTHCARE_ELIGIBILITY_INQ","NULL",NOT_REPEATABLE},
{B1_F104_PROMOTION_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","PROMOTION_DATA","NULL",NOT_REPEATABLE},
{B1_F104_VISA_RISK_ASSESSMENT_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","VISA_RISK_ASSESSMENT_DATA","NULL",NOT_REPEATABLE},
{B1_F104_COMMERCIAL_CARD_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","COMMERCIAL_CARD_DATA","NULL",NOT_REPEATABLE},
{B1_F104_INSTALLMENT_PAYMENT_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","INSTALLMENT_PAYMENT_DATA","NULL",NOT_REPEATABLE},
{B1_F104_SENDER_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","SENDER_DATA","NULL",NOT_REPEATABLE},
{B1_F104_AIRLINE_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","AIRLINE_DATA","NULL",NOT_REPEATABLE},
{B1_F104_CAR_RENTAL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","CAR_RENTAL_DATA","NULL",NOT_REPEATABLE},
{B1_F104_LODGING_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","LODGING_DATA","NULL",NOT_REPEATABLE},
{B1_F104_NON_INDUSTRY_SPECIFIC_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","NON_INDUSTRY_SPECIFIC_DATA","NULL",NOT_REPEATABLE},
{B1_F104_MASTERCARD_MEMBER_DEF_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","MASTERCARD_MEMBER_DEF_DATA","NULL",NOT_REPEATABLE},
{B1_F104_AMEX_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","AMEX_DATA","NULL",NOT_REPEATABLE},
{B1_F104_MULTIPLE_PAYMENT_FORMS, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","MULTIPLE_PAYMENT_FORMS","NULL",NOT_REPEATABLE},
{B1_F104_TRAVEL_TAG_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","TRAVEL_TAG_DATA","NULL",NOT_REPEATABLE},
{B1_F104_ISSUER_SUPPLIED_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","ISSUER_SUPPLIED_DATA","NULL",NOT_REPEATABLE},
{B1_F104_LOAN_DETAILS, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","LOAN_DETAILS","NULL",NOT_REPEATABLE},
{B1_F104_FREE_FORM_DESCRIPTION_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","FREE_FORM_DESCRIPTION_DATA","NULL",NOT_REPEATABLE},
{B1_F104_ADDITIONAL_SENDER_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","ADDITIONAL_SENDER_DATA","NULL",NOT_REPEATABLE},
{B1_F104_FREE_FORM_TEXT_ORG_CR_TRN, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_FIX,LU_BYTE,256,PP_PRINT,"NULL","FREE_FORM_TEXT_ORG_CR_TRN","NULL",NOT_REPEATABLE},
{B1_F104_RECURRING_PAY, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","RECURRING_PAY","NULL",NOT_REPEATABLE},   /*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/
},
"VisaTransSpecDataProp"
};

static const TlvInfoProperties	VisaF104T56DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T56_NB_FIELDS,
{
{B1_F104T56_PAY_FAC_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,11,PP_PRINT,"NULL","PAY_FAC_ID","NULL",NOT_REPEATABLE},
{B1_F104T56_SUB_MER_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,15,PP_PRINT,"NULL","SUB_MER_ID","NULL",NOT_REPEATABLE},
{B1_F104T56_ISO_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,11,PP_PRINT,"NULL","ISO_ID","NULL",NOT_REPEATABLE},
{B1_F104T56_ACC_LEGAL_BUSINESS_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"NULL","ACC_LEGAL_BUSINESS_NAME","NULL",NOT_REPEATABLE},   /*ZKO 05042022 PLUTONL-4550 ENH 22.Q2 VISA Art3.2*//*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
{B1_F104T56_PAY_FACILITATOR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"NULL","PAY_FACILITATOR","NULL",NOT_REPEATABLE},  /*ZKO 05042022 PLUTONL-4550 ENH 22.Q2 VISA Art3.2*//*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
},
"VisaF104T56DataProp"
};

/*Start PLUTONL-8878 Enh24Q4 AMANS AN 3.20*/
static const TlvInfoProperties	VisaF104T57DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T57_NB_FIELDS,
{
{B1_F104_T57_BUSINESS_APP_ID, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","BUSINESS_APP_ID","",NOT_REPEATABLE},
{B1_F104_T57_SERVICE_PROC_TYPE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","SERVICE_PROC_TYPE","",NOT_REPEATABLE},
{B1_F104_T57_DEFER_OCT_REQ_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,6,PP_PRINT,"NULL","DEFER_OCT_REQ_TYPE","",NOT_REPEATABLE},
{B1_F104_T57_PAY_PURPOSE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,12,PP_PRINT,"NULL","PAY_PURPOSE","",NOT_REPEATABLE},	/*AEA20210712 Enh21.Q4 Art2.9*/
{B1_F104_T57_MAX_PROC_DATE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_NIBBLES,4,PP_PRINT,"NULL","MAX_PROC_DATE","",NOT_REPEATABLE},
{B1_F104_T57_PT_SRC_FUNDS, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","FUNDS_SOURCE","",NOT_REPEATABLE},
},
"VisaF104T57DataProp"
};
/*End PLUTONL-8878 Enh24Q4 AMANS AN 3.20*/

/*Start IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/
static const TlvInfoProperties	VisaF104T18DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T18_NB_FIELDS,
{
{B1_F104T18_RECURRING_PAY_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,B1_F104T18_RECURRING_PAY_TYPE_LEN,PP_PRINT,"NULL","RECURRING_PAY_TYPE","NULL",NOT_REPEATABLE},	/*FF_ALPHA_N---> FF_BCD & LU_BYTE--->LU_NIBBLES IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{B1_F104T18_PAY_AMNT_IND_PER_TRANS, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,B1_F104T18_PAY_AMNT_IND_PER_TRANS_LEN,PP_PRINT,"NULL","PAY_AMNT_IND_PER_TRANS","NULL",NOT_REPEATABLE},	/*FF_ALPHA_N---> FF_BCD & LU_BYTE--->LU_NIBBLES IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{B1_F104T18_NBR_RECURRING_PAY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,B1_F104T18_NBR_RECURRING_PAY_LEN,PP_PRINT,"NULL","NBR_RECURRING_PAY","NULL",NOT_REPEATABLE},	/*FF_ALPHA_N---> FF_BCD & LU_BYTE--->LU_NIBBLES IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{B1_F104T18_FREQ_RECURRING_PAY, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,B1_F104T18_FREQ_RECURRING_PAY_LEN,PP_PRINT,"NULL","FREQ_RECURRING_PAY","NULL",NOT_REPEATABLE},	/*FF_ALPHA_N---> FF_BCD & LU_BYTE--->LU_NIBBLES IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{B1_F104T18_REGISTR_REF_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,B1_F104T18_REGISTR_REF_NBR_LEN,PP_PRINT,"NULL","REGISTR_REF_NBR","NULL",NOT_REPEATABLE},
{B1_F104T18_MAX_RECURRING_PAY_AMNT, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,LU_BYTE,B1_F104T18_MAX_RECURRING_PAY_AMNT_LEN,PP_PRINT,"NULL","MAX_RECURRING_PAY_AMNT","NULL",NOT_REPEATABLE},	/*FF_ALPHA_N---> & LU_BYTE--->LU_NIBBLES FF_BCD IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
{B1_F104T18_VALIDATION_IND, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,B1_F104T18_VALIDATION_IND_LEN,PP_PRINT,"NULL","VALIDATION_IND","NULL",NOT_REPEATABLE},	/*FF_ALPHA_N---> FF_BCD & LU_BYTE--->LU_NIBBLES  IZL 26092022 PLUTONL-5185 ENH 22.Q4 VISA Art3.17*/
},
"VisaF104T18DataProp"
};
/*End IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/

/*Start HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
static const TlvInfoProperties	VisaF34T01DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T01_NB_FIELDS,
{
{B1_F34T01_PROTOCOL_VERSION_NUMBER, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,8,PP_PRINT,"NULL","B1_F34T02_PROTOCOL_VERSION_NUMBER","NULL",NOT_REPEATABLE},
{B1_F34T01_AUTHENTICATION_PROGRAM, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,2,PP_PRINT,"NULL","B1_F34T01_AUTHENTICATION_PROGRAM","NULL",NOT_REPEATABLE}, /*PLUTONL-5548 Enh 2023Q2  Visa 1.2 AHA20221221*/
{B1_F34T01_AUTHEN_DATA_QUALITY_INDC, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","AUTHEN_DATA_QUALITY_INDC","NULL",NOT_REPEATABLE}, /*PLUTONL-8809 AMANS Enh2024Q4 VISA 3.9*/ 
{B1_F34T01_BROWSER_IP_ADDRESS, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,45,PP_PRINT,"NULL","3DS_BROWSER_IP_ADDRESS","NULL",NOT_REPEATABLE},  /*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
{B1_F34T01_3DS_APP_IP_ADDRESS, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,45,PP_PRINT,"NULL","3DS_APP_IP_ADDRESS","NULL",NOT_REPEATABLE},  /*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
{B1_F34T01_SHIPPING_INDICATOR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","SHIPPING_INDICATOR","NULL",NOT_REPEATABLE},  /*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
},
"VisaF34T01DataProp"
};
/*END HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/

static const TlvInfoProperties	VisaF104T5FDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T5F_NB_FIELDS,
{
{B1_F104T5F_SENDER_REF_NBR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,16,PP_PRINT,"NULL","SENDER_REF_NBR","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_ACCOUNT_NO, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,34,PP_PRINT,"NULL","SENDER_ACCOUNT_NO","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,30,PP_PRINT,"NULL","SENDER_NAME","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_STREET_ADDR, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,35,PP_PRINT,"NULL","SENDER_STREET_ADDR","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_CITY_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,25,PP_PRINT,"NULL","SENDER_CITY_NAME","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_STATE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","SENDER_STATE","NULL",NOT_REPEATABLE},
{B1_F104T5F_SENDER_COUNTRY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"NULL","SENDER_COUNTRY","NULL",NOT_REPEATABLE},
{B1_F104T5F_FUNDS_SOURCE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","FUNDS_SOURCE","NULL",NOT_REPEATABLE},
{B1_F104T5F_RECIPIENT_NAME, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,30,PP_PRINT,"NULL","RECIPIENT_NAME","NULL",NOT_REPEATABLE},
},
"VisaF104T5FDataProp"
};
/*
static const TlvInfoProperties	VisaF104T71DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F104_T71_NB_FIELDS,
{
{B1_F104T71_FREE_FORM_DATA, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,45,PP_PRINT,"","FREE_FORM_DATA","",NOT_REPEATABLE},
},
"VisaF104T71DataProp"
};
*/

 /*Start PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/

static const TlvInfoProperties	VisaF34T03DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T03_NB_FIELDS,
{
{B1_F34T03_ACC_NAME_REQUEST, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,1,PP_PRINT,"NULL","B1_F34T03_ACC_NAME_REQUEST","NULL",NOT_REPEATABLE},
},
"VisaF34T03DataProp"
};


static const TlvInfoProperties	VisaF34T04DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T04_NB_FIELDS,
{
{B1_F34T04_ACC_NAME_REQ_RES, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,8,PP_PRINT,"NULL","B1_F34T02_PROTOCOL_VERSION_NUMBER","NULL",NOT_REPEATABLE},
{B1_F34T04_FULL_NAME_MATCHING_RES, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,2,PP_PRINT,"NULL","B1_F34T04_FULL_NAME_MATCHING_RES","NULL",NOT_REPEATABLE}, 
{B1_F34T04_LAST_NAME_MATCHING_RES, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,35,PP_PRINT,"NULL","B1_F34T04_LAST_NAME_MATCHING_RES","NULL",NOT_REPEATABLE}, 
{B1_F34T04_MIDDLE_NAME_MATCHING_RES, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,35,PP_PRINT,"NULL","B1_F34T04_MIDDLE_NAME_MATCHING_RES","NULL",NOT_REPEATABLE}, 
{B1_F34T04_FIRST_NAME_MATCHING_RES, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,35,PP_PRINT,"NULL","B1_F34T04_FIRST_NAME_MATCHING_RES","NULL",NOT_REPEATABLE},

},
"VisaF34T04DataProp"
};
 /*End PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/
/*Start NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7 */

static const TlvInfoProperties	VisaF34T06DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T06_NB_FIELDS,
{
{B1_F34T06_PLATFORM_DEVICE_ID, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,64,PP_PRINT,"NULL","PLATFORM_DEVICE_ID","NULL",NOT_REPEATABLE},
{B1_F34T06_PLATFORM_DEVICE_TYPE, FT_SINGLE,FF_BCD,AF_EBCDIC,FL_FIX,/*LU_BYTE*/LU_NIBBLES,2,PP_PRINT,"NULL","PLATFORM_DEVICE_TYPE","NULL",NOT_REPEATABLE},	
},
"VisaF34T06DataProp"
};

static const TlvInfoProperties	VisaF34T07DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F34_T07_NB_FIELDS,
{
{B1_F34T07_SDK_APP_ID, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,37,PP_PRINT,"NULL","SDK_APP_ID","NULL",NOT_REPEATABLE},
},
"VisaF34T07DataProp"
};

/*End NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/

static const TlvInfoProperties	Base1VerifDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,2,
{
{B1_F123_ADDR_VERIF_DATA,	FT_STRUCT_TLV	,FF_BIN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,256	,PP_PRINT	,"NULL"	,"ADDR_VERIF_DATA"	,B1_F123_T66_PROP	,NOT_REPEATABLE},
{B1_F123_TOKEN_DATA,		FT_STRUCT_TLV	,FF_BIN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,256	,PP_PRINT	,"NULL"	,"TOKEN_DATA"		,B1_F123_T68_PROP	,NOT_REPEATABLE},
},
"Base1VerifDataProp"
};

static const TlvInfoProperties	Base1AddrVerifDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,B1_F123_T66_NB_FIELDS, /*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
{
{B1_F123_T66_POSTAL_CD	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,9	,PP_PRINT	,"NULL"	,"POSTAL_CODE"	,"NULL"	,NOT_REPEATABLE},
{B1_F123_T66_STREE_ADDR	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,40	,PP_PRINT	,"NULL"	,"STREET_ADDR"	,"NULL"	,NOT_REPEATABLE},
{B1_F123_T66_CH_SHIP_HASH	,FT_SINGLE	,FF_HEX	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,32	,PP_PRINT	,"NULL"	,"CARDHOLDER_SHIPPING_HASH"	,"NULL"	,NOT_REPEATABLE},/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/ /* + */ /*SKA17032023 PLUTONL-6018 Enh 2023Q2*/
},
"Base1AddrVerifDataProp"
};


static const TlvInfoProperties	Base1TokenDataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F123_T68_NB_FIELDS,     /*8-->9 IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art2.2*/ /* PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221  change nb of fields from 9->10*/
{
{B1_F123_T68_TOKEN		,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_LL	,LU_BYTE	,19	,PP_PRINT	,"NULL",	"TOKEN"			,"NULL"	,NOT_REPEATABLE},
{B1_F123_T68_TKN_ASS_LVL	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,2	,PP_PRINT	,"NULL",	"TOKEN_ASS_LVL"	,"NULL"	,NOT_REPEATABLE},
{B1_F123_T68_TKN_REQ_ID	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,11	,PP_PRINT	,"NULL",	"TOKEN_REQ_ID"	,"NULL"	,NOT_REPEATABLE},
{B1_F123_T68_TKN_RANGE	,FT_SINGLE	,FF_ALPHA_ANS	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,9	,PP_PRINT	,"NULL",	"PAN_RANGE"		,"NULL"	,NOT_REPEATABLE},
{B1_F123_T68_TKN_REFERENCE_ID		,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,32	,PP_PRINT	,"NULL",	"TKN_REFERENCE_ID"			,"NULL"	,NOT_REPEATABLE}, /*HAL2402 PLUTONL-4391*/
{B1_F123_T68_TKN_EXPIRATION_DATE	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,4	,PP_PRINT	,"NULL",	"TKN_EXPIRATION_DATE"	,"NULL"	,NOT_REPEATABLE},       /*HAL2402 PLUTONL-4391*/
{B1_F123_T68_TKN_TYPE	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,2	,PP_PRINT	,"NULL",	"TKN_TYPE"	,"NULL"	,NOT_REPEATABLE},                            /*HAL2402 PLUTONL-4391*/
{B1_F123_T68_TKN_STATUS	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,1	,PP_PRINT	,"NULL",	"TKN_STATUS"		,"NULL"	,NOT_REPEATABLE},                      /*HAL2402 PLUTONL-4391*/
{B1_F123_T68_AUTO_FILL_IND	,FT_SINGLE	,FF_ALPHA_AN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,1	,PP_PRINT	,"NULL",	"AUTO_FILL_IND"		,"NULL"	,NOT_REPEATABLE}, /*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art2.2*/
{B1_F123_T68_TKN_AUTHENTICATION_AMNT	,FT_SINGLE	,FF_BIN	,AF_EBCDIC	,FL_FIX	,LU_BYTE	,6	,PP_PRINT	,"NULL",	"TKN_AUTHENTICATION_AMNT"		,"NULL"	,NOT_REPEATABLE}, /* PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221  */ /* En23Q2-Hotfix-PLUTONL-6134 */ 
},
"Base1TokenDataProp"
};

/*Start IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/


static const TlvInfoProperties	VisaSupportInfDataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F125_NB_FIELDS,
{
{B1_F125_TOKEN_DEVICE, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","TOKEN_DEVICE","NULL",NOT_REPEATABLE},  /*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
{B1_F125_WALLET_PROVIDER, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","WALLET_PROVIDER","NULL",NOT_REPEATABLE},  /*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.1*/
{B1_F125_ADD_ORIGINAL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LL,LU_BYTE,256,PP_PRINT,"NULL","ADD_ORIGINAL_DATA","NULL",NOT_REPEATABLE},
},
"VisaSupportInfDataProp"
};

/*Start PLUTONL-9204 AMANS Enh24Q4 VISA AN 1.1*/
static const TlvInfoProperties	VisaF111DataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F111_NB_FIELDS,
{
{B1_F111_RATE_INFO, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_BB,LU_BYTE,1535,PP_HIDE,"NULL","RATE_INFO","NULL",NOT_REPEATABLE},
{B1_F111_JURISD_SETTL_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_BB,LU_BYTE,1535,PP_HIDE,"NULL","JURISD_SETTL_DATA","NULL",NOT_REPEATABLE},
{B1_F111_RESP_CLEARING_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_BB,LU_BYTE,1535,PP_PRINT,"NULL","RESP_CLEARING_DATA","NULL",NOT_REPEATABLE},
},
"VisaF111DataProp"
};
static const TlvInfoProperties	VisaF111T56DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F111_T56_NB_FIELDS,
{
{B1_F111_T56_ACCOUNT_FUNDING_SRC , FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","ACCOUNT_FUNDING_SRC","NULL",NOT_REPEATABLE},
{B1_F111_T56_APPLIED_ACI		 , FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","APPLIED_ACI","NULL",NOT_REPEATABLE},
{B1_F111_T56_APPLIED_MARKED_SPEC_DATA , FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","APPLIED_MARKED_SPEC_DATA","NULL",NOT_REPEATABLE},
{B1_F111_T56_APPLIED_CH_ID_METHOD , FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","APPLIED_CH_ID_METHOD","NULL",NOT_REPEATABLE},
{B1_F111_T56_APPLIED_ECI , FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","APPLIED_ECI","NULL",NOT_REPEATABLE},
{B1_F111_T56_DOWNGRADE_REASON_CODE , FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","DOWNGRADE_REASON_CODE","NULL",NOT_REPEATABLE},
},
"VisaF111T56DataProp"
};
/*End PLUTONL-9204 AMANS Enh24Q4 VISA AN 1.1*/

/*Start PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
static const TlvInfoProperties	VisaF125T01DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F125_T01_NB_FIELDS,
{
{B1_F125_T01_IP_ADDR, FT_STRUCT_TLV,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,30,PP_PRINT,"NULL","TOKEN_DEVICE address IP","NULL",NOT_REPEATABLE},

},
"VisaF125T01DataProp"
};
/*End PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/

/*Start IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.1*/
static const TlvInfoProperties	VisaF125T02DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F125_T02_NB_FIELDS,
{
{B1_F125T02_OVERALL_ASSESSMENT, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","OVERALL_ASSESSMENT","NULL",NOT_REPEATABLE},
{B1_F125T02_WP_DEVICE_SCORE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","WP_DEVICE_SCORE","NULL",NOT_REPEATABLE},/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
{B1_F125T02_WP_ACCOUNT_SCORE, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_FIX,LU_BYTE,8,PP_PRINT,"NULL","WP_ACCOUNT_SCORE","NULL",NOT_REPEATABLE},/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
},
"VisaF125T02DataProp"
};
/*End IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.1*/

static const TlvInfoProperties	VisaF125T03DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F125_T03_NB_FIELDS,
{
{B1_F125T03_ORIGINAL_TRA_ID, FT_STRUCT_TLV,FF_BCD,AF_EBCDIC,FL_LL,LU_BYTE,8,PP_PRINT,"NULL","ORIGINAL_TRA_ID","NULL",NOT_REPEATABLE},
},
"VisaF125T03DataProp"
};
/*End IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/


/*Start IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/
static const TlvInfoProperties	VisaF056DataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F056_NB_FIELDS,
{
{B1_F056_ACCOUNT_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","ACCOUNT_DATA","",NOT_REPEATABLE},
{B1_F056_CONTACT_INFO, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","CONTACT_INFO","",NOT_REPEATABLE},
{B1_F056_CUSTOMER_ID_DATA, FT_STRUCT_TLV,FF_BIN,AF_EBCDIC,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","CUSTOMER_ID_DATA","B1_F056_T03_PROP",NOT_REPEATABLE},
{B1_F056_ACCOUNT_OWNER_DATA, FT_STRUCT_TLV,FF_BIN/*FF_ALPHA_ANS*/,AF_EBCDIC,FL_LLL,LU_BYTE,256,PP_PRINT,"NULL","ACCOUNT_OWNER_DATA","",NOT_REPEATABLE},/*PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/

},
"VisaF056DataProp"
};
/*Start NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
static const TlvInfoProperties	VisaF056T02DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,1,
{
{B1_F056T02_OTHER_EMAIL_ADD, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","OTHER_EMAIL_ADDS","",0,"",-1,NOT_REPEATABLE},
},
"B1_F056_T02_PROP"
};
/*End NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
static const TlvInfoProperties	VisaF056T03DataProp = {
2,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F056_T03_NB_FIELDS,
{
{B1_F056T03_DATA_SENDER_RECIP, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_L,LU_BYTE,2,PP_PRINT,"NULL","DATA_SENDER_RECIP","NULL",NOT_REPEATABLE},
{B1_F056T03_ID_TYPE_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,4,PP_PRINT,"NULL","ID_TYPE_CODE","NULL",NOT_REPEATABLE},
{B1_F056T03_ID_SUBTYPE_CODE, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_FIX,LU_BYTE,2,PP_PRINT,"NULL","ID_SUBTYPE_CODE","NULL",NOT_REPEATABLE},
{B1_F056T03_ACQ_POPULATED_ID_VAL, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACQ_POPULATED_ID_VAL","NULL",NOT_REPEATABLE},
{B1_F056T03_CUSTOMER_ID_ISS_CNTRY_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_L,LU_BYTE,3,PP_PRINT,"NULL","CUSTOMER_ID_ISS_CNTRY_CODE","NULL",NOT_REPEATABLE},
},
"VisaF056T03DataProp"
};
/*End IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.2*/

/* Start FZL20220822 PLUTONL-4979 */
static const TlvInfoProperties	VisaF110DataProp = {
1,2,TLV_LT_BIN,TLV_LT_BIN,VISA_F110_NB_FIELDS,
{
{B1_F110T04_KEY_DATA, FT_STRUCT_TLV,FF_BIN,AF_ASCII,FL_LL,LU_BYTE,1537,PP_HIDE,"NULL","B1_F110_T04_PROP","NULL",NOT_REPEATABLE}

},
"VisaF110DataProp"
};
/* field 110 tag 04 details */
static const TlvInfoProperties	VisaF110T04DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,VISA_F110_T04_NB_FIELDS,
{
{B1_F110_T04_CONTROL,  FT_SINGLE,FF_HEX,AF_ASCII,FL_FIX,LU_BYTE,1,PP_PRINT,"NULL","Control","NULL",NOT_REPEATABLE},
{B1_F110_T04_KEY_IDENT,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,11,PP_PRINT,"","key set identifier","NULL",NOT_REPEATABLE},
{B1_F110_T04_ALGO,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,2,PP_PRINT,"","Algorithm","NULL",NOT_REPEATABLE},
{B1_F110_T04_KEY_PROTECT,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,2,PP_PRINT,"","key protection","NULL",NOT_REPEATABLE},
{B1_F110_T04_KEY_IND,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,2,PP_PRINT,"","key index","NULL",NOT_REPEATABLE},
{B1_F110_T04_ENCT_DATA ,  FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_BB,LU_BYTE,512,PP_PRINT,"","Encryption Data","NULL",NOT_REPEATABLE},
{B1_F110_T04_CHECK_VALUE,  FT_SINGLE,FF_HEX,AF_EBCDIC,FL_BB,LU_BYTE,128,PP_PRINT,"","key checksum value","NULL",NOT_REPEATABLE},

},
"VisaF110T04DataProp"
};
/* end FZL20220822 PLUTONL-4979 */


/*Start PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/

static const TlvInfoProperties	VisaF056T05DataProp = {
1,1,TLV_LT_BIN,TLV_LT_BIN,16/*VISA_F056_T05_NB_FIELDS*/, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*//*NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
{
{B1_F056T05_ACCOUNT_OWNER_TYPE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_L,LU_BYTE,2,PP_PRINT,"NULL","ACCOUNT_OWNER_TYPE","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_NAME_GIVEN, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACCOUNT_OWNER_NAME_GIVEN","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_NAME_MIDDLE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACCOUNT_OWNER_NAME_MIDDLE","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_NAME_LAST, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACCOUNT_OWNER_NAME_LAST","NULL",NOT_REPEATABLE},
{B1_F056T05_ACC_OWNER_NATIONALITY, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,3,PP_PRINT,"NULL","ACC_OWNER_NATIONALITY","NULL",NOT_REPEATABLE},/*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F056T05_ACC_OWNER_CTRY_OF_BIRTH, FT_SINGLE,FF_ALPHA_AN,AF_EBCDIC,FL_LL,LU_BYTE,3,PP_PRINT,"NULL","ACC_OWNER_CTRY_OF_BIRTH","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F056T05_ACC_OWNER_OCCUPATION, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,35,PP_PRINT,"NULL","ACC_OWNER_OCCUPATION","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F056T05_ACC_OWNER_DATE_OF_BIRTH, FT_SINGLE,FF_ALPHA_N,AF_EBCDIC,FL_LL,LU_BYTE,8,PP_PRINT,"NULL","ACC_OWNER_DATE_OF_BIRTH","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
{B1_F056T05_ACC_OWNER_EMAIL_ADDS, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"NULL","ACC_OWNER_EMAIL_ADDS","NULL",NOT_REPEATABLE}, /*PLUTONL-8807 AMANS Enh2024Q4 VISA 3.2 20240702*/
/*Start NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
{B1_F056T05_ACCOUNT_OWNER_ADDR_LINE1, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","ACCOUNT_OWNER_ADDR_LINE1","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_ADDR_LINE2, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","ACCOUNT_OWNER_ADDR_LINE2","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_STREET_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,99,PP_PRINT,"","ACCOUNT_OWNER_STREET_NAME","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_POSTAL_CODE, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,16,PP_PRINT,"","ACCOUNT_OWNER_POSTAL_CODE","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_CITY_NAME, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_LL,LU_BYTE,25,PP_PRINT,"","ACCOUNT_OWNER_CITY_NAME","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_COUNTRY_SUBDIV_CODE_MAJOR, FT_SINGLE,FF_ALPHA_ANS,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","ACCOUNT_OWNER_COUNTRY_SUBDIV_CODE_MAJOR","NULL",NOT_REPEATABLE},
{B1_F056T05_ACCOUNT_OWNER_COUNTRY_CODE, FT_SINGLE,FF_ALPHA_A,AF_EBCDIC,FL_FIX,LU_BYTE,3,PP_PRINT,"","ACCOUNT_OWNER_COUNTRY_CODE","NULL",NOT_REPEATABLE},
/*End NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
},
"VisaF056T05DataProp"
};
/*End PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/

/**Start MKB221208**/
static tag_info_t  tab_VisaTagInfo[] =
{
   { "7100",  VISA_TAG_VAR_HEX,   0},/* Issuer Script Template 1              */
   { "7200",  VISA_TAG_VAR_HEX,   0},/* Issuer Script Template 2              */
   { "8200",  VISA_TAG_VAR_HEX,   2},/* Application Interchange Profile       */
   { "8400",  VISA_TAG_VAR_HEX,   0},/* Dedicated File Name                   */
   { "9100",  VISA_TAG_VAR_HEX,   0},/* Issuer Authentication Data            */
   { "9500",  VISA_TAG_VAR_HEX,   5},/* Terminal Verification Results         */
   { "9A00",  VISA_TAG_VAR_HEX,   6},/* Transaction Date                      */
   { "9C00",  VISA_TAG_VAR_HEX,   2},/* Transaction TYPE                      */
   { "C000",  VISA_TAG_VAR_HEX,   8},/* Secondary PIN Block             	  */	/*AMER20180307 PROD00054205: Enh18.Q2 Art 8.1.1*/
   { "5F2A",  VISA_TAG_VAR_HEX,   3},/* Transaction Currency Code             */
   { "9F02",  VISA_TAG_VAR_HEX,  12},/* Transaction Amount                    */
   { "9F03",  VISA_TAG_VAR_HEX,  12},/* Other Amount                          */
   /* { "9F09",  VISA_TAG_VAR_HEX,   2},*/ /* Terminal Application Version Number   */
   { "9F10",  VISA_TAG_VAR_HEX,   0},/*  Issuer Application Data              */
   { "9F1A",  VISA_TAG_VAR_HEX,   3},/* Terminal Country Code                 */
   { "9F1E",  VISA_TAG_VAR_ALPHA, 8},/* Interface Device Serial Number        */
   { "9F26",  VISA_TAG_VAR_HEX,   8},/* Application cryptogram                */
   { "9F27",  VISA_TAG_VAR_HEX,   1},/* Cryptogram Information Data           */
   { "9F33",  VISA_TAG_VAR_HEX,   3},/* Terminal Capabilities                 */
   { "8A00",  VISA_TAG_VAR_ALPHA, 2},/* Authorization Response Code           */
   { "9F34",  VISA_TAG_VAR_HEX,   3},/* Cardholder Verification Method        */
   { "9F35",  VISA_TAG_VAR_HEX,   2},/* Terminal Type                         */
   { "9F36",  VISA_TAG_VAR_HEX,   2},/* Application Transaction Counter       */
   { "9F37",  VISA_TAG_VAR_HEX,   4},/* Unpredictable Number                  */
   { "9F41",  VISA_TAG_VAR_HEX,   0},/* Transaction Sequence Number           */
   /*{ "9F53",  VISA_TAG_VAR_HEX,   1}, */ /* Transaction Category Code             */
   { "9F6E",  VISA_TAG_VAR_HEX,   1},/* Form Factor Indicator             	  */	/*AMER20180307 PROD00054205: Enh18.Q2 Art 3.6*/
};


void  InitVisaIcTag  (TSTagVisa * msgInfo)
{
   int i;

   for (i = 0; i < MAX_VISA_CHIP_TAG; i++)
   {
      msgInfo->nPosTag [i] = 0;
      msgInfo->nPresent[i] = NOT_PRESENT;
   }
   msgInfo->nLength = 0;
   memset(msgInfo->sChipData,   '\0', MAX_VISA_CHIP_LEN);
}

int GetVisaTagIndice ( char * szTagName)
{
   int nIndice, nSize;

   nSize = sizeof(tab_VisaTagInfo) /sizeof(tag_info_t);
   nIndice = 0;

   do
   {
      if (memcmp(szTagName, tab_VisaTagInfo[nIndice].sTagName, 4) == 0)
         return(nIndice);
      nIndice++;
   }while (nIndice < nSize);
   return(-1);
}

int GetVisaTagType ( int nIndice )
{
   return ( tab_VisaTagInfo[nIndice].nType);
}

int GetVisaTagLength ( int nIndice )
{
   return ( tab_VisaTagInfo[nIndice].nLength);
}
/**End  MKB221208**/

/******************************************************************************/
/*start IBE PLUTONL-5640*/
void InitVisaSupplementalData  (BerInfo* pkBerInfo)		/*HAL  20202003 ENHS 2020Q2 ART 9.3.4*/
{
	pkBerInfo->pkProperties = &VisaF34T56DataProp;
	ResetBerInfo(pkBerInfo);
}
/*end IBE PLUTONL-5640*/
/******************************************************************************/
void InitVisaEcomAddDataTlv(TlvInfo* pkTlvInfo)		/*HAL PROD00073823 20202801 Enh Q2.2020 Art 3.10*/
{
	pkTlvInfo->pkProperties = &VisaF34T01DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
/*PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/
void InitVisaAddSrvReqDataTlv(TlvInfo* pkTlvInfo)		
{
	pkTlvInfo->pkProperties = &VisaF34T03DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaAddSrvResDataTlv(TlvInfo* pkTlvInfo)		
{
	pkTlvInfo->pkProperties = &VisaF34T04DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*Start NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7 */
void InitVisaDevPlatformDataTlv(TlvInfo* pkTlvInfo)		
{
	pkTlvInfo->pkProperties = &VisaF34T06DataProp;
	ResetTlvInfo(pkTlvInfo);
}
void InitVisaDevCommonDataTlv(TlvInfo* pkTlvInfo)		
{
	pkTlvInfo->pkProperties = &VisaF34T07DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*End NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7 */
/******************************************************************************/
void InitVisaElectComDataTlv(TlvInfo* pkTlvInfo)    /*IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/
{
	pkTlvInfo->pkProperties = &VisaElectComDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaAccEnvAddDataTlv(TlvInfo* pkTlvInfo)		/*IBO20190718 PROD00070403 Enh19.Q4 Art 9.1.4*/
{
	pkTlvInfo->pkProperties = &VisaF34T02DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaEuPsd2ScaCsc(TlvInfo* pkTlvInfo)    /*IBO20190719 PROD00070403 Enh19.Q4 Art 9.1.3*/
{
	pkTlvInfo->pkProperties = &VisaF34T4ADataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaTransSpecDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &VisaTransSpecDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaPayFacDataTlv(TlvInfo* pkTlvInfo)		/*AMER20190219 PROD00065991: VISA Enh19.Q2 Art2.4*/
{
	pkTlvInfo->pkProperties = &VisaF104T56DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaAppIdentDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &VisaF104T57DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaSenderDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &VisaF104T5FDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
/*
void InitVisaAddSenderDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &VisaF104T71DataProp;
	ResetTlvInfo(pkTlvInfo);
}*/
/******************************************************************************/

/******************************************************************************/
void InitB1VerifDataTlvInfo(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &Base1VerifDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitB1AddrVerifDataTlvInfo(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &Base1AddrVerifDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitB1TokenDataTlvInfo(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &Base1TokenDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaSupportInfDataTlv(TlvInfo* pkTlvInfo)    		/*IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/
{
	pkTlvInfo->pkProperties = &VisaSupportInfDataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaAddOriginalDataTlv(TlvInfo* pkTlvInfo)		/*IBO20190722 PROD00070403 Enh19.Q4 Art 2.17*/
{
	pkTlvInfo->pkProperties = &VisaF125T03DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaWalletProviderDataTlv(TlvInfo* pkTlvInfo)		/*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art3.1*/
{
	pkTlvInfo->pkProperties = &VisaF125T02DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitTokenDevice(TlvInfo* pkTlvInfo)		/*PLUTONL-5548  Enh 2023Q2  Visa 3.3 AHA20221221*/
{
	pkTlvInfo->pkProperties = &VisaF125T01DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaCustmRelatdDataTlv(TlvInfo* pkTlvInfo)		/*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art1.1*/
{
	pkTlvInfo->pkProperties = &VisaF056DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*Start NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
void InitVisaContactInfoDataTlv(TlvInfo* pkTlvInfo) /*ABA20231210 PLUTONL-7047*/
{
	pkTlvInfo->pkProperties = &VisaF056T02DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*End NAB PLUTONL-9856-Enh 2025Q2 VISA 3.7*/
/******************************************************************************/
void InitVisaCustomerIdDataTlv(TlvInfo* pkTlvInfo)		/*IZL 20220131 PLUTONL-4015 ENH 22.Q2 VISA Art1.1*/
{
	pkTlvInfo->pkProperties = &VisaF056T03DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaRecurringPayDataTlv(TlvInfo* pkTlvInfo)  /*IZL 27062022 PLUTONL-4902 ENH 22.Q4 VISA Art3.17*/
{
	pkTlvInfo->pkProperties = &VisaF104T18DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/******************************************************************************/
void InitVisaAdditionalDataTlv(TlvInfo* pkTlvInfo)		/* FZL20220822 PLUTONL-4979*/
{
	pkTlvInfo->pkProperties = &VisaF110DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/********************************************************************************/
void InitVisaKeyDataTlv(TlvInfo* pkTlvInfo)          /* FZL20220822 PLUTONL-4979*/
{
	pkTlvInfo->pkProperties = &VisaF110T04DataProp;
	ResetTlvInfo(pkTlvInfo);
}

/*Start PLUTONL-9204 AMANS Enh24Q4 VISA AN 1.1*/
void InitVisaAddtnlTrnSpecDataTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &VisaF111DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/********************************************************************************/
void InitVisaRespDataForClearingTlv(TlvInfo* pkTlvInfo)
{
	pkTlvInfo->pkProperties = &VisaF111T56DataProp;
	ResetTlvInfo(pkTlvInfo);
}
/*End PLUTONL-9204 AMANS Enh24Q4 VISA AN 1.1*/
/******************************************************************************/

/*PLUTONL-6505 -Enh 2023Q4 NAB AN 1.1*/
void InitVisaAccOwnerDataTlv(TlvInfo* pkTlvInfo)		

{
	pkTlvInfo->pkProperties = &VisaF056T05DataProp;
	ResetTlvInfo(pkTlvInfo);
}
